using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class addedMoreConnections_fixed : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "author",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    first_name = table.Column<string>(type: "text", nullable: false),
                    last_name = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_author", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "publisher",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false),
                    contact_details = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_publisher", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "book",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    publisher_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_book", x => x.id);
                    table.ForeignKey(
                        name: "FK_book_publisher_publisher_id",
                        column: x => x.publisher_id,
                        principalTable: "publisher",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "book_author",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    book_id = table.Column<int>(type: "integer", nullable: false),
                    author_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_book_author", x => x.id);
                    table.ForeignKey(
                        name: "FK_book_author_author_author_id",
                        column: x => x.author_id,
                        principalTable: "author",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_book_author_book_book_id",
                        column: x => x.book_id,
                        principalTable: "book",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "author",
                columns: new[] { "id", "email", "first_name", "last_name" },
                values: new object[,]
                {
                    { 1, "jimi.presley@google.com", "Jimi", "Presley" },
                    { 2, "audrey.jagger@tesla.com", "Audrey", "Jagger" },
                    { 3, "kate.winslet@something.com", "Kate", "Winslet" },
                    { 4, "barack.middleton@tesla.com", "Barack", "Middleton" },
                    { 5, "oprah.hepburn@bbc.co.uk", "Oprah", "Hepburn" },
                    { 6, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 7, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 8, "mick.presley@nasa.org.us", "Mick", "Presley" },
                    { 9, "audrey.presley@nasa.org.us", "Audrey", "Presley" },
                    { 10, "audrey.presley@gov.ru", "Audrey", "Presley" },
                    { 11, "audrey.trump@tesla.com", "Audrey", "Trump" },
                    { 12, "audrey.trump@nasa.org.us", "Audrey", "Trump" },
                    { 13, "jimi.jagger@theworld.ca", "Jimi", "Jagger" },
                    { 14, "charles.winfrey@theworld.ca", "Charles", "Winfrey" },
                    { 15, "donald.presley@gov.nl", "Donald", "Presley" },
                    { 16, "elvis.presley@gov.nl", "Elvis", "Presley" },
                    { 17, "mick.jagger@theworld.ca", "Mick", "Jagger" },
                    { 18, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 19, "donald.windsor@gov.nl", "Donald", "Windsor" },
                    { 20, "oprah.trump@gov.nl", "Oprah", "Trump" },
                    { 21, "oprah.obama@google.com", "Oprah", "Obama" },
                    { 22, "oprah.winslet@gov.nl", "Oprah", "Winslet" },
                    { 23, "donald.windsor@tesla.com", "Donald", "Windsor" },
                    { 24, "audrey.winslet@gov.nl", "Audrey", "Winslet" },
                    { 25, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 26, "donald.windsor@google.com", "Donald", "Windsor" },
                    { 27, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 28, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 29, "kate.trump@google.com", "Kate", "Trump" },
                    { 30, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 31, "charles.presley@gov.ru", "Charles", "Presley" },
                    { 32, "kate.presley@theworld.ca", "Kate", "Presley" },
                    { 33, "barack.middleton@gov.us", "Barack", "Middleton" },
                    { 34, "donald.jagger@google.com", "Donald", "Jagger" },
                    { 35, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 36, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 37, "donald.windsor@gov.us", "Donald", "Windsor" },
                    { 38, "elvis.obama@google.com", "Elvis", "Obama" },
                    { 39, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 40, "barack.jagger@tesla.com", "Barack", "Jagger" },
                    { 41, "elvis.hepburn@gov.nl", "Elvis", "Hepburn" },
                    { 42, "jimi.jagger@gov.gr", "Jimi", "Jagger" },
                    { 43, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 44, "kate.trump@tesla.com", "Kate", "Trump" },
                    { 45, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 46, "audrey.obama@google.com", "Audrey", "Obama" },
                    { 47, "elvis.middleton@theworld.ca", "Elvis", "Middleton" },
                    { 48, "jimi.trump@gov.ru", "Jimi", "Trump" },
                    { 49, "mick.presley@nasa.org.us", "Mick", "Presley" },
                    { 50, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 51, "charles.trump@bbc.co.uk", "Charles", "Trump" },
                    { 52, "elvis.obama@gov.us", "Elvis", "Obama" },
                    { 53, "oprah.presley@tesla.com", "Oprah", "Presley" },
                    { 54, "jimi.winfrey@something.com", "Jimi", "Winfrey" },
                    { 55, "mick.winslet@google.com", "Mick", "Winslet" },
                    { 56, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 57, "elvis.presley@gov.gr", "Elvis", "Presley" },
                    { 58, "audrey.obama@nasa.org.us", "Audrey", "Obama" },
                    { 59, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 60, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 61, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 62, "charles.jagger@gov.ru", "Charles", "Jagger" },
                    { 63, "jimi.trump@gov.ru", "Jimi", "Trump" },
                    { 64, "audrey.middleton@tesla.com", "Audrey", "Middleton" },
                    { 65, "elvis.hepburn@gov.ru", "Elvis", "Hepburn" },
                    { 66, "audrey.winfrey@something.com", "Audrey", "Winfrey" },
                    { 67, "donald.trump@theworld.ca", "Donald", "Trump" },
                    { 68, "jimi.trump@theworld.ca", "Jimi", "Trump" },
                    { 69, "oprah.hendrix@tesla.com", "Oprah", "Hendrix" },
                    { 70, "barack.presley@bbc.co.uk", "Barack", "Presley" },
                    { 71, "oprah.winslet@something.com", "Oprah", "Winslet" },
                    { 72, "kate.obama@gov.us", "Kate", "Obama" },
                    { 73, "mick.windsor@gov.us", "Mick", "Windsor" },
                    { 74, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 75, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 76, "elvis.windsor@gov.ru", "Elvis", "Windsor" },
                    { 77, "elvis.trump@nasa.org.us", "Elvis", "Trump" },
                    { 78, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 79, "jimi.obama@bbc.co.uk", "Jimi", "Obama" },
                    { 80, "charles.jagger@gov.nl", "Charles", "Jagger" },
                    { 81, "audrey.hepburn@gov.gr", "Audrey", "Hepburn" },
                    { 82, "barack.winslet@theworld.ca", "Barack", "Winslet" },
                    { 83, "elvis.hepburn@bbc.co.uk", "Elvis", "Hepburn" },
                    { 84, "kate.winfrey@google.com", "Kate", "Winfrey" },
                    { 85, "jimi.middleton@theworld.ca", "Jimi", "Middleton" },
                    { 86, "elvis.winfrey@gov.us", "Elvis", "Winfrey" },
                    { 87, "barack.windsor@google.com", "Barack", "Windsor" },
                    { 88, "jimi.winfrey@gov.nl", "Jimi", "Winfrey" },
                    { 89, "jimi.windsor@something.com", "Jimi", "Windsor" },
                    { 90, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 91, "elvis.presley@gov.us", "Elvis", "Presley" },
                    { 92, "mick.middleton@gov.us", "Mick", "Middleton" },
                    { 93, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 94, "oprah.winfrey@bbc.co.uk", "Oprah", "Winfrey" },
                    { 95, "oprah.middleton@something.com", "Oprah", "Middleton" },
                    { 96, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 97, "jimi.winfrey@nasa.org.us", "Jimi", "Winfrey" },
                    { 98, "barack.trump@something.com", "Barack", "Trump" },
                    { 99, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 100, "charles.presley@something.com", "Charles", "Presley" },
                    { 101, "barack.trump@gov.us", "Barack", "Trump" },
                    { 102, "elvis.winfrey@gov.nl", "Elvis", "Winfrey" },
                    { 103, "kate.winslet@something.com", "Kate", "Winslet" },
                    { 104, "oprah.trump@gov.ru", "Oprah", "Trump" },
                    { 105, "oprah.hepburn@bbc.co.uk", "Oprah", "Hepburn" },
                    { 106, "donald.winfrey@google.com", "Donald", "Winfrey" },
                    { 107, "mick.jagger@theworld.ca", "Mick", "Jagger" },
                    { 108, "barack.middleton@tesla.com", "Barack", "Middleton" },
                    { 109, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 110, "kate.obama@tesla.com", "Kate", "Obama" },
                    { 111, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 112, "audrey.windsor@bbc.co.uk", "Audrey", "Windsor" },
                    { 113, "kate.presley@theworld.ca", "Kate", "Presley" },
                    { 114, "barack.jagger@something.com", "Barack", "Jagger" },
                    { 115, "oprah.windsor@nasa.org.us", "Oprah", "Windsor" },
                    { 116, "barack.trump@tesla.com", "Barack", "Trump" },
                    { 117, "oprah.hepburn@nasa.org.us", "Oprah", "Hepburn" },
                    { 118, "barack.windsor@tesla.com", "Barack", "Windsor" },
                    { 119, "oprah.jagger@gov.gr", "Oprah", "Jagger" },
                    { 120, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 121, "jimi.winslet@something.com", "Jimi", "Winslet" },
                    { 122, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 123, "mick.presley@tesla.com", "Mick", "Presley" },
                    { 124, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 125, "mick.middleton@gov.gr", "Mick", "Middleton" },
                    { 126, "audrey.winfrey@theworld.ca", "Audrey", "Winfrey" },
                    { 127, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 128, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 129, "elvis.windsor@gov.gr", "Elvis", "Windsor" },
                    { 130, "oprah.presley@something.com", "Oprah", "Presley" },
                    { 131, "barack.jagger@google.com", "Barack", "Jagger" },
                    { 132, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 133, "oprah.hepburn@theworld.ca", "Oprah", "Hepburn" },
                    { 134, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 135, "barack.jagger@gov.gr", "Barack", "Jagger" },
                    { 136, "donald.obama@gov.ru", "Donald", "Obama" },
                    { 137, "mick.hepburn@tesla.com", "Mick", "Hepburn" },
                    { 138, "barack.hepburn@google.com", "Barack", "Hepburn" },
                    { 139, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 140, "mick.jagger@gov.gr", "Mick", "Jagger" },
                    { 141, "audrey.winslet@gov.us", "Audrey", "Winslet" },
                    { 142, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 143, "oprah.obama@something.com", "Oprah", "Obama" },
                    { 144, "donald.jagger@bbc.co.uk", "Donald", "Jagger" },
                    { 145, "barack.middleton@google.com", "Barack", "Middleton" },
                    { 146, "kate.hepburn@nasa.org.us", "Kate", "Hepburn" },
                    { 147, "oprah.jagger@tesla.com", "Oprah", "Jagger" },
                    { 148, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 149, "barack.winslet@gov.gr", "Barack", "Winslet" },
                    { 150, "audrey.presley@gov.gr", "Audrey", "Presley" },
                    { 151, "barack.winfrey@gov.nl", "Barack", "Winfrey" },
                    { 152, "elvis.winslet@nasa.org.us", "Elvis", "Winslet" },
                    { 153, "charles.trump@gov.nl", "Charles", "Trump" },
                    { 154, "charles.trump@something.com", "Charles", "Trump" },
                    { 155, "oprah.middleton@nasa.org.us", "Oprah", "Middleton" },
                    { 156, "oprah.presley@gov.gr", "Oprah", "Presley" },
                    { 157, "jimi.winfrey@google.com", "Jimi", "Winfrey" },
                    { 158, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 159, "elvis.winfrey@google.com", "Elvis", "Winfrey" },
                    { 160, "elvis.trump@gov.ru", "Elvis", "Trump" },
                    { 161, "donald.trump@tesla.com", "Donald", "Trump" },
                    { 162, "jimi.windsor@tesla.com", "Jimi", "Windsor" },
                    { 163, "elvis.hendrix@theworld.ca", "Elvis", "Hendrix" },
                    { 164, "kate.winfrey@google.com", "Kate", "Winfrey" },
                    { 165, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 166, "charles.winfrey@tesla.com", "Charles", "Winfrey" },
                    { 167, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 168, "donald.middleton@theworld.ca", "Donald", "Middleton" },
                    { 169, "jimi.obama@something.com", "Jimi", "Obama" },
                    { 170, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 171, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 172, "donald.winfrey@bbc.co.uk", "Donald", "Winfrey" },
                    { 173, "donald.hepburn@google.com", "Donald", "Hepburn" },
                    { 174, "oprah.winfrey@gov.us", "Oprah", "Winfrey" },
                    { 175, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 176, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 177, "mick.middleton@gov.gr", "Mick", "Middleton" },
                    { 178, "barack.jagger@gov.gr", "Barack", "Jagger" },
                    { 179, "charles.hepburn@gov.ru", "Charles", "Hepburn" },
                    { 180, "jimi.middleton@tesla.com", "Jimi", "Middleton" },
                    { 181, "barack.jagger@gov.us", "Barack", "Jagger" },
                    { 182, "charles.jagger@gov.nl", "Charles", "Jagger" },
                    { 183, "oprah.obama@something.com", "Oprah", "Obama" },
                    { 184, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 185, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 186, "mick.windsor@something.com", "Mick", "Windsor" },
                    { 187, "mick.winslet@nasa.org.us", "Mick", "Winslet" },
                    { 188, "elvis.middleton@nasa.org.us", "Elvis", "Middleton" },
                    { 189, "mick.trump@theworld.ca", "Mick", "Trump" },
                    { 190, "audrey.hendrix@something.com", "Audrey", "Hendrix" },
                    { 191, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 192, "oprah.hepburn@gov.ru", "Oprah", "Hepburn" },
                    { 193, "kate.middleton@gov.ru", "Kate", "Middleton" },
                    { 194, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 195, "elvis.winslet@something.com", "Elvis", "Winslet" },
                    { 196, "elvis.obama@tesla.com", "Elvis", "Obama" },
                    { 197, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 198, "donald.windsor@gov.us", "Donald", "Windsor" },
                    { 199, "elvis.winslet@theworld.ca", "Elvis", "Winslet" },
                    { 200, "elvis.winslet@tesla.com", "Elvis", "Winslet" },
                    { 201, "elvis.hendrix@gov.nl", "Elvis", "Hendrix" },
                    { 202, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 203, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 204, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 205, "jimi.hepburn@bbc.co.uk", "Jimi", "Hepburn" },
                    { 206, "audrey.hendrix@gov.us", "Audrey", "Hendrix" },
                    { 207, "mick.obama@bbc.co.uk", "Mick", "Obama" },
                    { 208, "charles.winfrey@tesla.com", "Charles", "Winfrey" },
                    { 209, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 210, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 211, "barack.hepburn@theworld.ca", "Barack", "Hepburn" },
                    { 212, "jimi.presley@theworld.ca", "Jimi", "Presley" },
                    { 213, "jimi.winslet@gov.gr", "Jimi", "Winslet" },
                    { 214, "mick.winslet@tesla.com", "Mick", "Winslet" },
                    { 215, "mick.middleton@google.com", "Mick", "Middleton" },
                    { 216, "jimi.jagger@nasa.org.us", "Jimi", "Jagger" },
                    { 217, "barack.jagger@something.com", "Barack", "Jagger" },
                    { 218, "kate.middleton@google.com", "Kate", "Middleton" },
                    { 219, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 220, "jimi.hepburn@gov.ru", "Jimi", "Hepburn" },
                    { 221, "jimi.jagger@gov.nl", "Jimi", "Jagger" },
                    { 222, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 223, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 224, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 225, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 226, "barack.hendrix@google.com", "Barack", "Hendrix" },
                    { 227, "jimi.jagger@gov.gr", "Jimi", "Jagger" },
                    { 228, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 229, "jimi.presley@gov.ru", "Jimi", "Presley" },
                    { 230, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 231, "jimi.jagger@something.com", "Jimi", "Jagger" },
                    { 232, "oprah.trump@gov.ru", "Oprah", "Trump" },
                    { 233, "jimi.trump@google.com", "Jimi", "Trump" },
                    { 234, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 235, "charles.windsor@gov.gr", "Charles", "Windsor" },
                    { 236, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 237, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 238, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 239, "kate.presley@theworld.ca", "Kate", "Presley" },
                    { 240, "kate.obama@something.com", "Kate", "Obama" },
                    { 241, "barack.hepburn@something.com", "Barack", "Hepburn" },
                    { 242, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 243, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 244, "mick.jagger@gov.nl", "Mick", "Jagger" },
                    { 245, "oprah.hendrix@theworld.ca", "Oprah", "Hendrix" },
                    { 246, "audrey.jagger@gov.nl", "Audrey", "Jagger" },
                    { 247, "mick.windsor@bbc.co.uk", "Mick", "Windsor" },
                    { 248, "elvis.hepburn@gov.nl", "Elvis", "Hepburn" },
                    { 249, "barack.obama@bbc.co.uk", "Barack", "Obama" }
                });

            migrationBuilder.InsertData(
                table: "publisher",
                columns: new[] { "id", "contact_details", "name" },
                values: new object[,]
                {
                    { 1, "transparent@gov.gr", "Flowers Two" },
                    { 2, "microscopic@tesla.com", "Buildings Two" },
                    { 3, "orange@gov.nl", "Leopards Several" },
                    { 4, "transparent@bbc.co.uk", "Leopards An army of" },
                    { 5, "large@something.com", "Cars Fifteen" },
                    { 6, "rose smelling@something.com", "Leopards A bunch of" },
                    { 7, "large@gov.us", "Leopards Two" },
                    { 8, "orange@gov.nl", "Buildings An army of" },
                    { 9, "microscopic@gov.gr", "Cars A herd of" },
                    { 10, "rose smelling@gov.gr", "Buildings Two" },
                    { 11, "large@nasa.org.us", "Flowers Two" },
                    { 12, "microscopic@gov.us", "Houses The" },
                    { 13, "microscopic@something.com", "Planets Two" },
                    { 14, "green@bbc.co.uk", "Flowers An army of" },
                    { 15, "rose smelling@google.com", "Houses Two" },
                    { 16, "microscopic@gov.nl", "Buildings An army of" },
                    { 17, "orange@gov.ru", "Houses A herd of" },
                    { 18, "large@theworld.ca", "Buildings An army of" },
                    { 19, "microscopic@google.com", "Planets A herd of" },
                    { 20, "bitter@gov.nl", "Cars Two" },
                    { 21, "green@something.com", "Leopards A herd of" },
                    { 22, "bitter@gov.ru", "Flowers A herd of" },
                    { 23, "green@theworld.ca", "Planets Two" },
                    { 24, "bitter@something.com", "Cars An army of" },
                    { 25, "green@theworld.ca", "Cars An army of" },
                    { 26, "orange@theworld.ca", "Cars The" },
                    { 27, "large@nasa.org.us", "Planets Several" },
                    { 28, "rose smelling@tesla.com", "Houses Several" },
                    { 29, "purple@gov.gr", "Flowers A herd of" },
                    { 30, "purple@google.com", "Houses Several" },
                    { 31, "green@bbc.co.uk", "Houses Several" },
                    { 32, "orange@nasa.org.us", "Flowers Several" },
                    { 33, "bitter@theworld.ca", "Buildings A bunch of" },
                    { 34, "green@google.com", "Cars An army of" },
                    { 35, "microscopic@gov.gr", "Houses A bunch of" },
                    { 36, "transparent@something.com", "Flowers The" },
                    { 37, "purple@gov.us", "Leopards A bunch of" },
                    { 38, "orange@gov.nl", "Planets Fifteen" },
                    { 39, "orange@gov.nl", "Buildings A herd of" },
                    { 40, "large@google.com", "Planets The" },
                    { 41, "transparent@something.com", "Planets Fifteen" },
                    { 42, "orange@gov.gr", "Leopards Several" },
                    { 43, "green@gov.us", "Flowers Two" },
                    { 44, "rose smelling@bbc.co.uk", "Houses Two" },
                    { 45, "bitter@gov.gr", "Planets An army of" },
                    { 46, "green@gov.nl", "Planets Two" },
                    { 47, "purple@gov.ru", "Leopards Several" },
                    { 48, "transparent@gov.us", "Cars A herd of" },
                    { 49, "rose smelling@something.com", "Leopards Fifteen" },
                    { 50, "transparent@gov.gr", "Flowers A bunch of" },
                    { 51, "large@theworld.ca", "Cars Fifteen" },
                    { 52, "orange@gov.gr", "Leopards An army of" },
                    { 53, "rose smelling@tesla.com", "Cars A herd of" },
                    { 54, "transparent@google.com", "Cars An army of" },
                    { 55, "rose smelling@gov.ru", "Leopards A bunch of" },
                    { 56, "purple@gov.us", "Cars Several" },
                    { 57, "transparent@theworld.ca", "Flowers An army of" },
                    { 58, "bitter@something.com", "Leopards A herd of" },
                    { 59, "purple@tesla.com", "Planets The" },
                    { 60, "transparent@gov.nl", "Buildings The" },
                    { 61, "rose smelling@gov.ru", "Buildings A herd of" },
                    { 62, "large@gov.nl", "Buildings A bunch of" },
                    { 63, "rose smelling@gov.nl", "Cars Two" },
                    { 64, "purple@tesla.com", "Planets The" },
                    { 65, "microscopic@nasa.org.us", "Leopards A herd of" },
                    { 66, "rose smelling@gov.us", "Houses An army of" },
                    { 67, "rose smelling@tesla.com", "Houses Two" },
                    { 68, "orange@gov.ru", "Buildings Several" },
                    { 69, "orange@gov.ru", "Planets Several" },
                    { 70, "green@gov.gr", "Houses Fifteen" },
                    { 71, "green@gov.nl", "Buildings Two" },
                    { 72, "transparent@gov.nl", "Leopards An army of" },
                    { 73, "rose smelling@gov.us", "Planets Several" },
                    { 74, "green@gov.nl", "Leopards A herd of" },
                    { 75, "microscopic@gov.us", "Cars A herd of" },
                    { 76, "purple@something.com", "Leopards Two" },
                    { 77, "large@tesla.com", "Flowers An army of" },
                    { 78, "rose smelling@gov.us", "Flowers The" },
                    { 79, "orange@gov.gr", "Cars The" },
                    { 80, "green@nasa.org.us", "Planets Fifteen" },
                    { 81, "transparent@bbc.co.uk", "Buildings A herd of" },
                    { 82, "green@bbc.co.uk", "Flowers The" },
                    { 83, "green@bbc.co.uk", "Flowers An army of" },
                    { 84, "microscopic@tesla.com", "Cars A bunch of" },
                    { 85, "orange@bbc.co.uk", "Leopards A herd of" },
                    { 86, "orange@gov.ru", "Houses A herd of" },
                    { 87, "orange@gov.gr", "Buildings An army of" },
                    { 88, "large@gov.nl", "Planets A bunch of" },
                    { 89, "transparent@gov.ru", "Buildings The" },
                    { 90, "microscopic@gov.nl", "Cars The" },
                    { 91, "bitter@theworld.ca", "Flowers Fifteen" },
                    { 92, "large@gov.us", "Houses An army of" },
                    { 93, "large@something.com", "Buildings A bunch of" },
                    { 94, "transparent@gov.ru", "Planets A bunch of" },
                    { 95, "green@bbc.co.uk", "Buildings Several" },
                    { 96, "transparent@gov.ru", "Houses The" },
                    { 97, "green@nasa.org.us", "Houses Two" },
                    { 98, "purple@gov.ru", "Cars An army of" },
                    { 99, "bitter@something.com", "Houses A herd of" },
                    { 100, "purple@tesla.com", "Cars A bunch of" },
                    { 101, "transparent@theworld.ca", "Planets Several" },
                    { 102, "orange@bbc.co.uk", "Leopards The" },
                    { 103, "transparent@gov.gr", "Cars The" },
                    { 104, "microscopic@google.com", "Leopards An army of" },
                    { 105, "purple@google.com", "Leopards A herd of" },
                    { 106, "orange@google.com", "Planets An army of" },
                    { 107, "green@gov.gr", "Cars The" },
                    { 108, "transparent@nasa.org.us", "Leopards A herd of" },
                    { 109, "microscopic@gov.us", "Flowers Several" },
                    { 110, "green@gov.nl", "Buildings An army of" },
                    { 111, "large@gov.ru", "Houses A herd of" },
                    { 112, "orange@gov.nl", "Planets A herd of" },
                    { 113, "large@nasa.org.us", "Houses A bunch of" },
                    { 114, "green@nasa.org.us", "Flowers The" },
                    { 115, "large@gov.us", "Houses Several" },
                    { 116, "microscopic@google.com", "Leopards Fifteen" },
                    { 117, "purple@gov.ru", "Houses Several" },
                    { 118, "rose smelling@nasa.org.us", "Buildings Several" },
                    { 119, "microscopic@tesla.com", "Cars An army of" },
                    { 120, "rose smelling@nasa.org.us", "Planets A herd of" },
                    { 121, "bitter@something.com", "Flowers Several" },
                    { 122, "green@gov.us", "Houses Fifteen" },
                    { 123, "microscopic@gov.gr", "Houses A herd of" },
                    { 124, "transparent@bbc.co.uk", "Planets An army of" },
                    { 125, "orange@google.com", "Buildings Fifteen" },
                    { 126, "orange@theworld.ca", "Planets A herd of" },
                    { 127, "orange@gov.nl", "Leopards A bunch of" },
                    { 128, "transparent@google.com", "Leopards An army of" },
                    { 129, "bitter@tesla.com", "Planets A bunch of" },
                    { 130, "microscopic@bbc.co.uk", "Flowers A bunch of" },
                    { 131, "orange@bbc.co.uk", "Leopards The" },
                    { 132, "transparent@gov.us", "Planets A herd of" },
                    { 133, "large@tesla.com", "Flowers Several" },
                    { 134, "microscopic@nasa.org.us", "Buildings Fifteen" },
                    { 135, "microscopic@gov.ru", "Buildings Fifteen" },
                    { 136, "orange@tesla.com", "Buildings Fifteen" },
                    { 137, "microscopic@theworld.ca", "Houses Several" },
                    { 138, "rose smelling@nasa.org.us", "Planets Several" },
                    { 139, "orange@google.com", "Flowers A bunch of" },
                    { 140, "transparent@gov.gr", "Cars Several" },
                    { 141, "large@theworld.ca", "Cars A herd of" },
                    { 142, "orange@nasa.org.us", "Leopards Two" },
                    { 143, "transparent@nasa.org.us", "Buildings An army of" },
                    { 144, "orange@tesla.com", "Leopards Several" },
                    { 145, "green@theworld.ca", "Cars Several" },
                    { 146, "orange@tesla.com", "Leopards Two" },
                    { 147, "green@gov.nl", "Leopards The" },
                    { 148, "rose smelling@theworld.ca", "Buildings Fifteen" },
                    { 149, "microscopic@gov.nl", "Houses The" },
                    { 150, "purple@gov.nl", "Houses Two" },
                    { 151, "green@gov.us", "Houses A bunch of" },
                    { 152, "large@gov.ru", "Flowers An army of" },
                    { 153, "rose smelling@bbc.co.uk", "Leopards Several" },
                    { 154, "large@gov.ru", "Houses Several" },
                    { 155, "large@theworld.ca", "Houses Two" },
                    { 156, "bitter@theworld.ca", "Buildings The" },
                    { 157, "transparent@tesla.com", "Buildings Fifteen" },
                    { 158, "microscopic@google.com", "Flowers Two" },
                    { 159, "rose smelling@theworld.ca", "Houses Fifteen" },
                    { 160, "orange@gov.gr", "Buildings Several" },
                    { 161, "purple@gov.ru", "Cars The" },
                    { 162, "purple@theworld.ca", "Cars An army of" },
                    { 163, "microscopic@gov.gr", "Buildings A bunch of" },
                    { 164, "orange@google.com", "Flowers Fifteen" },
                    { 165, "large@gov.nl", "Flowers Fifteen" },
                    { 166, "microscopic@gov.ru", "Buildings An army of" },
                    { 167, "green@gov.nl", "Leopards The" },
                    { 168, "transparent@tesla.com", "Houses Fifteen" },
                    { 169, "green@gov.us", "Leopards Several" },
                    { 170, "transparent@gov.ru", "Planets A bunch of" },
                    { 171, "bitter@gov.ru", "Houses A herd of" },
                    { 172, "bitter@something.com", "Buildings Several" },
                    { 173, "purple@google.com", "Flowers Two" },
                    { 174, "transparent@gov.us", "Leopards Fifteen" },
                    { 175, "microscopic@gov.nl", "Buildings Fifteen" },
                    { 176, "bitter@something.com", "Cars A bunch of" },
                    { 177, "transparent@gov.ru", "Buildings A herd of" },
                    { 178, "bitter@gov.us", "Flowers An army of" },
                    { 179, "green@something.com", "Houses Several" },
                    { 180, "microscopic@gov.ru", "Cars Fifteen" },
                    { 181, "bitter@google.com", "Cars An army of" },
                    { 182, "orange@bbc.co.uk", "Buildings A herd of" },
                    { 183, "bitter@something.com", "Cars Several" },
                    { 184, "large@theworld.ca", "Planets A bunch of" },
                    { 185, "rose smelling@gov.ru", "Planets The" },
                    { 186, "green@tesla.com", "Buildings The" },
                    { 187, "large@google.com", "Houses A bunch of" },
                    { 188, "rose smelling@gov.nl", "Leopards Several" },
                    { 189, "green@theworld.ca", "Buildings An army of" },
                    { 190, "purple@google.com", "Buildings A bunch of" },
                    { 191, "rose smelling@tesla.com", "Planets A bunch of" },
                    { 192, "bitter@gov.ru", "Houses Fifteen" },
                    { 193, "microscopic@tesla.com", "Cars Several" },
                    { 194, "bitter@gov.nl", "Leopards Several" },
                    { 195, "orange@google.com", "Planets The" },
                    { 196, "large@gov.gr", "Leopards The" },
                    { 197, "orange@google.com", "Planets Fifteen" },
                    { 198, "purple@something.com", "Cars An army of" },
                    { 199, "rose smelling@theworld.ca", "Buildings An army of" },
                    { 200, "rose smelling@gov.us", "Cars An army of" },
                    { 201, "purple@theworld.ca", "Buildings Fifteen" },
                    { 202, "large@tesla.com", "Cars A herd of" },
                    { 203, "orange@bbc.co.uk", "Leopards The" },
                    { 204, "rose smelling@gov.nl", "Flowers Two" },
                    { 205, "bitter@google.com", "Leopards A bunch of" },
                    { 206, "orange@google.com", "Houses Several" },
                    { 207, "rose smelling@tesla.com", "Flowers A herd of" },
                    { 208, "orange@gov.nl", "Leopards An army of" },
                    { 209, "transparent@tesla.com", "Flowers An army of" },
                    { 210, "large@gov.nl", "Flowers The" },
                    { 211, "green@google.com", "Planets Two" },
                    { 212, "large@google.com", "Planets An army of" },
                    { 213, "transparent@bbc.co.uk", "Buildings A bunch of" },
                    { 214, "purple@gov.gr", "Houses A herd of" },
                    { 215, "orange@gov.nl", "Flowers Fifteen" },
                    { 216, "transparent@something.com", "Flowers Two" },
                    { 217, "purple@nasa.org.us", "Flowers An army of" },
                    { 218, "large@tesla.com", "Houses A bunch of" },
                    { 219, "transparent@tesla.com", "Houses Several" },
                    { 220, "rose smelling@bbc.co.uk", "Leopards Two" },
                    { 221, "microscopic@tesla.com", "Leopards The" },
                    { 222, "large@gov.us", "Cars The" },
                    { 223, "orange@something.com", "Buildings Two" },
                    { 224, "rose smelling@gov.nl", "Buildings A bunch of" },
                    { 225, "microscopic@gov.us", "Cars Fifteen" },
                    { 226, "green@gov.nl", "Houses The" },
                    { 227, "green@bbc.co.uk", "Cars Two" },
                    { 228, "purple@gov.ru", "Leopards Two" },
                    { 229, "bitter@bbc.co.uk", "Buildings Two" },
                    { 230, "rose smelling@something.com", "Leopards Several" },
                    { 231, "transparent@bbc.co.uk", "Flowers A herd of" },
                    { 232, "green@gov.gr", "Cars A bunch of" },
                    { 233, "purple@nasa.org.us", "Cars An army of" },
                    { 234, "orange@nasa.org.us", "Houses The" },
                    { 235, "microscopic@google.com", "Houses An army of" },
                    { 236, "rose smelling@tesla.com", "Leopards The" },
                    { 237, "large@bbc.co.uk", "Leopards Several" },
                    { 238, "large@tesla.com", "Flowers A herd of" },
                    { 239, "green@theworld.ca", "Planets The" },
                    { 240, "microscopic@gov.ru", "Flowers A herd of" },
                    { 241, "green@nasa.org.us", "Buildings A herd of" },
                    { 242, "green@bbc.co.uk", "Houses A herd of" },
                    { 243, "rose smelling@bbc.co.uk", "Cars Two" },
                    { 244, "rose smelling@something.com", "Cars The" },
                    { 245, "bitter@gov.gr", "Cars An army of" },
                    { 246, "green@google.com", "Buildings Fifteen" },
                    { 247, "purple@gov.ru", "Leopards Fifteen" },
                    { 248, "bitter@gov.ru", "Leopards Several" },
                    { 249, "orange@gov.ru", "Planets A herd of" }
                });

            migrationBuilder.InsertData(
                table: "book",
                columns: new[] { "id", "publisher_id", "title" },
                values: new object[,]
                {
                    { 1, 126, "Several Microscopic Buildings" },
                    { 2, 112, "A herd of Orange Houses" },
                    { 3, 53, "Several Rose Smelling Flowers" },
                    { 4, 153, "A herd of Bitter Leopards" },
                    { 5, 81, "Two Purple Planets" },
                    { 6, 206, "The Green Houses" },
                    { 7, 124, "An army of Orange Houses" },
                    { 8, 234, "The Large Houses" },
                    { 9, 170, "Fifteen Bitter Cars" },
                    { 10, 238, "Two Purple Leopards" },
                    { 11, 23, "The Bitter Flowers" },
                    { 12, 116, "A bunch of Green Buildings" },
                    { 13, 16, "An army of Purple Houses" },
                    { 14, 54, "Several Bitter Houses" },
                    { 15, 241, "Fifteen Green Flowers" },
                    { 16, 99, "A herd of Large Flowers" },
                    { 17, 140, "A bunch of Transparent Buildings" },
                    { 18, 13, "Two Purple Flowers" },
                    { 19, 186, "Several Rose Smelling Cars" },
                    { 20, 50, "Fifteen Purple Cars" },
                    { 21, 142, "Fifteen Orange Cars" },
                    { 22, 178, "Two Purple Flowers" },
                    { 23, 30, "Two Purple Houses" },
                    { 24, 50, "A herd of Large Planets" },
                    { 25, 119, "A bunch of Large Leopards" },
                    { 26, 139, "Two Purple Flowers" },
                    { 27, 155, "A bunch of Rose Smelling Leopards" },
                    { 28, 197, "A bunch of Bitter Cars" },
                    { 29, 219, "Several Purple Buildings" },
                    { 30, 91, "Two Bitter Houses" },
                    { 31, 157, "Fifteen Bitter Cars" },
                    { 32, 110, "A herd of Large Leopards" },
                    { 33, 179, "Two Bitter Planets" },
                    { 34, 241, "An army of Microscopic Buildings" },
                    { 35, 190, "An army of Rose Smelling Buildings" },
                    { 36, 83, "Fifteen Transparent Buildings" },
                    { 37, 14, "A herd of Large Flowers" },
                    { 38, 75, "Two Rose Smelling Cars" },
                    { 39, 192, "Two Purple Planets" },
                    { 40, 234, "A herd of Transparent Leopards" },
                    { 41, 76, "A herd of Rose Smelling Houses" },
                    { 42, 128, "A herd of Purple Planets" },
                    { 43, 226, "A bunch of Orange Leopards" },
                    { 44, 150, "The Green Leopards" },
                    { 45, 121, "An army of Large Planets" },
                    { 46, 147, "Fifteen Green Cars" },
                    { 47, 177, "An army of Rose Smelling Flowers" },
                    { 48, 117, "Several Orange Houses" },
                    { 49, 49, "A bunch of Rose Smelling Planets" },
                    { 50, 80, "A herd of Purple Flowers" },
                    { 51, 98, "Fifteen Purple Cars" },
                    { 52, 176, "An army of Purple Houses" },
                    { 53, 82, "Two Green Leopards" },
                    { 54, 112, "The Bitter Planets" },
                    { 55, 76, "Several Purple Flowers" },
                    { 56, 214, "Fifteen Transparent Houses" },
                    { 57, 61, "An army of Purple Leopards" },
                    { 58, 231, "An army of Rose Smelling Buildings" },
                    { 59, 150, "The Large Leopards" },
                    { 60, 37, "Fifteen Green Flowers" },
                    { 61, 117, "The Orange Buildings" },
                    { 62, 180, "The Large Leopards" },
                    { 63, 179, "Two Rose Smelling Buildings" },
                    { 64, 113, "An army of Microscopic Buildings" },
                    { 65, 153, "Several Transparent Leopards" },
                    { 66, 237, "A herd of Transparent Leopards" },
                    { 67, 26, "Two Green Flowers" },
                    { 68, 102, "The Transparent Leopards" },
                    { 69, 196, "A herd of Microscopic Leopards" },
                    { 70, 238, "A herd of Orange Buildings" },
                    { 71, 98, "A bunch of Purple Leopards" },
                    { 72, 210, "An army of Orange Cars" },
                    { 73, 86, "An army of Microscopic Cars" },
                    { 74, 56, "Several Rose Smelling Buildings" },
                    { 75, 70, "Fifteen Microscopic Houses" },
                    { 76, 30, "The Large Houses" },
                    { 77, 110, "An army of Transparent Buildings" },
                    { 78, 238, "The Green Flowers" },
                    { 79, 74, "Fifteen Large Cars" },
                    { 80, 92, "An army of Green Leopards" },
                    { 81, 147, "Fifteen Green Houses" },
                    { 82, 101, "A herd of Large Flowers" },
                    { 83, 75, "Several Transparent Buildings" },
                    { 84, 200, "Fifteen Microscopic Planets" },
                    { 85, 74, "A herd of Transparent Houses" },
                    { 86, 182, "Fifteen Purple Buildings" },
                    { 87, 56, "A bunch of Transparent Flowers" },
                    { 88, 184, "A bunch of Microscopic Cars" },
                    { 89, 128, "The Bitter Leopards" },
                    { 90, 227, "Several Microscopic Planets" },
                    { 91, 142, "An army of Orange Cars" },
                    { 92, 1, "Two Bitter Cars" },
                    { 93, 218, "An army of Orange Planets" },
                    { 94, 151, "A herd of Transparent Cars" },
                    { 95, 246, "A herd of Rose Smelling Flowers" },
                    { 96, 17, "A bunch of Transparent Buildings" },
                    { 97, 234, "A herd of Microscopic Buildings" },
                    { 98, 54, "Fifteen Orange Buildings" },
                    { 99, 111, "An army of Purple Houses" },
                    { 100, 143, "A herd of Large Leopards" },
                    { 101, 101, "A herd of Bitter Cars" },
                    { 102, 98, "A bunch of Green Houses" },
                    { 103, 37, "A herd of Bitter Leopards" },
                    { 104, 126, "Fifteen Bitter Buildings" },
                    { 105, 183, "A bunch of Purple Buildings" },
                    { 106, 123, "Two Transparent Cars" },
                    { 107, 58, "A herd of Rose Smelling Houses" },
                    { 108, 98, "A herd of Rose Smelling Buildings" },
                    { 109, 233, "Several Green Cars" },
                    { 110, 65, "Fifteen Orange Cars" },
                    { 111, 14, "The Orange Houses" },
                    { 112, 76, "Fifteen Microscopic Leopards" },
                    { 113, 107, "An army of Green Planets" },
                    { 114, 174, "Two Transparent Planets" },
                    { 115, 91, "Several Rose Smelling Houses" },
                    { 116, 28, "An army of Large Leopards" },
                    { 117, 97, "Several Orange Buildings" },
                    { 118, 186, "A herd of Transparent Buildings" },
                    { 119, 86, "The Rose Smelling Planets" },
                    { 120, 120, "Two Large Buildings" },
                    { 121, 40, "The Microscopic Houses" },
                    { 122, 78, "Two Large Buildings" },
                    { 123, 148, "Several Microscopic Leopards" },
                    { 124, 238, "A herd of Rose Smelling Leopards" },
                    { 125, 82, "Several Microscopic Leopards" },
                    { 126, 63, "Several Orange Houses" },
                    { 127, 121, "Two Bitter Buildings" },
                    { 128, 9, "The Purple Leopards" },
                    { 129, 167, "Two Bitter Cars" },
                    { 130, 161, "The Orange Flowers" },
                    { 131, 224, "An army of Orange Cars" },
                    { 132, 70, "The Bitter Flowers" },
                    { 133, 123, "A herd of Microscopic Buildings" },
                    { 134, 58, "Two Rose Smelling Cars" },
                    { 135, 225, "Two Bitter Cars" },
                    { 136, 88, "Fifteen Green Houses" },
                    { 137, 50, "A bunch of Green Leopards" },
                    { 138, 177, "Two Microscopic Cars" },
                    { 139, 230, "A bunch of Bitter Flowers" },
                    { 140, 173, "A herd of Transparent Leopards" },
                    { 141, 22, "The Rose Smelling Buildings" },
                    { 142, 239, "An army of Transparent Houses" },
                    { 143, 84, "A bunch of Large Cars" },
                    { 144, 57, "Several Purple Flowers" },
                    { 145, 245, "A bunch of Green Buildings" },
                    { 146, 131, "Fifteen Microscopic Leopards" },
                    { 147, 6, "Several Transparent Leopards" },
                    { 148, 190, "A herd of Microscopic Planets" },
                    { 149, 111, "The Rose Smelling Cars" },
                    { 150, 213, "A bunch of Purple Buildings" },
                    { 151, 178, "The Microscopic Flowers" },
                    { 152, 167, "Fifteen Green Houses" },
                    { 153, 228, "A bunch of Microscopic Leopards" },
                    { 154, 36, "Two Bitter Buildings" },
                    { 155, 128, "A herd of Orange Leopards" },
                    { 156, 50, "An army of Large Leopards" },
                    { 157, 167, "Fifteen Microscopic Leopards" },
                    { 158, 107, "Two Orange Buildings" },
                    { 159, 233, "A bunch of Orange Cars" },
                    { 160, 163, "Fifteen Microscopic Flowers" },
                    { 161, 245, "The Microscopic Cars" },
                    { 162, 146, "Two Orange Planets" },
                    { 163, 131, "Several Microscopic Leopards" },
                    { 164, 197, "Fifteen Transparent Leopards" },
                    { 165, 197, "Several Large Leopards" },
                    { 166, 11, "An army of Green Planets" },
                    { 167, 237, "Two Transparent Leopards" },
                    { 168, 223, "An army of Transparent Flowers" },
                    { 169, 23, "A herd of Microscopic Buildings" },
                    { 170, 53, "The Large Cars" },
                    { 171, 242, "A herd of Purple Buildings" },
                    { 172, 216, "Fifteen Bitter Flowers" },
                    { 173, 207, "A herd of Green Houses" },
                    { 174, 216, "An army of Purple Leopards" },
                    { 175, 46, "An army of Rose Smelling Cars" },
                    { 176, 217, "Two Bitter Flowers" },
                    { 177, 9, "A herd of Rose Smelling Flowers" },
                    { 178, 44, "The Orange Houses" },
                    { 179, 47, "An army of Rose Smelling Flowers" },
                    { 180, 158, "Several Bitter Flowers" },
                    { 181, 145, "A herd of Purple Planets" },
                    { 182, 95, "Fifteen Purple Flowers" },
                    { 183, 209, "Several Transparent Flowers" },
                    { 184, 184, "Fifteen Transparent Buildings" },
                    { 185, 79, "Several Orange Houses" },
                    { 186, 24, "An army of Microscopic Planets" },
                    { 187, 232, "Fifteen Orange Flowers" },
                    { 188, 2, "Two Transparent Houses" },
                    { 189, 3, "A bunch of Purple Buildings" },
                    { 190, 174, "A herd of Orange Flowers" },
                    { 191, 129, "Two Transparent Flowers" },
                    { 192, 51, "Several Transparent Buildings" },
                    { 193, 73, "The Orange Planets" },
                    { 194, 164, "Several Purple Cars" },
                    { 195, 215, "Fifteen Rose Smelling Cars" },
                    { 196, 124, "The Microscopic Flowers" },
                    { 197, 108, "An army of Purple Planets" },
                    { 198, 189, "A herd of Bitter Houses" },
                    { 199, 33, "Two Large Leopards" },
                    { 200, 123, "Several Bitter Flowers" },
                    { 201, 5, "The Microscopic Buildings" },
                    { 202, 6, "Several Large Houses" },
                    { 203, 87, "A herd of Green Houses" },
                    { 204, 30, "Two Purple Cars" },
                    { 205, 57, "A herd of Large Cars" },
                    { 206, 113, "The Microscopic Flowers" },
                    { 207, 25, "Two Purple Leopards" },
                    { 208, 176, "An army of Transparent Cars" },
                    { 209, 207, "Several Large Buildings" },
                    { 210, 24, "An army of Large Cars" },
                    { 211, 149, "Two Microscopic Flowers" },
                    { 212, 170, "Several Purple Cars" },
                    { 213, 33, "An army of Transparent Houses" },
                    { 214, 56, "Two Orange Leopards" },
                    { 215, 231, "Fifteen Rose Smelling Buildings" },
                    { 216, 72, "An army of Transparent Buildings" },
                    { 217, 198, "Fifteen Bitter Flowers" },
                    { 218, 110, "An army of Bitter Planets" },
                    { 219, 223, "The Large Houses" },
                    { 220, 212, "Several Rose Smelling Flowers" },
                    { 221, 219, "The Large Cars" },
                    { 222, 49, "Fifteen Purple Flowers" },
                    { 223, 13, "Fifteen Rose Smelling Planets" },
                    { 224, 151, "An army of Transparent Planets" },
                    { 225, 123, "Fifteen Orange Houses" },
                    { 226, 137, "The Microscopic Buildings" },
                    { 227, 34, "Fifteen Large Cars" },
                    { 228, 175, "A herd of Rose Smelling Buildings" },
                    { 229, 206, "The Large Buildings" },
                    { 230, 186, "Fifteen Rose Smelling Buildings" },
                    { 231, 183, "Two Green Buildings" },
                    { 232, 225, "A herd of Green Flowers" },
                    { 233, 196, "An army of Microscopic Houses" },
                    { 234, 150, "The Purple Leopards" },
                    { 235, 138, "Fifteen Purple Leopards" },
                    { 236, 61, "An army of Purple Leopards" },
                    { 237, 153, "A herd of Purple Cars" },
                    { 238, 243, "Two Green Cars" },
                    { 239, 143, "A bunch of Transparent Buildings" },
                    { 240, 76, "The Orange Houses" },
                    { 241, 79, "The Orange Leopards" },
                    { 242, 64, "Two Orange Buildings" },
                    { 243, 57, "A herd of Rose Smelling Houses" },
                    { 244, 226, "A herd of Transparent Buildings" },
                    { 245, 41, "Fifteen Microscopic Flowers" },
                    { 246, 247, "Two Green Cars" },
                    { 247, 53, "Two Purple Leopards" },
                    { 248, 176, "The Rose Smelling Planets" },
                    { 249, 63, "Two Bitter Leopards" }
                });

            migrationBuilder.InsertData(
                table: "book_author",
                columns: new[] { "id", "author_id", "book_id" },
                values: new object[,]
                {
                    { 1, 193, 143 },
                    { 2, 245, 164 },
                    { 4, 147, 170 },
                    { 5, 238, 6 },
                    { 7, 31, 81 },
                    { 8, 80, 238 },
                    { 10, 235, 25 },
                    { 11, 62, 35 },
                    { 13, 219, 18 },
                    { 14, 190, 185 },
                    { 16, 181, 138 },
                    { 17, 112, 183 },
                    { 19, 32, 54 },
                    { 20, 185, 48 },
                    { 22, 72, 156 },
                    { 23, 166, 58 },
                    { 25, 72, 144 },
                    { 26, 219, 8 },
                    { 28, 207, 191 },
                    { 29, 239, 135 },
                    { 31, 186, 78 },
                    { 32, 170, 162 },
                    { 34, 212, 151 },
                    { 35, 237, 227 },
                    { 37, 139, 49 },
                    { 38, 177, 20 },
                    { 40, 142, 78 },
                    { 41, 81, 133 },
                    { 43, 85, 24 },
                    { 44, 104, 2 },
                    { 46, 201, 167 },
                    { 47, 8, 112 },
                    { 49, 196, 83 },
                    { 50, 137, 186 },
                    { 52, 19, 3 },
                    { 53, 185, 146 },
                    { 55, 117, 81 },
                    { 56, 53, 159 },
                    { 58, 183, 191 },
                    { 59, 107, 143 },
                    { 61, 102, 227 },
                    { 62, 131, 33 },
                    { 64, 16, 65 },
                    { 65, 194, 41 },
                    { 67, 22, 127 },
                    { 68, 31, 76 },
                    { 70, 193, 96 },
                    { 71, 54, 206 },
                    { 73, 63, 77 },
                    { 74, 242, 231 },
                    { 76, 20, 243 },
                    { 77, 38, 206 },
                    { 79, 122, 34 },
                    { 80, 94, 73 },
                    { 82, 245, 27 },
                    { 83, 16, 37 },
                    { 85, 71, 90 },
                    { 86, 82, 233 },
                    { 88, 201, 87 },
                    { 89, 198, 82 },
                    { 91, 132, 203 },
                    { 92, 212, 218 },
                    { 94, 183, 243 },
                    { 95, 223, 58 },
                    { 97, 8, 75 },
                    { 98, 17, 77 },
                    { 100, 201, 149 },
                    { 101, 53, 64 },
                    { 103, 200, 95 },
                    { 104, 172, 135 },
                    { 106, 66, 62 },
                    { 107, 54, 64 },
                    { 109, 20, 248 },
                    { 110, 169, 30 },
                    { 112, 65, 128 },
                    { 113, 87, 190 },
                    { 115, 9, 50 },
                    { 116, 217, 95 },
                    { 118, 211, 192 },
                    { 119, 125, 155 },
                    { 121, 97, 70 },
                    { 122, 103, 63 },
                    { 124, 24, 104 },
                    { 125, 248, 239 },
                    { 127, 86, 15 },
                    { 128, 5, 144 },
                    { 130, 69, 216 },
                    { 131, 154, 9 },
                    { 133, 73, 40 },
                    { 134, 246, 92 },
                    { 136, 25, 13 },
                    { 137, 85, 33 },
                    { 139, 130, 88 },
                    { 140, 91, 119 },
                    { 142, 96, 249 },
                    { 143, 173, 237 },
                    { 145, 109, 154 },
                    { 146, 70, 248 },
                    { 148, 90, 168 },
                    { 149, 102, 19 },
                    { 151, 61, 109 },
                    { 152, 92, 88 },
                    { 154, 1, 10 },
                    { 155, 238, 188 },
                    { 157, 158, 227 },
                    { 158, 67, 234 },
                    { 160, 80, 91 },
                    { 161, 72, 235 },
                    { 163, 120, 173 },
                    { 164, 199, 178 },
                    { 166, 137, 89 },
                    { 167, 65, 183 },
                    { 169, 16, 181 },
                    { 170, 202, 41 },
                    { 172, 17, 232 },
                    { 173, 122, 86 },
                    { 175, 44, 67 },
                    { 176, 98, 97 },
                    { 178, 155, 207 },
                    { 179, 196, 214 },
                    { 181, 164, 18 },
                    { 182, 208, 29 },
                    { 184, 135, 230 },
                    { 185, 209, 242 },
                    { 187, 168, 42 },
                    { 188, 59, 116 },
                    { 190, 43, 205 },
                    { 191, 243, 4 },
                    { 193, 154, 236 },
                    { 194, 164, 197 },
                    { 196, 83, 228 },
                    { 197, 220, 226 },
                    { 199, 244, 228 },
                    { 200, 55, 88 },
                    { 202, 99, 108 },
                    { 203, 190, 168 },
                    { 205, 103, 141 },
                    { 206, 119, 37 },
                    { 208, 182, 106 },
                    { 209, 233, 5 },
                    { 211, 61, 205 },
                    { 212, 159, 207 },
                    { 214, 95, 234 },
                    { 215, 20, 91 },
                    { 217, 25, 74 },
                    { 218, 155, 164 },
                    { 220, 88, 158 },
                    { 221, 112, 99 },
                    { 223, 119, 110 },
                    { 224, 187, 200 },
                    { 226, 11, 32 },
                    { 227, 76, 5 },
                    { 229, 134, 221 },
                    { 230, 70, 27 },
                    { 232, 87, 159 },
                    { 233, 191, 133 },
                    { 235, 38, 24 },
                    { 236, 83, 94 },
                    { 238, 81, 23 },
                    { 239, 182, 172 },
                    { 241, 167, 212 },
                    { 242, 64, 21 },
                    { 244, 106, 106 },
                    { 245, 89, 10 },
                    { 247, 135, 219 },
                    { 248, 89, 224 },
                    { 250, 236, 120 },
                    { 251, 7, 30 },
                    { 253, 149, 158 },
                    { 254, 239, 178 },
                    { 256, 195, 91 },
                    { 257, 192, 114 },
                    { 259, 131, 83 },
                    { 260, 111, 130 },
                    { 262, 28, 62 },
                    { 263, 126, 145 },
                    { 265, 44, 181 },
                    { 266, 77, 14 },
                    { 268, 12, 150 },
                    { 269, 78, 168 },
                    { 271, 136, 236 },
                    { 272, 16, 203 },
                    { 274, 166, 94 },
                    { 275, 230, 77 },
                    { 277, 173, 64 },
                    { 278, 113, 137 },
                    { 280, 233, 150 },
                    { 281, 224, 165 },
                    { 283, 165, 28 },
                    { 284, 10, 233 },
                    { 286, 17, 162 },
                    { 287, 190, 64 },
                    { 289, 22, 4 },
                    { 290, 124, 211 },
                    { 292, 218, 143 },
                    { 293, 223, 46 },
                    { 295, 172, 55 },
                    { 296, 77, 193 },
                    { 298, 233, 33 },
                    { 299, 201, 137 },
                    { 301, 135, 224 },
                    { 302, 221, 120 },
                    { 304, 200, 64 },
                    { 305, 143, 36 },
                    { 307, 190, 104 },
                    { 308, 57, 168 },
                    { 310, 234, 135 },
                    { 311, 106, 155 },
                    { 313, 247, 172 },
                    { 314, 187, 179 },
                    { 316, 19, 185 },
                    { 317, 176, 136 },
                    { 319, 243, 60 },
                    { 320, 24, 194 },
                    { 322, 26, 141 },
                    { 323, 148, 76 },
                    { 325, 184, 183 },
                    { 326, 25, 208 },
                    { 328, 87, 58 },
                    { 329, 178, 218 },
                    { 331, 58, 172 },
                    { 332, 222, 153 },
                    { 334, 62, 156 },
                    { 335, 54, 143 },
                    { 337, 32, 61 },
                    { 338, 15, 93 },
                    { 340, 29, 190 },
                    { 341, 198, 206 },
                    { 343, 51, 123 },
                    { 344, 119, 183 },
                    { 346, 50, 122 },
                    { 347, 85, 227 },
                    { 349, 179, 199 },
                    { 350, 31, 149 },
                    { 352, 154, 27 },
                    { 353, 201, 167 },
                    { 355, 14, 249 },
                    { 356, 32, 48 },
                    { 358, 155, 232 },
                    { 359, 123, 177 },
                    { 361, 100, 141 },
                    { 362, 183, 87 },
                    { 364, 233, 131 },
                    { 365, 240, 117 },
                    { 367, 81, 167 },
                    { 368, 37, 29 },
                    { 370, 133, 5 },
                    { 371, 24, 72 },
                    { 373, 8, 185 },
                    { 374, 51, 175 },
                    { 376, 197, 232 },
                    { 377, 29, 143 },
                    { 379, 41, 141 },
                    { 380, 238, 91 },
                    { 382, 202, 3 },
                    { 383, 139, 43 },
                    { 385, 18, 128 },
                    { 386, 222, 184 },
                    { 388, 146, 177 },
                    { 389, 169, 169 },
                    { 391, 110, 109 },
                    { 392, 168, 68 },
                    { 394, 23, 216 },
                    { 395, 149, 135 },
                    { 397, 211, 199 },
                    { 398, 152, 94 },
                    { 400, 101, 87 },
                    { 401, 164, 46 },
                    { 403, 143, 63 },
                    { 404, 246, 15 },
                    { 406, 248, 150 },
                    { 407, 159, 171 },
                    { 409, 213, 213 },
                    { 410, 15, 146 },
                    { 412, 204, 176 },
                    { 413, 12, 171 },
                    { 415, 186, 63 },
                    { 416, 134, 138 },
                    { 418, 121, 44 },
                    { 419, 58, 14 },
                    { 421, 184, 116 },
                    { 422, 146, 178 },
                    { 424, 11, 39 },
                    { 425, 87, 85 },
                    { 427, 194, 194 },
                    { 428, 199, 28 },
                    { 430, 187, 147 },
                    { 431, 156, 235 },
                    { 433, 84, 113 },
                    { 434, 190, 109 },
                    { 436, 141, 245 },
                    { 437, 167, 178 },
                    { 439, 95, 50 },
                    { 440, 202, 229 },
                    { 442, 245, 223 },
                    { 443, 232, 152 },
                    { 445, 71, 231 },
                    { 446, 95, 196 },
                    { 448, 97, 163 },
                    { 449, 182, 18 },
                    { 451, 78, 179 },
                    { 452, 197, 238 },
                    { 454, 182, 59 },
                    { 455, 100, 227 },
                    { 457, 99, 94 },
                    { 458, 43, 131 },
                    { 460, 170, 200 },
                    { 461, 234, 115 },
                    { 463, 23, 9 },
                    { 464, 179, 79 },
                    { 466, 50, 147 },
                    { 467, 34, 38 },
                    { 469, 234, 175 },
                    { 470, 217, 59 },
                    { 472, 12, 139 },
                    { 473, 228, 116 },
                    { 475, 13, 89 },
                    { 476, 172, 118 },
                    { 478, 80, 44 },
                    { 479, 149, 164 },
                    { 481, 178, 159 },
                    { 482, 187, 55 },
                    { 484, 216, 103 },
                    { 485, 205, 33 },
                    { 487, 79, 183 },
                    { 488, 126, 162 },
                    { 490, 239, 236 },
                    { 491, 145, 204 },
                    { 493, 46, 199 },
                    { 494, 172, 99 },
                    { 496, 168, 224 },
                    { 497, 243, 107 },
                    { 499, 122, 96 },
                    { 500, 215, 110 },
                    { 502, 88, 51 },
                    { 503, 54, 153 },
                    { 505, 58, 122 },
                    { 506, 56, 236 },
                    { 508, 17, 166 },
                    { 509, 115, 89 },
                    { 511, 209, 179 },
                    { 512, 214, 149 },
                    { 514, 184, 52 },
                    { 515, 236, 40 },
                    { 517, 97, 61 },
                    { 518, 249, 171 },
                    { 520, 160, 48 },
                    { 521, 121, 87 },
                    { 523, 50, 249 },
                    { 524, 101, 184 },
                    { 526, 116, 110 },
                    { 527, 127, 137 },
                    { 529, 70, 247 },
                    { 530, 11, 42 },
                    { 532, 4, 142 },
                    { 533, 128, 138 },
                    { 535, 151, 207 },
                    { 536, 218, 5 },
                    { 538, 214, 68 },
                    { 539, 144, 19 },
                    { 541, 216, 185 },
                    { 542, 179, 166 },
                    { 544, 193, 153 },
                    { 545, 214, 51 },
                    { 547, 128, 39 },
                    { 548, 56, 84 },
                    { 550, 225, 33 },
                    { 551, 24, 129 },
                    { 553, 84, 171 },
                    { 554, 35, 123 },
                    { 556, 168, 149 },
                    { 557, 201, 126 },
                    { 559, 201, 246 },
                    { 560, 75, 33 },
                    { 562, 148, 98 },
                    { 563, 159, 135 },
                    { 565, 222, 245 },
                    { 566, 68, 244 },
                    { 568, 242, 239 },
                    { 569, 215, 110 },
                    { 571, 47, 192 },
                    { 572, 222, 65 },
                    { 574, 225, 97 },
                    { 575, 213, 190 },
                    { 577, 23, 3 },
                    { 578, 115, 15 },
                    { 580, 158, 162 },
                    { 581, 213, 90 },
                    { 583, 123, 238 },
                    { 584, 156, 46 },
                    { 586, 112, 195 },
                    { 587, 244, 169 },
                    { 589, 165, 33 },
                    { 590, 235, 57 },
                    { 592, 85, 155 },
                    { 593, 211, 214 },
                    { 595, 241, 165 },
                    { 596, 142, 68 },
                    { 598, 85, 20 },
                    { 599, 31, 240 },
                    { 601, 84, 117 },
                    { 602, 234, 17 },
                    { 604, 69, 138 },
                    { 605, 124, 78 },
                    { 607, 13, 185 },
                    { 608, 198, 77 },
                    { 610, 44, 50 },
                    { 611, 44, 241 },
                    { 613, 22, 175 },
                    { 614, 19, 213 },
                    { 616, 226, 228 },
                    { 617, 55, 156 },
                    { 619, 185, 241 },
                    { 620, 177, 126 },
                    { 622, 247, 5 },
                    { 623, 172, 220 },
                    { 625, 77, 10 },
                    { 626, 194, 119 },
                    { 628, 5, 11 },
                    { 629, 3, 9 },
                    { 631, 206, 217 },
                    { 632, 240, 235 },
                    { 634, 102, 178 },
                    { 635, 132, 131 },
                    { 637, 77, 56 },
                    { 638, 92, 244 },
                    { 640, 51, 24 },
                    { 641, 85, 146 },
                    { 643, 90, 203 },
                    { 644, 159, 159 },
                    { 646, 44, 125 },
                    { 647, 115, 60 },
                    { 649, 5, 247 },
                    { 650, 115, 237 },
                    { 652, 123, 227 },
                    { 653, 125, 169 },
                    { 655, 21, 149 },
                    { 656, 167, 6 },
                    { 658, 2, 245 },
                    { 659, 249, 82 },
                    { 661, 160, 184 },
                    { 662, 171, 204 },
                    { 664, 88, 132 },
                    { 665, 66, 60 },
                    { 667, 51, 138 },
                    { 668, 156, 166 },
                    { 670, 62, 20 },
                    { 671, 6, 72 },
                    { 673, 210, 63 },
                    { 674, 164, 160 },
                    { 676, 164, 94 },
                    { 677, 23, 187 },
                    { 679, 212, 207 },
                    { 680, 77, 132 },
                    { 682, 55, 243 },
                    { 683, 207, 131 },
                    { 685, 43, 204 },
                    { 686, 77, 144 },
                    { 688, 116, 237 },
                    { 689, 29, 114 },
                    { 691, 127, 106 },
                    { 692, 201, 114 },
                    { 694, 30, 29 },
                    { 695, 210, 120 },
                    { 697, 25, 177 },
                    { 698, 34, 162 },
                    { 700, 196, 22 },
                    { 701, 196, 220 },
                    { 703, 219, 240 },
                    { 704, 188, 132 },
                    { 706, 213, 18 },
                    { 707, 228, 184 },
                    { 709, 5, 13 },
                    { 710, 196, 213 },
                    { 712, 125, 210 },
                    { 713, 220, 92 },
                    { 715, 223, 160 },
                    { 716, 53, 65 },
                    { 718, 176, 72 },
                    { 719, 239, 32 },
                    { 721, 21, 93 },
                    { 722, 130, 127 },
                    { 724, 166, 114 },
                    { 725, 46, 144 },
                    { 727, 168, 15 },
                    { 728, 182, 216 },
                    { 730, 180, 113 },
                    { 731, 231, 89 },
                    { 733, 236, 152 },
                    { 734, 203, 95 },
                    { 736, 106, 133 },
                    { 737, 136, 192 },
                    { 739, 239, 207 },
                    { 740, 93, 133 },
                    { 742, 46, 246 },
                    { 743, 136, 153 },
                    { 745, 240, 222 },
                    { 746, 184, 121 }
                });

            migrationBuilder.CreateIndex(
                name: "IX_book_publisher_id",
                table: "book",
                column: "publisher_id");

            migrationBuilder.CreateIndex(
                name: "IX_book_author_author_id",
                table: "book_author",
                column: "author_id");

            migrationBuilder.CreateIndex(
                name: "IX_book_author_book_id",
                table: "book_author",
                column: "book_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "book_author");

            migrationBuilder.DropTable(
                name: "author");

            migrationBuilder.DropTable(
                name: "book");

            migrationBuilder.DropTable(
                name: "publisher");
        }
    }
}
