using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class firstcommit : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    first_name = table.Column<string>(type: "text", nullable: false),
                    last_name = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "publishers",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_publishers", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    publisher_id = table.Column<int>(type: "integer", nullable: false),
                    author_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_authors_author_id",
                        column: x => x.author_id,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_books_publishers_publisher_id",
                        column: x => x.publisher_id,
                        principalTable: "publishers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "authors",
                columns: new[] { "id", "email", "first_name", "last_name" },
                values: new object[,]
                {
                    { 1, "audrey.winfrey@gov.gr", "Audrey", "Winfrey" },
                    { 2, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 3, "mick.jagger@gov.ru", "Mick", "Jagger" },
                    { 4, "jimi.hepburn@gov.gr", "Jimi", "Hepburn" },
                    { 5, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 6, "oprah.hepburn@gov.gr", "Oprah", "Hepburn" },
                    { 7, "kate.hendrix@theworld.ca", "Kate", "Hendrix" },
                    { 8, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 9, "audrey.presley@theworld.ca", "Audrey", "Presley" },
                    { 10, "kate.winslet@something.com", "Kate", "Winslet" },
                    { 11, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 12, "barack.trump@gov.ru", "Barack", "Trump" },
                    { 13, "elvis.hepburn@gov.ru", "Elvis", "Hepburn" },
                    { 14, "donald.winfrey@gov.gr", "Donald", "Winfrey" },
                    { 15, "charles.winslet@bbc.co.uk", "Charles", "Winslet" },
                    { 16, "mick.jagger@gov.nl", "Mick", "Jagger" },
                    { 17, "mick.winfrey@gov.ru", "Mick", "Winfrey" },
                    { 18, "elvis.middleton@google.com", "Elvis", "Middleton" },
                    { 19, "mick.obama@gov.us", "Mick", "Obama" },
                    { 20, "oprah.hepburn@gov.nl", "Oprah", "Hepburn" },
                    { 21, "oprah.hendrix@gov.nl", "Oprah", "Hendrix" },
                    { 22, "audrey.trump@tesla.com", "Audrey", "Trump" },
                    { 23, "donald.windsor@gov.gr", "Donald", "Windsor" },
                    { 24, "kate.trump@google.com", "Kate", "Trump" },
                    { 25, "oprah.hepburn@gov.ru", "Oprah", "Hepburn" },
                    { 26, "charles.hendrix@gov.ru", "Charles", "Hendrix" },
                    { 27, "elvis.winslet@gov.nl", "Elvis", "Winslet" },
                    { 28, "jimi.hendrix@bbc.co.uk", "Jimi", "Hendrix" },
                    { 29, "charles.winfrey@tesla.com", "Charles", "Winfrey" },
                    { 30, "donald.winfrey@gov.gr", "Donald", "Winfrey" },
                    { 31, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 32, "barack.trump@gov.us", "Barack", "Trump" },
                    { 33, "jimi.presley@gov.ru", "Jimi", "Presley" },
                    { 34, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 35, "barack.obama@tesla.com", "Barack", "Obama" },
                    { 36, "oprah.winslet@tesla.com", "Oprah", "Winslet" },
                    { 37, "kate.obama@google.com", "Kate", "Obama" },
                    { 38, "jimi.hepburn@gov.ru", "Jimi", "Hepburn" },
                    { 39, "oprah.jagger@gov.gr", "Oprah", "Jagger" },
                    { 40, "elvis.obama@bbc.co.uk", "Elvis", "Obama" },
                    { 41, "jimi.windsor@something.com", "Jimi", "Windsor" },
                    { 42, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 43, "jimi.hepburn@gov.gr", "Jimi", "Hepburn" },
                    { 44, "mick.winfrey@nasa.org.us", "Mick", "Winfrey" },
                    { 45, "oprah.winfrey@gov.us", "Oprah", "Winfrey" },
                    { 46, "kate.trump@google.com", "Kate", "Trump" },
                    { 47, "jimi.trump@theworld.ca", "Jimi", "Trump" },
                    { 48, "oprah.obama@nasa.org.us", "Oprah", "Obama" },
                    { 49, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 50, "elvis.presley@gov.ru", "Elvis", "Presley" },
                    { 51, "donald.trump@gov.gr", "Donald", "Trump" },
                    { 52, "kate.presley@gov.us", "Kate", "Presley" },
                    { 53, "jimi.winfrey@something.com", "Jimi", "Winfrey" },
                    { 54, "kate.winfrey@bbc.co.uk", "Kate", "Winfrey" },
                    { 55, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 56, "jimi.trump@gov.us", "Jimi", "Trump" },
                    { 57, "kate.presley@theworld.ca", "Kate", "Presley" },
                    { 58, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 59, "donald.windsor@google.com", "Donald", "Windsor" },
                    { 60, "oprah.hendrix@gov.us", "Oprah", "Hendrix" },
                    { 61, "elvis.windsor@gov.us", "Elvis", "Windsor" },
                    { 62, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 63, "mick.obama@something.com", "Mick", "Obama" },
                    { 64, "charles.trump@gov.gr", "Charles", "Trump" },
                    { 65, "oprah.hendrix@gov.gr", "Oprah", "Hendrix" },
                    { 66, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 67, "mick.presley@gov.us", "Mick", "Presley" },
                    { 68, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 69, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 70, "donald.presley@gov.us", "Donald", "Presley" },
                    { 71, "kate.presley@gov.nl", "Kate", "Presley" },
                    { 72, "audrey.presley@bbc.co.uk", "Audrey", "Presley" },
                    { 73, "barack.trump@google.com", "Barack", "Trump" },
                    { 74, "jimi.jagger@something.com", "Jimi", "Jagger" },
                    { 75, "charles.hepburn@bbc.co.uk", "Charles", "Hepburn" },
                    { 76, "elvis.jagger@gov.gr", "Elvis", "Jagger" },
                    { 77, "charles.obama@bbc.co.uk", "Charles", "Obama" },
                    { 78, "oprah.trump@nasa.org.us", "Oprah", "Trump" },
                    { 79, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 80, "jimi.middleton@google.com", "Jimi", "Middleton" },
                    { 81, "charles.presley@gov.us", "Charles", "Presley" },
                    { 82, "charles.obama@nasa.org.us", "Charles", "Obama" },
                    { 83, "donald.winfrey@gov.gr", "Donald", "Winfrey" },
                    { 84, "kate.trump@nasa.org.us", "Kate", "Trump" },
                    { 85, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 86, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 87, "charles.winfrey@theworld.ca", "Charles", "Winfrey" },
                    { 88, "oprah.jagger@tesla.com", "Oprah", "Jagger" },
                    { 89, "mick.windsor@gov.ru", "Mick", "Windsor" },
                    { 90, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 91, "elvis.presley@bbc.co.uk", "Elvis", "Presley" },
                    { 92, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 93, "oprah.winfrey@theworld.ca", "Oprah", "Winfrey" },
                    { 94, "audrey.obama@bbc.co.uk", "Audrey", "Obama" },
                    { 95, "mick.jagger@google.com", "Mick", "Jagger" },
                    { 96, "charles.presley@gov.ru", "Charles", "Presley" },
                    { 97, "oprah.middleton@gov.ru", "Oprah", "Middleton" },
                    { 98, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 99, "barack.obama@gov.us", "Barack", "Obama" },
                    { 100, "oprah.obama@gov.nl", "Oprah", "Obama" },
                    { 101, "donald.hendrix@nasa.org.us", "Donald", "Hendrix" },
                    { 102, "audrey.windsor@tesla.com", "Audrey", "Windsor" },
                    { 103, "mick.obama@google.com", "Mick", "Obama" },
                    { 104, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 105, "charles.hepburn@google.com", "Charles", "Hepburn" },
                    { 106, "barack.hepburn@something.com", "Barack", "Hepburn" },
                    { 107, "mick.trump@gov.nl", "Mick", "Trump" },
                    { 108, "elvis.winslet@gov.nl", "Elvis", "Winslet" },
                    { 109, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 110, "jimi.middleton@gov.gr", "Jimi", "Middleton" },
                    { 111, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 112, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 113, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 114, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 115, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 116, "jimi.obama@nasa.org.us", "Jimi", "Obama" },
                    { 117, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 118, "kate.trump@tesla.com", "Kate", "Trump" },
                    { 119, "kate.presley@gov.nl", "Kate", "Presley" },
                    { 120, "charles.jagger@theworld.ca", "Charles", "Jagger" },
                    { 121, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 122, "barack.jagger@nasa.org.us", "Barack", "Jagger" },
                    { 123, "mick.presley@theworld.ca", "Mick", "Presley" },
                    { 124, "jimi.winslet@gov.gr", "Jimi", "Winslet" },
                    { 125, "barack.winslet@tesla.com", "Barack", "Winslet" },
                    { 126, "jimi.jagger@gov.ru", "Jimi", "Jagger" },
                    { 127, "jimi.windsor@gov.nl", "Jimi", "Windsor" },
                    { 128, "donald.jagger@something.com", "Donald", "Jagger" },
                    { 129, "charles.windsor@theworld.ca", "Charles", "Windsor" },
                    { 130, "charles.windsor@bbc.co.uk", "Charles", "Windsor" },
                    { 131, "kate.hendrix@bbc.co.uk", "Kate", "Hendrix" },
                    { 132, "jimi.middleton@tesla.com", "Jimi", "Middleton" },
                    { 133, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 134, "mick.obama@something.com", "Mick", "Obama" },
                    { 135, "mick.winslet@gov.us", "Mick", "Winslet" },
                    { 136, "jimi.obama@gov.nl", "Jimi", "Obama" },
                    { 137, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 138, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 139, "elvis.trump@gov.nl", "Elvis", "Trump" },
                    { 140, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 141, "charles.hepburn@something.com", "Charles", "Hepburn" },
                    { 142, "kate.obama@gov.us", "Kate", "Obama" },
                    { 143, "elvis.jagger@nasa.org.us", "Elvis", "Jagger" },
                    { 144, "donald.presley@gov.gr", "Donald", "Presley" },
                    { 145, "jimi.hendrix@gov.nl", "Jimi", "Hendrix" },
                    { 146, "charles.jagger@nasa.org.us", "Charles", "Jagger" },
                    { 147, "donald.obama@bbc.co.uk", "Donald", "Obama" },
                    { 148, "mick.winfrey@nasa.org.us", "Mick", "Winfrey" },
                    { 149, "jimi.jagger@gov.us", "Jimi", "Jagger" },
                    { 150, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 151, "elvis.hepburn@something.com", "Elvis", "Hepburn" },
                    { 152, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 153, "oprah.trump@nasa.org.us", "Oprah", "Trump" },
                    { 154, "donald.obama@tesla.com", "Donald", "Obama" },
                    { 155, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 156, "elvis.hepburn@gov.gr", "Elvis", "Hepburn" },
                    { 157, "mick.trump@gov.ru", "Mick", "Trump" },
                    { 158, "oprah.middleton@bbc.co.uk", "Oprah", "Middleton" },
                    { 159, "donald.presley@something.com", "Donald", "Presley" },
                    { 160, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 161, "audrey.middleton@theworld.ca", "Audrey", "Middleton" },
                    { 162, "donald.presley@theworld.ca", "Donald", "Presley" },
                    { 163, "elvis.winfrey@gov.nl", "Elvis", "Winfrey" },
                    { 164, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 165, "oprah.windsor@google.com", "Oprah", "Windsor" },
                    { 166, "barack.trump@tesla.com", "Barack", "Trump" },
                    { 167, "charles.trump@gov.nl", "Charles", "Trump" },
                    { 168, "donald.hendrix@gov.gr", "Donald", "Hendrix" },
                    { 169, "mick.presley@something.com", "Mick", "Presley" },
                    { 170, "barack.hendrix@nasa.org.us", "Barack", "Hendrix" },
                    { 171, "jimi.presley@gov.gr", "Jimi", "Presley" },
                    { 172, "jimi.middleton@nasa.org.us", "Jimi", "Middleton" },
                    { 173, "jimi.trump@gov.us", "Jimi", "Trump" },
                    { 174, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 175, "mick.middleton@gov.ru", "Mick", "Middleton" },
                    { 176, "kate.obama@google.com", "Kate", "Obama" },
                    { 177, "kate.middleton@tesla.com", "Kate", "Middleton" },
                    { 178, "kate.jagger@gov.us", "Kate", "Jagger" },
                    { 179, "audrey.jagger@bbc.co.uk", "Audrey", "Jagger" },
                    { 180, "kate.presley@bbc.co.uk", "Kate", "Presley" },
                    { 181, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 182, "elvis.winfrey@something.com", "Elvis", "Winfrey" },
                    { 183, "kate.trump@bbc.co.uk", "Kate", "Trump" },
                    { 184, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 185, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 186, "mick.middleton@gov.us", "Mick", "Middleton" },
                    { 187, "oprah.trump@nasa.org.us", "Oprah", "Trump" },
                    { 188, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 189, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 190, "charles.middleton@tesla.com", "Charles", "Middleton" },
                    { 191, "barack.presley@bbc.co.uk", "Barack", "Presley" },
                    { 192, "charles.presley@tesla.com", "Charles", "Presley" },
                    { 193, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 194, "donald.middleton@gov.gr", "Donald", "Middleton" },
                    { 195, "mick.hepburn@gov.gr", "Mick", "Hepburn" },
                    { 196, "barack.obama@something.com", "Barack", "Obama" },
                    { 197, "kate.trump@gov.us", "Kate", "Trump" },
                    { 198, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 199, "jimi.hepburn@tesla.com", "Jimi", "Hepburn" },
                    { 200, "mick.middleton@nasa.org.us", "Mick", "Middleton" },
                    { 201, "oprah.middleton@gov.us", "Oprah", "Middleton" },
                    { 202, "kate.middleton@gov.us", "Kate", "Middleton" },
                    { 203, "donald.hendrix@gov.ru", "Donald", "Hendrix" },
                    { 204, "jimi.hendrix@bbc.co.uk", "Jimi", "Hendrix" },
                    { 205, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 206, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 207, "barack.obama@gov.gr", "Barack", "Obama" },
                    { 208, "donald.winfrey@theworld.ca", "Donald", "Winfrey" },
                    { 209, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 210, "audrey.presley@gov.gr", "Audrey", "Presley" },
                    { 211, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 212, "audrey.winslet@gov.us", "Audrey", "Winslet" },
                    { 213, "kate.winslet@tesla.com", "Kate", "Winslet" },
                    { 214, "barack.presley@google.com", "Barack", "Presley" },
                    { 215, "donald.winfrey@gov.nl", "Donald", "Winfrey" },
                    { 216, "barack.hepburn@theworld.ca", "Barack", "Hepburn" },
                    { 217, "charles.obama@gov.gr", "Charles", "Obama" },
                    { 218, "audrey.jagger@gov.gr", "Audrey", "Jagger" },
                    { 219, "oprah.hendrix@theworld.ca", "Oprah", "Hendrix" },
                    { 220, "audrey.windsor@gov.gr", "Audrey", "Windsor" },
                    { 221, "charles.trump@google.com", "Charles", "Trump" },
                    { 222, "charles.hendrix@gov.nl", "Charles", "Hendrix" },
                    { 223, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 224, "mick.hendrix@gov.us", "Mick", "Hendrix" },
                    { 225, "barack.winfrey@something.com", "Barack", "Winfrey" },
                    { 226, "donald.hendrix@tesla.com", "Donald", "Hendrix" },
                    { 227, "audrey.presley@something.com", "Audrey", "Presley" },
                    { 228, "charles.winslet@gov.nl", "Charles", "Winslet" },
                    { 229, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 230, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 231, "donald.hendrix@gov.ru", "Donald", "Hendrix" },
                    { 232, "donald.jagger@theworld.ca", "Donald", "Jagger" },
                    { 233, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 234, "oprah.winfrey@bbc.co.uk", "Oprah", "Winfrey" },
                    { 235, "elvis.middleton@theworld.ca", "Elvis", "Middleton" },
                    { 236, "audrey.hepburn@something.com", "Audrey", "Hepburn" },
                    { 237, "charles.middleton@something.com", "Charles", "Middleton" },
                    { 238, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 239, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 240, "oprah.hepburn@nasa.org.us", "Oprah", "Hepburn" },
                    { 241, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 242, "charles.winslet@gov.ru", "Charles", "Winslet" },
                    { 243, "charles.trump@gov.us", "Charles", "Trump" },
                    { 244, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 245, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 246, "barack.winslet@gov.nl", "Barack", "Winslet" },
                    { 247, "elvis.winfrey@nasa.org.us", "Elvis", "Winfrey" },
                    { 248, "jimi.hendrix@tesla.com", "Jimi", "Hendrix" },
                    { 249, "jimi.presley@something.com", "Jimi", "Presley" }
                });

            migrationBuilder.InsertData(
                table: "publishers",
                columns: new[] { "id", "name" },
                values: new object[,]
                {
                    { 1, "Penguin" },
                    { 2, "Random House" },
                    { 3, "Harper Collins" },
                    { 4, "Simon & Schuster" },
                    { 5, "Hachette" },
                    { 6, "Macmillan" },
                    { 7, "Bloomsbury" },
                    { 8, "Scholastic" },
                    { 9, "Pearson" },
                    { 10, "Holtzbrinck" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "author_id", "publisher_id", "title" },
                values: new object[,]
                {
                    { 1, 147, 9, "An army of Orange Flowers" },
                    { 2, 179, 10, "The Bitter Planets" },
                    { 3, 21, 3, "Several Transparent Buildings" },
                    { 4, 159, 2, "A bunch of Transparent Flowers" },
                    { 5, 100, 5, "Several Microscopic Planets" },
                    { 6, 229, 1, "Two Transparent Leopards" },
                    { 7, 63, 9, "The Transparent Flowers" },
                    { 8, 68, 8, "The Large Cars" },
                    { 9, 217, 10, "A herd of Green Planets" },
                    { 10, 113, 10, "Two Green Buildings" },
                    { 11, 32, 5, "Several Microscopic Buildings" },
                    { 12, 235, 5, "Two Microscopic Leopards" },
                    { 13, 94, 1, "The Bitter Buildings" },
                    { 14, 163, 7, "The Green Planets" },
                    { 15, 18, 3, "An army of Microscopic Cars" },
                    { 16, 102, 7, "A herd of Purple Buildings" },
                    { 17, 137, 8, "Two Purple Planets" },
                    { 18, 168, 10, "The Bitter Houses" },
                    { 19, 4, 5, "The Microscopic Cars" },
                    { 20, 6, 1, "The Orange Cars" },
                    { 21, 109, 3, "Two Orange Leopards" },
                    { 22, 198, 1, "Several Purple Planets" },
                    { 23, 179, 2, "The Orange Houses" },
                    { 24, 98, 8, "Fifteen Orange Buildings" },
                    { 25, 15, 4, "Fifteen Purple Cars" },
                    { 26, 179, 5, "The Microscopic Planets" },
                    { 27, 208, 2, "The Transparent Houses" },
                    { 28, 150, 5, "The Purple Planets" },
                    { 29, 224, 9, "Several Transparent Leopards" },
                    { 30, 219, 2, "Two Orange Buildings" },
                    { 31, 150, 9, "A herd of Bitter Houses" },
                    { 32, 177, 10, "A bunch of Purple Houses" },
                    { 33, 175, 10, "A bunch of Purple Planets" },
                    { 34, 26, 5, "Fifteen Purple Planets" },
                    { 35, 125, 8, "The Transparent Cars" },
                    { 36, 134, 8, "An army of Orange Houses" },
                    { 37, 50, 7, "Several Green Cars" },
                    { 38, 32, 5, "Two Microscopic Planets" },
                    { 39, 240, 10, "Two Microscopic Leopards" },
                    { 40, 86, 6, "An army of Bitter Flowers" },
                    { 41, 33, 5, "A bunch of Orange Planets" },
                    { 42, 53, 1, "Fifteen Transparent Flowers" },
                    { 43, 147, 10, "Two Bitter Houses" },
                    { 44, 210, 3, "A bunch of Large Houses" },
                    { 45, 11, 3, "The Orange Buildings" },
                    { 46, 89, 10, "The Orange Houses" },
                    { 47, 186, 8, "Several Green Cars" },
                    { 48, 140, 3, "A herd of Large Flowers" },
                    { 49, 19, 5, "Several Large Houses" },
                    { 50, 133, 2, "A herd of Purple Houses" },
                    { 51, 95, 7, "Fifteen Orange Cars" },
                    { 52, 8, 2, "Two Large Planets" },
                    { 53, 17, 4, "Fifteen Transparent Leopards" },
                    { 54, 180, 9, "Two Purple Cars" },
                    { 55, 249, 5, "Fifteen Purple Buildings" },
                    { 56, 189, 1, "A bunch of Microscopic Buildings" },
                    { 57, 70, 9, "The Large Houses" },
                    { 58, 173, 1, "A bunch of Large Leopards" },
                    { 59, 225, 1, "An army of Purple Cars" },
                    { 60, 144, 4, "Several Green Leopards" },
                    { 61, 71, 6, "An army of Rose Smelling Flowers" },
                    { 62, 147, 10, "The Purple Houses" },
                    { 63, 123, 4, "A herd of Purple Cars" },
                    { 64, 51, 2, "Fifteen Large Flowers" },
                    { 65, 150, 6, "An army of Microscopic Leopards" },
                    { 66, 204, 1, "A bunch of Orange Houses" },
                    { 67, 210, 3, "Fifteen Transparent Planets" },
                    { 68, 148, 5, "Two Microscopic Flowers" },
                    { 69, 91, 6, "Several Microscopic Buildings" },
                    { 70, 173, 9, "Two Transparent Leopards" },
                    { 71, 204, 8, "A bunch of Microscopic Planets" },
                    { 72, 57, 4, "The Orange Buildings" },
                    { 73, 210, 5, "The Bitter Leopards" },
                    { 74, 65, 1, "Two Rose Smelling Houses" },
                    { 75, 236, 1, "Two Large Cars" },
                    { 76, 224, 6, "A herd of Bitter Leopards" },
                    { 77, 100, 8, "The Orange Houses" },
                    { 78, 189, 7, "An army of Microscopic Planets" },
                    { 79, 105, 4, "Fifteen Microscopic Planets" },
                    { 80, 25, 6, "The Large Buildings" },
                    { 81, 37, 4, "A bunch of Microscopic Leopards" },
                    { 82, 26, 5, "An army of Orange Planets" },
                    { 83, 151, 4, "An army of Orange Planets" },
                    { 84, 218, 6, "Several Microscopic Cars" },
                    { 85, 211, 2, "An army of Large Planets" },
                    { 86, 147, 7, "Fifteen Rose Smelling Cars" },
                    { 87, 229, 2, "The Transparent Buildings" },
                    { 88, 39, 9, "A bunch of Microscopic Flowers" },
                    { 89, 72, 8, "A herd of Green Planets" },
                    { 90, 126, 7, "An army of Green Cars" },
                    { 91, 168, 9, "Fifteen Bitter Flowers" },
                    { 92, 92, 3, "Fifteen Microscopic Buildings" },
                    { 93, 193, 5, "Fifteen Transparent Cars" },
                    { 94, 226, 10, "Fifteen Rose Smelling Cars" },
                    { 95, 15, 7, "Fifteen Large Leopards" },
                    { 96, 44, 7, "Fifteen Rose Smelling Houses" },
                    { 97, 114, 9, "The Rose Smelling Buildings" },
                    { 98, 71, 6, "Two Orange Buildings" },
                    { 99, 143, 9, "A bunch of Microscopic Planets" },
                    { 100, 187, 3, "Two Bitter Cars" },
                    { 101, 167, 1, "The Bitter Buildings" },
                    { 102, 171, 8, "Two Green Leopards" },
                    { 103, 225, 10, "The Rose Smelling Buildings" },
                    { 104, 92, 5, "A herd of Orange Planets" },
                    { 105, 46, 3, "Fifteen Bitter Flowers" },
                    { 106, 58, 9, "A herd of Purple Flowers" },
                    { 107, 15, 3, "The Orange Flowers" },
                    { 108, 211, 4, "Several Rose Smelling Buildings" },
                    { 109, 211, 2, "The Large Cars" },
                    { 110, 143, 5, "Two Orange Houses" },
                    { 111, 190, 7, "A bunch of Purple Flowers" },
                    { 112, 137, 8, "An army of Orange Houses" },
                    { 113, 118, 6, "A bunch of Orange Buildings" },
                    { 114, 185, 7, "Several Bitter Leopards" },
                    { 115, 101, 7, "Two Microscopic Cars" },
                    { 116, 219, 1, "A herd of Microscopic Buildings" },
                    { 117, 29, 8, "Two Purple Planets" },
                    { 118, 144, 1, "Several Bitter Leopards" },
                    { 119, 43, 8, "Several Purple Flowers" },
                    { 120, 116, 10, "A herd of Large Leopards" },
                    { 121, 113, 3, "The Large Buildings" },
                    { 122, 218, 3, "Two Transparent Houses" },
                    { 123, 110, 9, "Fifteen Orange Buildings" },
                    { 124, 191, 7, "Several Microscopic Houses" },
                    { 125, 132, 3, "Several Green Cars" },
                    { 126, 120, 7, "Two Rose Smelling Flowers" },
                    { 127, 155, 2, "Fifteen Orange Planets" },
                    { 128, 194, 6, "An army of Purple Houses" },
                    { 129, 23, 2, "The Rose Smelling Houses" },
                    { 130, 204, 1, "An army of Large Houses" },
                    { 131, 102, 7, "Fifteen Orange Cars" },
                    { 132, 79, 6, "A herd of Large Leopards" },
                    { 133, 53, 9, "A bunch of Rose Smelling Planets" },
                    { 134, 10, 7, "Several Microscopic Buildings" },
                    { 135, 30, 7, "A bunch of Bitter Buildings" },
                    { 136, 36, 9, "Two Purple Leopards" },
                    { 137, 104, 3, "Fifteen Transparent Leopards" },
                    { 138, 247, 7, "Two Microscopic Planets" },
                    { 139, 188, 2, "A bunch of Purple Buildings" },
                    { 140, 82, 6, "Fifteen Purple Buildings" },
                    { 141, 152, 4, "Several Rose Smelling Planets" },
                    { 142, 165, 4, "An army of Large Cars" },
                    { 143, 160, 3, "Two Bitter Cars" },
                    { 144, 143, 5, "An army of Orange Cars" },
                    { 145, 202, 2, "Two Bitter Cars" },
                    { 146, 106, 6, "The Transparent Planets" },
                    { 147, 232, 2, "Two Transparent Cars" },
                    { 148, 210, 2, "A herd of Large Leopards" },
                    { 149, 209, 8, "A herd of Microscopic Cars" },
                    { 150, 42, 10, "The Large Leopards" },
                    { 151, 144, 3, "The Rose Smelling Planets" },
                    { 152, 88, 5, "Fifteen Orange Cars" },
                    { 153, 228, 6, "The Orange Houses" },
                    { 154, 16, 1, "Several Bitter Leopards" },
                    { 155, 69, 4, "A bunch of Bitter Houses" },
                    { 156, 179, 7, "Several Green Houses" },
                    { 157, 75, 6, "An army of Microscopic Planets" },
                    { 158, 80, 7, "Several Rose Smelling Flowers" },
                    { 159, 208, 7, "Fifteen Orange Flowers" },
                    { 160, 100, 2, "An army of Large Cars" },
                    { 161, 13, 5, "Two Purple Flowers" },
                    { 162, 161, 2, "A bunch of Microscopic Leopards" },
                    { 163, 106, 7, "An army of Purple Planets" },
                    { 164, 174, 1, "A herd of Orange Planets" },
                    { 165, 167, 10, "An army of Orange Flowers" },
                    { 166, 242, 9, "A bunch of Transparent Buildings" },
                    { 167, 162, 8, "An army of Purple Buildings" },
                    { 168, 187, 2, "Two Transparent Cars" },
                    { 169, 218, 5, "The Bitter Leopards" },
                    { 170, 30, 8, "A bunch of Bitter Houses" },
                    { 171, 14, 6, "Two Rose Smelling Cars" },
                    { 172, 226, 7, "The Rose Smelling Flowers" },
                    { 173, 221, 9, "An army of Bitter Leopards" },
                    { 174, 211, 10, "A bunch of Green Planets" },
                    { 175, 33, 2, "Two Large Leopards" },
                    { 176, 57, 10, "A herd of Green Houses" },
                    { 177, 95, 5, "An army of Large Cars" },
                    { 178, 142, 5, "A bunch of Large Houses" },
                    { 179, 152, 10, "A herd of Orange Flowers" },
                    { 180, 48, 4, "The Large Buildings" },
                    { 181, 167, 8, "Fifteen Rose Smelling Leopards" },
                    { 182, 189, 5, "A herd of Large Leopards" },
                    { 183, 88, 7, "The Purple Houses" },
                    { 184, 238, 4, "A herd of Rose Smelling Planets" },
                    { 185, 41, 3, "A bunch of Purple Buildings" },
                    { 186, 200, 3, "Several Orange Planets" },
                    { 187, 239, 1, "The Large Houses" },
                    { 188, 166, 8, "Fifteen Orange Buildings" },
                    { 189, 26, 9, "Several Orange Flowers" },
                    { 190, 231, 3, "Several Transparent Planets" },
                    { 191, 66, 5, "A bunch of Orange Flowers" },
                    { 192, 202, 6, "The Rose Smelling Leopards" },
                    { 193, 114, 9, "A herd of Green Cars" },
                    { 194, 234, 6, "A herd of Microscopic Planets" },
                    { 195, 176, 6, "A herd of Purple Leopards" },
                    { 196, 166, 8, "The Orange Buildings" },
                    { 197, 172, 5, "A bunch of Transparent Planets" },
                    { 198, 145, 6, "Fifteen Bitter Planets" },
                    { 199, 26, 10, "The Rose Smelling Flowers" },
                    { 200, 2, 4, "Fifteen Orange Flowers" },
                    { 201, 115, 4, "Fifteen Green Flowers" },
                    { 202, 216, 9, "The Microscopic Flowers" },
                    { 203, 40, 5, "An army of Orange Flowers" },
                    { 204, 163, 5, "The Bitter Leopards" },
                    { 205, 247, 4, "An army of Microscopic Buildings" },
                    { 206, 235, 10, "An army of Orange Houses" },
                    { 207, 167, 4, "Two Transparent Flowers" },
                    { 208, 219, 1, "The Large Houses" },
                    { 209, 102, 6, "A herd of Orange Flowers" },
                    { 210, 105, 6, "A herd of Rose Smelling Buildings" },
                    { 211, 205, 8, "Two Large Cars" },
                    { 212, 226, 9, "Fifteen Purple Leopards" },
                    { 213, 15, 8, "Two Purple Flowers" },
                    { 214, 24, 7, "Two Transparent Houses" },
                    { 215, 62, 5, "A herd of Bitter Planets" },
                    { 216, 63, 3, "Several Rose Smelling Houses" },
                    { 217, 16, 4, "Several Microscopic Buildings" },
                    { 218, 155, 9, "Two Bitter Cars" },
                    { 219, 159, 4, "An army of Purple Cars" },
                    { 220, 213, 3, "The Bitter Flowers" },
                    { 221, 163, 7, "A herd of Large Planets" },
                    { 222, 74, 6, "The Bitter Flowers" },
                    { 223, 208, 3, "A bunch of Purple Houses" },
                    { 224, 50, 3, "Several Orange Cars" },
                    { 225, 229, 2, "An army of Microscopic Cars" },
                    { 226, 105, 2, "Several Transparent Cars" },
                    { 227, 22, 4, "A bunch of Bitter Flowers" },
                    { 228, 227, 2, "Several Green Flowers" },
                    { 229, 65, 4, "An army of Large Leopards" },
                    { 230, 245, 9, "Two Bitter Houses" },
                    { 231, 33, 7, "A bunch of Microscopic Houses" },
                    { 232, 131, 3, "A herd of Microscopic Buildings" },
                    { 233, 209, 5, "Fifteen Transparent Planets" },
                    { 234, 233, 2, "A bunch of Transparent Buildings" },
                    { 235, 227, 2, "Fifteen Microscopic Cars" },
                    { 236, 164, 10, "A herd of Microscopic Planets" },
                    { 237, 132, 4, "An army of Purple Houses" },
                    { 238, 192, 7, "A herd of Green Leopards" },
                    { 239, 241, 7, "The Microscopic Flowers" },
                    { 240, 36, 3, "Fifteen Transparent Buildings" },
                    { 241, 242, 1, "Fifteen Orange Cars" },
                    { 242, 202, 4, "The Purple Flowers" },
                    { 243, 165, 7, "Fifteen Large Buildings" },
                    { 244, 128, 4, "The Green Cars" },
                    { 245, 165, 5, "Fifteen Rose Smelling Buildings" },
                    { 246, 246, 1, "Several Bitter Flowers" },
                    { 247, 142, 1, "An army of Large Cars" },
                    { 248, 12, 5, "A herd of Microscopic Planets" },
                    { 249, 101, 7, "The Transparent Houses" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_books_author_id",
                table: "books",
                column: "author_id");

            migrationBuilder.CreateIndex(
                name: "IX_books_publisher_id",
                table: "books",
                column: "publisher_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "authors");

            migrationBuilder.DropTable(
                name: "publishers");
        }
    }
}
