using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class initialMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    FirstName = table.Column<string>(type: "text", nullable: false),
                    LastName = table.Column<string>(type: "text", nullable: false),
                    Email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Books",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Books", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Books_Authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Authors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "Id", "Email", "FirstName", "LastName" },
                values: new object[,]
                {
                    { 1, "audrey.hendrix@gov.ru", "Audrey", "Hendrix" },
                    { 2, "oprah.trump@gov.nl", "Oprah", "Trump" },
                    { 3, "mick.trump@tesla.com", "Mick", "Trump" },
                    { 4, "elvis.presley@nasa.org.us", "Elvis", "Presley" },
                    { 5, "barack.jagger@bbc.co.uk", "Barack", "Jagger" },
                    { 6, "mick.winslet@gov.ru", "Mick", "Winslet" },
                    { 7, "barack.jagger@nasa.org.us", "Barack", "Jagger" },
                    { 8, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 9, "elvis.hendrix@something.com", "Elvis", "Hendrix" },
                    { 10, "barack.windsor@gov.nl", "Barack", "Windsor" },
                    { 11, "elvis.hendrix@gov.us", "Elvis", "Hendrix" },
                    { 12, "charles.trump@theworld.ca", "Charles", "Trump" },
                    { 13, "donald.trump@gov.gr", "Donald", "Trump" },
                    { 14, "kate.winfrey@bbc.co.uk", "Kate", "Winfrey" },
                    { 15, "kate.trump@nasa.org.us", "Kate", "Trump" },
                    { 16, "kate.obama@gov.us", "Kate", "Obama" },
                    { 17, "elvis.obama@bbc.co.uk", "Elvis", "Obama" },
                    { 18, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 19, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 20, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 21, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 22, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 23, "barack.presley@gov.ru", "Barack", "Presley" },
                    { 24, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 25, "oprah.winslet@gov.nl", "Oprah", "Winslet" },
                    { 26, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 27, "oprah.winslet@gov.ru", "Oprah", "Winslet" },
                    { 28, "barack.middleton@gov.us", "Barack", "Middleton" },
                    { 29, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 30, "audrey.presley@gov.us", "Audrey", "Presley" },
                    { 31, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 32, "charles.winfrey@something.com", "Charles", "Winfrey" },
                    { 33, "barack.winfrey@google.com", "Barack", "Winfrey" },
                    { 34, "barack.jagger@something.com", "Barack", "Jagger" },
                    { 35, "audrey.winfrey@gov.us", "Audrey", "Winfrey" },
                    { 36, "audrey.winfrey@google.com", "Audrey", "Winfrey" },
                    { 37, "donald.trump@something.com", "Donald", "Trump" },
                    { 38, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 39, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 40, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 41, "jimi.middleton@theworld.ca", "Jimi", "Middleton" },
                    { 42, "barack.hepburn@bbc.co.uk", "Barack", "Hepburn" },
                    { 43, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 44, "oprah.obama@bbc.co.uk", "Oprah", "Obama" },
                    { 45, "audrey.hepburn@bbc.co.uk", "Audrey", "Hepburn" },
                    { 46, "audrey.obama@google.com", "Audrey", "Obama" },
                    { 47, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 48, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 49, "oprah.hendrix@gov.gr", "Oprah", "Hendrix" },
                    { 50, "charles.hendrix@gov.us", "Charles", "Hendrix" },
                    { 51, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 52, "charles.presley@something.com", "Charles", "Presley" },
                    { 53, "charles.hepburn@something.com", "Charles", "Hepburn" },
                    { 54, "audrey.middleton@tesla.com", "Audrey", "Middleton" },
                    { 55, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 56, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 57, "charles.winfrey@something.com", "Charles", "Winfrey" },
                    { 58, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 59, "kate.trump@nasa.org.us", "Kate", "Trump" },
                    { 60, "oprah.winfrey@gov.ru", "Oprah", "Winfrey" },
                    { 61, "mick.middleton@google.com", "Mick", "Middleton" },
                    { 62, "donald.windsor@gov.ru", "Donald", "Windsor" },
                    { 63, "barack.windsor@nasa.org.us", "Barack", "Windsor" },
                    { 64, "barack.windsor@bbc.co.uk", "Barack", "Windsor" },
                    { 65, "audrey.winslet@gov.ru", "Audrey", "Winslet" },
                    { 66, "donald.windsor@gov.us", "Donald", "Windsor" },
                    { 67, "donald.windsor@gov.gr", "Donald", "Windsor" },
                    { 68, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 69, "donald.trump@gov.nl", "Donald", "Trump" },
                    { 70, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 71, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 72, "mick.middleton@gov.us", "Mick", "Middleton" },
                    { 73, "charles.jagger@something.com", "Charles", "Jagger" },
                    { 74, "mick.hendrix@tesla.com", "Mick", "Hendrix" },
                    { 75, "mick.hepburn@theworld.ca", "Mick", "Hepburn" },
                    { 76, "elvis.middleton@gov.gr", "Elvis", "Middleton" },
                    { 77, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 78, "elvis.middleton@theworld.ca", "Elvis", "Middleton" },
                    { 79, "jimi.winslet@tesla.com", "Jimi", "Winslet" },
                    { 80, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 81, "jimi.winfrey@tesla.com", "Jimi", "Winfrey" },
                    { 82, "kate.trump@google.com", "Kate", "Trump" },
                    { 83, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 84, "kate.presley@bbc.co.uk", "Kate", "Presley" },
                    { 85, "donald.obama@gov.us", "Donald", "Obama" },
                    { 86, "mick.windsor@google.com", "Mick", "Windsor" },
                    { 87, "elvis.middleton@gov.nl", "Elvis", "Middleton" },
                    { 88, "donald.hendrix@nasa.org.us", "Donald", "Hendrix" },
                    { 89, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 90, "audrey.presley@gov.gr", "Audrey", "Presley" },
                    { 91, "mick.hendrix@theworld.ca", "Mick", "Hendrix" },
                    { 92, "elvis.winslet@gov.us", "Elvis", "Winslet" },
                    { 93, "donald.winslet@nasa.org.us", "Donald", "Winslet" },
                    { 94, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 95, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 96, "elvis.middleton@theworld.ca", "Elvis", "Middleton" },
                    { 97, "charles.presley@google.com", "Charles", "Presley" },
                    { 98, "donald.obama@theworld.ca", "Donald", "Obama" },
                    { 99, "charles.winslet@tesla.com", "Charles", "Winslet" },
                    { 100, "audrey.windsor@gov.gr", "Audrey", "Windsor" },
                    { 101, "elvis.trump@tesla.com", "Elvis", "Trump" },
                    { 102, "jimi.trump@bbc.co.uk", "Jimi", "Trump" },
                    { 103, "donald.jagger@gov.nl", "Donald", "Jagger" },
                    { 104, "jimi.middleton@gov.ru", "Jimi", "Middleton" },
                    { 105, "charles.hendrix@gov.nl", "Charles", "Hendrix" },
                    { 106, "kate.presley@gov.us", "Kate", "Presley" },
                    { 107, "elvis.hendrix@something.com", "Elvis", "Hendrix" },
                    { 108, "mick.presley@gov.nl", "Mick", "Presley" },
                    { 109, "donald.trump@gov.us", "Donald", "Trump" },
                    { 110, "audrey.obama@gov.us", "Audrey", "Obama" },
                    { 111, "jimi.trump@bbc.co.uk", "Jimi", "Trump" },
                    { 112, "mick.obama@gov.gr", "Mick", "Obama" },
                    { 113, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 114, "jimi.windsor@bbc.co.uk", "Jimi", "Windsor" },
                    { 115, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 116, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 117, "charles.middleton@nasa.org.us", "Charles", "Middleton" },
                    { 118, "elvis.winfrey@gov.ru", "Elvis", "Winfrey" },
                    { 119, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 120, "audrey.winfrey@gov.ru", "Audrey", "Winfrey" },
                    { 121, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 122, "oprah.obama@google.com", "Oprah", "Obama" },
                    { 123, "elvis.jagger@bbc.co.uk", "Elvis", "Jagger" },
                    { 124, "audrey.middleton@nasa.org.us", "Audrey", "Middleton" },
                    { 125, "elvis.hendrix@nasa.org.us", "Elvis", "Hendrix" },
                    { 126, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 127, "mick.hendrix@bbc.co.uk", "Mick", "Hendrix" },
                    { 128, "elvis.presley@tesla.com", "Elvis", "Presley" },
                    { 129, "mick.winfrey@gov.nl", "Mick", "Winfrey" },
                    { 130, "audrey.trump@theworld.ca", "Audrey", "Trump" },
                    { 131, "jimi.hendrix@theworld.ca", "Jimi", "Hendrix" },
                    { 132, "kate.hepburn@gov.us", "Kate", "Hepburn" },
                    { 133, "elvis.jagger@bbc.co.uk", "Elvis", "Jagger" },
                    { 134, "audrey.obama@gov.us", "Audrey", "Obama" },
                    { 135, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 136, "mick.middleton@tesla.com", "Mick", "Middleton" },
                    { 137, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 138, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 139, "barack.obama@nasa.org.us", "Barack", "Obama" },
                    { 140, "elvis.hepburn@nasa.org.us", "Elvis", "Hepburn" },
                    { 141, "kate.hepburn@nasa.org.us", "Kate", "Hepburn" },
                    { 142, "jimi.windsor@gov.us", "Jimi", "Windsor" },
                    { 143, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 144, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 145, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 146, "mick.hepburn@google.com", "Mick", "Hepburn" },
                    { 147, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 148, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 149, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 150, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 151, "audrey.windsor@google.com", "Audrey", "Windsor" },
                    { 152, "barack.middleton@theworld.ca", "Barack", "Middleton" },
                    { 153, "mick.jagger@bbc.co.uk", "Mick", "Jagger" },
                    { 154, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 155, "kate.trump@google.com", "Kate", "Trump" },
                    { 156, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 157, "oprah.hendrix@nasa.org.us", "Oprah", "Hendrix" },
                    { 158, "mick.winfrey@something.com", "Mick", "Winfrey" },
                    { 159, "charles.hepburn@theworld.ca", "Charles", "Hepburn" },
                    { 160, "charles.trump@nasa.org.us", "Charles", "Trump" },
                    { 161, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 162, "donald.presley@something.com", "Donald", "Presley" },
                    { 163, "charles.jagger@gov.us", "Charles", "Jagger" },
                    { 164, "donald.trump@bbc.co.uk", "Donald", "Trump" },
                    { 165, "jimi.hepburn@theworld.ca", "Jimi", "Hepburn" },
                    { 166, "donald.trump@nasa.org.us", "Donald", "Trump" },
                    { 167, "mick.jagger@tesla.com", "Mick", "Jagger" },
                    { 168, "charles.presley@something.com", "Charles", "Presley" },
                    { 169, "audrey.hepburn@tesla.com", "Audrey", "Hepburn" },
                    { 170, "audrey.windsor@theworld.ca", "Audrey", "Windsor" },
                    { 171, "elvis.winslet@gov.gr", "Elvis", "Winslet" },
                    { 172, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 173, "jimi.windsor@gov.us", "Jimi", "Windsor" },
                    { 174, "kate.trump@google.com", "Kate", "Trump" },
                    { 175, "jimi.obama@gov.gr", "Jimi", "Obama" },
                    { 176, "mick.windsor@tesla.com", "Mick", "Windsor" },
                    { 177, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 178, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 179, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 180, "barack.hepburn@nasa.org.us", "Barack", "Hepburn" },
                    { 181, "barack.winslet@google.com", "Barack", "Winslet" },
                    { 182, "donald.presley@nasa.org.us", "Donald", "Presley" },
                    { 183, "donald.middleton@gov.us", "Donald", "Middleton" },
                    { 184, "elvis.winfrey@tesla.com", "Elvis", "Winfrey" },
                    { 185, "elvis.middleton@gov.us", "Elvis", "Middleton" },
                    { 186, "oprah.winfrey@gov.us", "Oprah", "Winfrey" },
                    { 187, "oprah.trump@tesla.com", "Oprah", "Trump" },
                    { 188, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 189, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 190, "oprah.middleton@nasa.org.us", "Oprah", "Middleton" },
                    { 191, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 192, "audrey.winfrey@gov.gr", "Audrey", "Winfrey" },
                    { 193, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 194, "elvis.obama@gov.us", "Elvis", "Obama" },
                    { 195, "jimi.obama@gov.us", "Jimi", "Obama" },
                    { 196, "audrey.jagger@gov.gr", "Audrey", "Jagger" },
                    { 197, "barack.presley@gov.us", "Barack", "Presley" },
                    { 198, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 199, "elvis.hepburn@google.com", "Elvis", "Hepburn" },
                    { 200, "elvis.windsor@gov.nl", "Elvis", "Windsor" },
                    { 201, "oprah.presley@something.com", "Oprah", "Presley" },
                    { 202, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 203, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 204, "kate.trump@google.com", "Kate", "Trump" },
                    { 205, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 206, "mick.winfrey@tesla.com", "Mick", "Winfrey" },
                    { 207, "mick.middleton@something.com", "Mick", "Middleton" },
                    { 208, "elvis.hepburn@gov.ru", "Elvis", "Hepburn" },
                    { 209, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 210, "barack.presley@gov.us", "Barack", "Presley" },
                    { 211, "oprah.obama@nasa.org.us", "Oprah", "Obama" },
                    { 212, "kate.presley@gov.us", "Kate", "Presley" },
                    { 213, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 214, "kate.obama@tesla.com", "Kate", "Obama" },
                    { 215, "kate.winslet@gov.us", "Kate", "Winslet" },
                    { 216, "jimi.obama@tesla.com", "Jimi", "Obama" },
                    { 217, "charles.obama@gov.gr", "Charles", "Obama" },
                    { 218, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 219, "mick.winslet@google.com", "Mick", "Winslet" },
                    { 220, "charles.obama@google.com", "Charles", "Obama" },
                    { 221, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 222, "audrey.hepburn@nasa.org.us", "Audrey", "Hepburn" },
                    { 223, "kate.middleton@nasa.org.us", "Kate", "Middleton" },
                    { 224, "mick.middleton@theworld.ca", "Mick", "Middleton" },
                    { 225, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 226, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 227, "kate.presley@theworld.ca", "Kate", "Presley" },
                    { 228, "elvis.jagger@gov.gr", "Elvis", "Jagger" },
                    { 229, "oprah.presley@tesla.com", "Oprah", "Presley" },
                    { 230, "kate.presley@tesla.com", "Kate", "Presley" },
                    { 231, "audrey.windsor@nasa.org.us", "Audrey", "Windsor" },
                    { 232, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 233, "jimi.winfrey@gov.gr", "Jimi", "Winfrey" },
                    { 234, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 235, "kate.winslet@google.com", "Kate", "Winslet" },
                    { 236, "elvis.jagger@google.com", "Elvis", "Jagger" },
                    { 237, "donald.trump@something.com", "Donald", "Trump" },
                    { 238, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 239, "mick.hendrix@google.com", "Mick", "Hendrix" },
                    { 240, "barack.trump@gov.ru", "Barack", "Trump" },
                    { 241, "charles.windsor@bbc.co.uk", "Charles", "Windsor" },
                    { 242, "charles.winslet@google.com", "Charles", "Winslet" },
                    { 243, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 244, "mick.hepburn@nasa.org.us", "Mick", "Hepburn" },
                    { 245, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 246, "jimi.windsor@tesla.com", "Jimi", "Windsor" },
                    { 247, "oprah.obama@gov.ru", "Oprah", "Obama" },
                    { 248, "kate.trump@google.com", "Kate", "Trump" },
                    { 249, "oprah.hepburn@gov.nl", "Oprah", "Hepburn" }
                });

            migrationBuilder.InsertData(
                table: "Books",
                columns: new[] { "Id", "AuthorId", "Title" },
                values: new object[,]
                {
                    { 1, 229, "A herd of Microscopic Leopards" },
                    { 2, 11, "The Large Buildings" },
                    { 3, 207, "A bunch of Large Planets" },
                    { 4, 5, "Several Transparent Leopards" },
                    { 5, 52, "A bunch of Bitter Houses" },
                    { 6, 120, "Two Transparent Leopards" },
                    { 7, 247, "A bunch of Microscopic Houses" },
                    { 8, 130, "Fifteen Rose Smelling Planets" },
                    { 9, 239, "Two Purple Flowers" },
                    { 10, 179, "Two Microscopic Houses" },
                    { 11, 89, "A herd of Green Buildings" },
                    { 12, 15, "The Orange Buildings" },
                    { 13, 212, "A bunch of Large Planets" },
                    { 14, 70, "Two Large Leopards" },
                    { 15, 73, "The Green Houses" },
                    { 16, 228, "The Orange Houses" },
                    { 17, 173, "The Orange Flowers" },
                    { 18, 189, "The Large Leopards" },
                    { 19, 49, "Two Transparent Flowers" },
                    { 20, 17, "Two Rose Smelling Flowers" },
                    { 21, 102, "Fifteen Green Planets" },
                    { 22, 177, "Two Microscopic Flowers" },
                    { 23, 68, "Several Transparent Leopards" },
                    { 24, 244, "A bunch of Large Cars" },
                    { 25, 153, "Several Orange Leopards" },
                    { 26, 240, "Several Green Houses" },
                    { 27, 142, "Two Large Houses" },
                    { 28, 94, "Several Green Leopards" },
                    { 29, 196, "Fifteen Bitter Planets" },
                    { 30, 46, "Fifteen Microscopic Cars" },
                    { 31, 159, "Two Orange Planets" },
                    { 32, 45, "Fifteen Large Houses" },
                    { 33, 25, "Two Rose Smelling Houses" },
                    { 34, 218, "Several Large Houses" },
                    { 35, 18, "Fifteen Rose Smelling Planets" },
                    { 36, 45, "A herd of Rose Smelling Leopards" },
                    { 37, 127, "A bunch of Bitter Houses" },
                    { 38, 210, "The Rose Smelling Planets" },
                    { 39, 238, "Several Green Houses" },
                    { 40, 52, "A herd of Purple Houses" },
                    { 41, 241, "A herd of Rose Smelling Houses" },
                    { 42, 247, "A bunch of Purple Flowers" },
                    { 43, 13, "Fifteen Microscopic Flowers" },
                    { 44, 120, "Two Purple Flowers" },
                    { 45, 26, "Several Transparent Flowers" },
                    { 46, 149, "An army of Green Cars" },
                    { 47, 143, "A bunch of Transparent Flowers" },
                    { 48, 224, "A herd of Purple Flowers" },
                    { 49, 113, "A bunch of Large Planets" },
                    { 50, 84, "A herd of Rose Smelling Flowers" },
                    { 51, 34, "An army of Microscopic Buildings" },
                    { 52, 206, "A herd of Green Buildings" },
                    { 53, 210, "Several Bitter Buildings" },
                    { 54, 201, "An army of Microscopic Leopards" },
                    { 55, 61, "A herd of Transparent Planets" },
                    { 56, 125, "Fifteen Purple Planets" },
                    { 57, 85, "An army of Microscopic Planets" },
                    { 58, 125, "A bunch of Purple Cars" },
                    { 59, 81, "Fifteen Green Houses" },
                    { 60, 137, "A herd of Large Leopards" },
                    { 61, 205, "A herd of Orange Planets" },
                    { 62, 35, "An army of Microscopic Leopards" },
                    { 63, 130, "An army of Transparent Houses" },
                    { 64, 43, "Several Green Planets" },
                    { 65, 159, "Fifteen Purple Houses" },
                    { 66, 81, "Two Rose Smelling Leopards" },
                    { 67, 21, "An army of Rose Smelling Leopards" },
                    { 68, 68, "A herd of Microscopic Cars" },
                    { 69, 132, "An army of Orange Leopards" },
                    { 70, 52, "A bunch of Purple Cars" },
                    { 71, 123, "A bunch of Bitter Houses" },
                    { 72, 102, "The Purple Flowers" },
                    { 73, 54, "A bunch of Green Cars" },
                    { 74, 107, "The Large Buildings" },
                    { 75, 15, "A bunch of Orange Buildings" },
                    { 76, 173, "The Purple Planets" },
                    { 77, 48, "An army of Microscopic Flowers" },
                    { 78, 28, "Several Bitter Buildings" },
                    { 79, 165, "A bunch of Transparent Flowers" },
                    { 80, 186, "Two Transparent Houses" },
                    { 81, 223, "The Green Buildings" },
                    { 82, 104, "Fifteen Transparent Buildings" },
                    { 83, 194, "A bunch of Orange Houses" },
                    { 84, 140, "Two Microscopic Cars" },
                    { 85, 195, "A herd of Orange Houses" },
                    { 86, 157, "Several Green Flowers" },
                    { 87, 46, "Fifteen Rose Smelling Leopards" },
                    { 88, 143, "An army of Green Flowers" },
                    { 89, 234, "A bunch of Green Cars" },
                    { 90, 156, "Several Bitter Houses" },
                    { 91, 216, "A bunch of Microscopic Leopards" },
                    { 92, 124, "A bunch of Large Leopards" },
                    { 93, 65, "Several Transparent Buildings" },
                    { 94, 82, "Several Orange Houses" },
                    { 95, 82, "A herd of Green Buildings" },
                    { 96, 72, "Fifteen Transparent Houses" },
                    { 97, 225, "A herd of Orange Planets" },
                    { 98, 83, "Several Large Planets" },
                    { 99, 164, "A bunch of Green Planets" },
                    { 100, 236, "A herd of Bitter Cars" },
                    { 101, 68, "The Orange Flowers" },
                    { 102, 203, "A bunch of Purple Flowers" },
                    { 103, 50, "A bunch of Microscopic Houses" },
                    { 104, 82, "A bunch of Purple Leopards" },
                    { 105, 198, "A bunch of Transparent Buildings" },
                    { 106, 106, "An army of Large Leopards" },
                    { 107, 119, "An army of Green Cars" },
                    { 108, 33, "Fifteen Orange Flowers" },
                    { 109, 93, "A herd of Microscopic Flowers" },
                    { 110, 86, "The Bitter Leopards" },
                    { 111, 232, "Two Bitter Planets" },
                    { 112, 123, "Several Purple Houses" },
                    { 113, 197, "Several Purple Leopards" },
                    { 114, 165, "An army of Rose Smelling Planets" },
                    { 115, 5, "Two Green Planets" },
                    { 116, 243, "A bunch of Microscopic Cars" },
                    { 117, 125, "A herd of Purple Flowers" },
                    { 118, 1, "An army of Microscopic Flowers" },
                    { 119, 24, "Two Orange Leopards" },
                    { 120, 243, "Several Purple Planets" },
                    { 121, 161, "Several Transparent Flowers" },
                    { 122, 67, "A bunch of Purple Cars" },
                    { 123, 212, "A herd of Transparent Cars" },
                    { 124, 84, "The Green Cars" },
                    { 125, 119, "Fifteen Purple Houses" },
                    { 126, 52, "A herd of Transparent Planets" },
                    { 127, 202, "An army of Bitter Cars" },
                    { 128, 88, "A bunch of Bitter Planets" },
                    { 129, 234, "A herd of Large Cars" },
                    { 130, 204, "A bunch of Orange Planets" },
                    { 131, 65, "A bunch of Rose Smelling Houses" },
                    { 132, 203, "A herd of Transparent Leopards" },
                    { 133, 212, "An army of Purple Houses" },
                    { 134, 31, "The Rose Smelling Flowers" },
                    { 135, 57, "A bunch of Rose Smelling Buildings" },
                    { 136, 103, "Several Bitter Houses" },
                    { 137, 189, "An army of Large Leopards" },
                    { 138, 198, "Fifteen Green Buildings" },
                    { 139, 200, "Two Transparent Houses" },
                    { 140, 181, "A bunch of Microscopic Planets" },
                    { 141, 18, "Fifteen Rose Smelling Cars" },
                    { 142, 101, "A herd of Purple Planets" },
                    { 143, 67, "A bunch of Orange Cars" },
                    { 144, 235, "The Purple Planets" },
                    { 145, 44, "The Bitter Leopards" },
                    { 146, 42, "A herd of Rose Smelling Houses" },
                    { 147, 128, "Two Bitter Cars" },
                    { 148, 90, "A herd of Orange Houses" },
                    { 149, 183, "A herd of Microscopic Houses" },
                    { 150, 53, "Fifteen Bitter Flowers" },
                    { 151, 2, "Several Orange Flowers" },
                    { 152, 224, "Several Bitter Flowers" },
                    { 153, 103, "An army of Purple Flowers" },
                    { 154, 147, "Fifteen Rose Smelling Houses" },
                    { 155, 22, "A bunch of Orange Cars" },
                    { 156, 212, "Two Large Planets" },
                    { 157, 206, "The Green Houses" },
                    { 158, 149, "The Bitter Cars" },
                    { 159, 104, "Fifteen Transparent Buildings" },
                    { 160, 77, "The Bitter Leopards" },
                    { 161, 150, "A bunch of Orange Leopards" },
                    { 162, 182, "A herd of Rose Smelling Cars" },
                    { 163, 127, "Two Green Houses" },
                    { 164, 238, "Two Rose Smelling Leopards" },
                    { 165, 67, "Fifteen Large Houses" },
                    { 166, 1, "Two Transparent Cars" },
                    { 167, 17, "A herd of Purple Buildings" },
                    { 168, 110, "Two Green Cars" },
                    { 169, 221, "Fifteen Large Planets" },
                    { 170, 68, "An army of Orange Cars" },
                    { 171, 192, "A herd of Purple Cars" },
                    { 172, 236, "A herd of Purple Planets" },
                    { 173, 114, "Two Purple Flowers" },
                    { 174, 178, "An army of Green Planets" },
                    { 175, 25, "A herd of Rose Smelling Houses" },
                    { 176, 111, "Two Orange Flowers" },
                    { 177, 81, "A herd of Transparent Cars" },
                    { 178, 38, "Fifteen Green Cars" },
                    { 179, 52, "An army of Rose Smelling Houses" },
                    { 180, 159, "A bunch of Orange Flowers" },
                    { 181, 26, "A bunch of Rose Smelling Flowers" },
                    { 182, 130, "The Orange Planets" },
                    { 183, 234, "A bunch of Rose Smelling Leopards" },
                    { 184, 26, "An army of Green Buildings" },
                    { 185, 122, "Two Purple Buildings" },
                    { 186, 84, "Fifteen Transparent Houses" },
                    { 187, 109, "Fifteen Bitter Flowers" },
                    { 188, 15, "Several Orange Flowers" },
                    { 189, 119, "An army of Green Flowers" },
                    { 190, 236, "Fifteen Large Flowers" },
                    { 191, 75, "Fifteen Rose Smelling Houses" },
                    { 192, 210, "Several Rose Smelling Planets" },
                    { 193, 193, "A bunch of Large Leopards" },
                    { 194, 2, "Fifteen Rose Smelling Cars" },
                    { 195, 112, "An army of Microscopic Houses" },
                    { 196, 198, "Two Green Houses" },
                    { 197, 197, "A bunch of Orange Flowers" },
                    { 198, 182, "Several Green Houses" },
                    { 199, 243, "Two Transparent Flowers" },
                    { 200, 243, "Several Rose Smelling Flowers" },
                    { 201, 18, "An army of Bitter Houses" },
                    { 202, 137, "Fifteen Transparent Cars" },
                    { 203, 247, "Two Transparent Leopards" },
                    { 204, 238, "A herd of Large Cars" },
                    { 205, 34, "Fifteen Microscopic Cars" },
                    { 206, 27, "The Microscopic Buildings" },
                    { 207, 198, "Fifteen Orange Leopards" },
                    { 208, 21, "Two Bitter Flowers" },
                    { 209, 28, "An army of Microscopic Cars" },
                    { 210, 164, "Several Transparent Buildings" },
                    { 211, 91, "Several Orange Leopards" },
                    { 212, 197, "Fifteen Green Flowers" },
                    { 213, 173, "A bunch of Transparent Buildings" },
                    { 214, 10, "A bunch of Large Buildings" },
                    { 215, 221, "A herd of Large Cars" },
                    { 216, 149, "Fifteen Purple Buildings" },
                    { 217, 224, "An army of Microscopic Flowers" },
                    { 218, 220, "Fifteen Rose Smelling Buildings" },
                    { 219, 182, "A bunch of Transparent Planets" },
                    { 220, 134, "Several Large Leopards" },
                    { 221, 182, "The Microscopic Leopards" },
                    { 222, 221, "A herd of Transparent Leopards" },
                    { 223, 210, "Several Purple Cars" },
                    { 224, 51, "Several Green Leopards" },
                    { 225, 16, "A bunch of Rose Smelling Leopards" },
                    { 226, 36, "Several Purple Cars" },
                    { 227, 125, "The Large Planets" },
                    { 228, 171, "The Orange Planets" },
                    { 229, 218, "A herd of Large Buildings" },
                    { 230, 126, "An army of Microscopic Leopards" },
                    { 231, 76, "Fifteen Purple Flowers" },
                    { 232, 119, "The Microscopic Leopards" },
                    { 233, 96, "The Transparent Houses" },
                    { 234, 183, "An army of Microscopic Planets" },
                    { 235, 49, "Fifteen Green Houses" },
                    { 236, 138, "Two Rose Smelling Cars" },
                    { 237, 96, "Two Rose Smelling Flowers" },
                    { 238, 142, "A herd of Purple Cars" },
                    { 239, 246, "Several Rose Smelling Leopards" },
                    { 240, 105, "The Purple Planets" },
                    { 241, 202, "An army of Large Leopards" },
                    { 242, 154, "A bunch of Transparent Planets" },
                    { 243, 119, "The Rose Smelling Buildings" },
                    { 244, 76, "An army of Orange Cars" },
                    { 245, 123, "The Purple Houses" },
                    { 246, 185, "Two Green Leopards" },
                    { 247, 245, "Two Bitter Leopards" },
                    { 248, 237, "The Purple Cars" },
                    { 249, 163, "Fifteen Transparent Flowers" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Books_AuthorId",
                table: "Books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Books");

            migrationBuilder.DropTable(
                name: "Authors");
        }
    }
}
