using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    firstname = table.Column<string>(type: "text", nullable: false),
                    lastname = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "authors",
                columns: new[] { "id", "email", "firstname", "lastname" },
                values: new object[,]
                {
                    { 1, "jimi.jagger@gov.ru", "Jimi", "Jagger" },
                    { 2, "barack.middleton@bbc.co.uk", "Barack", "Middleton" },
                    { 3, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 4, "kate.hepburn@gov.us", "Kate", "Hepburn" },
                    { 5, "mick.windsor@google.com", "Mick", "Windsor" },
                    { 6, "barack.hepburn@nasa.org.us", "Barack", "Hepburn" },
                    { 7, "oprah.winslet@something.com", "Oprah", "Winslet" },
                    { 8, "elvis.winslet@gov.ru", "Elvis", "Winslet" },
                    { 9, "donald.jagger@bbc.co.uk", "Donald", "Jagger" },
                    { 10, "barack.hendrix@tesla.com", "Barack", "Hendrix" },
                    { 11, "elvis.winfrey@theworld.ca", "Elvis", "Winfrey" },
                    { 12, "mick.middleton@gov.gr", "Mick", "Middleton" },
                    { 13, "audrey.jagger@gov.ru", "Audrey", "Jagger" },
                    { 14, "audrey.presley@google.com", "Audrey", "Presley" },
                    { 15, "donald.trump@something.com", "Donald", "Trump" },
                    { 16, "kate.winslet@google.com", "Kate", "Winslet" },
                    { 17, "donald.hendrix@gov.gr", "Donald", "Hendrix" },
                    { 18, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 19, "barack.windsor@tesla.com", "Barack", "Windsor" },
                    { 20, "audrey.presley@tesla.com", "Audrey", "Presley" },
                    { 21, "mick.middleton@google.com", "Mick", "Middleton" },
                    { 22, "charles.winslet@something.com", "Charles", "Winslet" },
                    { 23, "jimi.winslet@something.com", "Jimi", "Winslet" },
                    { 24, "jimi.winfrey@nasa.org.us", "Jimi", "Winfrey" },
                    { 25, "elvis.windsor@tesla.com", "Elvis", "Windsor" },
                    { 26, "mick.windsor@theworld.ca", "Mick", "Windsor" },
                    { 27, "mick.windsor@gov.nl", "Mick", "Windsor" },
                    { 28, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 29, "barack.trump@nasa.org.us", "Barack", "Trump" },
                    { 30, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 31, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 32, "donald.obama@tesla.com", "Donald", "Obama" },
                    { 33, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 34, "donald.trump@theworld.ca", "Donald", "Trump" },
                    { 35, "mick.hendrix@theworld.ca", "Mick", "Hendrix" },
                    { 36, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 37, "donald.presley@google.com", "Donald", "Presley" },
                    { 38, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 39, "jimi.obama@nasa.org.us", "Jimi", "Obama" },
                    { 40, "elvis.presley@google.com", "Elvis", "Presley" },
                    { 41, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 42, "jimi.winfrey@nasa.org.us", "Jimi", "Winfrey" },
                    { 43, "oprah.windsor@gov.us", "Oprah", "Windsor" },
                    { 44, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 45, "elvis.trump@gov.nl", "Elvis", "Trump" },
                    { 46, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 47, "donald.hepburn@tesla.com", "Donald", "Hepburn" },
                    { 48, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 49, "oprah.obama@gov.gr", "Oprah", "Obama" },
                    { 50, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 51, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 52, "jimi.middleton@nasa.org.us", "Jimi", "Middleton" },
                    { 53, "kate.middleton@nasa.org.us", "Kate", "Middleton" },
                    { 54, "kate.obama@something.com", "Kate", "Obama" },
                    { 55, "audrey.obama@bbc.co.uk", "Audrey", "Obama" },
                    { 56, "audrey.hendrix@gov.gr", "Audrey", "Hendrix" },
                    { 57, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 58, "elvis.presley@nasa.org.us", "Elvis", "Presley" },
                    { 59, "mick.middleton@theworld.ca", "Mick", "Middleton" },
                    { 60, "elvis.presley@google.com", "Elvis", "Presley" },
                    { 61, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 62, "elvis.middleton@bbc.co.uk", "Elvis", "Middleton" },
                    { 63, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 64, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 65, "jimi.jagger@gov.nl", "Jimi", "Jagger" },
                    { 66, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 67, "charles.hepburn@gov.ru", "Charles", "Hepburn" },
                    { 68, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 69, "oprah.winfrey@something.com", "Oprah", "Winfrey" },
                    { 70, "charles.trump@gov.gr", "Charles", "Trump" },
                    { 71, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 72, "oprah.jagger@gov.ru", "Oprah", "Jagger" },
                    { 73, "mick.hepburn@google.com", "Mick", "Hepburn" },
                    { 74, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 75, "oprah.windsor@gov.nl", "Oprah", "Windsor" },
                    { 76, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 77, "mick.jagger@bbc.co.uk", "Mick", "Jagger" },
                    { 78, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 79, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 80, "audrey.hepburn@gov.nl", "Audrey", "Hepburn" },
                    { 81, "donald.presley@nasa.org.us", "Donald", "Presley" },
                    { 82, "audrey.winslet@gov.ru", "Audrey", "Winslet" },
                    { 83, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 84, "charles.hendrix@tesla.com", "Charles", "Hendrix" },
                    { 85, "donald.winfrey@something.com", "Donald", "Winfrey" },
                    { 86, "barack.jagger@tesla.com", "Barack", "Jagger" },
                    { 87, "donald.winfrey@gov.us", "Donald", "Winfrey" },
                    { 88, "oprah.windsor@google.com", "Oprah", "Windsor" },
                    { 89, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 90, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 91, "mick.presley@theworld.ca", "Mick", "Presley" },
                    { 92, "kate.winslet@theworld.ca", "Kate", "Winslet" },
                    { 93, "elvis.winfrey@tesla.com", "Elvis", "Winfrey" },
                    { 94, "jimi.trump@gov.us", "Jimi", "Trump" },
                    { 95, "elvis.hepburn@bbc.co.uk", "Elvis", "Hepburn" },
                    { 96, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 97, "donald.trump@tesla.com", "Donald", "Trump" },
                    { 98, "oprah.obama@gov.gr", "Oprah", "Obama" },
                    { 99, "barack.hepburn@tesla.com", "Barack", "Hepburn" },
                    { 100, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 101, "jimi.hendrix@google.com", "Jimi", "Hendrix" },
                    { 102, "barack.hepburn@something.com", "Barack", "Hepburn" },
                    { 103, "kate.middleton@nasa.org.us", "Kate", "Middleton" },
                    { 104, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 105, "jimi.trump@theworld.ca", "Jimi", "Trump" },
                    { 106, "kate.trump@nasa.org.us", "Kate", "Trump" },
                    { 107, "audrey.middleton@gov.nl", "Audrey", "Middleton" },
                    { 108, "elvis.middleton@google.com", "Elvis", "Middleton" },
                    { 109, "mick.hendrix@gov.us", "Mick", "Hendrix" },
                    { 110, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 111, "mick.middleton@gov.ru", "Mick", "Middleton" },
                    { 112, "barack.obama@something.com", "Barack", "Obama" },
                    { 113, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 114, "audrey.winfrey@gov.nl", "Audrey", "Winfrey" },
                    { 115, "elvis.jagger@gov.us", "Elvis", "Jagger" },
                    { 116, "kate.winfrey@bbc.co.uk", "Kate", "Winfrey" },
                    { 117, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 118, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 119, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 120, "donald.windsor@gov.nl", "Donald", "Windsor" },
                    { 121, "jimi.hepburn@gov.nl", "Jimi", "Hepburn" },
                    { 122, "barack.winslet@gov.gr", "Barack", "Winslet" },
                    { 123, "audrey.hepburn@gov.nl", "Audrey", "Hepburn" },
                    { 124, "donald.obama@theworld.ca", "Donald", "Obama" },
                    { 125, "oprah.winslet@something.com", "Oprah", "Winslet" },
                    { 126, "charles.winslet@gov.ru", "Charles", "Winslet" },
                    { 127, "charles.windsor@gov.ru", "Charles", "Windsor" },
                    { 128, "elvis.winslet@bbc.co.uk", "Elvis", "Winslet" },
                    { 129, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 130, "charles.obama@gov.us", "Charles", "Obama" },
                    { 131, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 132, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 133, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 134, "charles.winslet@gov.gr", "Charles", "Winslet" },
                    { 135, "elvis.jagger@gov.gr", "Elvis", "Jagger" },
                    { 136, "jimi.hendrix@gov.gr", "Jimi", "Hendrix" },
                    { 137, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 138, "elvis.obama@tesla.com", "Elvis", "Obama" },
                    { 139, "elvis.presley@bbc.co.uk", "Elvis", "Presley" },
                    { 140, "audrey.hepburn@nasa.org.us", "Audrey", "Hepburn" },
                    { 141, "elvis.hepburn@gov.ru", "Elvis", "Hepburn" },
                    { 142, "mick.middleton@gov.ru", "Mick", "Middleton" },
                    { 143, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 144, "charles.middleton@google.com", "Charles", "Middleton" },
                    { 145, "jimi.jagger@nasa.org.us", "Jimi", "Jagger" },
                    { 146, "oprah.windsor@nasa.org.us", "Oprah", "Windsor" },
                    { 147, "elvis.hendrix@bbc.co.uk", "Elvis", "Hendrix" },
                    { 148, "kate.presley@google.com", "Kate", "Presley" },
                    { 149, "donald.trump@theworld.ca", "Donald", "Trump" },
                    { 150, "kate.presley@gov.us", "Kate", "Presley" },
                    { 151, "elvis.windsor@gov.ru", "Elvis", "Windsor" },
                    { 152, "oprah.obama@gov.nl", "Oprah", "Obama" },
                    { 153, "mick.jagger@gov.nl", "Mick", "Jagger" },
                    { 154, "donald.winfrey@google.com", "Donald", "Winfrey" },
                    { 155, "audrey.windsor@gov.gr", "Audrey", "Windsor" },
                    { 156, "donald.winfrey@gov.nl", "Donald", "Winfrey" },
                    { 157, "elvis.winfrey@gov.nl", "Elvis", "Winfrey" },
                    { 158, "oprah.obama@gov.ru", "Oprah", "Obama" },
                    { 159, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 160, "oprah.middleton@gov.ru", "Oprah", "Middleton" },
                    { 161, "donald.trump@gov.gr", "Donald", "Trump" },
                    { 162, "mick.hendrix@theworld.ca", "Mick", "Hendrix" },
                    { 163, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 164, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 165, "mick.presley@tesla.com", "Mick", "Presley" },
                    { 166, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 167, "jimi.hepburn@google.com", "Jimi", "Hepburn" },
                    { 168, "mick.jagger@gov.nl", "Mick", "Jagger" },
                    { 169, "charles.presley@google.com", "Charles", "Presley" },
                    { 170, "charles.trump@something.com", "Charles", "Trump" },
                    { 171, "oprah.trump@theworld.ca", "Oprah", "Trump" },
                    { 172, "mick.hepburn@gov.us", "Mick", "Hepburn" },
                    { 173, "charles.winslet@tesla.com", "Charles", "Winslet" },
                    { 174, "charles.hepburn@google.com", "Charles", "Hepburn" },
                    { 175, "barack.windsor@nasa.org.us", "Barack", "Windsor" },
                    { 176, "oprah.winslet@gov.ru", "Oprah", "Winslet" },
                    { 177, "barack.hepburn@bbc.co.uk", "Barack", "Hepburn" },
                    { 178, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 179, "oprah.winslet@google.com", "Oprah", "Winslet" },
                    { 180, "charles.windsor@tesla.com", "Charles", "Windsor" },
                    { 181, "donald.winfrey@gov.ru", "Donald", "Winfrey" },
                    { 182, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 183, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 184, "barack.trump@google.com", "Barack", "Trump" },
                    { 185, "audrey.trump@something.com", "Audrey", "Trump" },
                    { 186, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 187, "elvis.middleton@something.com", "Elvis", "Middleton" },
                    { 188, "elvis.jagger@something.com", "Elvis", "Jagger" },
                    { 189, "kate.hendrix@theworld.ca", "Kate", "Hendrix" },
                    { 190, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 191, "jimi.presley@google.com", "Jimi", "Presley" },
                    { 192, "audrey.obama@google.com", "Audrey", "Obama" },
                    { 193, "elvis.winfrey@tesla.com", "Elvis", "Winfrey" },
                    { 194, "donald.middleton@nasa.org.us", "Donald", "Middleton" },
                    { 195, "audrey.hepburn@bbc.co.uk", "Audrey", "Hepburn" },
                    { 196, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 197, "mick.winfrey@tesla.com", "Mick", "Winfrey" },
                    { 198, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 199, "audrey.hepburn@gov.gr", "Audrey", "Hepburn" },
                    { 200, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 201, "elvis.trump@something.com", "Elvis", "Trump" },
                    { 202, "oprah.trump@gov.ru", "Oprah", "Trump" },
                    { 203, "barack.jagger@bbc.co.uk", "Barack", "Jagger" },
                    { 204, "elvis.windsor@gov.ru", "Elvis", "Windsor" },
                    { 205, "oprah.obama@google.com", "Oprah", "Obama" },
                    { 206, "kate.winslet@tesla.com", "Kate", "Winslet" },
                    { 207, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 208, "jimi.hendrix@gov.ru", "Jimi", "Hendrix" },
                    { 209, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 210, "audrey.obama@gov.us", "Audrey", "Obama" },
                    { 211, "kate.jagger@nasa.org.us", "Kate", "Jagger" },
                    { 212, "kate.hendrix@bbc.co.uk", "Kate", "Hendrix" },
                    { 213, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 214, "audrey.windsor@bbc.co.uk", "Audrey", "Windsor" },
                    { 215, "mick.hepburn@gov.us", "Mick", "Hepburn" },
                    { 216, "oprah.hepburn@gov.ru", "Oprah", "Hepburn" },
                    { 217, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 218, "oprah.winfrey@gov.gr", "Oprah", "Winfrey" },
                    { 219, "elvis.windsor@gov.ru", "Elvis", "Windsor" },
                    { 220, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 221, "barack.winslet@tesla.com", "Barack", "Winslet" },
                    { 222, "jimi.winfrey@nasa.org.us", "Jimi", "Winfrey" },
                    { 223, "donald.presley@gov.nl", "Donald", "Presley" },
                    { 224, "jimi.middleton@nasa.org.us", "Jimi", "Middleton" },
                    { 225, "oprah.trump@gov.gr", "Oprah", "Trump" },
                    { 226, "oprah.obama@tesla.com", "Oprah", "Obama" },
                    { 227, "jimi.middleton@tesla.com", "Jimi", "Middleton" },
                    { 228, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 229, "oprah.winslet@bbc.co.uk", "Oprah", "Winslet" },
                    { 230, "jimi.windsor@gov.ru", "Jimi", "Windsor" },
                    { 231, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 232, "audrey.obama@gov.nl", "Audrey", "Obama" },
                    { 233, "jimi.obama@gov.us", "Jimi", "Obama" },
                    { 234, "kate.hepburn@gov.us", "Kate", "Hepburn" },
                    { 235, "kate.hendrix@theworld.ca", "Kate", "Hendrix" },
                    { 236, "oprah.winfrey@gov.ru", "Oprah", "Winfrey" },
                    { 237, "donald.middleton@something.com", "Donald", "Middleton" },
                    { 238, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 239, "audrey.jagger@theworld.ca", "Audrey", "Jagger" },
                    { 240, "charles.hendrix@nasa.org.us", "Charles", "Hendrix" },
                    { 241, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 242, "kate.winslet@tesla.com", "Kate", "Winslet" },
                    { 243, "audrey.presley@gov.us", "Audrey", "Presley" },
                    { 244, "kate.winfrey@tesla.com", "Kate", "Winfrey" },
                    { 245, "jimi.obama@gov.us", "Jimi", "Obama" },
                    { 246, "oprah.hepburn@gov.gr", "Oprah", "Hepburn" },
                    { 247, "kate.jagger@gov.us", "Kate", "Jagger" },
                    { 248, "audrey.hepburn@bbc.co.uk", "Audrey", "Hepburn" },
                    { 249, "donald.hepburn@tesla.com", "Donald", "Hepburn" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "AuthorId", "title" },
                values: new object[,]
                {
                    { 1, 46, "Fifteen Orange Planets" },
                    { 2, 100, "An army of Rose Smelling Leopards" },
                    { 3, 165, "A bunch of Green Cars" },
                    { 4, 19, "The Transparent Houses" },
                    { 5, 138, "The Microscopic Planets" },
                    { 6, 234, "Several Transparent Houses" },
                    { 7, 166, "Fifteen Microscopic Planets" },
                    { 8, 98, "Several Microscopic Leopards" },
                    { 9, 14, "An army of Orange Buildings" },
                    { 10, 53, "A bunch of Bitter Planets" },
                    { 11, 137, "The Transparent Leopards" },
                    { 12, 227, "Two Green Houses" },
                    { 13, 158, "Fifteen Large Houses" },
                    { 14, 223, "Fifteen Orange Houses" },
                    { 15, 186, "A herd of Microscopic Planets" },
                    { 16, 159, "Several Large Cars" },
                    { 17, 108, "Several Microscopic Cars" },
                    { 18, 223, "Two Orange Flowers" },
                    { 19, 55, "A herd of Bitter Flowers" },
                    { 20, 220, "Several Orange Houses" },
                    { 21, 83, "Fifteen Purple Flowers" },
                    { 22, 186, "A herd of Purple Planets" },
                    { 23, 54, "Two Orange Planets" },
                    { 24, 169, "Fifteen Large Leopards" },
                    { 25, 227, "Fifteen Purple Cars" },
                    { 26, 213, "Two Bitter Planets" },
                    { 27, 127, "An army of Bitter Leopards" },
                    { 28, 24, "Two Transparent Cars" },
                    { 29, 153, "Fifteen Transparent Planets" },
                    { 30, 112, "Two Green Buildings" },
                    { 31, 120, "An army of Green Planets" },
                    { 32, 219, "Two Green Buildings" },
                    { 33, 20, "A bunch of Rose Smelling Cars" },
                    { 34, 107, "The Large Buildings" },
                    { 35, 129, "Two Rose Smelling Houses" },
                    { 36, 110, "The Large Cars" },
                    { 37, 164, "The Rose Smelling Flowers" },
                    { 38, 15, "Fifteen Green Buildings" },
                    { 39, 93, "Fifteen Large Houses" },
                    { 40, 91, "The Purple Leopards" },
                    { 41, 129, "A herd of Transparent Planets" },
                    { 42, 98, "Fifteen Large Buildings" },
                    { 43, 147, "Two Orange Cars" },
                    { 44, 232, "Several Rose Smelling Planets" },
                    { 45, 187, "Two Transparent Flowers" },
                    { 46, 108, "A herd of Green Buildings" },
                    { 47, 166, "A herd of Bitter Leopards" },
                    { 48, 9, "The Green Flowers" },
                    { 49, 150, "A bunch of Green Buildings" },
                    { 50, 95, "An army of Orange Houses" },
                    { 51, 32, "Several Rose Smelling Houses" },
                    { 52, 189, "A herd of Microscopic Cars" },
                    { 53, 229, "Two Microscopic Leopards" },
                    { 54, 5, "Two Bitter Houses" },
                    { 55, 202, "A herd of Green Cars" },
                    { 56, 182, "Several Large Planets" },
                    { 57, 122, "Two Transparent Houses" },
                    { 58, 12, "Several Microscopic Flowers" },
                    { 59, 187, "Fifteen Bitter Cars" },
                    { 60, 217, "Two Large Flowers" },
                    { 61, 17, "Fifteen Bitter Houses" },
                    { 62, 54, "The Microscopic Flowers" },
                    { 63, 105, "A herd of Rose Smelling Houses" },
                    { 64, 172, "Two Large Leopards" },
                    { 65, 24, "An army of Microscopic Flowers" },
                    { 66, 159, "An army of Rose Smelling Planets" },
                    { 67, 90, "An army of Purple Houses" },
                    { 68, 15, "Two Rose Smelling Flowers" },
                    { 69, 82, "Fifteen Bitter Flowers" },
                    { 70, 9, "A bunch of Transparent Buildings" },
                    { 71, 226, "An army of Large Leopards" },
                    { 72, 13, "The Microscopic Flowers" },
                    { 73, 142, "A bunch of Green Houses" },
                    { 74, 164, "Fifteen Large Buildings" },
                    { 75, 25, "A herd of Orange Leopards" },
                    { 76, 32, "Several Bitter Buildings" },
                    { 77, 156, "An army of Green Cars" },
                    { 78, 19, "Several Orange Planets" },
                    { 79, 125, "The Bitter Flowers" },
                    { 80, 19, "Two Transparent Flowers" },
                    { 81, 241, "The Purple Planets" },
                    { 82, 105, "An army of Green Flowers" },
                    { 83, 98, "Two Purple Buildings" },
                    { 84, 152, "An army of Transparent Flowers" },
                    { 85, 117, "An army of Bitter Leopards" },
                    { 86, 220, "Two Bitter Planets" },
                    { 87, 176, "An army of Orange Houses" },
                    { 88, 232, "Two Transparent Cars" },
                    { 89, 207, "A herd of Large Buildings" },
                    { 90, 73, "The Microscopic Cars" },
                    { 91, 203, "Fifteen Transparent Planets" },
                    { 92, 145, "A bunch of Orange Buildings" },
                    { 93, 135, "An army of Green Houses" },
                    { 94, 146, "A bunch of Purple Houses" },
                    { 95, 74, "An army of Green Buildings" },
                    { 96, 71, "An army of Rose Smelling Leopards" },
                    { 97, 75, "Several Large Flowers" },
                    { 98, 188, "Several Large Flowers" },
                    { 99, 172, "Several Microscopic Planets" },
                    { 100, 34, "Two Orange Buildings" },
                    { 101, 243, "Fifteen Large Flowers" },
                    { 102, 46, "Two Bitter Flowers" },
                    { 103, 108, "Several Rose Smelling Flowers" },
                    { 104, 143, "Several Large Cars" },
                    { 105, 149, "Two Green Flowers" },
                    { 106, 49, "A bunch of Microscopic Flowers" },
                    { 107, 225, "The Large Flowers" },
                    { 108, 200, "A herd of Microscopic Leopards" },
                    { 109, 84, "A herd of Bitter Planets" },
                    { 110, 74, "Two Large Leopards" },
                    { 111, 53, "A bunch of Purple Buildings" },
                    { 112, 71, "A bunch of Orange Planets" },
                    { 113, 242, "Two Large Cars" },
                    { 114, 99, "Several Rose Smelling Buildings" },
                    { 115, 95, "Several Orange Planets" },
                    { 116, 215, "An army of Rose Smelling Flowers" },
                    { 117, 150, "A herd of Large Planets" },
                    { 118, 145, "Fifteen Transparent Cars" },
                    { 119, 92, "Several Bitter Leopards" },
                    { 120, 153, "Fifteen Transparent Flowers" },
                    { 121, 22, "A herd of Bitter Flowers" },
                    { 122, 62, "Two Orange Cars" },
                    { 123, 81, "The Orange Planets" },
                    { 124, 21, "Fifteen Orange Houses" },
                    { 125, 167, "A herd of Rose Smelling Buildings" },
                    { 126, 194, "An army of Green Buildings" },
                    { 127, 82, "Fifteen Rose Smelling Leopards" },
                    { 128, 86, "The Purple Houses" },
                    { 129, 69, "A herd of Bitter Planets" },
                    { 130, 160, "Two Orange Flowers" },
                    { 131, 191, "Fifteen Microscopic Planets" },
                    { 132, 198, "An army of Large Planets" },
                    { 133, 98, "Fifteen Microscopic Planets" },
                    { 134, 22, "A bunch of Orange Planets" },
                    { 135, 10, "Two Microscopic Planets" },
                    { 136, 130, "Several Large Planets" },
                    { 137, 140, "Fifteen Orange Cars" },
                    { 138, 5, "Several Transparent Cars" },
                    { 139, 119, "The Large Houses" },
                    { 140, 197, "An army of Green Buildings" },
                    { 141, 143, "Fifteen Rose Smelling Buildings" },
                    { 142, 188, "The Green Houses" },
                    { 143, 27, "Fifteen Purple Leopards" },
                    { 144, 201, "A bunch of Orange Leopards" },
                    { 145, 209, "Two Orange Planets" },
                    { 146, 231, "A bunch of Purple Leopards" },
                    { 147, 144, "The Rose Smelling Flowers" },
                    { 148, 7, "Several Bitter Flowers" },
                    { 149, 147, "A herd of Green Houses" },
                    { 150, 119, "Several Bitter Leopards" },
                    { 151, 11, "The Large Buildings" },
                    { 152, 226, "A herd of Orange Leopards" },
                    { 153, 194, "A herd of Orange Buildings" },
                    { 154, 187, "A herd of Large Houses" },
                    { 155, 128, "A herd of Transparent Houses" },
                    { 156, 17, "Several Rose Smelling Planets" },
                    { 157, 207, "Several Orange Flowers" },
                    { 158, 130, "Two Green Buildings" },
                    { 159, 104, "An army of Bitter Cars" },
                    { 160, 33, "An army of Green Flowers" },
                    { 161, 17, "Fifteen Orange Cars" },
                    { 162, 28, "A herd of Large Houses" },
                    { 163, 18, "Two Bitter Buildings" },
                    { 164, 105, "A bunch of Rose Smelling Cars" },
                    { 165, 227, "Two Microscopic Leopards" },
                    { 166, 130, "A bunch of Transparent Cars" },
                    { 167, 137, "A herd of Purple Cars" },
                    { 168, 241, "An army of Green Buildings" },
                    { 169, 181, "The Purple Leopards" },
                    { 170, 44, "An army of Large Buildings" },
                    { 171, 24, "A herd of Purple Buildings" },
                    { 172, 66, "Two Rose Smelling Planets" },
                    { 173, 149, "A bunch of Transparent Flowers" },
                    { 174, 155, "Several Orange Planets" },
                    { 175, 167, "Several Bitter Cars" },
                    { 176, 36, "Fifteen Rose Smelling Leopards" },
                    { 177, 183, "Two Microscopic Leopards" },
                    { 178, 82, "Fifteen Microscopic Planets" },
                    { 179, 15, "An army of Orange Leopards" },
                    { 180, 113, "A bunch of Purple Buildings" },
                    { 181, 126, "Two Rose Smelling Flowers" },
                    { 182, 196, "An army of Large Leopards" },
                    { 183, 122, "Several Transparent Planets" },
                    { 184, 74, "The Microscopic Flowers" },
                    { 185, 7, "Two Microscopic Planets" },
                    { 186, 7, "An army of Rose Smelling Houses" },
                    { 187, 207, "Two Rose Smelling Flowers" },
                    { 188, 154, "Several Large Leopards" },
                    { 189, 70, "The Green Leopards" },
                    { 190, 135, "A bunch of Purple Flowers" },
                    { 191, 148, "An army of Rose Smelling Planets" },
                    { 192, 221, "The Rose Smelling Planets" },
                    { 193, 22, "Several Transparent Flowers" },
                    { 194, 59, "A bunch of Orange Houses" },
                    { 195, 147, "Fifteen Microscopic Flowers" },
                    { 196, 14, "An army of Large Flowers" },
                    { 197, 199, "An army of Microscopic Houses" },
                    { 198, 84, "A herd of Purple Houses" },
                    { 199, 167, "An army of Transparent Cars" },
                    { 200, 85, "A bunch of Green Buildings" },
                    { 201, 8, "Fifteen Purple Cars" },
                    { 202, 190, "Several Bitter Planets" },
                    { 203, 171, "A bunch of Large Flowers" },
                    { 204, 12, "The Orange Cars" },
                    { 205, 69, "A bunch of Microscopic Cars" },
                    { 206, 228, "Two Transparent Houses" },
                    { 207, 145, "Two Bitter Leopards" },
                    { 208, 7, "A bunch of Microscopic Flowers" },
                    { 209, 212, "An army of Bitter Buildings" },
                    { 210, 241, "An army of Large Flowers" },
                    { 211, 219, "Fifteen Rose Smelling Leopards" },
                    { 212, 223, "Several Microscopic Planets" },
                    { 213, 107, "The Large Houses" },
                    { 214, 20, "The Large Cars" },
                    { 215, 53, "Two Microscopic Buildings" },
                    { 216, 142, "An army of Rose Smelling Cars" },
                    { 217, 135, "Several Microscopic Planets" },
                    { 218, 11, "An army of Purple Leopards" },
                    { 219, 20, "A herd of Green Houses" },
                    { 220, 65, "The Orange Houses" },
                    { 221, 42, "Several Rose Smelling Leopards" },
                    { 222, 76, "A bunch of Bitter Flowers" },
                    { 223, 44, "A herd of Purple Houses" },
                    { 224, 155, "The Microscopic Planets" },
                    { 225, 109, "Several Microscopic Buildings" },
                    { 226, 57, "A bunch of Transparent Flowers" },
                    { 227, 233, "Two Microscopic Buildings" },
                    { 228, 214, "Fifteen Large Houses" },
                    { 229, 169, "A bunch of Green Buildings" },
                    { 230, 148, "Fifteen Large Houses" },
                    { 231, 160, "Fifteen Microscopic Leopards" },
                    { 232, 202, "The Transparent Buildings" },
                    { 233, 157, "Two Purple Buildings" },
                    { 234, 109, "Fifteen Microscopic Leopards" },
                    { 235, 192, "Fifteen Microscopic Leopards" },
                    { 236, 81, "Fifteen Purple Leopards" },
                    { 237, 238, "The Green Planets" },
                    { 238, 220, "Fifteen Purple Leopards" },
                    { 239, 129, "Several Microscopic Buildings" },
                    { 240, 19, "Two Purple Planets" },
                    { 241, 72, "A herd of Rose Smelling Leopards" },
                    { 242, 50, "The Orange Planets" },
                    { 243, 35, "A bunch of Rose Smelling Planets" },
                    { 244, 79, "Fifteen Purple Houses" },
                    { 245, 244, "Fifteen Rose Smelling Planets" },
                    { 246, 52, "A herd of Purple Leopards" },
                    { 247, 104, "The Orange Houses" },
                    { 248, 30, "Fifteen Large Planets" },
                    { 249, 156, "The Large Flowers" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_books_AuthorId",
                table: "books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "authors");
        }
    }
}
