using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class letsgo : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    FirstName = table.Column<string>(type: "text", nullable: false),
                    LastName = table.Column<string>(type: "text", nullable: false),
                    Email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Publishers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Publishers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Books",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: false),
                    Publisher_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Books", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Books_Publishers_Publisher_id",
                        column: x => x.Publisher_id,
                        principalTable: "Publishers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "BookAuthors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    BookId = table.Column<int>(type: "integer", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BookAuthors", x => x.Id);
                    table.ForeignKey(
                        name: "FK_BookAuthors_Authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Authors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_BookAuthors_Books_BookId",
                        column: x => x.BookId,
                        principalTable: "Books",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "Id", "Email", "FirstName", "LastName" },
                values: new object[,]
                {
                    { 1, "donald.obama@google.com", "Donald", "Obama" },
                    { 2, "barack.trump@google.com", "Barack", "Trump" },
                    { 3, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 4, "oprah.middleton@something.com", "Oprah", "Middleton" },
                    { 5, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 6, "jimi.presley@nasa.org.us", "Jimi", "Presley" },
                    { 7, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 8, "jimi.hepburn@something.com", "Jimi", "Hepburn" },
                    { 9, "elvis.winfrey@gov.gr", "Elvis", "Winfrey" },
                    { 10, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 11, "elvis.windsor@gov.us", "Elvis", "Windsor" },
                    { 12, "barack.middleton@gov.gr", "Barack", "Middleton" },
                    { 13, "barack.trump@google.com", "Barack", "Trump" },
                    { 14, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 15, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 16, "donald.windsor@something.com", "Donald", "Windsor" },
                    { 17, "donald.middleton@gov.ru", "Donald", "Middleton" },
                    { 18, "donald.windsor@bbc.co.uk", "Donald", "Windsor" },
                    { 19, "oprah.hendrix@bbc.co.uk", "Oprah", "Hendrix" },
                    { 20, "mick.winfrey@gov.ru", "Mick", "Winfrey" },
                    { 21, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 22, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 23, "elvis.hepburn@nasa.org.us", "Elvis", "Hepburn" },
                    { 24, "oprah.middleton@something.com", "Oprah", "Middleton" },
                    { 25, "donald.windsor@theworld.ca", "Donald", "Windsor" },
                    { 26, "barack.jagger@bbc.co.uk", "Barack", "Jagger" },
                    { 27, "audrey.winslet@something.com", "Audrey", "Winslet" },
                    { 28, "kate.presley@gov.us", "Kate", "Presley" },
                    { 29, "charles.hepburn@something.com", "Charles", "Hepburn" },
                    { 30, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 31, "charles.presley@bbc.co.uk", "Charles", "Presley" },
                    { 32, "donald.jagger@nasa.org.us", "Donald", "Jagger" },
                    { 33, "barack.obama@gov.gr", "Barack", "Obama" },
                    { 34, "elvis.trump@google.com", "Elvis", "Trump" },
                    { 35, "charles.jagger@something.com", "Charles", "Jagger" },
                    { 36, "oprah.hepburn@gov.ru", "Oprah", "Hepburn" },
                    { 37, "jimi.hendrix@google.com", "Jimi", "Hendrix" },
                    { 38, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 39, "jimi.windsor@gov.ru", "Jimi", "Windsor" },
                    { 40, "audrey.presley@gov.nl", "Audrey", "Presley" },
                    { 41, "audrey.presley@something.com", "Audrey", "Presley" },
                    { 42, "oprah.obama@gov.gr", "Oprah", "Obama" },
                    { 43, "donald.obama@google.com", "Donald", "Obama" },
                    { 44, "jimi.obama@google.com", "Jimi", "Obama" },
                    { 45, "charles.trump@tesla.com", "Charles", "Trump" },
                    { 46, "barack.hepburn@tesla.com", "Barack", "Hepburn" },
                    { 47, "donald.obama@gov.us", "Donald", "Obama" },
                    { 48, "elvis.obama@nasa.org.us", "Elvis", "Obama" },
                    { 49, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 50, "charles.presley@something.com", "Charles", "Presley" },
                    { 51, "oprah.hepburn@bbc.co.uk", "Oprah", "Hepburn" },
                    { 52, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 53, "barack.hepburn@gov.us", "Barack", "Hepburn" },
                    { 54, "mick.obama@gov.us", "Mick", "Obama" },
                    { 55, "elvis.trump@gov.ru", "Elvis", "Trump" },
                    { 56, "donald.hendrix@gov.us", "Donald", "Hendrix" },
                    { 57, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 58, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 59, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 60, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 61, "charles.obama@gov.nl", "Charles", "Obama" },
                    { 62, "charles.winfrey@tesla.com", "Charles", "Winfrey" },
                    { 63, "donald.obama@google.com", "Donald", "Obama" },
                    { 64, "oprah.hendrix@tesla.com", "Oprah", "Hendrix" },
                    { 65, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 66, "donald.trump@bbc.co.uk", "Donald", "Trump" },
                    { 67, "kate.winfrey@tesla.com", "Kate", "Winfrey" },
                    { 68, "elvis.middleton@gov.nl", "Elvis", "Middleton" },
                    { 69, "charles.hepburn@tesla.com", "Charles", "Hepburn" },
                    { 70, "mick.obama@something.com", "Mick", "Obama" },
                    { 71, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 72, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 73, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 74, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 75, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 76, "donald.middleton@gov.nl", "Donald", "Middleton" },
                    { 77, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 78, "elvis.windsor@nasa.org.us", "Elvis", "Windsor" },
                    { 79, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 80, "donald.middleton@gov.ru", "Donald", "Middleton" },
                    { 81, "mick.jagger@tesla.com", "Mick", "Jagger" },
                    { 82, "jimi.hendrix@something.com", "Jimi", "Hendrix" },
                    { 83, "elvis.presley@gov.ru", "Elvis", "Presley" },
                    { 84, "elvis.hepburn@gov.gr", "Elvis", "Hepburn" },
                    { 85, "mick.presley@gov.nl", "Mick", "Presley" },
                    { 86, "barack.trump@gov.gr", "Barack", "Trump" },
                    { 87, "oprah.hepburn@something.com", "Oprah", "Hepburn" },
                    { 88, "elvis.hendrix@nasa.org.us", "Elvis", "Hendrix" },
                    { 89, "elvis.jagger@bbc.co.uk", "Elvis", "Jagger" },
                    { 90, "mick.winslet@gov.gr", "Mick", "Winslet" },
                    { 91, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 92, "jimi.hendrix@theworld.ca", "Jimi", "Hendrix" },
                    { 93, "oprah.trump@theworld.ca", "Oprah", "Trump" },
                    { 94, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 95, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 96, "donald.windsor@gov.gr", "Donald", "Windsor" },
                    { 97, "elvis.windsor@gov.nl", "Elvis", "Windsor" },
                    { 98, "jimi.winslet@google.com", "Jimi", "Winslet" },
                    { 99, "jimi.hepburn@gov.ru", "Jimi", "Hepburn" },
                    { 100, "audrey.presley@tesla.com", "Audrey", "Presley" },
                    { 101, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 102, "jimi.hepburn@bbc.co.uk", "Jimi", "Hepburn" },
                    { 103, "charles.obama@something.com", "Charles", "Obama" },
                    { 104, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 105, "elvis.hepburn@something.com", "Elvis", "Hepburn" },
                    { 106, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 107, "jimi.winslet@gov.ru", "Jimi", "Winslet" },
                    { 108, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 109, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 110, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 111, "elvis.hendrix@gov.ru", "Elvis", "Hendrix" },
                    { 112, "donald.winslet@bbc.co.uk", "Donald", "Winslet" },
                    { 113, "charles.obama@google.com", "Charles", "Obama" },
                    { 114, "charles.windsor@google.com", "Charles", "Windsor" },
                    { 115, "barack.jagger@gov.ru", "Barack", "Jagger" },
                    { 116, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 117, "charles.jagger@something.com", "Charles", "Jagger" },
                    { 118, "barack.winfrey@bbc.co.uk", "Barack", "Winfrey" },
                    { 119, "jimi.winslet@gov.us", "Jimi", "Winslet" },
                    { 120, "audrey.jagger@theworld.ca", "Audrey", "Jagger" },
                    { 121, "kate.presley@tesla.com", "Kate", "Presley" },
                    { 122, "audrey.middleton@google.com", "Audrey", "Middleton" },
                    { 123, "oprah.trump@gov.ru", "Oprah", "Trump" },
                    { 124, "kate.presley@google.com", "Kate", "Presley" },
                    { 125, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 126, "oprah.hepburn@bbc.co.uk", "Oprah", "Hepburn" },
                    { 127, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 128, "kate.winslet@google.com", "Kate", "Winslet" },
                    { 129, "oprah.hendrix@gov.nl", "Oprah", "Hendrix" },
                    { 130, "barack.trump@nasa.org.us", "Barack", "Trump" },
                    { 131, "barack.presley@nasa.org.us", "Barack", "Presley" },
                    { 132, "oprah.trump@nasa.org.us", "Oprah", "Trump" },
                    { 133, "oprah.middleton@google.com", "Oprah", "Middleton" },
                    { 134, "mick.jagger@gov.ru", "Mick", "Jagger" },
                    { 135, "mick.windsor@something.com", "Mick", "Windsor" },
                    { 136, "donald.presley@gov.ru", "Donald", "Presley" },
                    { 137, "donald.presley@nasa.org.us", "Donald", "Presley" },
                    { 138, "elvis.winfrey@tesla.com", "Elvis", "Winfrey" },
                    { 139, "jimi.jagger@theworld.ca", "Jimi", "Jagger" },
                    { 140, "kate.obama@something.com", "Kate", "Obama" },
                    { 141, "donald.hendrix@tesla.com", "Donald", "Hendrix" },
                    { 142, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 143, "jimi.windsor@bbc.co.uk", "Jimi", "Windsor" },
                    { 144, "barack.winfrey@gov.gr", "Barack", "Winfrey" },
                    { 145, "barack.windsor@gov.ru", "Barack", "Windsor" },
                    { 146, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 147, "oprah.middleton@tesla.com", "Oprah", "Middleton" },
                    { 148, "oprah.winfrey@theworld.ca", "Oprah", "Winfrey" },
                    { 149, "charles.jagger@gov.gr", "Charles", "Jagger" },
                    { 150, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 151, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 152, "audrey.middleton@gov.ru", "Audrey", "Middleton" },
                    { 153, "elvis.winslet@gov.nl", "Elvis", "Winslet" },
                    { 154, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 155, "elvis.obama@tesla.com", "Elvis", "Obama" },
                    { 156, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 157, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 158, "kate.hepburn@nasa.org.us", "Kate", "Hepburn" },
                    { 159, "mick.trump@gov.nl", "Mick", "Trump" },
                    { 160, "elvis.hendrix@gov.nl", "Elvis", "Hendrix" },
                    { 161, "audrey.jagger@something.com", "Audrey", "Jagger" },
                    { 162, "charles.obama@gov.us", "Charles", "Obama" },
                    { 163, "barack.hepburn@gov.ru", "Barack", "Hepburn" },
                    { 164, "mick.windsor@gov.ru", "Mick", "Windsor" },
                    { 165, "kate.middleton@google.com", "Kate", "Middleton" },
                    { 166, "elvis.trump@something.com", "Elvis", "Trump" },
                    { 167, "mick.jagger@gov.us", "Mick", "Jagger" },
                    { 168, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 169, "jimi.obama@tesla.com", "Jimi", "Obama" },
                    { 170, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 171, "donald.trump@theworld.ca", "Donald", "Trump" },
                    { 172, "mick.jagger@gov.ru", "Mick", "Jagger" },
                    { 173, "kate.presley@bbc.co.uk", "Kate", "Presley" },
                    { 174, "charles.trump@nasa.org.us", "Charles", "Trump" },
                    { 175, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 176, "mick.hendrix@gov.gr", "Mick", "Hendrix" },
                    { 177, "mick.obama@nasa.org.us", "Mick", "Obama" },
                    { 178, "mick.winfrey@tesla.com", "Mick", "Winfrey" },
                    { 179, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 180, "audrey.middleton@nasa.org.us", "Audrey", "Middleton" },
                    { 181, "elvis.presley@something.com", "Elvis", "Presley" },
                    { 182, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 183, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 184, "elvis.obama@bbc.co.uk", "Elvis", "Obama" },
                    { 185, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 186, "donald.winslet@gov.us", "Donald", "Winslet" },
                    { 187, "donald.hepburn@gov.ru", "Donald", "Hepburn" },
                    { 188, "audrey.winslet@gov.nl", "Audrey", "Winslet" },
                    { 189, "mick.windsor@gov.gr", "Mick", "Windsor" },
                    { 190, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 191, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 192, "jimi.winfrey@something.com", "Jimi", "Winfrey" },
                    { 193, "elvis.jagger@gov.nl", "Elvis", "Jagger" },
                    { 194, "charles.trump@theworld.ca", "Charles", "Trump" },
                    { 195, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 196, "oprah.trump@nasa.org.us", "Oprah", "Trump" },
                    { 197, "elvis.winfrey@bbc.co.uk", "Elvis", "Winfrey" },
                    { 198, "kate.obama@something.com", "Kate", "Obama" },
                    { 199, "kate.trump@bbc.co.uk", "Kate", "Trump" },
                    { 200, "donald.presley@gov.ru", "Donald", "Presley" },
                    { 201, "oprah.windsor@google.com", "Oprah", "Windsor" },
                    { 202, "oprah.presley@bbc.co.uk", "Oprah", "Presley" },
                    { 203, "mick.windsor@gov.ru", "Mick", "Windsor" },
                    { 204, "mick.trump@tesla.com", "Mick", "Trump" },
                    { 205, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 206, "donald.middleton@gov.nl", "Donald", "Middleton" },
                    { 207, "elvis.obama@gov.nl", "Elvis", "Obama" },
                    { 208, "jimi.hendrix@nasa.org.us", "Jimi", "Hendrix" },
                    { 209, "jimi.obama@theworld.ca", "Jimi", "Obama" },
                    { 210, "mick.winfrey@bbc.co.uk", "Mick", "Winfrey" },
                    { 211, "oprah.winfrey@something.com", "Oprah", "Winfrey" },
                    { 212, "donald.windsor@bbc.co.uk", "Donald", "Windsor" },
                    { 213, "jimi.windsor@tesla.com", "Jimi", "Windsor" },
                    { 214, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 215, "donald.middleton@something.com", "Donald", "Middleton" },
                    { 216, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 217, "barack.winfrey@tesla.com", "Barack", "Winfrey" },
                    { 218, "charles.windsor@something.com", "Charles", "Windsor" },
                    { 219, "barack.winslet@gov.us", "Barack", "Winslet" },
                    { 220, "jimi.middleton@bbc.co.uk", "Jimi", "Middleton" },
                    { 221, "mick.presley@google.com", "Mick", "Presley" },
                    { 222, "mick.hepburn@theworld.ca", "Mick", "Hepburn" },
                    { 223, "donald.winfrey@bbc.co.uk", "Donald", "Winfrey" },
                    { 224, "audrey.jagger@gov.nl", "Audrey", "Jagger" },
                    { 225, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 226, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 227, "jimi.trump@tesla.com", "Jimi", "Trump" },
                    { 228, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 229, "elvis.obama@tesla.com", "Elvis", "Obama" },
                    { 230, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 231, "jimi.middleton@gov.nl", "Jimi", "Middleton" },
                    { 232, "elvis.windsor@nasa.org.us", "Elvis", "Windsor" },
                    { 233, "jimi.hendrix@nasa.org.us", "Jimi", "Hendrix" },
                    { 234, "oprah.trump@gov.us", "Oprah", "Trump" },
                    { 235, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 236, "audrey.hendrix@tesla.com", "Audrey", "Hendrix" },
                    { 237, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 238, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 239, "donald.presley@theworld.ca", "Donald", "Presley" },
                    { 240, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 241, "elvis.trump@gov.us", "Elvis", "Trump" },
                    { 242, "barack.presley@something.com", "Barack", "Presley" },
                    { 243, "donald.jagger@nasa.org.us", "Donald", "Jagger" },
                    { 244, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 245, "oprah.winslet@gov.nl", "Oprah", "Winslet" },
                    { 246, "elvis.middleton@google.com", "Elvis", "Middleton" },
                    { 247, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 248, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 249, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" }
                });

            migrationBuilder.InsertData(
                table: "Publishers",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Hammock" },
                    { 2, "Strawberry" },
                    { 3, "NewsCoo" },
                    { 4, "BreakingNews" },
                    { 5, "Indo" },
                    { 6, "Pearson" },
                    { 7, "Bjørnstjerne" },
                    { 8, "Bjørnson" }
                });

            migrationBuilder.InsertData(
                table: "Books",
                columns: new[] { "Id", "Publisher_id", "Title" },
                values: new object[,]
                {
                    { 1, 8, "Fifteen Rose Smelling Buildings" },
                    { 2, 1, "Several Orange Flowers" },
                    { 3, 2, "Two Green Houses" },
                    { 4, 6, "Several Microscopic Leopards" },
                    { 5, 3, "The Orange Planets" },
                    { 6, 6, "Several Orange Buildings" },
                    { 7, 7, "Fifteen Purple Planets" },
                    { 8, 5, "Fifteen Orange Buildings" },
                    { 9, 1, "The Orange Leopards" },
                    { 10, 4, "A bunch of Bitter Buildings" },
                    { 11, 2, "Fifteen Microscopic Planets" },
                    { 12, 7, "A herd of Rose Smelling Leopards" },
                    { 13, 5, "A bunch of Purple Flowers" },
                    { 14, 6, "An army of Bitter Leopards" },
                    { 15, 7, "A bunch of Rose Smelling Planets" },
                    { 16, 3, "Two Purple Planets" },
                    { 17, 5, "Two Orange Leopards" },
                    { 18, 5, "A herd of Bitter Planets" },
                    { 19, 6, "A herd of Orange Buildings" },
                    { 20, 3, "Fifteen Microscopic Flowers" },
                    { 21, 1, "Fifteen Orange Leopards" },
                    { 22, 1, "An army of Orange Leopards" },
                    { 23, 6, "Several Rose Smelling Flowers" },
                    { 24, 5, "A herd of Rose Smelling Flowers" },
                    { 25, 5, "Two Bitter Buildings" },
                    { 26, 7, "Fifteen Orange Cars" },
                    { 27, 2, "The Orange Leopards" },
                    { 28, 6, "A bunch of Transparent Flowers" },
                    { 29, 1, "An army of Bitter Planets" },
                    { 30, 8, "The Orange Leopards" },
                    { 31, 8, "Several Transparent Houses" },
                    { 32, 8, "An army of Orange Houses" },
                    { 33, 1, "A herd of Green Planets" },
                    { 34, 7, "An army of Rose Smelling Buildings" },
                    { 35, 6, "A herd of Large Buildings" },
                    { 36, 6, "An army of Orange Buildings" },
                    { 37, 7, "An army of Orange Flowers" },
                    { 38, 1, "Fifteen Green Leopards" },
                    { 39, 8, "Fifteen Transparent Buildings" },
                    { 40, 2, "Fifteen Bitter Planets" },
                    { 41, 2, "A herd of Large Buildings" },
                    { 42, 3, "Two Rose Smelling Leopards" },
                    { 43, 6, "A herd of Orange Houses" },
                    { 44, 4, "Several Bitter Houses" },
                    { 45, 8, "Fifteen Rose Smelling Buildings" },
                    { 46, 2, "Fifteen Microscopic Flowers" },
                    { 47, 1, "A bunch of Rose Smelling Planets" },
                    { 48, 5, "An army of Bitter Cars" },
                    { 49, 5, "The Large Flowers" },
                    { 50, 4, "Two Transparent Leopards" },
                    { 51, 3, "An army of Orange Houses" },
                    { 52, 2, "Two Purple Leopards" },
                    { 53, 5, "The Transparent Cars" },
                    { 54, 1, "Several Green Cars" },
                    { 55, 8, "An army of Large Leopards" },
                    { 56, 3, "An army of Green Cars" },
                    { 57, 6, "Two Orange Planets" },
                    { 58, 6, "A herd of Purple Houses" },
                    { 59, 5, "Fifteen Bitter Houses" },
                    { 60, 8, "Two Bitter Buildings" },
                    { 61, 7, "Fifteen Microscopic Buildings" },
                    { 62, 1, "The Orange Planets" },
                    { 63, 3, "The Rose Smelling Leopards" },
                    { 64, 5, "Two Microscopic Houses" },
                    { 65, 6, "Fifteen Microscopic Planets" },
                    { 66, 1, "The Large Leopards" },
                    { 67, 7, "Two Purple Cars" },
                    { 68, 5, "Two Transparent Leopards" },
                    { 69, 5, "The Purple Houses" },
                    { 70, 4, "Two Green Cars" },
                    { 71, 5, "A herd of Bitter Flowers" },
                    { 72, 2, "A herd of Rose Smelling Buildings" },
                    { 73, 1, "Several Bitter Planets" },
                    { 74, 8, "Several Microscopic Cars" },
                    { 75, 4, "Fifteen Bitter Leopards" },
                    { 76, 3, "Two Transparent Buildings" },
                    { 77, 2, "An army of Microscopic Cars" },
                    { 78, 1, "Several Green Cars" },
                    { 79, 3, "Two Transparent Planets" },
                    { 80, 7, "An army of Bitter Flowers" },
                    { 81, 2, "Two Microscopic Buildings" },
                    { 82, 1, "An army of Green Leopards" },
                    { 83, 8, "Two Orange Houses" },
                    { 84, 3, "An army of Green Cars" },
                    { 85, 7, "A bunch of Purple Planets" },
                    { 86, 1, "Fifteen Green Leopards" },
                    { 87, 5, "Two Transparent Flowers" },
                    { 88, 3, "The Orange Buildings" },
                    { 89, 6, "Several Rose Smelling Houses" },
                    { 90, 3, "A herd of Purple Flowers" },
                    { 91, 2, "The Large Houses" },
                    { 92, 5, "The Microscopic Flowers" },
                    { 93, 2, "Fifteen Transparent Leopards" },
                    { 94, 7, "Fifteen Purple Leopards" },
                    { 95, 8, "The Rose Smelling Buildings" },
                    { 96, 8, "A bunch of Rose Smelling Planets" },
                    { 97, 1, "A herd of Orange Cars" },
                    { 98, 3, "Two Rose Smelling Leopards" },
                    { 99, 2, "A herd of Transparent Cars" },
                    { 100, 2, "Two Green Houses" },
                    { 101, 7, "Fifteen Green Houses" },
                    { 102, 4, "The Purple Buildings" },
                    { 103, 8, "Fifteen Microscopic Leopards" },
                    { 104, 8, "Fifteen Green Cars" },
                    { 105, 7, "An army of Orange Planets" },
                    { 106, 6, "The Rose Smelling Flowers" },
                    { 107, 7, "A bunch of Bitter Planets" },
                    { 108, 8, "A herd of Bitter Planets" },
                    { 109, 3, "The Orange Buildings" },
                    { 110, 2, "A herd of Rose Smelling Buildings" },
                    { 111, 5, "A herd of Transparent Cars" },
                    { 112, 6, "Two Bitter Planets" },
                    { 113, 8, "A bunch of Green Cars" },
                    { 114, 6, "Fifteen Green Planets" },
                    { 115, 2, "A bunch of Microscopic Leopards" },
                    { 116, 1, "Two Orange Houses" },
                    { 117, 1, "Two Green Leopards" },
                    { 118, 7, "Fifteen Microscopic Houses" },
                    { 119, 7, "A bunch of Large Houses" },
                    { 120, 8, "The Orange Cars" },
                    { 121, 7, "An army of Transparent Cars" },
                    { 122, 7, "A herd of Purple Flowers" },
                    { 123, 7, "The Transparent Buildings" },
                    { 124, 1, "The Bitter Flowers" },
                    { 125, 5, "A herd of Large Buildings" },
                    { 126, 2, "A herd of Large Buildings" },
                    { 127, 6, "An army of Transparent Houses" },
                    { 128, 8, "The Purple Buildings" },
                    { 129, 2, "A herd of Purple Buildings" },
                    { 130, 5, "Two Bitter Cars" },
                    { 131, 7, "A bunch of Purple Leopards" },
                    { 132, 5, "Fifteen Rose Smelling Cars" },
                    { 133, 6, "A bunch of Green Buildings" },
                    { 134, 2, "Two Large Cars" },
                    { 135, 3, "An army of Purple Leopards" },
                    { 136, 8, "The Rose Smelling Houses" },
                    { 137, 2, "Fifteen Bitter Leopards" },
                    { 138, 8, "Several Large Cars" },
                    { 139, 3, "A bunch of Bitter Leopards" },
                    { 140, 8, "A herd of Green Flowers" },
                    { 141, 7, "An army of Rose Smelling Flowers" },
                    { 142, 4, "The Rose Smelling Buildings" },
                    { 143, 6, "An army of Bitter Houses" },
                    { 144, 4, "A herd of Rose Smelling Houses" },
                    { 145, 2, "A herd of Purple Cars" },
                    { 146, 2, "A herd of Microscopic Cars" },
                    { 147, 4, "An army of Purple Flowers" },
                    { 148, 1, "The Purple Houses" },
                    { 149, 8, "A bunch of Green Houses" },
                    { 150, 2, "Two Rose Smelling Buildings" },
                    { 151, 3, "Two Transparent Planets" },
                    { 152, 6, "A herd of Bitter Houses" },
                    { 153, 2, "The Bitter Cars" },
                    { 154, 7, "An army of Rose Smelling Houses" },
                    { 155, 8, "A herd of Orange Buildings" },
                    { 156, 4, "Two Orange Buildings" },
                    { 157, 6, "A herd of Green Houses" },
                    { 158, 4, "The Orange Leopards" },
                    { 159, 4, "Two Large Cars" },
                    { 160, 1, "The Purple Cars" },
                    { 161, 7, "Fifteen Rose Smelling Houses" },
                    { 162, 2, "An army of Microscopic Planets" },
                    { 163, 5, "Fifteen Large Buildings" },
                    { 164, 3, "An army of Green Buildings" },
                    { 165, 1, "The Transparent Planets" },
                    { 166, 5, "A bunch of Bitter Planets" },
                    { 167, 7, "A bunch of Bitter Cars" },
                    { 168, 7, "A herd of Green Houses" },
                    { 169, 5, "Several Transparent Planets" },
                    { 170, 7, "Fifteen Purple Leopards" },
                    { 171, 8, "A herd of Microscopic Planets" },
                    { 172, 1, "Fifteen Purple Houses" },
                    { 173, 4, "Several Microscopic Houses" },
                    { 174, 4, "A herd of Green Leopards" },
                    { 175, 1, "An army of Microscopic Cars" },
                    { 176, 5, "A herd of Purple Cars" },
                    { 177, 2, "Two Large Cars" },
                    { 178, 8, "Two Transparent Houses" },
                    { 179, 7, "An army of Large Cars" },
                    { 180, 6, "An army of Rose Smelling Flowers" },
                    { 181, 4, "Fifteen Transparent Buildings" },
                    { 182, 3, "The Bitter Cars" },
                    { 183, 4, "A bunch of Orange Flowers" },
                    { 184, 5, "The Purple Leopards" },
                    { 185, 5, "A bunch of Transparent Buildings" },
                    { 186, 8, "A herd of Bitter Flowers" },
                    { 187, 1, "A herd of Green Buildings" },
                    { 188, 6, "Several Green Flowers" },
                    { 189, 3, "A bunch of Bitter Planets" },
                    { 190, 5, "An army of Microscopic Flowers" },
                    { 191, 5, "A bunch of Purple Planets" },
                    { 192, 2, "A herd of Large Buildings" },
                    { 193, 6, "The Large Leopards" },
                    { 194, 7, "A bunch of Rose Smelling Flowers" },
                    { 195, 8, "A bunch of Large Flowers" },
                    { 196, 4, "A bunch of Green Buildings" },
                    { 197, 7, "A bunch of Bitter Cars" },
                    { 198, 7, "The Purple Planets" },
                    { 199, 3, "Several Transparent Buildings" },
                    { 200, 5, "Fifteen Green Leopards" },
                    { 201, 8, "A herd of Orange Flowers" },
                    { 202, 1, "A bunch of Purple Leopards" },
                    { 203, 7, "Two Rose Smelling Planets" },
                    { 204, 3, "Fifteen Purple Planets" },
                    { 205, 8, "Two Microscopic Cars" },
                    { 206, 1, "Several Large Buildings" },
                    { 207, 4, "A herd of Orange Buildings" },
                    { 208, 8, "The Rose Smelling Leopards" },
                    { 209, 5, "Several Rose Smelling Planets" },
                    { 210, 8, "An army of Orange Cars" },
                    { 211, 4, "Two Bitter Planets" },
                    { 212, 8, "Several Rose Smelling Planets" },
                    { 213, 1, "Several Microscopic Buildings" },
                    { 214, 3, "Fifteen Large Planets" },
                    { 215, 4, "The Transparent Leopards" },
                    { 216, 1, "Fifteen Purple Houses" },
                    { 217, 4, "An army of Bitter Buildings" },
                    { 218, 2, "Several Purple Buildings" },
                    { 219, 2, "A herd of Green Cars" },
                    { 220, 8, "A herd of Purple Buildings" },
                    { 221, 4, "Two Orange Buildings" },
                    { 222, 6, "The Bitter Cars" },
                    { 223, 7, "A bunch of Purple Buildings" },
                    { 224, 8, "A herd of Bitter Buildings" },
                    { 225, 7, "A bunch of Transparent Leopards" },
                    { 226, 2, "An army of Purple Planets" },
                    { 227, 5, "A herd of Transparent Leopards" },
                    { 228, 7, "A herd of Transparent Houses" },
                    { 229, 1, "Two Rose Smelling Leopards" },
                    { 230, 3, "A herd of Transparent Cars" },
                    { 231, 2, "The Transparent Leopards" },
                    { 232, 1, "A bunch of Orange Cars" },
                    { 233, 8, "A herd of Transparent Cars" },
                    { 234, 7, "Several Bitter Leopards" },
                    { 235, 2, "Several Transparent Cars" },
                    { 236, 8, "An army of Bitter Buildings" },
                    { 237, 6, "A bunch of Purple Planets" },
                    { 238, 4, "An army of Purple Houses" },
                    { 239, 4, "The Green Cars" },
                    { 240, 2, "The Orange Cars" },
                    { 241, 5, "A bunch of Microscopic Leopards" },
                    { 242, 3, "A bunch of Purple Planets" },
                    { 243, 6, "The Green Houses" },
                    { 244, 2, "An army of Orange Houses" },
                    { 245, 4, "Several Transparent Planets" },
                    { 246, 8, "Two Bitter Flowers" },
                    { 247, 3, "A herd of Bitter Flowers" },
                    { 248, 1, "The Orange Houses" },
                    { 249, 7, "Two Microscopic Flowers" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_BookAuthors_AuthorId",
                table: "BookAuthors",
                column: "AuthorId");

            migrationBuilder.CreateIndex(
                name: "IX_BookAuthors_BookId",
                table: "BookAuthors",
                column: "BookId");

            migrationBuilder.CreateIndex(
                name: "IX_Books_Publisher_id",
                table: "Books",
                column: "Publisher_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "BookAuthors");

            migrationBuilder.DropTable(
                name: "Authors");

            migrationBuilder.DropTable(
                name: "Books");

            migrationBuilder.DropTable(
                name: "Publishers");
        }
    }
}
