using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class first : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    first_name = table.Column<string>(type: "text", nullable: false),
                    last_name = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "authors",
                columns: new[] { "id", "email", "first_name", "last_name" },
                values: new object[,]
                {
                    { 1, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 2, "donald.presley@gov.gr", "Donald", "Presley" },
                    { 3, "audrey.winfrey@theworld.ca", "Audrey", "Winfrey" },
                    { 4, "mick.hendrix@gov.ru", "Mick", "Hendrix" },
                    { 5, "jimi.trump@gov.ru", "Jimi", "Trump" },
                    { 6, "donald.jagger@google.com", "Donald", "Jagger" },
                    { 7, "jimi.hendrix@bbc.co.uk", "Jimi", "Hendrix" },
                    { 8, "oprah.middleton@tesla.com", "Oprah", "Middleton" },
                    { 9, "jimi.jagger@gov.ru", "Jimi", "Jagger" },
                    { 10, "donald.winslet@gov.nl", "Donald", "Winslet" },
                    { 11, "kate.winfrey@bbc.co.uk", "Kate", "Winfrey" },
                    { 12, "kate.winfrey@tesla.com", "Kate", "Winfrey" },
                    { 13, "audrey.winfrey@gov.gr", "Audrey", "Winfrey" },
                    { 14, "audrey.middleton@gov.nl", "Audrey", "Middleton" },
                    { 15, "mick.hendrix@nasa.org.us", "Mick", "Hendrix" },
                    { 16, "audrey.hendrix@theworld.ca", "Audrey", "Hendrix" },
                    { 17, "elvis.middleton@theworld.ca", "Elvis", "Middleton" },
                    { 18, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 19, "oprah.hendrix@gov.ru", "Oprah", "Hendrix" },
                    { 20, "jimi.winslet@gov.gr", "Jimi", "Winslet" },
                    { 21, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 22, "elvis.winslet@nasa.org.us", "Elvis", "Winslet" },
                    { 23, "charles.trump@gov.nl", "Charles", "Trump" },
                    { 24, "barack.presley@gov.ru", "Barack", "Presley" },
                    { 25, "mick.hepburn@gov.gr", "Mick", "Hepburn" },
                    { 26, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 27, "donald.winfrey@gov.us", "Donald", "Winfrey" },
                    { 28, "donald.winslet@gov.us", "Donald", "Winslet" },
                    { 29, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 30, "mick.hepburn@gov.us", "Mick", "Hepburn" },
                    { 31, "kate.jagger@nasa.org.us", "Kate", "Jagger" },
                    { 32, "charles.obama@gov.gr", "Charles", "Obama" },
                    { 33, "oprah.hendrix@theworld.ca", "Oprah", "Hendrix" },
                    { 34, "barack.jagger@gov.us", "Barack", "Jagger" },
                    { 35, "barack.presley@something.com", "Barack", "Presley" },
                    { 36, "donald.winslet@nasa.org.us", "Donald", "Winslet" },
                    { 37, "jimi.winfrey@gov.gr", "Jimi", "Winfrey" },
                    { 38, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 39, "donald.middleton@bbc.co.uk", "Donald", "Middleton" },
                    { 40, "charles.hendrix@tesla.com", "Charles", "Hendrix" },
                    { 41, "kate.middleton@google.com", "Kate", "Middleton" },
                    { 42, "donald.windsor@gov.nl", "Donald", "Windsor" },
                    { 43, "mick.obama@google.com", "Mick", "Obama" },
                    { 44, "kate.trump@gov.us", "Kate", "Trump" },
                    { 45, "charles.obama@gov.us", "Charles", "Obama" },
                    { 46, "mick.middleton@google.com", "Mick", "Middleton" },
                    { 47, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 48, "kate.trump@nasa.org.us", "Kate", "Trump" },
                    { 49, "charles.jagger@nasa.org.us", "Charles", "Jagger" },
                    { 50, "kate.middleton@tesla.com", "Kate", "Middleton" },
                    { 51, "charles.trump@nasa.org.us", "Charles", "Trump" },
                    { 52, "audrey.jagger@something.com", "Audrey", "Jagger" },
                    { 53, "jimi.trump@something.com", "Jimi", "Trump" },
                    { 54, "elvis.trump@gov.ru", "Elvis", "Trump" },
                    { 55, "oprah.trump@gov.ru", "Oprah", "Trump" },
                    { 56, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 57, "barack.presley@gov.us", "Barack", "Presley" },
                    { 58, "oprah.hendrix@theworld.ca", "Oprah", "Hendrix" },
                    { 59, "mick.windsor@tesla.com", "Mick", "Windsor" },
                    { 60, "audrey.windsor@google.com", "Audrey", "Windsor" },
                    { 61, "elvis.windsor@google.com", "Elvis", "Windsor" },
                    { 62, "charles.obama@gov.us", "Charles", "Obama" },
                    { 63, "mick.winfrey@theworld.ca", "Mick", "Winfrey" },
                    { 64, "elvis.presley@gov.us", "Elvis", "Presley" },
                    { 65, "audrey.jagger@gov.ru", "Audrey", "Jagger" },
                    { 66, "jimi.hendrix@gov.nl", "Jimi", "Hendrix" },
                    { 67, "elvis.hendrix@gov.ru", "Elvis", "Hendrix" },
                    { 68, "mick.jagger@theworld.ca", "Mick", "Jagger" },
                    { 69, "elvis.trump@gov.ru", "Elvis", "Trump" },
                    { 70, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 71, "oprah.winslet@bbc.co.uk", "Oprah", "Winslet" },
                    { 72, "oprah.winfrey@something.com", "Oprah", "Winfrey" },
                    { 73, "barack.hepburn@theworld.ca", "Barack", "Hepburn" },
                    { 74, "jimi.middleton@tesla.com", "Jimi", "Middleton" },
                    { 75, "donald.middleton@theworld.ca", "Donald", "Middleton" },
                    { 76, "oprah.presley@tesla.com", "Oprah", "Presley" },
                    { 77, "barack.presley@tesla.com", "Barack", "Presley" },
                    { 78, "charles.hepburn@tesla.com", "Charles", "Hepburn" },
                    { 79, "oprah.trump@gov.us", "Oprah", "Trump" },
                    { 80, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 81, "barack.windsor@nasa.org.us", "Barack", "Windsor" },
                    { 82, "elvis.hendrix@tesla.com", "Elvis", "Hendrix" },
                    { 83, "mick.winfrey@tesla.com", "Mick", "Winfrey" },
                    { 84, "mick.middleton@something.com", "Mick", "Middleton" },
                    { 85, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 86, "mick.winslet@gov.us", "Mick", "Winslet" },
                    { 87, "barack.presley@gov.us", "Barack", "Presley" },
                    { 88, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 89, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 90, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 91, "jimi.hendrix@gov.ru", "Jimi", "Hendrix" },
                    { 92, "mick.winfrey@gov.us", "Mick", "Winfrey" },
                    { 93, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 94, "elvis.winfrey@tesla.com", "Elvis", "Winfrey" },
                    { 95, "donald.presley@theworld.ca", "Donald", "Presley" },
                    { 96, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 97, "barack.hepburn@tesla.com", "Barack", "Hepburn" },
                    { 98, "charles.middleton@nasa.org.us", "Charles", "Middleton" },
                    { 99, "oprah.winfrey@gov.nl", "Oprah", "Winfrey" },
                    { 100, "kate.obama@google.com", "Kate", "Obama" },
                    { 101, "audrey.middleton@gov.gr", "Audrey", "Middleton" },
                    { 102, "donald.windsor@gov.gr", "Donald", "Windsor" },
                    { 103, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 104, "jimi.trump@google.com", "Jimi", "Trump" },
                    { 105, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 106, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 107, "jimi.presley@bbc.co.uk", "Jimi", "Presley" },
                    { 108, "oprah.windsor@gov.nl", "Oprah", "Windsor" },
                    { 109, "charles.jagger@gov.gr", "Charles", "Jagger" },
                    { 110, "audrey.winslet@gov.ru", "Audrey", "Winslet" },
                    { 111, "barack.hendrix@nasa.org.us", "Barack", "Hendrix" },
                    { 112, "charles.winslet@something.com", "Charles", "Winslet" },
                    { 113, "mick.windsor@bbc.co.uk", "Mick", "Windsor" },
                    { 114, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 115, "oprah.middleton@gov.ru", "Oprah", "Middleton" },
                    { 116, "kate.trump@gov.us", "Kate", "Trump" },
                    { 117, "jimi.trump@gov.us", "Jimi", "Trump" },
                    { 118, "barack.trump@theworld.ca", "Barack", "Trump" },
                    { 119, "barack.obama@gov.us", "Barack", "Obama" },
                    { 120, "donald.winfrey@google.com", "Donald", "Winfrey" },
                    { 121, "audrey.winslet@nasa.org.us", "Audrey", "Winslet" },
                    { 122, "audrey.hepburn@nasa.org.us", "Audrey", "Hepburn" },
                    { 123, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 124, "charles.presley@tesla.com", "Charles", "Presley" },
                    { 125, "donald.obama@something.com", "Donald", "Obama" },
                    { 126, "jimi.obama@gov.nl", "Jimi", "Obama" },
                    { 127, "mick.jagger@theworld.ca", "Mick", "Jagger" },
                    { 128, "elvis.middleton@google.com", "Elvis", "Middleton" },
                    { 129, "charles.hepburn@theworld.ca", "Charles", "Hepburn" },
                    { 130, "kate.hendrix@bbc.co.uk", "Kate", "Hendrix" },
                    { 131, "charles.winslet@nasa.org.us", "Charles", "Winslet" },
                    { 132, "donald.winfrey@bbc.co.uk", "Donald", "Winfrey" },
                    { 133, "charles.hendrix@bbc.co.uk", "Charles", "Hendrix" },
                    { 134, "kate.obama@tesla.com", "Kate", "Obama" },
                    { 135, "elvis.middleton@gov.nl", "Elvis", "Middleton" },
                    { 136, "elvis.windsor@bbc.co.uk", "Elvis", "Windsor" },
                    { 137, "elvis.middleton@gov.ru", "Elvis", "Middleton" },
                    { 138, "elvis.middleton@bbc.co.uk", "Elvis", "Middleton" },
                    { 139, "audrey.windsor@gov.us", "Audrey", "Windsor" },
                    { 140, "barack.winfrey@theworld.ca", "Barack", "Winfrey" },
                    { 141, "jimi.middleton@tesla.com", "Jimi", "Middleton" },
                    { 142, "mick.hendrix@theworld.ca", "Mick", "Hendrix" },
                    { 143, "kate.middleton@gov.ru", "Kate", "Middleton" },
                    { 144, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 145, "kate.middleton@tesla.com", "Kate", "Middleton" },
                    { 146, "oprah.middleton@nasa.org.us", "Oprah", "Middleton" },
                    { 147, "jimi.middleton@nasa.org.us", "Jimi", "Middleton" },
                    { 148, "donald.presley@gov.nl", "Donald", "Presley" },
                    { 149, "oprah.obama@nasa.org.us", "Oprah", "Obama" },
                    { 150, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 151, "barack.hendrix@gov.us", "Barack", "Hendrix" },
                    { 152, "elvis.middleton@tesla.com", "Elvis", "Middleton" },
                    { 153, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 154, "oprah.trump@tesla.com", "Oprah", "Trump" },
                    { 155, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 156, "charles.middleton@theworld.ca", "Charles", "Middleton" },
                    { 157, "donald.winfrey@bbc.co.uk", "Donald", "Winfrey" },
                    { 158, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 159, "mick.winfrey@nasa.org.us", "Mick", "Winfrey" },
                    { 160, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 161, "mick.obama@gov.ru", "Mick", "Obama" },
                    { 162, "charles.hendrix@gov.gr", "Charles", "Hendrix" },
                    { 163, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 164, "audrey.jagger@nasa.org.us", "Audrey", "Jagger" },
                    { 165, "audrey.hendrix@gov.nl", "Audrey", "Hendrix" },
                    { 166, "barack.hendrix@google.com", "Barack", "Hendrix" },
                    { 167, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 168, "kate.winslet@gov.us", "Kate", "Winslet" },
                    { 169, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 170, "elvis.presley@bbc.co.uk", "Elvis", "Presley" },
                    { 171, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 172, "audrey.winslet@something.com", "Audrey", "Winslet" },
                    { 173, "mick.jagger@gov.us", "Mick", "Jagger" },
                    { 174, "audrey.middleton@tesla.com", "Audrey", "Middleton" },
                    { 175, "charles.presley@gov.ru", "Charles", "Presley" },
                    { 176, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 177, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 178, "oprah.presley@gov.gr", "Oprah", "Presley" },
                    { 179, "oprah.obama@something.com", "Oprah", "Obama" },
                    { 180, "mick.hepburn@tesla.com", "Mick", "Hepburn" },
                    { 181, "barack.obama@bbc.co.uk", "Barack", "Obama" },
                    { 182, "charles.hepburn@google.com", "Charles", "Hepburn" },
                    { 183, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 184, "jimi.trump@gov.ru", "Jimi", "Trump" },
                    { 185, "donald.hendrix@nasa.org.us", "Donald", "Hendrix" },
                    { 186, "oprah.winslet@gov.nl", "Oprah", "Winslet" },
                    { 187, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 188, "charles.windsor@gov.nl", "Charles", "Windsor" },
                    { 189, "donald.trump@theworld.ca", "Donald", "Trump" },
                    { 190, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 191, "jimi.hepburn@bbc.co.uk", "Jimi", "Hepburn" },
                    { 192, "mick.hendrix@bbc.co.uk", "Mick", "Hendrix" },
                    { 193, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 194, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 195, "oprah.winslet@tesla.com", "Oprah", "Winslet" },
                    { 196, "oprah.obama@nasa.org.us", "Oprah", "Obama" },
                    { 197, "elvis.winslet@nasa.org.us", "Elvis", "Winslet" },
                    { 198, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 199, "charles.obama@theworld.ca", "Charles", "Obama" },
                    { 200, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 201, "oprah.trump@gov.ru", "Oprah", "Trump" },
                    { 202, "charles.jagger@gov.ru", "Charles", "Jagger" },
                    { 203, "charles.middleton@tesla.com", "Charles", "Middleton" },
                    { 204, "barack.trump@something.com", "Barack", "Trump" },
                    { 205, "mick.obama@gov.ru", "Mick", "Obama" },
                    { 206, "charles.winslet@gov.gr", "Charles", "Winslet" },
                    { 207, "donald.trump@gov.nl", "Donald", "Trump" },
                    { 208, "donald.winslet@nasa.org.us", "Donald", "Winslet" },
                    { 209, "donald.windsor@gov.gr", "Donald", "Windsor" },
                    { 210, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 211, "charles.windsor@gov.nl", "Charles", "Windsor" },
                    { 212, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 213, "barack.windsor@gov.us", "Barack", "Windsor" },
                    { 214, "oprah.middleton@gov.gr", "Oprah", "Middleton" },
                    { 215, "elvis.hepburn@gov.nl", "Elvis", "Hepburn" },
                    { 216, "charles.obama@theworld.ca", "Charles", "Obama" },
                    { 217, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 218, "elvis.windsor@tesla.com", "Elvis", "Windsor" },
                    { 219, "oprah.windsor@gov.nl", "Oprah", "Windsor" },
                    { 220, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 221, "barack.winfrey@nasa.org.us", "Barack", "Winfrey" },
                    { 222, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 223, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 224, "jimi.winslet@google.com", "Jimi", "Winslet" },
                    { 225, "jimi.winslet@gov.gr", "Jimi", "Winslet" },
                    { 226, "mick.presley@tesla.com", "Mick", "Presley" },
                    { 227, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 228, "charles.presley@bbc.co.uk", "Charles", "Presley" },
                    { 229, "charles.presley@theworld.ca", "Charles", "Presley" },
                    { 230, "barack.jagger@something.com", "Barack", "Jagger" },
                    { 231, "charles.winslet@nasa.org.us", "Charles", "Winslet" },
                    { 232, "mick.jagger@bbc.co.uk", "Mick", "Jagger" },
                    { 233, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 234, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 235, "kate.presley@tesla.com", "Kate", "Presley" },
                    { 236, "oprah.obama@gov.us", "Oprah", "Obama" },
                    { 237, "kate.middleton@google.com", "Kate", "Middleton" },
                    { 238, "elvis.middleton@something.com", "Elvis", "Middleton" },
                    { 239, "jimi.obama@theworld.ca", "Jimi", "Obama" },
                    { 240, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 241, "charles.obama@theworld.ca", "Charles", "Obama" },
                    { 242, "elvis.hendrix@gov.gr", "Elvis", "Hendrix" },
                    { 243, "kate.trump@google.com", "Kate", "Trump" },
                    { 244, "audrey.presley@bbc.co.uk", "Audrey", "Presley" },
                    { 245, "barack.hendrix@google.com", "Barack", "Hendrix" },
                    { 246, "charles.winfrey@gov.ru", "Charles", "Winfrey" },
                    { 247, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 248, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 249, "kate.trump@tesla.com", "Kate", "Trump" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "AuthorId", "title" },
                values: new object[,]
                {
                    { 1, 219, "A bunch of Green Houses" },
                    { 2, 92, "A herd of Orange Leopards" },
                    { 3, 139, "Two Microscopic Flowers" },
                    { 4, 216, "Several Large Buildings" },
                    { 5, 121, "Several Microscopic Flowers" },
                    { 6, 90, "A bunch of Transparent Leopards" },
                    { 7, 12, "A herd of Orange Leopards" },
                    { 8, 10, "A herd of Bitter Buildings" },
                    { 9, 152, "A herd of Microscopic Planets" },
                    { 10, 170, "A herd of Bitter Planets" },
                    { 11, 177, "The Orange Houses" },
                    { 12, 146, "A herd of Large Planets" },
                    { 13, 225, "Several Purple Houses" },
                    { 14, 51, "A bunch of Rose Smelling Leopards" },
                    { 15, 173, "A herd of Purple Leopards" },
                    { 16, 196, "Two Microscopic Buildings" },
                    { 17, 7, "The Rose Smelling Planets" },
                    { 18, 59, "Several Purple Planets" },
                    { 19, 34, "Two Large Buildings" },
                    { 20, 87, "An army of Large Buildings" },
                    { 21, 200, "An army of Microscopic Flowers" },
                    { 22, 233, "Two Microscopic Houses" },
                    { 23, 1, "Several Bitter Houses" },
                    { 24, 172, "A bunch of Rose Smelling Leopards" },
                    { 25, 152, "A herd of Large Flowers" },
                    { 26, 128, "The Transparent Flowers" },
                    { 27, 87, "A herd of Bitter Planets" },
                    { 28, 218, "Fifteen Large Leopards" },
                    { 29, 231, "An army of Large Houses" },
                    { 30, 197, "The Purple Houses" },
                    { 31, 69, "The Purple Flowers" },
                    { 32, 125, "A herd of Rose Smelling Leopards" },
                    { 33, 21, "Two Transparent Buildings" },
                    { 34, 98, "Two Transparent Planets" },
                    { 35, 19, "A bunch of Green Flowers" },
                    { 36, 223, "An army of Rose Smelling Houses" },
                    { 37, 73, "The Rose Smelling Planets" },
                    { 38, 120, "The Green Leopards" },
                    { 39, 23, "Fifteen Orange Buildings" },
                    { 40, 62, "Fifteen Bitter Planets" },
                    { 41, 228, "Fifteen Bitter Planets" },
                    { 42, 11, "A bunch of Orange Flowers" },
                    { 43, 152, "The Purple Flowers" },
                    { 44, 246, "The Orange Flowers" },
                    { 45, 8, "Several Rose Smelling Buildings" },
                    { 46, 14, "Two Large Buildings" },
                    { 47, 245, "The Large Cars" },
                    { 48, 141, "Two Rose Smelling Cars" },
                    { 49, 22, "Two Green Cars" },
                    { 50, 197, "Several Bitter Flowers" },
                    { 51, 222, "A bunch of Microscopic Leopards" },
                    { 52, 13, "Fifteen Rose Smelling Planets" },
                    { 53, 76, "Fifteen Purple Buildings" },
                    { 54, 143, "A herd of Transparent Leopards" },
                    { 55, 101, "An army of Microscopic Houses" },
                    { 56, 16, "Several Bitter Flowers" },
                    { 57, 163, "Fifteen Rose Smelling Leopards" },
                    { 58, 103, "Fifteen Green Flowers" },
                    { 59, 189, "A herd of Rose Smelling Planets" },
                    { 60, 208, "Several Purple Houses" },
                    { 61, 148, "A bunch of Microscopic Flowers" },
                    { 62, 207, "Two Rose Smelling Leopards" },
                    { 63, 113, "Two Microscopic Houses" },
                    { 64, 131, "A herd of Purple Leopards" },
                    { 65, 167, "An army of Orange Houses" },
                    { 66, 25, "The Orange Houses" },
                    { 67, 168, "A bunch of Transparent Buildings" },
                    { 68, 95, "Fifteen Orange Cars" },
                    { 69, 100, "Two Orange Buildings" },
                    { 70, 57, "A herd of Large Cars" },
                    { 71, 13, "Two Large Leopards" },
                    { 72, 212, "A bunch of Orange Houses" },
                    { 73, 228, "An army of Purple Houses" },
                    { 74, 195, "The Transparent Buildings" },
                    { 75, 6, "A herd of Purple Planets" },
                    { 76, 190, "The Orange Leopards" },
                    { 77, 136, "A bunch of Microscopic Planets" },
                    { 78, 39, "A bunch of Purple Planets" },
                    { 79, 93, "Fifteen Bitter Cars" },
                    { 80, 203, "A herd of Orange Houses" },
                    { 81, 76, "An army of Green Cars" },
                    { 82, 87, "The Transparent Leopards" },
                    { 83, 4, "A bunch of Bitter Cars" },
                    { 84, 171, "A bunch of Microscopic Cars" },
                    { 85, 13, "An army of Transparent Houses" },
                    { 86, 194, "An army of Microscopic Planets" },
                    { 87, 156, "A herd of Microscopic Cars" },
                    { 88, 136, "A herd of Transparent Flowers" },
                    { 89, 214, "A bunch of Microscopic Buildings" },
                    { 90, 174, "The Green Leopards" },
                    { 91, 211, "The Bitter Leopards" },
                    { 92, 5, "A bunch of Bitter Planets" },
                    { 93, 119, "A bunch of Bitter Planets" },
                    { 94, 147, "An army of Green Houses" },
                    { 95, 229, "An army of Orange Buildings" },
                    { 96, 64, "A bunch of Bitter Buildings" },
                    { 97, 110, "Several Orange Leopards" },
                    { 98, 34, "An army of Bitter Buildings" },
                    { 99, 5, "The Large Leopards" },
                    { 100, 243, "The Orange Leopards" },
                    { 101, 68, "An army of Purple Houses" },
                    { 102, 249, "The Green Buildings" },
                    { 103, 182, "An army of Large Planets" },
                    { 104, 110, "An army of Bitter Leopards" },
                    { 105, 174, "Two Orange Flowers" },
                    { 106, 34, "Two Large Cars" },
                    { 107, 193, "An army of Purple Flowers" },
                    { 108, 80, "Fifteen Green Planets" },
                    { 109, 50, "Several Green Planets" },
                    { 110, 113, "The Bitter Leopards" },
                    { 111, 177, "Two Transparent Houses" },
                    { 112, 169, "Several Transparent Flowers" },
                    { 113, 37, "Fifteen Microscopic Cars" },
                    { 114, 11, "An army of Transparent Planets" },
                    { 115, 174, "Several Green Cars" },
                    { 116, 61, "An army of Large Houses" },
                    { 117, 122, "Two Large Planets" },
                    { 118, 54, "Fifteen Orange Flowers" },
                    { 119, 28, "The Purple Houses" },
                    { 120, 37, "An army of Microscopic Leopards" },
                    { 121, 229, "Fifteen Large Flowers" },
                    { 122, 231, "Several Bitter Flowers" },
                    { 123, 17, "A herd of Bitter Leopards" },
                    { 124, 98, "A bunch of Microscopic Buildings" },
                    { 125, 14, "An army of Purple Houses" },
                    { 126, 172, "Several Orange Flowers" },
                    { 127, 249, "A herd of Large Planets" },
                    { 128, 245, "Two Rose Smelling Flowers" },
                    { 129, 126, "Two Orange Cars" },
                    { 130, 105, "An army of Transparent Flowers" },
                    { 131, 151, "Two Purple Houses" },
                    { 132, 151, "A bunch of Purple Leopards" },
                    { 133, 226, "A herd of Rose Smelling Buildings" },
                    { 134, 201, "Two Orange Houses" },
                    { 135, 192, "Several Purple Cars" },
                    { 136, 143, "Several Rose Smelling Planets" },
                    { 137, 123, "Several Bitter Planets" },
                    { 138, 113, "Several Microscopic Flowers" },
                    { 139, 31, "A bunch of Large Flowers" },
                    { 140, 145, "A herd of Orange Flowers" },
                    { 141, 100, "Two Large Flowers" },
                    { 142, 64, "Two Orange Buildings" },
                    { 143, 27, "Two Large Houses" },
                    { 144, 225, "A bunch of Purple Leopards" },
                    { 145, 180, "The Orange Houses" },
                    { 146, 42, "Fifteen Purple Cars" },
                    { 147, 131, "Fifteen Rose Smelling Flowers" },
                    { 148, 89, "Fifteen Green Cars" },
                    { 149, 223, "An army of Rose Smelling Flowers" },
                    { 150, 88, "Several Orange Buildings" },
                    { 151, 209, "A herd of Transparent Planets" },
                    { 152, 40, "A herd of Transparent Flowers" },
                    { 153, 206, "A herd of Microscopic Planets" },
                    { 154, 182, "Several Microscopic Cars" },
                    { 155, 207, "Several Large Cars" },
                    { 156, 135, "A bunch of Purple Planets" },
                    { 157, 82, "The Microscopic Buildings" },
                    { 158, 212, "A herd of Rose Smelling Planets" },
                    { 159, 103, "A herd of Orange Flowers" },
                    { 160, 222, "A bunch of Transparent Leopards" },
                    { 161, 124, "Fifteen Purple Cars" },
                    { 162, 67, "A bunch of Purple Planets" },
                    { 163, 238, "A herd of Purple Planets" },
                    { 164, 138, "Fifteen Large Leopards" },
                    { 165, 118, "An army of Bitter Cars" },
                    { 166, 190, "The Rose Smelling Buildings" },
                    { 167, 153, "Several Purple Planets" },
                    { 168, 66, "Two Bitter Planets" },
                    { 169, 7, "A bunch of Bitter Flowers" },
                    { 170, 200, "A herd of Rose Smelling Leopards" },
                    { 171, 51, "An army of Bitter Houses" },
                    { 172, 31, "Several Transparent Planets" },
                    { 173, 241, "The Orange Houses" },
                    { 174, 192, "Several Purple Flowers" },
                    { 175, 213, "A herd of Green Buildings" },
                    { 176, 203, "The Green Cars" },
                    { 177, 157, "Two Transparent Flowers" },
                    { 178, 47, "Fifteen Transparent Planets" },
                    { 179, 165, "The Purple Houses" },
                    { 180, 121, "The Bitter Leopards" },
                    { 181, 187, "Fifteen Microscopic Houses" },
                    { 182, 202, "The Transparent Leopards" },
                    { 183, 201, "A bunch of Large Cars" },
                    { 184, 75, "Two Green Cars" },
                    { 185, 63, "An army of Green Houses" },
                    { 186, 142, "A herd of Transparent Houses" },
                    { 187, 90, "A herd of Transparent Cars" },
                    { 188, 209, "An army of Microscopic Flowers" },
                    { 189, 214, "The Microscopic Cars" },
                    { 190, 218, "Several Microscopic Planets" },
                    { 191, 167, "Two Microscopic Flowers" },
                    { 192, 68, "Two Transparent Flowers" },
                    { 193, 187, "Two Microscopic Leopards" },
                    { 194, 60, "A bunch of Transparent Planets" },
                    { 195, 170, "A herd of Large Flowers" },
                    { 196, 150, "Several Orange Buildings" },
                    { 197, 167, "A herd of Orange Flowers" },
                    { 198, 202, "The Purple Cars" },
                    { 199, 158, "The Transparent Cars" },
                    { 200, 112, "A herd of Bitter Cars" },
                    { 201, 225, "A bunch of Bitter Buildings" },
                    { 202, 169, "Several Rose Smelling Buildings" },
                    { 203, 53, "Several Transparent Buildings" },
                    { 204, 19, "A bunch of Bitter Leopards" },
                    { 205, 239, "Several Large Leopards" },
                    { 206, 183, "The Orange Houses" },
                    { 207, 81, "Several Orange Buildings" },
                    { 208, 169, "A herd of Bitter Planets" },
                    { 209, 202, "An army of Purple Buildings" },
                    { 210, 188, "Fifteen Transparent Planets" },
                    { 211, 2, "Two Orange Houses" },
                    { 212, 205, "Two Green Flowers" },
                    { 213, 89, "A bunch of Transparent Buildings" },
                    { 214, 158, "An army of Green Leopards" },
                    { 215, 38, "Fifteen Orange Buildings" },
                    { 216, 183, "Two Microscopic Flowers" },
                    { 217, 140, "Several Transparent Buildings" },
                    { 218, 216, "Several Orange Cars" },
                    { 219, 5, "An army of Large Planets" },
                    { 220, 181, "Two Orange Leopards" },
                    { 221, 52, "Several Orange Leopards" },
                    { 222, 44, "A bunch of Microscopic Leopards" },
                    { 223, 7, "The Bitter Houses" },
                    { 224, 164, "An army of Purple Buildings" },
                    { 225, 82, "A bunch of Microscopic Houses" },
                    { 226, 24, "Fifteen Green Flowers" },
                    { 227, 133, "A herd of Orange Cars" },
                    { 228, 35, "A bunch of Bitter Flowers" },
                    { 229, 118, "Two Green Cars" },
                    { 230, 96, "Two Bitter Leopards" },
                    { 231, 113, "Two Purple Cars" },
                    { 232, 125, "Fifteen Bitter Leopards" },
                    { 233, 98, "The Bitter Leopards" },
                    { 234, 57, "A herd of Microscopic Cars" },
                    { 235, 85, "A bunch of Transparent Flowers" },
                    { 236, 119, "A herd of Green Buildings" },
                    { 237, 125, "A herd of Rose Smelling Planets" },
                    { 238, 15, "Two Transparent Buildings" },
                    { 239, 19, "Two Transparent Houses" },
                    { 240, 182, "Two Transparent Planets" },
                    { 241, 103, "Two Large Leopards" },
                    { 242, 118, "The Bitter Flowers" },
                    { 243, 189, "An army of Large Houses" },
                    { 244, 103, "A herd of Green Leopards" },
                    { 245, 12, "Two Orange Planets" },
                    { 246, 74, "A herd of Purple Planets" },
                    { 247, 38, "Fifteen Rose Smelling Cars" },
                    { 248, 134, "Two Bitter Leopards" },
                    { 249, 142, "A bunch of Rose Smelling Planets" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_books_AuthorId",
                table: "books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "authors");
        }
    }
}
