using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    firstname = table.Column<string>(type: "text", nullable: false),
                    lastname = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_Authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "id", "email", "firstname", "lastname" },
                values: new object[,]
                {
                    { 1, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 2, "charles.hendrix@bbc.co.uk", "Charles", "Hendrix" },
                    { 3, "kate.trump@something.com", "Kate", "Trump" },
                    { 4, "barack.winfrey@theworld.ca", "Barack", "Winfrey" },
                    { 5, "mick.presley@gov.ru", "Mick", "Presley" },
                    { 6, "barack.presley@bbc.co.uk", "Barack", "Presley" },
                    { 7, "audrey.obama@bbc.co.uk", "Audrey", "Obama" },
                    { 8, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 9, "mick.presley@gov.nl", "Mick", "Presley" },
                    { 10, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 11, "mick.windsor@something.com", "Mick", "Windsor" },
                    { 12, "oprah.middleton@tesla.com", "Oprah", "Middleton" },
                    { 13, "oprah.winslet@something.com", "Oprah", "Winslet" },
                    { 14, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 15, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 16, "mick.middleton@bbc.co.uk", "Mick", "Middleton" },
                    { 17, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 18, "audrey.middleton@something.com", "Audrey", "Middleton" },
                    { 19, "barack.trump@nasa.org.us", "Barack", "Trump" },
                    { 20, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 21, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 22, "elvis.windsor@bbc.co.uk", "Elvis", "Windsor" },
                    { 23, "barack.hepburn@google.com", "Barack", "Hepburn" },
                    { 24, "donald.trump@gov.us", "Donald", "Trump" },
                    { 25, "donald.middleton@theworld.ca", "Donald", "Middleton" },
                    { 26, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 27, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 28, "mick.trump@something.com", "Mick", "Trump" },
                    { 29, "kate.obama@google.com", "Kate", "Obama" },
                    { 30, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 31, "donald.presley@something.com", "Donald", "Presley" },
                    { 32, "oprah.presley@something.com", "Oprah", "Presley" },
                    { 33, "mick.winslet@tesla.com", "Mick", "Winslet" },
                    { 34, "mick.jagger@bbc.co.uk", "Mick", "Jagger" },
                    { 35, "jimi.winslet@tesla.com", "Jimi", "Winslet" },
                    { 36, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 37, "donald.jagger@gov.gr", "Donald", "Jagger" },
                    { 38, "charles.winslet@gov.gr", "Charles", "Winslet" },
                    { 39, "jimi.trump@gov.gr", "Jimi", "Trump" },
                    { 40, "oprah.jagger@gov.nl", "Oprah", "Jagger" },
                    { 41, "barack.winfrey@something.com", "Barack", "Winfrey" },
                    { 42, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 43, "jimi.winslet@tesla.com", "Jimi", "Winslet" },
                    { 44, "barack.hepburn@something.com", "Barack", "Hepburn" },
                    { 45, "elvis.trump@google.com", "Elvis", "Trump" },
                    { 46, "mick.hendrix@gov.nl", "Mick", "Hendrix" },
                    { 47, "charles.presley@theworld.ca", "Charles", "Presley" },
                    { 48, "kate.winfrey@nasa.org.us", "Kate", "Winfrey" },
                    { 49, "kate.presley@google.com", "Kate", "Presley" },
                    { 50, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 51, "oprah.windsor@tesla.com", "Oprah", "Windsor" },
                    { 52, "mick.windsor@theworld.ca", "Mick", "Windsor" },
                    { 53, "elvis.winslet@bbc.co.uk", "Elvis", "Winslet" },
                    { 54, "kate.middleton@tesla.com", "Kate", "Middleton" },
                    { 55, "oprah.hendrix@nasa.org.us", "Oprah", "Hendrix" },
                    { 56, "charles.winfrey@gov.ru", "Charles", "Winfrey" },
                    { 57, "mick.winfrey@gov.gr", "Mick", "Winfrey" },
                    { 58, "charles.jagger@tesla.com", "Charles", "Jagger" },
                    { 59, "jimi.trump@bbc.co.uk", "Jimi", "Trump" },
                    { 60, "elvis.winfrey@gov.us", "Elvis", "Winfrey" },
                    { 61, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 62, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 63, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 64, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 65, "charles.trump@gov.nl", "Charles", "Trump" },
                    { 66, "jimi.middleton@something.com", "Jimi", "Middleton" },
                    { 67, "jimi.winfrey@gov.ru", "Jimi", "Winfrey" },
                    { 68, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 69, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 70, "mick.winfrey@gov.ru", "Mick", "Winfrey" },
                    { 71, "barack.presley@gov.nl", "Barack", "Presley" },
                    { 72, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 73, "jimi.windsor@gov.nl", "Jimi", "Windsor" },
                    { 74, "oprah.hendrix@nasa.org.us", "Oprah", "Hendrix" },
                    { 75, "jimi.trump@gov.gr", "Jimi", "Trump" },
                    { 76, "jimi.middleton@nasa.org.us", "Jimi", "Middleton" },
                    { 77, "elvis.presley@google.com", "Elvis", "Presley" },
                    { 78, "elvis.windsor@google.com", "Elvis", "Windsor" },
                    { 79, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 80, "donald.presley@gov.gr", "Donald", "Presley" },
                    { 81, "barack.presley@something.com", "Barack", "Presley" },
                    { 82, "donald.hendrix@tesla.com", "Donald", "Hendrix" },
                    { 83, "donald.hendrix@something.com", "Donald", "Hendrix" },
                    { 84, "elvis.hendrix@gov.ru", "Elvis", "Hendrix" },
                    { 85, "audrey.middleton@nasa.org.us", "Audrey", "Middleton" },
                    { 86, "audrey.presley@bbc.co.uk", "Audrey", "Presley" },
                    { 87, "mick.hepburn@something.com", "Mick", "Hepburn" },
                    { 88, "barack.jagger@gov.gr", "Barack", "Jagger" },
                    { 89, "donald.winfrey@gov.ru", "Donald", "Winfrey" },
                    { 90, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 91, "barack.jagger@nasa.org.us", "Barack", "Jagger" },
                    { 92, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 93, "oprah.winslet@gov.nl", "Oprah", "Winslet" },
                    { 94, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 95, "elvis.hendrix@gov.gr", "Elvis", "Hendrix" },
                    { 96, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 97, "donald.jagger@gov.ru", "Donald", "Jagger" },
                    { 98, "donald.windsor@something.com", "Donald", "Windsor" },
                    { 99, "oprah.winslet@tesla.com", "Oprah", "Winslet" },
                    { 100, "oprah.hendrix@gov.nl", "Oprah", "Hendrix" },
                    { 101, "oprah.winfrey@theworld.ca", "Oprah", "Winfrey" },
                    { 102, "elvis.obama@gov.ru", "Elvis", "Obama" },
                    { 103, "donald.jagger@gov.us", "Donald", "Jagger" },
                    { 104, "oprah.trump@gov.nl", "Oprah", "Trump" },
                    { 105, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 106, "donald.windsor@google.com", "Donald", "Windsor" },
                    { 107, "jimi.windsor@nasa.org.us", "Jimi", "Windsor" },
                    { 108, "elvis.windsor@gov.us", "Elvis", "Windsor" },
                    { 109, "donald.obama@tesla.com", "Donald", "Obama" },
                    { 110, "barack.trump@gov.ru", "Barack", "Trump" },
                    { 111, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 112, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 113, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 114, "jimi.obama@gov.us", "Jimi", "Obama" },
                    { 115, "donald.presley@gov.us", "Donald", "Presley" },
                    { 116, "jimi.hepburn@theworld.ca", "Jimi", "Hepburn" },
                    { 117, "donald.winslet@gov.gr", "Donald", "Winslet" },
                    { 118, "elvis.winslet@bbc.co.uk", "Elvis", "Winslet" },
                    { 119, "donald.trump@google.com", "Donald", "Trump" },
                    { 120, "charles.windsor@tesla.com", "Charles", "Windsor" },
                    { 121, "elvis.hendrix@google.com", "Elvis", "Hendrix" },
                    { 122, "audrey.obama@gov.ru", "Audrey", "Obama" },
                    { 123, "barack.hepburn@nasa.org.us", "Barack", "Hepburn" },
                    { 124, "kate.obama@google.com", "Kate", "Obama" },
                    { 125, "mick.jagger@google.com", "Mick", "Jagger" },
                    { 126, "audrey.obama@nasa.org.us", "Audrey", "Obama" },
                    { 127, "jimi.obama@gov.us", "Jimi", "Obama" },
                    { 128, "elvis.middleton@nasa.org.us", "Elvis", "Middleton" },
                    { 129, "audrey.hendrix@gov.us", "Audrey", "Hendrix" },
                    { 130, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 131, "barack.obama@google.com", "Barack", "Obama" },
                    { 132, "audrey.trump@bbc.co.uk", "Audrey", "Trump" },
                    { 133, "charles.presley@something.com", "Charles", "Presley" },
                    { 134, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 135, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 136, "donald.middleton@gov.ru", "Donald", "Middleton" },
                    { 137, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 138, "mick.jagger@bbc.co.uk", "Mick", "Jagger" },
                    { 139, "mick.winfrey@google.com", "Mick", "Winfrey" },
                    { 140, "jimi.hepburn@bbc.co.uk", "Jimi", "Hepburn" },
                    { 141, "charles.trump@nasa.org.us", "Charles", "Trump" },
                    { 142, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 143, "donald.winslet@gov.ru", "Donald", "Winslet" },
                    { 144, "audrey.windsor@something.com", "Audrey", "Windsor" },
                    { 145, "elvis.jagger@bbc.co.uk", "Elvis", "Jagger" },
                    { 146, "elvis.hepburn@bbc.co.uk", "Elvis", "Hepburn" },
                    { 147, "audrey.hendrix@gov.ru", "Audrey", "Hendrix" },
                    { 148, "oprah.winfrey@bbc.co.uk", "Oprah", "Winfrey" },
                    { 149, "mick.middleton@theworld.ca", "Mick", "Middleton" },
                    { 150, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 151, "barack.obama@gov.gr", "Barack", "Obama" },
                    { 152, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 153, "audrey.winslet@something.com", "Audrey", "Winslet" },
                    { 154, "charles.winslet@gov.nl", "Charles", "Winslet" },
                    { 155, "charles.hendrix@nasa.org.us", "Charles", "Hendrix" },
                    { 156, "mick.winfrey@something.com", "Mick", "Winfrey" },
                    { 157, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 158, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 159, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 160, "kate.presley@something.com", "Kate", "Presley" },
                    { 161, "audrey.hepburn@something.com", "Audrey", "Hepburn" },
                    { 162, "donald.hepburn@theworld.ca", "Donald", "Hepburn" },
                    { 163, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 164, "donald.hendrix@theworld.ca", "Donald", "Hendrix" },
                    { 165, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 166, "elvis.hendrix@gov.ru", "Elvis", "Hendrix" },
                    { 167, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 168, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 169, "jimi.middleton@google.com", "Jimi", "Middleton" },
                    { 170, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 171, "barack.presley@tesla.com", "Barack", "Presley" },
                    { 172, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 173, "mick.hendrix@tesla.com", "Mick", "Hendrix" },
                    { 174, "mick.presley@google.com", "Mick", "Presley" },
                    { 175, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 176, "charles.obama@gov.nl", "Charles", "Obama" },
                    { 177, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 178, "elvis.obama@bbc.co.uk", "Elvis", "Obama" },
                    { 179, "kate.winfrey@bbc.co.uk", "Kate", "Winfrey" },
                    { 180, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 181, "barack.windsor@nasa.org.us", "Barack", "Windsor" },
                    { 182, "barack.trump@nasa.org.us", "Barack", "Trump" },
                    { 183, "mick.windsor@gov.us", "Mick", "Windsor" },
                    { 184, "audrey.trump@gov.nl", "Audrey", "Trump" },
                    { 185, "jimi.middleton@theworld.ca", "Jimi", "Middleton" },
                    { 186, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 187, "oprah.middleton@tesla.com", "Oprah", "Middleton" },
                    { 188, "charles.hepburn@gov.ru", "Charles", "Hepburn" },
                    { 189, "barack.trump@theworld.ca", "Barack", "Trump" },
                    { 190, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 191, "audrey.jagger@gov.us", "Audrey", "Jagger" },
                    { 192, "elvis.jagger@something.com", "Elvis", "Jagger" },
                    { 193, "oprah.hepburn@nasa.org.us", "Oprah", "Hepburn" },
                    { 194, "kate.trump@gov.us", "Kate", "Trump" },
                    { 195, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 196, "audrey.windsor@nasa.org.us", "Audrey", "Windsor" },
                    { 197, "oprah.obama@gov.ru", "Oprah", "Obama" },
                    { 198, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 199, "barack.windsor@gov.gr", "Barack", "Windsor" },
                    { 200, "oprah.winslet@bbc.co.uk", "Oprah", "Winslet" },
                    { 201, "charles.presley@bbc.co.uk", "Charles", "Presley" },
                    { 202, "oprah.trump@theworld.ca", "Oprah", "Trump" },
                    { 203, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 204, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 205, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 206, "mick.hendrix@gov.gr", "Mick", "Hendrix" },
                    { 207, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 208, "donald.windsor@nasa.org.us", "Donald", "Windsor" },
                    { 209, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 210, "donald.middleton@gov.us", "Donald", "Middleton" },
                    { 211, "kate.presley@something.com", "Kate", "Presley" },
                    { 212, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 213, "oprah.hendrix@something.com", "Oprah", "Hendrix" },
                    { 214, "jimi.jagger@bbc.co.uk", "Jimi", "Jagger" },
                    { 215, "oprah.jagger@gov.gr", "Oprah", "Jagger" },
                    { 216, "charles.hendrix@nasa.org.us", "Charles", "Hendrix" },
                    { 217, "elvis.middleton@gov.us", "Elvis", "Middleton" },
                    { 218, "elvis.windsor@nasa.org.us", "Elvis", "Windsor" },
                    { 219, "elvis.hendrix@google.com", "Elvis", "Hendrix" },
                    { 220, "oprah.obama@gov.gr", "Oprah", "Obama" },
                    { 221, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 222, "charles.obama@theworld.ca", "Charles", "Obama" },
                    { 223, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 224, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 225, "elvis.jagger@something.com", "Elvis", "Jagger" },
                    { 226, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 227, "jimi.winfrey@gov.gr", "Jimi", "Winfrey" },
                    { 228, "barack.obama@tesla.com", "Barack", "Obama" },
                    { 229, "jimi.winslet@tesla.com", "Jimi", "Winslet" },
                    { 230, "barack.windsor@google.com", "Barack", "Windsor" },
                    { 231, "audrey.obama@bbc.co.uk", "Audrey", "Obama" },
                    { 232, "audrey.hepburn@nasa.org.us", "Audrey", "Hepburn" },
                    { 233, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 234, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 235, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 236, "kate.obama@something.com", "Kate", "Obama" },
                    { 237, "donald.winfrey@tesla.com", "Donald", "Winfrey" },
                    { 238, "charles.hepburn@nasa.org.us", "Charles", "Hepburn" },
                    { 239, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 240, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 241, "mick.hendrix@something.com", "Mick", "Hendrix" },
                    { 242, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 243, "elvis.obama@nasa.org.us", "Elvis", "Obama" },
                    { 244, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 245, "oprah.winfrey@gov.nl", "Oprah", "Winfrey" },
                    { 246, "audrey.presley@gov.gr", "Audrey", "Presley" },
                    { 247, "mick.winfrey@google.com", "Mick", "Winfrey" },
                    { 248, "audrey.trump@gov.gr", "Audrey", "Trump" },
                    { 249, "charles.trump@bbc.co.uk", "Charles", "Trump" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "AuthorId", "title" },
                values: new object[,]
                {
                    { 1, 41, "The Bitter Leopards" },
                    { 2, 249, "The Orange Planets" },
                    { 3, 180, "An army of Transparent Houses" },
                    { 4, 9, "The Bitter Buildings" },
                    { 5, 107, "An army of Orange Houses" },
                    { 6, 20, "Several Rose Smelling Buildings" },
                    { 7, 165, "A herd of Microscopic Buildings" },
                    { 8, 68, "The Bitter Flowers" },
                    { 9, 38, "Two Transparent Buildings" },
                    { 10, 212, "An army of Rose Smelling Leopards" },
                    { 11, 245, "The Purple Houses" },
                    { 12, 63, "Two Microscopic Buildings" },
                    { 13, 234, "A bunch of Transparent Planets" },
                    { 14, 244, "An army of Transparent Flowers" },
                    { 15, 224, "Fifteen Large Houses" },
                    { 16, 201, "A herd of Rose Smelling Flowers" },
                    { 17, 18, "The Orange Planets" },
                    { 18, 23, "Several Microscopic Buildings" },
                    { 19, 118, "Fifteen Bitter Planets" },
                    { 20, 203, "The Rose Smelling Leopards" },
                    { 21, 76, "Fifteen Rose Smelling Buildings" },
                    { 22, 10, "Fifteen Rose Smelling Leopards" },
                    { 23, 148, "A bunch of Bitter Leopards" },
                    { 24, 40, "Several Green Planets" },
                    { 25, 244, "Fifteen Rose Smelling Cars" },
                    { 26, 112, "Fifteen Large Houses" },
                    { 27, 63, "A bunch of Bitter Leopards" },
                    { 28, 166, "Two Microscopic Flowers" },
                    { 29, 72, "Several Transparent Houses" },
                    { 30, 45, "A herd of Transparent Cars" },
                    { 31, 4, "An army of Rose Smelling Houses" },
                    { 32, 62, "Two Large Buildings" },
                    { 33, 124, "A bunch of Transparent Planets" },
                    { 34, 120, "Several Bitter Buildings" },
                    { 35, 220, "Fifteen Orange Houses" },
                    { 36, 113, "A bunch of Large Houses" },
                    { 37, 151, "Several Purple Leopards" },
                    { 38, 96, "The Green Cars" },
                    { 39, 79, "A herd of Rose Smelling Flowers" },
                    { 40, 244, "Fifteen Large Leopards" },
                    { 41, 46, "A herd of Bitter Houses" },
                    { 42, 106, "The Large Buildings" },
                    { 43, 177, "The Purple Cars" },
                    { 44, 15, "Two Rose Smelling Planets" },
                    { 45, 196, "An army of Microscopic Flowers" },
                    { 46, 95, "Several Purple Flowers" },
                    { 47, 177, "A bunch of Rose Smelling Leopards" },
                    { 48, 240, "A herd of Bitter Planets" },
                    { 49, 79, "An army of Rose Smelling Flowers" },
                    { 50, 209, "Several Green Houses" },
                    { 51, 158, "Several Transparent Buildings" },
                    { 52, 170, "A herd of Orange Buildings" },
                    { 53, 215, "The Transparent Planets" },
                    { 54, 100, "Several Purple Buildings" },
                    { 55, 234, "A bunch of Green Leopards" },
                    { 56, 231, "The Bitter Buildings" },
                    { 57, 148, "An army of Purple Planets" },
                    { 58, 148, "A bunch of Rose Smelling Cars" },
                    { 59, 50, "Two Transparent Leopards" },
                    { 60, 223, "Several Transparent Leopards" },
                    { 61, 125, "A bunch of Green Leopards" },
                    { 62, 71, "A herd of Green Buildings" },
                    { 63, 192, "Two Orange Flowers" },
                    { 64, 47, "A bunch of Microscopic Planets" },
                    { 65, 2, "A herd of Large Planets" },
                    { 66, 248, "The Orange Leopards" },
                    { 67, 2, "Fifteen Microscopic Buildings" },
                    { 68, 180, "An army of Transparent Cars" },
                    { 69, 35, "Fifteen Purple Leopards" },
                    { 70, 232, "A bunch of Large Planets" },
                    { 71, 230, "The Rose Smelling Leopards" },
                    { 72, 177, "A bunch of Rose Smelling Flowers" },
                    { 73, 113, "A herd of Purple Buildings" },
                    { 74, 49, "Fifteen Transparent Flowers" },
                    { 75, 222, "A herd of Large Flowers" },
                    { 76, 142, "Two Orange Buildings" },
                    { 77, 18, "A bunch of Green Planets" },
                    { 78, 34, "Fifteen Microscopic Cars" },
                    { 79, 49, "Several Large Flowers" },
                    { 80, 95, "Fifteen Orange Houses" },
                    { 81, 103, "Several Purple Flowers" },
                    { 82, 161, "The Purple Buildings" },
                    { 83, 109, "Several Rose Smelling Houses" },
                    { 84, 49, "Fifteen Green Planets" },
                    { 85, 234, "The Transparent Leopards" },
                    { 86, 27, "Fifteen Transparent Planets" },
                    { 87, 176, "Several Bitter Planets" },
                    { 88, 5, "The Microscopic Houses" },
                    { 89, 151, "A herd of Rose Smelling Planets" },
                    { 90, 92, "The Large Houses" },
                    { 91, 140, "A bunch of Bitter Flowers" },
                    { 92, 9, "The Microscopic Planets" },
                    { 93, 68, "The Orange Planets" },
                    { 94, 197, "A bunch of Bitter Cars" },
                    { 95, 186, "A herd of Green Leopards" },
                    { 96, 43, "An army of Large Leopards" },
                    { 97, 58, "Several Transparent Houses" },
                    { 98, 32, "The Green Houses" },
                    { 99, 63, "Two Orange Flowers" },
                    { 100, 126, "An army of Green Cars" },
                    { 101, 178, "Two Microscopic Flowers" },
                    { 102, 210, "A bunch of Microscopic Buildings" },
                    { 103, 188, "A bunch of Bitter Planets" },
                    { 104, 162, "The Transparent Buildings" },
                    { 105, 232, "A herd of Transparent Leopards" },
                    { 106, 136, "Several Large Leopards" },
                    { 107, 239, "Fifteen Orange Leopards" },
                    { 108, 248, "A bunch of Purple Buildings" },
                    { 109, 186, "Two Rose Smelling Planets" },
                    { 110, 136, "The Green Planets" },
                    { 111, 197, "A herd of Transparent Leopards" },
                    { 112, 183, "An army of Bitter Planets" },
                    { 113, 4, "A bunch of Orange Cars" },
                    { 114, 48, "A bunch of Microscopic Houses" },
                    { 115, 112, "Fifteen Green Houses" },
                    { 116, 191, "Two Large Planets" },
                    { 117, 219, "Two Transparent Planets" },
                    { 118, 224, "An army of Purple Houses" },
                    { 119, 119, "An army of Transparent Buildings" },
                    { 120, 111, "An army of Microscopic Houses" },
                    { 121, 8, "A bunch of Microscopic Houses" },
                    { 122, 135, "Two Rose Smelling Houses" },
                    { 123, 225, "Fifteen Purple Planets" },
                    { 124, 89, "Several Bitter Leopards" },
                    { 125, 198, "Fifteen Microscopic Planets" },
                    { 126, 102, "Two Rose Smelling Flowers" },
                    { 127, 211, "An army of Microscopic Buildings" },
                    { 128, 86, "Several Green Leopards" },
                    { 129, 95, "Fifteen Transparent Leopards" },
                    { 130, 57, "A bunch of Microscopic Buildings" },
                    { 131, 136, "Several Transparent Leopards" },
                    { 132, 83, "Two Green Flowers" },
                    { 133, 155, "The Transparent Flowers" },
                    { 134, 205, "An army of Green Flowers" },
                    { 135, 154, "A bunch of Microscopic Flowers" },
                    { 136, 220, "Several Rose Smelling Leopards" },
                    { 137, 89, "A bunch of Orange Flowers" },
                    { 138, 57, "The Bitter Planets" },
                    { 139, 163, "The Transparent Buildings" },
                    { 140, 59, "Several Green Cars" },
                    { 141, 119, "An army of Purple Cars" },
                    { 142, 179, "An army of Green Cars" },
                    { 143, 72, "The Transparent Flowers" },
                    { 144, 163, "Fifteen Green Cars" },
                    { 145, 111, "A herd of Purple Leopards" },
                    { 146, 108, "Fifteen Transparent Cars" },
                    { 147, 61, "A bunch of Transparent Houses" },
                    { 148, 239, "Several Rose Smelling Planets" },
                    { 149, 46, "Two Rose Smelling Houses" },
                    { 150, 212, "An army of Transparent Houses" },
                    { 151, 188, "Fifteen Rose Smelling Houses" },
                    { 152, 121, "An army of Purple Buildings" },
                    { 153, 238, "Two Bitter Flowers" },
                    { 154, 213, "Fifteen Purple Leopards" },
                    { 155, 237, "Two Green Leopards" },
                    { 156, 115, "A herd of Green Planets" },
                    { 157, 105, "Several Large Cars" },
                    { 158, 166, "Several Orange Houses" },
                    { 159, 28, "Fifteen Microscopic Buildings" },
                    { 160, 75, "Several Orange Cars" },
                    { 161, 146, "Several Bitter Flowers" },
                    { 162, 59, "Two Microscopic Buildings" },
                    { 163, 148, "The Microscopic Buildings" },
                    { 164, 192, "A herd of Bitter Buildings" },
                    { 165, 144, "Fifteen Orange Houses" },
                    { 166, 60, "A bunch of Purple Planets" },
                    { 167, 231, "A bunch of Green Buildings" },
                    { 168, 197, "Fifteen Purple Buildings" },
                    { 169, 147, "The Transparent Planets" },
                    { 170, 144, "Fifteen Rose Smelling Planets" },
                    { 171, 77, "A herd of Purple Leopards" },
                    { 172, 20, "Fifteen Bitter Flowers" },
                    { 173, 193, "Fifteen Large Leopards" },
                    { 174, 15, "A bunch of Orange Flowers" },
                    { 175, 34, "Several Green Flowers" },
                    { 176, 85, "Fifteen Transparent Flowers" },
                    { 177, 143, "An army of Green Houses" },
                    { 178, 193, "A bunch of Green Planets" },
                    { 179, 184, "A herd of Microscopic Planets" },
                    { 180, 86, "An army of Orange Planets" },
                    { 181, 25, "Several Large Buildings" },
                    { 182, 8, "Fifteen Green Leopards" },
                    { 183, 199, "Fifteen Rose Smelling Flowers" },
                    { 184, 245, "An army of Green Cars" },
                    { 185, 8, "The Purple Leopards" },
                    { 186, 148, "Several Orange Buildings" },
                    { 187, 219, "The Large Flowers" },
                    { 188, 81, "The Rose Smelling Houses" },
                    { 189, 128, "An army of Large Houses" },
                    { 190, 180, "A herd of Rose Smelling Houses" },
                    { 191, 204, "An army of Microscopic Buildings" },
                    { 192, 181, "The Purple Buildings" },
                    { 193, 239, "Fifteen Large Buildings" },
                    { 194, 188, "Several Microscopic Flowers" },
                    { 195, 110, "Fifteen Orange Planets" },
                    { 196, 83, "Two Bitter Leopards" },
                    { 197, 84, "Two Bitter Houses" },
                    { 198, 91, "A herd of Microscopic Flowers" },
                    { 199, 35, "The Purple Houses" },
                    { 200, 203, "The Orange Cars" },
                    { 201, 163, "An army of Green Buildings" },
                    { 202, 220, "Fifteen Purple Houses" },
                    { 203, 112, "The Transparent Cars" },
                    { 204, 64, "A bunch of Large Buildings" },
                    { 205, 14, "An army of Rose Smelling Houses" },
                    { 206, 120, "The Bitter Houses" },
                    { 207, 61, "The Rose Smelling Leopards" },
                    { 208, 218, "Several Large Buildings" },
                    { 209, 32, "An army of Bitter Cars" },
                    { 210, 71, "Several Orange Planets" },
                    { 211, 16, "Several Microscopic Cars" },
                    { 212, 169, "A bunch of Bitter Planets" },
                    { 213, 231, "Several Bitter Cars" },
                    { 214, 115, "A herd of Orange Buildings" },
                    { 215, 82, "Two Purple Cars" },
                    { 216, 213, "A bunch of Orange Leopards" },
                    { 217, 36, "An army of Transparent Buildings" },
                    { 218, 83, "A bunch of Large Cars" },
                    { 219, 235, "A herd of Orange Planets" },
                    { 220, 168, "Several Orange Leopards" },
                    { 221, 209, "A bunch of Microscopic Cars" },
                    { 222, 195, "Fifteen Rose Smelling Houses" },
                    { 223, 106, "A herd of Orange Planets" },
                    { 224, 229, "Fifteen Microscopic Buildings" },
                    { 225, 238, "The Purple Planets" },
                    { 226, 26, "A herd of Green Buildings" },
                    { 227, 19, "A herd of Green Cars" },
                    { 228, 80, "The Large Flowers" },
                    { 229, 101, "The Rose Smelling Houses" },
                    { 230, 88, "The Microscopic Leopards" },
                    { 231, 208, "An army of Green Flowers" },
                    { 232, 54, "Fifteen Orange Flowers" },
                    { 233, 202, "A bunch of Orange Houses" },
                    { 234, 129, "The Large Buildings" },
                    { 235, 79, "Fifteen Transparent Leopards" },
                    { 236, 158, "A bunch of Bitter Planets" },
                    { 237, 223, "Several Bitter Planets" },
                    { 238, 190, "A bunch of Large Houses" },
                    { 239, 7, "Fifteen Purple Leopards" },
                    { 240, 44, "The Orange Houses" },
                    { 241, 111, "An army of Green Planets" },
                    { 242, 92, "Two Transparent Houses" },
                    { 243, 12, "An army of Microscopic Flowers" },
                    { 244, 88, "A herd of Bitter Houses" },
                    { 245, 31, "Fifteen Transparent Flowers" },
                    { 246, 166, "An army of Green Houses" },
                    { 247, 55, "Fifteen Bitter Planets" },
                    { 248, 178, "Two Transparent Flowers" },
                    { 249, 225, "A herd of Green Leopards" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_books_AuthorId",
                table: "books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "Authors");
        }
    }
}
