using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    FirstName = table.Column<string>(type: "text", nullable: false),
                    LastName = table.Column<string>(type: "text", nullable: false),
                    Email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Publishers",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Publishers", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Books",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Books", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Books_Authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Authors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "Id", "Email", "FirstName", "LastName" },
                values: new object[,]
                {
                    { 1, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 2, "audrey.obama@gov.us", "Audrey", "Obama" },
                    { 3, "charles.jagger@gov.gr", "Charles", "Jagger" },
                    { 4, "jimi.windsor@google.com", "Jimi", "Windsor" },
                    { 5, "donald.hepburn@gov.nl", "Donald", "Hepburn" },
                    { 6, "oprah.winslet@something.com", "Oprah", "Winslet" },
                    { 7, "charles.winfrey@bbc.co.uk", "Charles", "Winfrey" },
                    { 8, "mick.windsor@google.com", "Mick", "Windsor" },
                    { 9, "donald.presley@bbc.co.uk", "Donald", "Presley" },
                    { 10, "mick.jagger@theworld.ca", "Mick", "Jagger" },
                    { 11, "elvis.winslet@something.com", "Elvis", "Winslet" },
                    { 12, "kate.winslet@tesla.com", "Kate", "Winslet" },
                    { 13, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 14, "donald.presley@gov.nl", "Donald", "Presley" },
                    { 15, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 16, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 17, "elvis.hepburn@gov.gr", "Elvis", "Hepburn" },
                    { 18, "kate.jagger@gov.us", "Kate", "Jagger" },
                    { 19, "kate.winfrey@nasa.org.us", "Kate", "Winfrey" },
                    { 20, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 21, "audrey.presley@bbc.co.uk", "Audrey", "Presley" },
                    { 22, "barack.winslet@tesla.com", "Barack", "Winslet" },
                    { 23, "charles.jagger@gov.us", "Charles", "Jagger" },
                    { 24, "audrey.hepburn@gov.nl", "Audrey", "Hepburn" },
                    { 25, "charles.trump@bbc.co.uk", "Charles", "Trump" },
                    { 26, "oprah.jagger@nasa.org.us", "Oprah", "Jagger" },
                    { 27, "charles.hepburn@theworld.ca", "Charles", "Hepburn" },
                    { 28, "charles.middleton@google.com", "Charles", "Middleton" },
                    { 29, "jimi.presley@gov.ru", "Jimi", "Presley" },
                    { 30, "barack.presley@nasa.org.us", "Barack", "Presley" },
                    { 31, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 32, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 33, "donald.trump@google.com", "Donald", "Trump" },
                    { 34, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 35, "mick.trump@something.com", "Mick", "Trump" },
                    { 36, "donald.obama@something.com", "Donald", "Obama" },
                    { 37, "barack.obama@gov.gr", "Barack", "Obama" },
                    { 38, "barack.winfrey@google.com", "Barack", "Winfrey" },
                    { 39, "audrey.presley@google.com", "Audrey", "Presley" },
                    { 40, "barack.winfrey@gov.gr", "Barack", "Winfrey" },
                    { 41, "kate.trump@something.com", "Kate", "Trump" },
                    { 42, "donald.trump@gov.us", "Donald", "Trump" },
                    { 43, "donald.middleton@gov.nl", "Donald", "Middleton" },
                    { 44, "donald.winfrey@something.com", "Donald", "Winfrey" },
                    { 45, "oprah.jagger@gov.us", "Oprah", "Jagger" },
                    { 46, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 47, "elvis.presley@gov.ru", "Elvis", "Presley" },
                    { 48, "charles.winslet@something.com", "Charles", "Winslet" },
                    { 49, "oprah.obama@tesla.com", "Oprah", "Obama" },
                    { 50, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 51, "elvis.hendrix@gov.gr", "Elvis", "Hendrix" },
                    { 52, "audrey.middleton@something.com", "Audrey", "Middleton" },
                    { 53, "donald.jagger@theworld.ca", "Donald", "Jagger" },
                    { 54, "donald.windsor@gov.ru", "Donald", "Windsor" },
                    { 55, "barack.trump@gov.ru", "Barack", "Trump" },
                    { 56, "jimi.jagger@something.com", "Jimi", "Jagger" },
                    { 57, "audrey.hendrix@gov.ru", "Audrey", "Hendrix" },
                    { 58, "jimi.trump@gov.us", "Jimi", "Trump" },
                    { 59, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 60, "charles.winfrey@nasa.org.us", "Charles", "Winfrey" },
                    { 61, "charles.winslet@theworld.ca", "Charles", "Winslet" },
                    { 62, "charles.winslet@tesla.com", "Charles", "Winslet" },
                    { 63, "mick.windsor@something.com", "Mick", "Windsor" },
                    { 64, "jimi.winfrey@bbc.co.uk", "Jimi", "Winfrey" },
                    { 65, "kate.middleton@nasa.org.us", "Kate", "Middleton" },
                    { 66, "audrey.winfrey@nasa.org.us", "Audrey", "Winfrey" },
                    { 67, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 68, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 69, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 70, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 71, "barack.trump@google.com", "Barack", "Trump" },
                    { 72, "barack.jagger@bbc.co.uk", "Barack", "Jagger" },
                    { 73, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 74, "kate.obama@tesla.com", "Kate", "Obama" },
                    { 75, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 76, "jimi.windsor@gov.gr", "Jimi", "Windsor" },
                    { 77, "barack.obama@something.com", "Barack", "Obama" },
                    { 78, "audrey.middleton@something.com", "Audrey", "Middleton" },
                    { 79, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 80, "mick.presley@gov.us", "Mick", "Presley" },
                    { 81, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 82, "audrey.hepburn@gov.ru", "Audrey", "Hepburn" },
                    { 83, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 84, "oprah.middleton@gov.ru", "Oprah", "Middleton" },
                    { 85, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 86, "jimi.trump@theworld.ca", "Jimi", "Trump" },
                    { 87, "audrey.windsor@theworld.ca", "Audrey", "Windsor" },
                    { 88, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 89, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 90, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 91, "audrey.presley@gov.nl", "Audrey", "Presley" },
                    { 92, "kate.trump@nasa.org.us", "Kate", "Trump" },
                    { 93, "charles.jagger@tesla.com", "Charles", "Jagger" },
                    { 94, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 95, "jimi.winslet@gov.ru", "Jimi", "Winslet" },
                    { 96, "audrey.windsor@gov.nl", "Audrey", "Windsor" },
                    { 97, "donald.hepburn@tesla.com", "Donald", "Hepburn" },
                    { 98, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 99, "elvis.middleton@gov.us", "Elvis", "Middleton" },
                    { 100, "kate.presley@bbc.co.uk", "Kate", "Presley" },
                    { 101, "kate.trump@something.com", "Kate", "Trump" },
                    { 102, "mick.presley@theworld.ca", "Mick", "Presley" },
                    { 103, "charles.windsor@gov.nl", "Charles", "Windsor" },
                    { 104, "oprah.obama@bbc.co.uk", "Oprah", "Obama" },
                    { 105, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 106, "charles.winslet@gov.nl", "Charles", "Winslet" },
                    { 107, "oprah.jagger@gov.nl", "Oprah", "Jagger" },
                    { 108, "barack.obama@gov.nl", "Barack", "Obama" },
                    { 109, "jimi.jagger@gov.nl", "Jimi", "Jagger" },
                    { 110, "elvis.presley@gov.gr", "Elvis", "Presley" },
                    { 111, "mick.trump@gov.gr", "Mick", "Trump" },
                    { 112, "barack.obama@gov.us", "Barack", "Obama" },
                    { 113, "donald.obama@theworld.ca", "Donald", "Obama" },
                    { 114, "oprah.obama@google.com", "Oprah", "Obama" },
                    { 115, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 116, "donald.presley@gov.ru", "Donald", "Presley" },
                    { 117, "audrey.hepburn@bbc.co.uk", "Audrey", "Hepburn" },
                    { 118, "donald.middleton@gov.gr", "Donald", "Middleton" },
                    { 119, "audrey.obama@gov.ru", "Audrey", "Obama" },
                    { 120, "charles.presley@tesla.com", "Charles", "Presley" },
                    { 121, "audrey.winslet@tesla.com", "Audrey", "Winslet" },
                    { 122, "audrey.jagger@something.com", "Audrey", "Jagger" },
                    { 123, "elvis.presley@google.com", "Elvis", "Presley" },
                    { 124, "oprah.winslet@bbc.co.uk", "Oprah", "Winslet" },
                    { 125, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 126, "charles.hepburn@gov.gr", "Charles", "Hepburn" },
                    { 127, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 128, "oprah.winfrey@gov.us", "Oprah", "Winfrey" },
                    { 129, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 130, "elvis.obama@google.com", "Elvis", "Obama" },
                    { 131, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 132, "mick.hendrix@tesla.com", "Mick", "Hendrix" },
                    { 133, "audrey.jagger@nasa.org.us", "Audrey", "Jagger" },
                    { 134, "donald.hepburn@tesla.com", "Donald", "Hepburn" },
                    { 135, "charles.obama@gov.ru", "Charles", "Obama" },
                    { 136, "charles.trump@gov.ru", "Charles", "Trump" },
                    { 137, "donald.winslet@gov.ru", "Donald", "Winslet" },
                    { 138, "mick.hendrix@gov.gr", "Mick", "Hendrix" },
                    { 139, "donald.windsor@bbc.co.uk", "Donald", "Windsor" },
                    { 140, "oprah.presley@gov.nl", "Oprah", "Presley" },
                    { 141, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 142, "jimi.trump@tesla.com", "Jimi", "Trump" },
                    { 143, "oprah.winfrey@nasa.org.us", "Oprah", "Winfrey" },
                    { 144, "audrey.middleton@theworld.ca", "Audrey", "Middleton" },
                    { 145, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 146, "kate.middleton@gov.us", "Kate", "Middleton" },
                    { 147, "jimi.trump@tesla.com", "Jimi", "Trump" },
                    { 148, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 149, "audrey.middleton@something.com", "Audrey", "Middleton" },
                    { 150, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 151, "mick.jagger@gov.ru", "Mick", "Jagger" },
                    { 152, "charles.hendrix@gov.us", "Charles", "Hendrix" },
                    { 153, "kate.presley@bbc.co.uk", "Kate", "Presley" },
                    { 154, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 155, "oprah.obama@gov.nl", "Oprah", "Obama" },
                    { 156, "donald.windsor@gov.us", "Donald", "Windsor" },
                    { 157, "charles.obama@theworld.ca", "Charles", "Obama" },
                    { 158, "oprah.winfrey@google.com", "Oprah", "Winfrey" },
                    { 159, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 160, "charles.hepburn@nasa.org.us", "Charles", "Hepburn" },
                    { 161, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 162, "elvis.winslet@gov.ru", "Elvis", "Winslet" },
                    { 163, "barack.middleton@google.com", "Barack", "Middleton" },
                    { 164, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 165, "oprah.hepburn@google.com", "Oprah", "Hepburn" },
                    { 166, "barack.trump@gov.nl", "Barack", "Trump" },
                    { 167, "jimi.windsor@gov.nl", "Jimi", "Windsor" },
                    { 168, "donald.winfrey@tesla.com", "Donald", "Winfrey" },
                    { 169, "oprah.windsor@theworld.ca", "Oprah", "Windsor" },
                    { 170, "elvis.trump@gov.nl", "Elvis", "Trump" },
                    { 171, "jimi.winslet@tesla.com", "Jimi", "Winslet" },
                    { 172, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 173, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 174, "audrey.winslet@gov.ru", "Audrey", "Winslet" },
                    { 175, "mick.winslet@gov.ru", "Mick", "Winslet" },
                    { 176, "mick.middleton@bbc.co.uk", "Mick", "Middleton" },
                    { 177, "barack.presley@tesla.com", "Barack", "Presley" },
                    { 178, "audrey.winslet@nasa.org.us", "Audrey", "Winslet" },
                    { 179, "kate.obama@google.com", "Kate", "Obama" },
                    { 180, "donald.presley@gov.gr", "Donald", "Presley" },
                    { 181, "barack.jagger@nasa.org.us", "Barack", "Jagger" },
                    { 182, "donald.winfrey@nasa.org.us", "Donald", "Winfrey" },
                    { 183, "jimi.trump@gov.nl", "Jimi", "Trump" },
                    { 184, "charles.trump@bbc.co.uk", "Charles", "Trump" },
                    { 185, "oprah.windsor@gov.nl", "Oprah", "Windsor" },
                    { 186, "audrey.middleton@tesla.com", "Audrey", "Middleton" },
                    { 187, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 188, "charles.windsor@gov.us", "Charles", "Windsor" },
                    { 189, "charles.jagger@gov.nl", "Charles", "Jagger" },
                    { 190, "mick.jagger@tesla.com", "Mick", "Jagger" },
                    { 191, "jimi.trump@something.com", "Jimi", "Trump" },
                    { 192, "mick.presley@google.com", "Mick", "Presley" },
                    { 193, "barack.hepburn@gov.nl", "Barack", "Hepburn" },
                    { 194, "elvis.presley@nasa.org.us", "Elvis", "Presley" },
                    { 195, "mick.winslet@gov.nl", "Mick", "Winslet" },
                    { 196, "jimi.winslet@theworld.ca", "Jimi", "Winslet" },
                    { 197, "jimi.winslet@theworld.ca", "Jimi", "Winslet" },
                    { 198, "elvis.hendrix@google.com", "Elvis", "Hendrix" },
                    { 199, "oprah.trump@gov.nl", "Oprah", "Trump" },
                    { 200, "elvis.jagger@gov.nl", "Elvis", "Jagger" },
                    { 201, "oprah.winfrey@gov.nl", "Oprah", "Winfrey" },
                    { 202, "charles.trump@theworld.ca", "Charles", "Trump" },
                    { 203, "kate.obama@gov.nl", "Kate", "Obama" },
                    { 204, "jimi.windsor@tesla.com", "Jimi", "Windsor" },
                    { 205, "kate.winslet@theworld.ca", "Kate", "Winslet" },
                    { 206, "barack.winfrey@theworld.ca", "Barack", "Winfrey" },
                    { 207, "oprah.jagger@nasa.org.us", "Oprah", "Jagger" },
                    { 208, "elvis.winslet@something.com", "Elvis", "Winslet" },
                    { 209, "elvis.jagger@something.com", "Elvis", "Jagger" },
                    { 210, "mick.windsor@gov.ru", "Mick", "Windsor" },
                    { 211, "barack.presley@gov.ru", "Barack", "Presley" },
                    { 212, "audrey.jagger@gov.nl", "Audrey", "Jagger" },
                    { 213, "oprah.middleton@gov.us", "Oprah", "Middleton" },
                    { 214, "donald.hepburn@gov.gr", "Donald", "Hepburn" },
                    { 215, "elvis.hendrix@google.com", "Elvis", "Hendrix" },
                    { 216, "charles.presley@nasa.org.us", "Charles", "Presley" },
                    { 217, "barack.winslet@gov.nl", "Barack", "Winslet" },
                    { 218, "charles.presley@gov.gr", "Charles", "Presley" },
                    { 219, "elvis.trump@something.com", "Elvis", "Trump" },
                    { 220, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 221, "mick.hepburn@tesla.com", "Mick", "Hepburn" },
                    { 222, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 223, "mick.obama@bbc.co.uk", "Mick", "Obama" },
                    { 224, "elvis.hepburn@gov.nl", "Elvis", "Hepburn" },
                    { 225, "donald.middleton@something.com", "Donald", "Middleton" },
                    { 226, "mick.hendrix@google.com", "Mick", "Hendrix" },
                    { 227, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 228, "elvis.obama@bbc.co.uk", "Elvis", "Obama" },
                    { 229, "mick.jagger@something.com", "Mick", "Jagger" },
                    { 230, "audrey.middleton@gov.ru", "Audrey", "Middleton" },
                    { 231, "charles.trump@gov.gr", "Charles", "Trump" },
                    { 232, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 233, "jimi.presley@theworld.ca", "Jimi", "Presley" },
                    { 234, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 235, "kate.hendrix@theworld.ca", "Kate", "Hendrix" },
                    { 236, "audrey.hendrix@something.com", "Audrey", "Hendrix" },
                    { 237, "audrey.windsor@google.com", "Audrey", "Windsor" },
                    { 238, "donald.winfrey@nasa.org.us", "Donald", "Winfrey" },
                    { 239, "barack.middleton@gov.nl", "Barack", "Middleton" },
                    { 240, "elvis.hendrix@tesla.com", "Elvis", "Hendrix" },
                    { 241, "mick.obama@nasa.org.us", "Mick", "Obama" },
                    { 242, "barack.middleton@gov.ru", "Barack", "Middleton" },
                    { 243, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 244, "audrey.trump@nasa.org.us", "Audrey", "Trump" },
                    { 245, "mick.presley@gov.gr", "Mick", "Presley" },
                    { 246, "elvis.winfrey@gov.ru", "Elvis", "Winfrey" },
                    { 247, "kate.obama@google.com", "Kate", "Obama" },
                    { 248, "jimi.windsor@something.com", "Jimi", "Windsor" },
                    { 249, "kate.jagger@something.com", "Kate", "Jagger" }
                });

            migrationBuilder.InsertData(
                table: "Books",
                columns: new[] { "Id", "AuthorId", "Title" },
                values: new object[,]
                {
                    { 1, 68, "An army of Green Buildings" },
                    { 2, 136, "Two Large Houses" },
                    { 3, 16, "A bunch of Microscopic Houses" },
                    { 4, 93, "Two Transparent Houses" },
                    { 5, 153, "An army of Microscopic Flowers" },
                    { 6, 79, "A bunch of Transparent Buildings" },
                    { 7, 112, "Fifteen Bitter Flowers" },
                    { 8, 181, "Two Large Planets" },
                    { 9, 168, "A bunch of Microscopic Flowers" },
                    { 10, 106, "An army of Transparent Planets" },
                    { 11, 39, "Several Rose Smelling Houses" },
                    { 12, 143, "Several Transparent Cars" },
                    { 13, 37, "A bunch of Large Planets" },
                    { 14, 147, "A herd of Purple Flowers" },
                    { 15, 235, "A herd of Orange Leopards" },
                    { 16, 185, "An army of Green Cars" },
                    { 17, 217, "Two Orange Flowers" },
                    { 18, 193, "Several Purple Leopards" },
                    { 19, 114, "Several Transparent Cars" },
                    { 20, 56, "A bunch of Bitter Cars" },
                    { 21, 232, "Fifteen Large Houses" },
                    { 22, 79, "An army of Green Houses" },
                    { 23, 22, "A bunch of Transparent Buildings" },
                    { 24, 197, "Two Bitter Planets" },
                    { 25, 238, "Several Purple Planets" },
                    { 26, 145, "A bunch of Microscopic Buildings" },
                    { 27, 199, "Two Orange Leopards" },
                    { 28, 227, "The Purple Flowers" },
                    { 29, 39, "A herd of Rose Smelling Leopards" },
                    { 30, 145, "Fifteen Transparent Cars" },
                    { 31, 137, "A herd of Rose Smelling Leopards" },
                    { 32, 11, "Two Transparent Leopards" },
                    { 33, 106, "Fifteen Microscopic Leopards" },
                    { 34, 168, "Several Large Planets" },
                    { 35, 108, "A bunch of Rose Smelling Cars" },
                    { 36, 141, "A bunch of Purple Leopards" },
                    { 37, 192, "Two Green Leopards" },
                    { 38, 23, "A bunch of Bitter Flowers" },
                    { 39, 167, "Two Microscopic Planets" },
                    { 40, 133, "A bunch of Orange Cars" },
                    { 41, 109, "A bunch of Orange Cars" },
                    { 42, 5, "A bunch of Microscopic Flowers" },
                    { 43, 61, "Two Purple Cars" },
                    { 44, 214, "A herd of Rose Smelling Flowers" },
                    { 45, 7, "Two Purple Houses" },
                    { 46, 7, "The Rose Smelling Planets" },
                    { 47, 9, "A bunch of Purple Flowers" },
                    { 48, 62, "The Purple Planets" },
                    { 49, 126, "Fifteen Large Flowers" },
                    { 50, 96, "An army of Transparent Cars" },
                    { 51, 48, "An army of Microscopic Planets" },
                    { 52, 245, "A bunch of Bitter Houses" },
                    { 53, 92, "Several Orange Flowers" },
                    { 54, 117, "A bunch of Orange Leopards" },
                    { 55, 41, "Several Purple Cars" },
                    { 56, 138, "Fifteen Transparent Flowers" },
                    { 57, 236, "A bunch of Transparent Cars" },
                    { 58, 204, "Several Green Planets" },
                    { 59, 133, "Two Bitter Houses" },
                    { 60, 210, "The Bitter Houses" },
                    { 61, 27, "A bunch of Orange Flowers" },
                    { 62, 120, "Two Microscopic Cars" },
                    { 63, 122, "The Orange Buildings" },
                    { 64, 105, "Several Bitter Planets" },
                    { 65, 117, "A herd of Orange Planets" },
                    { 66, 219, "Several Orange Leopards" },
                    { 67, 202, "Two Transparent Cars" },
                    { 68, 86, "Two Rose Smelling Houses" },
                    { 69, 74, "Two Bitter Leopards" },
                    { 70, 200, "A herd of Green Leopards" },
                    { 71, 228, "Two Transparent Flowers" },
                    { 72, 58, "Several Microscopic Planets" },
                    { 73, 87, "An army of Bitter Leopards" },
                    { 74, 173, "An army of Microscopic Flowers" },
                    { 75, 156, "The Transparent Leopards" },
                    { 76, 122, "A bunch of Microscopic Houses" },
                    { 77, 218, "A bunch of Transparent Houses" },
                    { 78, 214, "Fifteen Microscopic Leopards" },
                    { 79, 14, "Fifteen Transparent Buildings" },
                    { 80, 11, "The Transparent Cars" },
                    { 81, 181, "A bunch of Purple Leopards" },
                    { 82, 120, "The Bitter Buildings" },
                    { 83, 54, "An army of Microscopic Leopards" },
                    { 84, 25, "Several Purple Houses" },
                    { 85, 147, "A bunch of Microscopic Houses" },
                    { 86, 113, "A herd of Large Cars" },
                    { 87, 214, "Two Rose Smelling Leopards" },
                    { 88, 152, "Fifteen Green Flowers" },
                    { 89, 183, "A herd of Orange Flowers" },
                    { 90, 220, "A herd of Green Cars" },
                    { 91, 176, "Fifteen Rose Smelling Cars" },
                    { 92, 145, "An army of Rose Smelling Planets" },
                    { 93, 36, "Several Bitter Leopards" },
                    { 94, 100, "A bunch of Bitter Flowers" },
                    { 95, 19, "An army of Orange Buildings" },
                    { 96, 184, "An army of Rose Smelling Planets" },
                    { 97, 16, "A bunch of Rose Smelling Flowers" },
                    { 98, 118, "An army of Orange Cars" },
                    { 99, 16, "An army of Bitter Leopards" },
                    { 100, 12, "A bunch of Bitter Planets" },
                    { 101, 243, "Fifteen Transparent Buildings" },
                    { 102, 171, "Two Rose Smelling Houses" },
                    { 103, 11, "A bunch of Rose Smelling Cars" },
                    { 104, 170, "Several Orange Cars" },
                    { 105, 90, "Two Transparent Houses" },
                    { 106, 40, "Several Transparent Leopards" },
                    { 107, 54, "Fifteen Bitter Houses" },
                    { 108, 104, "A bunch of Green Planets" },
                    { 109, 131, "The Bitter Houses" },
                    { 110, 201, "An army of Green Planets" },
                    { 111, 52, "Several Large Flowers" },
                    { 112, 199, "Fifteen Large Planets" },
                    { 113, 32, "The Purple Leopards" },
                    { 114, 82, "A bunch of Large Houses" },
                    { 115, 185, "A bunch of Purple Flowers" },
                    { 116, 182, "A bunch of Orange Flowers" },
                    { 117, 59, "A bunch of Bitter Cars" },
                    { 118, 187, "A bunch of Orange Cars" },
                    { 119, 114, "Several Transparent Planets" },
                    { 120, 46, "Two Transparent Houses" },
                    { 121, 166, "Several Purple Houses" },
                    { 122, 104, "The Large Flowers" },
                    { 123, 128, "Fifteen Large Cars" },
                    { 124, 161, "A bunch of Microscopic Houses" },
                    { 125, 155, "A herd of Bitter Planets" },
                    { 126, 97, "Two Green Houses" },
                    { 127, 205, "The Orange Houses" },
                    { 128, 27, "Fifteen Bitter Cars" },
                    { 129, 169, "A bunch of Green Flowers" },
                    { 130, 12, "Several Transparent Leopards" },
                    { 131, 152, "The Rose Smelling Leopards" },
                    { 132, 217, "Two Orange Houses" },
                    { 133, 95, "The Large Flowers" },
                    { 134, 110, "A herd of Orange Leopards" },
                    { 135, 69, "An army of Microscopic Flowers" },
                    { 136, 53, "A herd of Green Houses" },
                    { 137, 24, "Two Green Buildings" },
                    { 138, 27, "Fifteen Green Houses" },
                    { 139, 4, "Two Orange Flowers" },
                    { 140, 57, "Two Transparent Planets" },
                    { 141, 179, "Fifteen Transparent Houses" },
                    { 142, 63, "Fifteen Orange Cars" },
                    { 143, 217, "A bunch of Large Houses" },
                    { 144, 171, "Two Large Cars" },
                    { 145, 198, "Two Large Leopards" },
                    { 146, 156, "Two Green Houses" },
                    { 147, 75, "An army of Transparent Houses" },
                    { 148, 25, "Fifteen Large Cars" },
                    { 149, 148, "The Rose Smelling Buildings" },
                    { 150, 28, "Fifteen Green Planets" },
                    { 151, 214, "Several Rose Smelling Cars" },
                    { 152, 203, "Fifteen Purple Cars" },
                    { 153, 243, "An army of Purple Cars" },
                    { 154, 137, "Two Microscopic Flowers" },
                    { 155, 121, "The Transparent Buildings" },
                    { 156, 99, "An army of Microscopic Leopards" },
                    { 157, 6, "Two Transparent Planets" },
                    { 158, 91, "A herd of Rose Smelling Cars" },
                    { 159, 220, "An army of Green Houses" },
                    { 160, 70, "Two Green Planets" },
                    { 161, 102, "Two Microscopic Buildings" },
                    { 162, 173, "An army of Large Leopards" },
                    { 163, 196, "A bunch of Rose Smelling Cars" },
                    { 164, 169, "A bunch of Transparent Flowers" },
                    { 165, 128, "A herd of Orange Planets" },
                    { 166, 221, "The Transparent Houses" },
                    { 167, 221, "A herd of Microscopic Houses" },
                    { 168, 11, "An army of Microscopic Leopards" },
                    { 169, 202, "Fifteen Transparent Houses" },
                    { 170, 163, "The Orange Planets" },
                    { 171, 75, "An army of Large Leopards" },
                    { 172, 107, "Several Green Leopards" },
                    { 173, 220, "Fifteen Microscopic Cars" },
                    { 174, 24, "Two Green Flowers" },
                    { 175, 200, "A herd of Orange Leopards" },
                    { 176, 189, "Two Purple Cars" },
                    { 177, 134, "The Transparent Houses" },
                    { 178, 21, "The Transparent Cars" },
                    { 179, 188, "Fifteen Rose Smelling Cars" },
                    { 180, 199, "A herd of Green Houses" },
                    { 181, 171, "The Rose Smelling Planets" },
                    { 182, 194, "An army of Green Houses" },
                    { 183, 112, "Two Rose Smelling Buildings" },
                    { 184, 168, "An army of Bitter Planets" },
                    { 185, 242, "An army of Green Leopards" },
                    { 186, 226, "A bunch of Green Flowers" },
                    { 187, 10, "A herd of Orange Houses" },
                    { 188, 63, "A herd of Transparent Buildings" },
                    { 189, 14, "A herd of Orange Cars" },
                    { 190, 228, "An army of Purple Leopards" },
                    { 191, 216, "Several Rose Smelling Cars" },
                    { 192, 183, "The Microscopic Cars" },
                    { 193, 39, "Several Rose Smelling Leopards" },
                    { 194, 47, "A herd of Transparent Leopards" },
                    { 195, 59, "Several Orange Cars" },
                    { 196, 239, "Several Rose Smelling Leopards" },
                    { 197, 158, "A herd of Rose Smelling Cars" },
                    { 198, 30, "Several Purple Leopards" },
                    { 199, 113, "A herd of Rose Smelling Flowers" },
                    { 200, 249, "Fifteen Bitter Cars" },
                    { 201, 147, "Two Orange Flowers" },
                    { 202, 24, "Two Transparent Planets" },
                    { 203, 243, "Two Bitter Houses" },
                    { 204, 131, "An army of Orange Flowers" },
                    { 205, 3, "An army of Microscopic Buildings" },
                    { 206, 20, "A herd of Orange Cars" },
                    { 207, 223, "A bunch of Green Leopards" },
                    { 208, 86, "A bunch of Bitter Houses" },
                    { 209, 44, "A herd of Bitter Buildings" },
                    { 210, 62, "A herd of Microscopic Leopards" },
                    { 211, 174, "Fifteen Green Buildings" },
                    { 212, 140, "Two Orange Planets" },
                    { 213, 83, "A herd of Orange Planets" },
                    { 214, 66, "Several Purple Planets" },
                    { 215, 7, "An army of Rose Smelling Buildings" },
                    { 216, 159, "A herd of Rose Smelling Planets" },
                    { 217, 216, "An army of Purple Planets" },
                    { 218, 74, "The Microscopic Planets" },
                    { 219, 173, "Fifteen Green Leopards" },
                    { 220, 57, "A herd of Orange Houses" },
                    { 221, 227, "A bunch of Bitter Planets" },
                    { 222, 177, "Two Purple Leopards" },
                    { 223, 85, "Fifteen Bitter Planets" },
                    { 224, 176, "A bunch of Bitter Houses" },
                    { 225, 88, "Fifteen Rose Smelling Buildings" },
                    { 226, 29, "Several Purple Leopards" },
                    { 227, 161, "A bunch of Green Flowers" },
                    { 228, 3, "A bunch of Rose Smelling Houses" },
                    { 229, 63, "A bunch of Rose Smelling Leopards" },
                    { 230, 92, "A herd of Transparent Houses" },
                    { 231, 75, "Several Purple Leopards" },
                    { 232, 182, "Fifteen Bitter Houses" },
                    { 233, 105, "A herd of Bitter Planets" },
                    { 234, 54, "A bunch of Orange Leopards" },
                    { 235, 56, "Two Microscopic Cars" },
                    { 236, 98, "The Large Buildings" },
                    { 237, 66, "A bunch of Orange Leopards" },
                    { 238, 18, "Fifteen Microscopic Leopards" },
                    { 239, 149, "The Transparent Flowers" },
                    { 240, 133, "A herd of Orange Planets" },
                    { 241, 189, "Fifteen Large Buildings" },
                    { 242, 219, "A herd of Transparent Leopards" },
                    { 243, 191, "An army of Purple Leopards" },
                    { 244, 128, "An army of Bitter Leopards" },
                    { 245, 222, "Two Rose Smelling Planets" },
                    { 246, 57, "An army of Green Buildings" },
                    { 247, 185, "A bunch of Green Cars" },
                    { 248, 173, "The Large Leopards" },
                    { 249, 167, "A herd of Rose Smelling Cars" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Books_AuthorId",
                table: "Books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Books");

            migrationBuilder.DropTable(
                name: "Publishers");

            migrationBuilder.DropTable(
                name: "Authors");
        }
    }
}
