using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    FirstName = table.Column<string>(type: "text", nullable: false),
                    LastName = table.Column<string>(type: "text", nullable: false),
                    Email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Books",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Books", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Books_Authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Authors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "Id", "Email", "FirstName", "LastName" },
                values: new object[,]
                {
                    { 1, "charles.trump@gov.nl", "Charles", "Trump" },
                    { 2, "charles.hepburn@tesla.com", "Charles", "Hepburn" },
                    { 3, "audrey.winfrey@nasa.org.us", "Audrey", "Winfrey" },
                    { 4, "jimi.obama@google.com", "Jimi", "Obama" },
                    { 5, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 6, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 7, "elvis.presley@gov.ru", "Elvis", "Presley" },
                    { 8, "elvis.hepburn@gov.nl", "Elvis", "Hepburn" },
                    { 9, "donald.jagger@gov.gr", "Donald", "Jagger" },
                    { 10, "barack.winfrey@gov.gr", "Barack", "Winfrey" },
                    { 11, "donald.winslet@gov.nl", "Donald", "Winslet" },
                    { 12, "oprah.hendrix@nasa.org.us", "Oprah", "Hendrix" },
                    { 13, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 14, "barack.jagger@tesla.com", "Barack", "Jagger" },
                    { 15, "charles.winslet@bbc.co.uk", "Charles", "Winslet" },
                    { 16, "audrey.hepburn@nasa.org.us", "Audrey", "Hepburn" },
                    { 17, "oprah.trump@something.com", "Oprah", "Trump" },
                    { 18, "kate.obama@gov.us", "Kate", "Obama" },
                    { 19, "kate.winslet@theworld.ca", "Kate", "Winslet" },
                    { 20, "audrey.obama@google.com", "Audrey", "Obama" },
                    { 21, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 22, "barack.winslet@gov.nl", "Barack", "Winslet" },
                    { 23, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 24, "mick.middleton@gov.gr", "Mick", "Middleton" },
                    { 25, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 26, "charles.presley@tesla.com", "Charles", "Presley" },
                    { 27, "audrey.winslet@bbc.co.uk", "Audrey", "Winslet" },
                    { 28, "oprah.windsor@theworld.ca", "Oprah", "Windsor" },
                    { 29, "mick.windsor@tesla.com", "Mick", "Windsor" },
                    { 30, "kate.obama@gov.us", "Kate", "Obama" },
                    { 31, "mick.winslet@something.com", "Mick", "Winslet" },
                    { 32, "donald.winslet@theworld.ca", "Donald", "Winslet" },
                    { 33, "barack.presley@nasa.org.us", "Barack", "Presley" },
                    { 34, "donald.jagger@tesla.com", "Donald", "Jagger" },
                    { 35, "charles.trump@gov.us", "Charles", "Trump" },
                    { 36, "oprah.winfrey@gov.nl", "Oprah", "Winfrey" },
                    { 37, "jimi.winfrey@google.com", "Jimi", "Winfrey" },
                    { 38, "mick.hendrix@google.com", "Mick", "Hendrix" },
                    { 39, "mick.trump@google.com", "Mick", "Trump" },
                    { 40, "audrey.trump@theworld.ca", "Audrey", "Trump" },
                    { 41, "audrey.trump@theworld.ca", "Audrey", "Trump" },
                    { 42, "mick.winfrey@nasa.org.us", "Mick", "Winfrey" },
                    { 43, "kate.winslet@something.com", "Kate", "Winslet" },
                    { 44, "barack.presley@google.com", "Barack", "Presley" },
                    { 45, "jimi.presley@bbc.co.uk", "Jimi", "Presley" },
                    { 46, "oprah.presley@something.com", "Oprah", "Presley" },
                    { 47, "charles.winslet@theworld.ca", "Charles", "Winslet" },
                    { 48, "elvis.presley@gov.nl", "Elvis", "Presley" },
                    { 49, "kate.presley@bbc.co.uk", "Kate", "Presley" },
                    { 50, "charles.hepburn@google.com", "Charles", "Hepburn" },
                    { 51, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 52, "oprah.middleton@gov.ru", "Oprah", "Middleton" },
                    { 53, "donald.presley@google.com", "Donald", "Presley" },
                    { 54, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 55, "mick.jagger@gov.ru", "Mick", "Jagger" },
                    { 56, "barack.jagger@tesla.com", "Barack", "Jagger" },
                    { 57, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 58, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 59, "donald.windsor@gov.gr", "Donald", "Windsor" },
                    { 60, "audrey.hepburn@tesla.com", "Audrey", "Hepburn" },
                    { 61, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 62, "oprah.trump@gov.us", "Oprah", "Trump" },
                    { 63, "donald.jagger@gov.nl", "Donald", "Jagger" },
                    { 64, "mick.middleton@gov.us", "Mick", "Middleton" },
                    { 65, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 66, "donald.winfrey@tesla.com", "Donald", "Winfrey" },
                    { 67, "charles.presley@something.com", "Charles", "Presley" },
                    { 68, "mick.trump@gov.us", "Mick", "Trump" },
                    { 69, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 70, "donald.presley@something.com", "Donald", "Presley" },
                    { 71, "elvis.winfrey@something.com", "Elvis", "Winfrey" },
                    { 72, "elvis.windsor@nasa.org.us", "Elvis", "Windsor" },
                    { 73, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 74, "mick.jagger@something.com", "Mick", "Jagger" },
                    { 75, "barack.hepburn@gov.ru", "Barack", "Hepburn" },
                    { 76, "barack.obama@gov.us", "Barack", "Obama" },
                    { 77, "oprah.winslet@something.com", "Oprah", "Winslet" },
                    { 78, "jimi.winfrey@nasa.org.us", "Jimi", "Winfrey" },
                    { 79, "donald.presley@gov.us", "Donald", "Presley" },
                    { 80, "oprah.presley@gov.us", "Oprah", "Presley" },
                    { 81, "audrey.presley@gov.nl", "Audrey", "Presley" },
                    { 82, "charles.presley@bbc.co.uk", "Charles", "Presley" },
                    { 83, "barack.hepburn@google.com", "Barack", "Hepburn" },
                    { 84, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 85, "mick.presley@bbc.co.uk", "Mick", "Presley" },
                    { 86, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 87, "donald.middleton@gov.ru", "Donald", "Middleton" },
                    { 88, "audrey.hendrix@something.com", "Audrey", "Hendrix" },
                    { 89, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 90, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 91, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 92, "kate.trump@something.com", "Kate", "Trump" },
                    { 93, "mick.hepburn@gov.nl", "Mick", "Hepburn" },
                    { 94, "mick.trump@tesla.com", "Mick", "Trump" },
                    { 95, "barack.trump@something.com", "Barack", "Trump" },
                    { 96, "barack.presley@theworld.ca", "Barack", "Presley" },
                    { 97, "audrey.hendrix@gov.ru", "Audrey", "Hendrix" },
                    { 98, "elvis.hepburn@nasa.org.us", "Elvis", "Hepburn" },
                    { 99, "audrey.jagger@tesla.com", "Audrey", "Jagger" },
                    { 100, "oprah.jagger@gov.ru", "Oprah", "Jagger" },
                    { 101, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 102, "charles.winslet@theworld.ca", "Charles", "Winslet" },
                    { 103, "charles.presley@gov.ru", "Charles", "Presley" },
                    { 104, "barack.obama@nasa.org.us", "Barack", "Obama" },
                    { 105, "donald.winslet@gov.nl", "Donald", "Winslet" },
                    { 106, "kate.obama@google.com", "Kate", "Obama" },
                    { 107, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 108, "mick.obama@something.com", "Mick", "Obama" },
                    { 109, "donald.windsor@tesla.com", "Donald", "Windsor" },
                    { 110, "mick.winfrey@tesla.com", "Mick", "Winfrey" },
                    { 111, "audrey.middleton@nasa.org.us", "Audrey", "Middleton" },
                    { 112, "elvis.presley@gov.nl", "Elvis", "Presley" },
                    { 113, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 114, "charles.winfrey@gov.us", "Charles", "Winfrey" },
                    { 115, "donald.hepburn@nasa.org.us", "Donald", "Hepburn" },
                    { 116, "charles.hepburn@gov.ru", "Charles", "Hepburn" },
                    { 117, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 118, "charles.windsor@theworld.ca", "Charles", "Windsor" },
                    { 119, "audrey.hendrix@gov.gr", "Audrey", "Hendrix" },
                    { 120, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 121, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 122, "audrey.jagger@gov.ru", "Audrey", "Jagger" },
                    { 123, "donald.jagger@gov.us", "Donald", "Jagger" },
                    { 124, "donald.trump@something.com", "Donald", "Trump" },
                    { 125, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 126, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 127, "donald.jagger@bbc.co.uk", "Donald", "Jagger" },
                    { 128, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 129, "elvis.winfrey@google.com", "Elvis", "Winfrey" },
                    { 130, "donald.trump@google.com", "Donald", "Trump" },
                    { 131, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 132, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 133, "audrey.trump@theworld.ca", "Audrey", "Trump" },
                    { 134, "mick.hepburn@theworld.ca", "Mick", "Hepburn" },
                    { 135, "elvis.hepburn@something.com", "Elvis", "Hepburn" },
                    { 136, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 137, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 138, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 139, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 140, "oprah.middleton@bbc.co.uk", "Oprah", "Middleton" },
                    { 141, "audrey.presley@something.com", "Audrey", "Presley" },
                    { 142, "audrey.hendrix@gov.ru", "Audrey", "Hendrix" },
                    { 143, "oprah.winfrey@bbc.co.uk", "Oprah", "Winfrey" },
                    { 144, "kate.winfrey@google.com", "Kate", "Winfrey" },
                    { 145, "mick.winslet@something.com", "Mick", "Winslet" },
                    { 146, "elvis.presley@bbc.co.uk", "Elvis", "Presley" },
                    { 147, "donald.winslet@bbc.co.uk", "Donald", "Winslet" },
                    { 148, "audrey.middleton@gov.ru", "Audrey", "Middleton" },
                    { 149, "barack.jagger@bbc.co.uk", "Barack", "Jagger" },
                    { 150, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 151, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 152, "jimi.presley@theworld.ca", "Jimi", "Presley" },
                    { 153, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 154, "elvis.hepburn@bbc.co.uk", "Elvis", "Hepburn" },
                    { 155, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 156, "elvis.presley@something.com", "Elvis", "Presley" },
                    { 157, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 158, "audrey.windsor@tesla.com", "Audrey", "Windsor" },
                    { 159, "barack.trump@something.com", "Barack", "Trump" },
                    { 160, "audrey.jagger@gov.nl", "Audrey", "Jagger" },
                    { 161, "mick.jagger@gov.nl", "Mick", "Jagger" },
                    { 162, "mick.trump@gov.us", "Mick", "Trump" },
                    { 163, "jimi.hepburn@something.com", "Jimi", "Hepburn" },
                    { 164, "audrey.windsor@something.com", "Audrey", "Windsor" },
                    { 165, "mick.trump@theworld.ca", "Mick", "Trump" },
                    { 166, "barack.presley@bbc.co.uk", "Barack", "Presley" },
                    { 167, "donald.winfrey@theworld.ca", "Donald", "Winfrey" },
                    { 168, "charles.jagger@gov.ru", "Charles", "Jagger" },
                    { 169, "jimi.jagger@gov.us", "Jimi", "Jagger" },
                    { 170, "kate.winfrey@tesla.com", "Kate", "Winfrey" },
                    { 171, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 172, "audrey.obama@something.com", "Audrey", "Obama" },
                    { 173, "mick.presley@theworld.ca", "Mick", "Presley" },
                    { 174, "donald.jagger@bbc.co.uk", "Donald", "Jagger" },
                    { 175, "donald.middleton@gov.us", "Donald", "Middleton" },
                    { 176, "barack.obama@tesla.com", "Barack", "Obama" },
                    { 177, "barack.windsor@nasa.org.us", "Barack", "Windsor" },
                    { 178, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 179, "elvis.middleton@bbc.co.uk", "Elvis", "Middleton" },
                    { 180, "donald.middleton@nasa.org.us", "Donald", "Middleton" },
                    { 181, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 182, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 183, "audrey.presley@bbc.co.uk", "Audrey", "Presley" },
                    { 184, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 185, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 186, "audrey.obama@gov.ru", "Audrey", "Obama" },
                    { 187, "donald.winfrey@nasa.org.us", "Donald", "Winfrey" },
                    { 188, "oprah.windsor@theworld.ca", "Oprah", "Windsor" },
                    { 189, "kate.presley@tesla.com", "Kate", "Presley" },
                    { 190, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 191, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 192, "elvis.winslet@something.com", "Elvis", "Winslet" },
                    { 193, "mick.presley@tesla.com", "Mick", "Presley" },
                    { 194, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 195, "audrey.winfrey@something.com", "Audrey", "Winfrey" },
                    { 196, "kate.trump@google.com", "Kate", "Trump" },
                    { 197, "donald.winslet@tesla.com", "Donald", "Winslet" },
                    { 198, "audrey.winslet@bbc.co.uk", "Audrey", "Winslet" },
                    { 199, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 200, "barack.winfrey@something.com", "Barack", "Winfrey" },
                    { 201, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 202, "jimi.windsor@bbc.co.uk", "Jimi", "Windsor" },
                    { 203, "elvis.winfrey@gov.gr", "Elvis", "Winfrey" },
                    { 204, "jimi.winfrey@tesla.com", "Jimi", "Winfrey" },
                    { 205, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 206, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 207, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 208, "kate.middleton@tesla.com", "Kate", "Middleton" },
                    { 209, "mick.jagger@theworld.ca", "Mick", "Jagger" },
                    { 210, "kate.winfrey@nasa.org.us", "Kate", "Winfrey" },
                    { 211, "donald.hendrix@gov.us", "Donald", "Hendrix" },
                    { 212, "donald.middleton@gov.gr", "Donald", "Middleton" },
                    { 213, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 214, "mick.windsor@bbc.co.uk", "Mick", "Windsor" },
                    { 215, "oprah.middleton@nasa.org.us", "Oprah", "Middleton" },
                    { 216, "kate.trump@gov.us", "Kate", "Trump" },
                    { 217, "barack.winslet@something.com", "Barack", "Winslet" },
                    { 218, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 219, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 220, "mick.obama@gov.nl", "Mick", "Obama" },
                    { 221, "mick.winfrey@gov.ru", "Mick", "Winfrey" },
                    { 222, "mick.presley@gov.ru", "Mick", "Presley" },
                    { 223, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 224, "charles.hendrix@gov.nl", "Charles", "Hendrix" },
                    { 225, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 226, "elvis.winslet@theworld.ca", "Elvis", "Winslet" },
                    { 227, "donald.obama@gov.gr", "Donald", "Obama" },
                    { 228, "donald.jagger@gov.us", "Donald", "Jagger" },
                    { 229, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 230, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 231, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 232, "audrey.windsor@gov.gr", "Audrey", "Windsor" },
                    { 233, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 234, "elvis.hendrix@nasa.org.us", "Elvis", "Hendrix" },
                    { 235, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 236, "jimi.trump@gov.us", "Jimi", "Trump" },
                    { 237, "audrey.hepburn@tesla.com", "Audrey", "Hepburn" },
                    { 238, "kate.obama@something.com", "Kate", "Obama" },
                    { 239, "barack.hepburn@gov.gr", "Barack", "Hepburn" },
                    { 240, "donald.winfrey@google.com", "Donald", "Winfrey" },
                    { 241, "oprah.presley@tesla.com", "Oprah", "Presley" },
                    { 242, "kate.middleton@tesla.com", "Kate", "Middleton" },
                    { 243, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 244, "kate.middleton@gov.us", "Kate", "Middleton" },
                    { 245, "barack.hepburn@nasa.org.us", "Barack", "Hepburn" },
                    { 246, "elvis.hendrix@gov.us", "Elvis", "Hendrix" },
                    { 247, "elvis.middleton@theworld.ca", "Elvis", "Middleton" },
                    { 248, "oprah.middleton@gov.gr", "Oprah", "Middleton" },
                    { 249, "mick.trump@theworld.ca", "Mick", "Trump" }
                });

            migrationBuilder.InsertData(
                table: "Books",
                columns: new[] { "Id", "AuthorId", "Title" },
                values: new object[,]
                {
                    { 1, 188, "The Large Buildings" },
                    { 2, 205, "An army of Large Flowers" },
                    { 3, 28, "A bunch of Rose Smelling Cars" },
                    { 4, 63, "Several Bitter Flowers" },
                    { 5, 191, "An army of Transparent Leopards" },
                    { 6, 80, "An army of Microscopic Houses" },
                    { 7, 169, "The Purple Houses" },
                    { 8, 29, "The Green Planets" },
                    { 9, 238, "A herd of Purple Buildings" },
                    { 10, 145, "A herd of Large Leopards" },
                    { 11, 230, "A herd of Transparent Flowers" },
                    { 12, 6, "The Microscopic Cars" },
                    { 13, 24, "An army of Purple Leopards" },
                    { 14, 103, "A bunch of Purple Houses" },
                    { 15, 224, "Two Rose Smelling Buildings" },
                    { 16, 175, "An army of Microscopic Planets" },
                    { 17, 83, "An army of Transparent Leopards" },
                    { 18, 1, "Two Orange Flowers" },
                    { 19, 159, "A bunch of Large Leopards" },
                    { 20, 9, "Several Transparent Planets" },
                    { 21, 153, "A herd of Orange Leopards" },
                    { 22, 137, "An army of Rose Smelling Planets" },
                    { 23, 171, "A herd of Green Houses" },
                    { 24, 32, "Several Bitter Flowers" },
                    { 25, 34, "A bunch of Microscopic Cars" },
                    { 26, 100, "Two Large Buildings" },
                    { 27, 118, "An army of Microscopic Buildings" },
                    { 28, 8, "Fifteen Rose Smelling Leopards" },
                    { 29, 131, "An army of Orange Leopards" },
                    { 30, 199, "A herd of Microscopic Leopards" },
                    { 31, 18, "A bunch of Microscopic Houses" },
                    { 32, 1, "The Purple Houses" },
                    { 33, 81, "A bunch of Microscopic Leopards" },
                    { 34, 20, "Several Microscopic Flowers" },
                    { 35, 69, "Several Green Buildings" },
                    { 36, 21, "The Large Flowers" },
                    { 37, 56, "An army of Green Cars" },
                    { 38, 103, "Two Purple Leopards" },
                    { 39, 164, "An army of Orange Planets" },
                    { 40, 191, "An army of Transparent Leopards" },
                    { 41, 109, "A herd of Rose Smelling Buildings" },
                    { 42, 245, "A herd of Microscopic Buildings" },
                    { 43, 188, "An army of Large Houses" },
                    { 44, 113, "Two Transparent Leopards" },
                    { 45, 159, "Two Rose Smelling Cars" },
                    { 46, 79, "A bunch of Orange Cars" },
                    { 47, 72, "Fifteen Large Cars" },
                    { 48, 223, "An army of Purple Buildings" },
                    { 49, 21, "A bunch of Rose Smelling Leopards" },
                    { 50, 101, "A bunch of Green Cars" },
                    { 51, 224, "An army of Green Buildings" },
                    { 52, 104, "Fifteen Purple Planets" },
                    { 53, 245, "A herd of Bitter Houses" },
                    { 54, 64, "A bunch of Purple Planets" },
                    { 55, 29, "The Transparent Planets" },
                    { 56, 183, "The Microscopic Buildings" },
                    { 57, 130, "A bunch of Bitter Leopards" },
                    { 58, 4, "A bunch of Large Buildings" },
                    { 59, 20, "The Rose Smelling Planets" },
                    { 60, 154, "A herd of Purple Leopards" },
                    { 61, 27, "Two Green Planets" },
                    { 62, 64, "A herd of Large Flowers" },
                    { 63, 50, "Fifteen Bitter Houses" },
                    { 64, 110, "Several Purple Buildings" },
                    { 65, 186, "Two Purple Flowers" },
                    { 66, 72, "A herd of Rose Smelling Flowers" },
                    { 67, 83, "Several Transparent Buildings" },
                    { 68, 78, "Two Rose Smelling Buildings" },
                    { 69, 195, "A herd of Rose Smelling Buildings" },
                    { 70, 78, "An army of Orange Flowers" },
                    { 71, 142, "A herd of Transparent Flowers" },
                    { 72, 41, "Fifteen Rose Smelling Flowers" },
                    { 73, 85, "The Bitter Buildings" },
                    { 74, 5, "Several Green Flowers" },
                    { 75, 195, "Several Green Leopards" },
                    { 76, 22, "A herd of Purple Leopards" },
                    { 77, 150, "Several Bitter Buildings" },
                    { 78, 190, "An army of Green Cars" },
                    { 79, 86, "Fifteen Bitter Cars" },
                    { 80, 45, "Fifteen Orange Leopards" },
                    { 81, 121, "A herd of Green Cars" },
                    { 82, 134, "Several Microscopic Buildings" },
                    { 83, 111, "Several Microscopic Planets" },
                    { 84, 86, "Several Large Cars" },
                    { 85, 52, "Fifteen Microscopic Leopards" },
                    { 86, 10, "Several Orange Flowers" },
                    { 87, 138, "Two Large Planets" },
                    { 88, 90, "Several Transparent Houses" },
                    { 89, 47, "The Transparent Buildings" },
                    { 90, 148, "Several Purple Cars" },
                    { 91, 43, "Several Purple Planets" },
                    { 92, 240, "The Bitter Houses" },
                    { 93, 222, "An army of Microscopic Leopards" },
                    { 94, 223, "A herd of Purple Buildings" },
                    { 95, 221, "Two Microscopic Leopards" },
                    { 96, 236, "An army of Microscopic Leopards" },
                    { 97, 14, "A herd of Bitter Leopards" },
                    { 98, 120, "An army of Rose Smelling Buildings" },
                    { 99, 229, "Several Microscopic Flowers" },
                    { 100, 60, "The Large Houses" },
                    { 101, 219, "An army of Bitter Planets" },
                    { 102, 234, "A herd of Large Leopards" },
                    { 103, 145, "The Rose Smelling Flowers" },
                    { 104, 124, "Fifteen Orange Planets" },
                    { 105, 11, "An army of Purple Flowers" },
                    { 106, 16, "Fifteen Large Leopards" },
                    { 107, 231, "A bunch of Rose Smelling Flowers" },
                    { 108, 85, "An army of Orange Houses" },
                    { 109, 54, "A bunch of Large Cars" },
                    { 110, 63, "Several Transparent Leopards" },
                    { 111, 117, "A herd of Transparent Planets" },
                    { 112, 166, "An army of Large Buildings" },
                    { 113, 161, "Fifteen Microscopic Flowers" },
                    { 114, 144, "Fifteen Purple Planets" },
                    { 115, 80, "Two Purple Cars" },
                    { 116, 81, "Two Purple Houses" },
                    { 117, 61, "Fifteen Bitter Houses" },
                    { 118, 243, "Fifteen Transparent Flowers" },
                    { 119, 142, "Two Large Flowers" },
                    { 120, 232, "The Purple Planets" },
                    { 121, 202, "A bunch of Microscopic Flowers" },
                    { 122, 156, "The Bitter Planets" },
                    { 123, 9, "The Transparent Houses" },
                    { 124, 245, "Fifteen Orange Planets" },
                    { 125, 66, "Several Purple Planets" },
                    { 126, 245, "The Large Cars" },
                    { 127, 9, "A herd of Microscopic Buildings" },
                    { 128, 9, "An army of Green Leopards" },
                    { 129, 19, "Several Microscopic Leopards" },
                    { 130, 189, "An army of Green Flowers" },
                    { 131, 123, "A herd of Green Flowers" },
                    { 132, 132, "Several Microscopic Planets" },
                    { 133, 229, "An army of Bitter Cars" },
                    { 134, 128, "The Purple Cars" },
                    { 135, 207, "A bunch of Bitter Leopards" },
                    { 136, 224, "A bunch of Transparent Buildings" },
                    { 137, 34, "A herd of Microscopic Planets" },
                    { 138, 1, "Two Rose Smelling Leopards" },
                    { 139, 241, "An army of Transparent Houses" },
                    { 140, 233, "Several Orange Houses" },
                    { 141, 207, "A bunch of Microscopic Buildings" },
                    { 142, 133, "An army of Rose Smelling Leopards" },
                    { 143, 221, "Several Orange Buildings" },
                    { 144, 223, "The Green Flowers" },
                    { 145, 114, "Fifteen Bitter Houses" },
                    { 146, 129, "Two Microscopic Buildings" },
                    { 147, 183, "A bunch of Orange Leopards" },
                    { 148, 13, "A bunch of Bitter Cars" },
                    { 149, 67, "A herd of Microscopic Buildings" },
                    { 150, 144, "Fifteen Orange Houses" },
                    { 151, 157, "Two Green Planets" },
                    { 152, 63, "Several Purple Flowers" },
                    { 153, 137, "A herd of Large Leopards" },
                    { 154, 158, "A herd of Microscopic Houses" },
                    { 155, 28, "A bunch of Orange Cars" },
                    { 156, 107, "An army of Green Flowers" },
                    { 157, 152, "Fifteen Large Cars" },
                    { 158, 53, "A bunch of Transparent Cars" },
                    { 159, 115, "Several Purple Flowers" },
                    { 160, 20, "A herd of Transparent Leopards" },
                    { 161, 55, "An army of Large Buildings" },
                    { 162, 199, "Several Rose Smelling Flowers" },
                    { 163, 67, "Several Rose Smelling Buildings" },
                    { 164, 98, "Several Purple Leopards" },
                    { 165, 98, "Several Orange Cars" },
                    { 166, 209, "Fifteen Green Cars" },
                    { 167, 153, "Fifteen Orange Cars" },
                    { 168, 210, "A herd of Rose Smelling Houses" },
                    { 169, 94, "An army of Large Houses" },
                    { 170, 241, "A herd of Rose Smelling Buildings" },
                    { 171, 112, "An army of Transparent Buildings" },
                    { 172, 1, "The Green Buildings" },
                    { 173, 45, "Two Rose Smelling Buildings" },
                    { 174, 67, "Fifteen Transparent Houses" },
                    { 175, 198, "Two Large Houses" },
                    { 176, 163, "Several Transparent Flowers" },
                    { 177, 24, "A bunch of Orange Planets" },
                    { 178, 67, "A herd of Green Planets" },
                    { 179, 16, "Two Bitter Buildings" },
                    { 180, 195, "An army of Transparent Leopards" },
                    { 181, 167, "A herd of Orange Buildings" },
                    { 182, 40, "A bunch of Rose Smelling Leopards" },
                    { 183, 58, "A bunch of Transparent Cars" },
                    { 184, 187, "Fifteen Orange Cars" },
                    { 185, 98, "A herd of Large Houses" },
                    { 186, 234, "Fifteen Microscopic Cars" },
                    { 187, 116, "Several Green Houses" },
                    { 188, 147, "An army of Green Houses" },
                    { 189, 145, "The Large Flowers" },
                    { 190, 110, "A herd of Transparent Houses" },
                    { 191, 8, "The Rose Smelling Buildings" },
                    { 192, 183, "A bunch of Purple Planets" },
                    { 193, 93, "The Orange Cars" },
                    { 194, 29, "The Microscopic Houses" },
                    { 195, 149, "A bunch of Transparent Cars" },
                    { 196, 233, "Several Orange Leopards" },
                    { 197, 121, "A herd of Large Leopards" },
                    { 198, 52, "A herd of Green Flowers" },
                    { 199, 243, "Fifteen Large Buildings" },
                    { 200, 191, "An army of Purple Buildings" },
                    { 201, 191, "A bunch of Rose Smelling Buildings" },
                    { 202, 117, "An army of Rose Smelling Cars" },
                    { 203, 191, "An army of Large Leopards" },
                    { 204, 158, "Several Rose Smelling Houses" },
                    { 205, 121, "The Green Flowers" },
                    { 206, 29, "An army of Green Cars" },
                    { 207, 230, "The Transparent Houses" },
                    { 208, 20, "The Bitter Planets" },
                    { 209, 83, "Several Rose Smelling Leopards" },
                    { 210, 103, "A herd of Purple Flowers" },
                    { 211, 208, "The Microscopic Flowers" },
                    { 212, 88, "Two Purple Houses" },
                    { 213, 232, "A herd of Purple Houses" },
                    { 214, 103, "Fifteen Large Flowers" },
                    { 215, 189, "A bunch of Orange Houses" },
                    { 216, 144, "A herd of Green Leopards" },
                    { 217, 159, "Two Microscopic Planets" },
                    { 218, 121, "The Rose Smelling Planets" },
                    { 219, 248, "An army of Purple Leopards" },
                    { 220, 89, "Fifteen Transparent Flowers" },
                    { 221, 168, "Two Green Planets" },
                    { 222, 97, "Several Orange Planets" },
                    { 223, 69, "Two Bitter Flowers" },
                    { 224, 189, "Two Transparent Planets" },
                    { 225, 247, "Two Purple Buildings" },
                    { 226, 196, "A bunch of Orange Houses" },
                    { 227, 134, "A bunch of Large Buildings" },
                    { 228, 135, "Fifteen Large Buildings" },
                    { 229, 161, "The Transparent Planets" },
                    { 230, 218, "An army of Bitter Leopards" },
                    { 231, 88, "An army of Large Flowers" },
                    { 232, 226, "Two Orange Planets" },
                    { 233, 176, "Several Bitter Planets" },
                    { 234, 6, "A bunch of Large Cars" },
                    { 235, 28, "The Microscopic Buildings" },
                    { 236, 45, "A herd of Rose Smelling Cars" },
                    { 237, 168, "Several Rose Smelling Flowers" },
                    { 238, 188, "The Transparent Houses" },
                    { 239, 73, "An army of Orange Cars" },
                    { 240, 176, "Several Transparent Houses" },
                    { 241, 54, "The Rose Smelling Buildings" },
                    { 242, 177, "A herd of Green Buildings" },
                    { 243, 4, "An army of Bitter Houses" },
                    { 244, 77, "Several Purple Buildings" },
                    { 245, 65, "Several Green Leopards" },
                    { 246, 39, "A herd of Rose Smelling Buildings" },
                    { 247, 132, "Fifteen Green Buildings" },
                    { 248, 226, "An army of Large Planets" },
                    { 249, 93, "The Green Buildings" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Books_AuthorId",
                table: "Books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Books");

            migrationBuilder.DropTable(
                name: "Authors");
        }
    }
}
