// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.webapi.Data;

#nullable disable

namespace exercise.webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240906111646_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.webapi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "elvis.hepburn@bbc.co.uk",
                            FirstName = "Elvis",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 2,
                            Email = "kate.presley@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 3,
                            Email = "audrey.windsor@gov.gr",
                            FirstName = "Audrey",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mick.trump@gov.gr",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 5,
                            Email = "donald.winfrey@gov.nl",
                            FirstName = "Donald",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 6,
                            Email = "oprah.middleton@gov.nl",
                            FirstName = "Oprah",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 7,
                            Email = "barack.trump@bbc.co.uk",
                            FirstName = "Barack",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 8,
                            Email = "charles.trump@bbc.co.uk",
                            FirstName = "Charles",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 9,
                            Email = "jimi.hepburn@gov.nl",
                            FirstName = "Jimi",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 10,
                            Email = "charles.middleton@gov.gr",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 11,
                            Email = "kate.jagger@tesla.com",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 12,
                            Email = "mick.hendrix@gov.ru",
                            FirstName = "Mick",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 13,
                            Email = "mick.middleton@gov.us",
                            FirstName = "Mick",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 14,
                            Email = "oprah.trump@gov.us",
                            FirstName = "Oprah",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 15,
                            Email = "kate.trump@gov.us",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 16,
                            Email = "donald.hepburn@gov.us",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 17,
                            Email = "mick.presley@something.com",
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 18,
                            Email = "audrey.obama@gov.us",
                            FirstName = "Audrey",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 19,
                            Email = "kate.windsor@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 20,
                            Email = "mick.winfrey@bbc.co.uk",
                            FirstName = "Mick",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 21,
                            Email = "charles.presley@gov.gr",
                            FirstName = "Charles",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 22,
                            Email = "jimi.winfrey@something.com",
                            FirstName = "Jimi",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 23,
                            Email = "mick.trump@gov.us",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 24,
                            Email = "mick.presley@bbc.co.uk",
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 25,
                            Email = "jimi.windsor@gov.ru",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 26,
                            Email = "barack.trump@gov.nl",
                            FirstName = "Barack",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 27,
                            Email = "mick.trump@tesla.com",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 28,
                            Email = "mick.winslet@bbc.co.uk",
                            FirstName = "Mick",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 29,
                            Email = "donald.hepburn@theworld.ca",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 30,
                            Email = "jimi.jagger@something.com",
                            FirstName = "Jimi",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 31,
                            Email = "kate.middleton@something.com",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 32,
                            Email = "charles.obama@gov.gr",
                            FirstName = "Charles",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 33,
                            Email = "mick.windsor@nasa.org.us",
                            FirstName = "Mick",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 34,
                            Email = "kate.winfrey@tesla.com",
                            FirstName = "Kate",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 35,
                            Email = "charles.hendrix@theworld.ca",
                            FirstName = "Charles",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 36,
                            Email = "oprah.presley@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 37,
                            Email = "donald.presley@theworld.ca",
                            FirstName = "Donald",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 38,
                            Email = "kate.winslet@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 39,
                            Email = "audrey.obama@theworld.ca",
                            FirstName = "Audrey",
                            LastName = "Obama"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 5,
                            Title = "A bunch of Orange Flowers"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 12,
                            Title = "A bunch of Orange Buildings"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 6,
                            Title = "The Rose Smelling Planets"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 25,
                            Title = "A herd of Purple Buildings"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 24,
                            Title = "Several Green Buildings"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 11,
                            Title = "A bunch of Bitter Houses"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 26,
                            Title = "The Transparent Flowers"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 20,
                            Title = "Fifteen Microscopic Buildings"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Title = "A bunch of Orange Flowers"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 27,
                            Title = "Fifteen Bitter Planets"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 30,
                            Title = "A bunch of Orange Flowers"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 36,
                            Title = "A bunch of Green Leopards"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 20,
                            Title = "An army of Large Planets"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 25,
                            Title = "The Purple Cars"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 6,
                            Title = "Several Transparent Leopards"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 33,
                            Title = "Fifteen Rose Smelling Leopards"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 4,
                            Title = "The Purple Houses"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 26,
                            Title = "An army of Purple Cars"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 27,
                            Title = "An army of Purple Cars"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 26,
                            Title = "An army of Green Houses"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 31,
                            Title = "A bunch of Rose Smelling Cars"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 39,
                            Title = "An army of Transparent Flowers"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 30,
                            Title = "The Green Planets"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 23,
                            Title = "A bunch of Rose Smelling Planets"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 29,
                            Title = "The Purple Flowers"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 27,
                            Title = "An army of Rose Smelling Planets"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 5,
                            Title = "Two Orange Cars"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 25,
                            Title = "An army of Green Leopards"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 33,
                            Title = "Fifteen Large Planets"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 12,
                            Title = "An army of Rose Smelling Houses"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 14,
                            Title = "A herd of Purple Leopards"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 12,
                            Title = "An army of Rose Smelling Planets"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 32,
                            Title = "Fifteen Purple Flowers"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 19,
                            Title = "The Large Planets"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 37,
                            Title = "A herd of Purple Leopards"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 29,
                            Title = "Several Microscopic Cars"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 22,
                            Title = "A bunch of Orange Flowers"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 26,
                            Title = "Fifteen Microscopic Flowers"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 29,
                            Title = "The Orange Houses"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Book", b =>
                {
                    b.HasOne("exercise.webapi.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("exercise.webapi.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
