using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class RebuildDatabase : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    first_name = table.Column<string>(type: "text", nullable: false),
                    last_name = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "Publishers",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Publishers", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "Books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    author_id = table.Column<int>(type: "integer", nullable: false),
                    publisher_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Books", x => x.id);
                    table.ForeignKey(
                        name: "FK_Books_Authors_author_id",
                        column: x => x.author_id,
                        principalTable: "Authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Books_Publishers_publisher_id",
                        column: x => x.publisher_id,
                        principalTable: "Publishers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "id", "email", "first_name", "last_name" },
                values: new object[,]
                {
                    { 1, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 2, "audrey.winslet@theworld.ca", "Audrey", "Winslet" },
                    { 3, "jimi.winslet@gov.ru", "Jimi", "Winslet" },
                    { 4, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 5, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 6, "jimi.winslet@gov.ru", "Jimi", "Winslet" },
                    { 7, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 8, "elvis.trump@bbc.co.uk", "Elvis", "Trump" },
                    { 9, "barack.presley@bbc.co.uk", "Barack", "Presley" },
                    { 10, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 11, "mick.winfrey@tesla.com", "Mick", "Winfrey" },
                    { 12, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 13, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 14, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 15, "elvis.hendrix@gov.us", "Elvis", "Hendrix" },
                    { 16, "audrey.middleton@tesla.com", "Audrey", "Middleton" },
                    { 17, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 18, "jimi.jagger@nasa.org.us", "Jimi", "Jagger" },
                    { 19, "kate.hendrix@theworld.ca", "Kate", "Hendrix" },
                    { 20, "donald.winfrey@theworld.ca", "Donald", "Winfrey" },
                    { 21, "oprah.presley@gov.us", "Oprah", "Presley" },
                    { 22, "donald.winslet@theworld.ca", "Donald", "Winslet" },
                    { 23, "audrey.trump@something.com", "Audrey", "Trump" },
                    { 24, "donald.presley@bbc.co.uk", "Donald", "Presley" },
                    { 25, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 26, "mick.middleton@nasa.org.us", "Mick", "Middleton" },
                    { 27, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 28, "kate.trump@gov.us", "Kate", "Trump" },
                    { 29, "elvis.middleton@gov.gr", "Elvis", "Middleton" },
                    { 30, "mick.middleton@gov.gr", "Mick", "Middleton" },
                    { 31, "audrey.jagger@nasa.org.us", "Audrey", "Jagger" },
                    { 32, "donald.windsor@tesla.com", "Donald", "Windsor" },
                    { 33, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 34, "oprah.hepburn@theworld.ca", "Oprah", "Hepburn" },
                    { 35, "audrey.hepburn@gov.gr", "Audrey", "Hepburn" },
                    { 36, "oprah.winslet@something.com", "Oprah", "Winslet" },
                    { 37, "kate.obama@something.com", "Kate", "Obama" },
                    { 38, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 39, "barack.jagger@gov.ru", "Barack", "Jagger" },
                    { 40, "elvis.presley@gov.us", "Elvis", "Presley" },
                    { 41, "kate.presley@gov.us", "Kate", "Presley" },
                    { 42, "elvis.winslet@tesla.com", "Elvis", "Winslet" },
                    { 43, "mick.middleton@nasa.org.us", "Mick", "Middleton" },
                    { 44, "barack.hepburn@tesla.com", "Barack", "Hepburn" },
                    { 45, "audrey.middleton@tesla.com", "Audrey", "Middleton" },
                    { 46, "mick.hepburn@theworld.ca", "Mick", "Hepburn" },
                    { 47, "charles.winfrey@nasa.org.us", "Charles", "Winfrey" },
                    { 48, "barack.obama@theworld.ca", "Barack", "Obama" },
                    { 49, "jimi.winfrey@bbc.co.uk", "Jimi", "Winfrey" },
                    { 50, "donald.hepburn@gov.nl", "Donald", "Hepburn" },
                    { 51, "barack.obama@tesla.com", "Barack", "Obama" },
                    { 52, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 53, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 54, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 55, "kate.winfrey@bbc.co.uk", "Kate", "Winfrey" },
                    { 56, "oprah.hendrix@bbc.co.uk", "Oprah", "Hendrix" },
                    { 57, "kate.winslet@gov.us", "Kate", "Winslet" },
                    { 58, "oprah.trump@theworld.ca", "Oprah", "Trump" },
                    { 59, "kate.jagger@gov.us", "Kate", "Jagger" },
                    { 60, "kate.hendrix@bbc.co.uk", "Kate", "Hendrix" },
                    { 61, "barack.presley@tesla.com", "Barack", "Presley" },
                    { 62, "donald.obama@gov.gr", "Donald", "Obama" },
                    { 63, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 64, "mick.hendrix@gov.nl", "Mick", "Hendrix" },
                    { 65, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 66, "charles.winfrey@nasa.org.us", "Charles", "Winfrey" },
                    { 67, "kate.presley@gov.nl", "Kate", "Presley" },
                    { 68, "audrey.obama@something.com", "Audrey", "Obama" },
                    { 69, "oprah.obama@something.com", "Oprah", "Obama" },
                    { 70, "barack.obama@tesla.com", "Barack", "Obama" },
                    { 71, "elvis.windsor@gov.us", "Elvis", "Windsor" },
                    { 72, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 73, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 74, "mick.winfrey@bbc.co.uk", "Mick", "Winfrey" },
                    { 75, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 76, "charles.hepburn@theworld.ca", "Charles", "Hepburn" },
                    { 77, "jimi.winslet@gov.us", "Jimi", "Winslet" },
                    { 78, "elvis.hendrix@something.com", "Elvis", "Hendrix" },
                    { 79, "mick.presley@gov.nl", "Mick", "Presley" },
                    { 80, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 81, "donald.winfrey@gov.gr", "Donald", "Winfrey" },
                    { 82, "jimi.presley@nasa.org.us", "Jimi", "Presley" },
                    { 83, "audrey.middleton@nasa.org.us", "Audrey", "Middleton" },
                    { 84, "elvis.middleton@gov.gr", "Elvis", "Middleton" },
                    { 85, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 86, "jimi.jagger@nasa.org.us", "Jimi", "Jagger" },
                    { 87, "elvis.middleton@gov.us", "Elvis", "Middleton" },
                    { 88, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 89, "audrey.windsor@gov.us", "Audrey", "Windsor" },
                    { 90, "jimi.winfrey@theworld.ca", "Jimi", "Winfrey" },
                    { 91, "elvis.trump@google.com", "Elvis", "Trump" },
                    { 92, "donald.hepburn@gov.ru", "Donald", "Hepburn" },
                    { 93, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 94, "barack.trump@something.com", "Barack", "Trump" },
                    { 95, "barack.hendrix@google.com", "Barack", "Hendrix" },
                    { 96, "kate.trump@something.com", "Kate", "Trump" },
                    { 97, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 98, "kate.obama@something.com", "Kate", "Obama" },
                    { 99, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 100, "donald.obama@gov.nl", "Donald", "Obama" },
                    { 101, "charles.middleton@google.com", "Charles", "Middleton" },
                    { 102, "mick.trump@something.com", "Mick", "Trump" },
                    { 103, "oprah.winslet@google.com", "Oprah", "Winslet" },
                    { 104, "mick.jagger@google.com", "Mick", "Jagger" },
                    { 105, "elvis.hendrix@tesla.com", "Elvis", "Hendrix" },
                    { 106, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 107, "barack.obama@something.com", "Barack", "Obama" },
                    { 108, "oprah.hendrix@google.com", "Oprah", "Hendrix" },
                    { 109, "donald.winslet@gov.ru", "Donald", "Winslet" },
                    { 110, "charles.windsor@gov.gr", "Charles", "Windsor" },
                    { 111, "barack.trump@nasa.org.us", "Barack", "Trump" },
                    { 112, "mick.middleton@bbc.co.uk", "Mick", "Middleton" },
                    { 113, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 114, "jimi.windsor@gov.ru", "Jimi", "Windsor" },
                    { 115, "jimi.hepburn@gov.gr", "Jimi", "Hepburn" },
                    { 116, "mick.winslet@gov.ru", "Mick", "Winslet" },
                    { 117, "elvis.jagger@gov.gr", "Elvis", "Jagger" },
                    { 118, "elvis.obama@nasa.org.us", "Elvis", "Obama" },
                    { 119, "barack.hepburn@gov.ru", "Barack", "Hepburn" },
                    { 120, "audrey.middleton@gov.gr", "Audrey", "Middleton" },
                    { 121, "oprah.windsor@bbc.co.uk", "Oprah", "Windsor" },
                    { 122, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 123, "charles.obama@nasa.org.us", "Charles", "Obama" },
                    { 124, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 125, "kate.winslet@something.com", "Kate", "Winslet" },
                    { 126, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 127, "charles.middleton@gov.ru", "Charles", "Middleton" },
                    { 128, "charles.winslet@gov.gr", "Charles", "Winslet" },
                    { 129, "jimi.middleton@bbc.co.uk", "Jimi", "Middleton" },
                    { 130, "mick.middleton@nasa.org.us", "Mick", "Middleton" },
                    { 131, "donald.presley@google.com", "Donald", "Presley" },
                    { 132, "donald.windsor@bbc.co.uk", "Donald", "Windsor" },
                    { 133, "audrey.obama@tesla.com", "Audrey", "Obama" },
                    { 134, "audrey.presley@theworld.ca", "Audrey", "Presley" },
                    { 135, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 136, "charles.winfrey@gov.nl", "Charles", "Winfrey" },
                    { 137, "barack.jagger@gov.nl", "Barack", "Jagger" },
                    { 138, "charles.windsor@bbc.co.uk", "Charles", "Windsor" },
                    { 139, "charles.windsor@tesla.com", "Charles", "Windsor" },
                    { 140, "charles.presley@gov.us", "Charles", "Presley" },
                    { 141, "audrey.hepburn@nasa.org.us", "Audrey", "Hepburn" },
                    { 142, "mick.hepburn@something.com", "Mick", "Hepburn" },
                    { 143, "mick.winfrey@gov.us", "Mick", "Winfrey" },
                    { 144, "audrey.hepburn@theworld.ca", "Audrey", "Hepburn" },
                    { 145, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 146, "donald.hepburn@gov.gr", "Donald", "Hepburn" },
                    { 147, "donald.hepburn@theworld.ca", "Donald", "Hepburn" },
                    { 148, "elvis.jagger@gov.gr", "Elvis", "Jagger" },
                    { 149, "jimi.hendrix@gov.gr", "Jimi", "Hendrix" },
                    { 150, "charles.presley@gov.gr", "Charles", "Presley" },
                    { 151, "elvis.winfrey@gov.us", "Elvis", "Winfrey" },
                    { 152, "mick.winfrey@gov.nl", "Mick", "Winfrey" },
                    { 153, "kate.obama@google.com", "Kate", "Obama" },
                    { 154, "mick.hendrix@something.com", "Mick", "Hendrix" },
                    { 155, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 156, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 157, "donald.windsor@google.com", "Donald", "Windsor" },
                    { 158, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 159, "audrey.obama@nasa.org.us", "Audrey", "Obama" },
                    { 160, "charles.winslet@nasa.org.us", "Charles", "Winslet" },
                    { 161, "donald.hendrix@gov.gr", "Donald", "Hendrix" },
                    { 162, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 163, "mick.obama@bbc.co.uk", "Mick", "Obama" },
                    { 164, "elvis.jagger@google.com", "Elvis", "Jagger" },
                    { 165, "mick.presley@something.com", "Mick", "Presley" },
                    { 166, "charles.winslet@gov.nl", "Charles", "Winslet" },
                    { 167, "elvis.trump@gov.nl", "Elvis", "Trump" },
                    { 168, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 169, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 170, "mick.trump@gov.us", "Mick", "Trump" },
                    { 171, "jimi.winfrey@gov.nl", "Jimi", "Winfrey" },
                    { 172, "barack.obama@gov.nl", "Barack", "Obama" },
                    { 173, "jimi.presley@google.com", "Jimi", "Presley" },
                    { 174, "mick.winfrey@nasa.org.us", "Mick", "Winfrey" },
                    { 175, "oprah.obama@theworld.ca", "Oprah", "Obama" },
                    { 176, "charles.obama@tesla.com", "Charles", "Obama" },
                    { 177, "jimi.presley@bbc.co.uk", "Jimi", "Presley" },
                    { 178, "oprah.jagger@nasa.org.us", "Oprah", "Jagger" },
                    { 179, "jimi.windsor@nasa.org.us", "Jimi", "Windsor" },
                    { 180, "jimi.presley@gov.ru", "Jimi", "Presley" },
                    { 181, "mick.jagger@gov.us", "Mick", "Jagger" },
                    { 182, "audrey.winslet@gov.gr", "Audrey", "Winslet" },
                    { 183, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 184, "audrey.obama@bbc.co.uk", "Audrey", "Obama" },
                    { 185, "oprah.presley@gov.gr", "Oprah", "Presley" },
                    { 186, "oprah.hepburn@tesla.com", "Oprah", "Hepburn" },
                    { 187, "donald.presley@gov.gr", "Donald", "Presley" },
                    { 188, "barack.obama@bbc.co.uk", "Barack", "Obama" },
                    { 189, "oprah.obama@gov.ru", "Oprah", "Obama" },
                    { 190, "elvis.jagger@google.com", "Elvis", "Jagger" },
                    { 191, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 192, "oprah.hepburn@something.com", "Oprah", "Hepburn" },
                    { 193, "mick.middleton@theworld.ca", "Mick", "Middleton" },
                    { 194, "barack.presley@nasa.org.us", "Barack", "Presley" },
                    { 195, "charles.middleton@gov.nl", "Charles", "Middleton" },
                    { 196, "jimi.hepburn@something.com", "Jimi", "Hepburn" },
                    { 197, "oprah.trump@gov.us", "Oprah", "Trump" },
                    { 198, "elvis.middleton@gov.nl", "Elvis", "Middleton" },
                    { 199, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 200, "kate.winfrey@nasa.org.us", "Kate", "Winfrey" },
                    { 201, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 202, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 203, "charles.trump@gov.gr", "Charles", "Trump" },
                    { 204, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 205, "barack.windsor@something.com", "Barack", "Windsor" },
                    { 206, "barack.winfrey@gov.us", "Barack", "Winfrey" },
                    { 207, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 208, "kate.obama@something.com", "Kate", "Obama" },
                    { 209, "mick.obama@something.com", "Mick", "Obama" },
                    { 210, "audrey.winslet@gov.gr", "Audrey", "Winslet" },
                    { 211, "charles.hepburn@gov.gr", "Charles", "Hepburn" },
                    { 212, "audrey.winslet@gov.us", "Audrey", "Winslet" },
                    { 213, "oprah.presley@gov.us", "Oprah", "Presley" },
                    { 214, "jimi.winfrey@google.com", "Jimi", "Winfrey" },
                    { 215, "charles.obama@gov.nl", "Charles", "Obama" },
                    { 216, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 217, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 218, "audrey.windsor@theworld.ca", "Audrey", "Windsor" },
                    { 219, "charles.windsor@theworld.ca", "Charles", "Windsor" },
                    { 220, "mick.middleton@gov.us", "Mick", "Middleton" },
                    { 221, "audrey.obama@bbc.co.uk", "Audrey", "Obama" },
                    { 222, "oprah.trump@gov.gr", "Oprah", "Trump" },
                    { 223, "oprah.presley@something.com", "Oprah", "Presley" },
                    { 224, "audrey.winslet@gov.us", "Audrey", "Winslet" },
                    { 225, "kate.hepburn@gov.us", "Kate", "Hepburn" },
                    { 226, "charles.winfrey@gov.nl", "Charles", "Winfrey" },
                    { 227, "barack.obama@tesla.com", "Barack", "Obama" },
                    { 228, "barack.hendrix@bbc.co.uk", "Barack", "Hendrix" },
                    { 229, "mick.winslet@gov.us", "Mick", "Winslet" },
                    { 230, "charles.hendrix@tesla.com", "Charles", "Hendrix" },
                    { 231, "mick.winfrey@gov.gr", "Mick", "Winfrey" },
                    { 232, "kate.hepburn@gov.us", "Kate", "Hepburn" },
                    { 233, "audrey.trump@nasa.org.us", "Audrey", "Trump" },
                    { 234, "mick.winslet@gov.gr", "Mick", "Winslet" },
                    { 235, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 236, "audrey.winfrey@gov.us", "Audrey", "Winfrey" },
                    { 237, "audrey.hendrix@bbc.co.uk", "Audrey", "Hendrix" },
                    { 238, "elvis.winfrey@gov.gr", "Elvis", "Winfrey" },
                    { 239, "mick.hendrix@something.com", "Mick", "Hendrix" },
                    { 240, "kate.trump@tesla.com", "Kate", "Trump" },
                    { 241, "barack.windsor@gov.gr", "Barack", "Windsor" },
                    { 242, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 243, "jimi.winslet@gov.gr", "Jimi", "Winslet" },
                    { 244, "elvis.trump@something.com", "Elvis", "Trump" },
                    { 245, "barack.windsor@gov.us", "Barack", "Windsor" },
                    { 246, "kate.presley@gov.nl", "Kate", "Presley" },
                    { 247, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 248, "barack.trump@gov.gr", "Barack", "Trump" },
                    { 249, "oprah.trump@bbc.co.uk", "Oprah", "Trump" }
                });

            migrationBuilder.InsertData(
                table: "Publishers",
                columns: new[] { "id", "name" },
                values: new object[,]
                {
                    { 1, "Penguin" },
                    { 2, "Random House" },
                    { 3, "Harper Collins" },
                    { 4, "Simon & Schuster" },
                    { 5, "Hachette" },
                    { 6, "Macmillan" },
                    { 7, "Bloomsbury" },
                    { 8, "Scholastic" },
                    { 9, "Pearson" },
                    { 10, "Holtzbrinck" }
                });

            migrationBuilder.InsertData(
                table: "Books",
                columns: new[] { "id", "author_id", "publisher_id", "title" },
                values: new object[,]
                {
                    { 1, 125, 3, "An army of Microscopic Houses" },
                    { 2, 6, 5, "A herd of Microscopic Leopards" },
                    { 3, 245, 7, "Several Purple Houses" },
                    { 4, 221, 1, "Two Orange Leopards" },
                    { 5, 49, 8, "A bunch of Bitter Houses" },
                    { 6, 196, 7, "Fifteen Transparent Flowers" },
                    { 7, 109, 2, "A herd of Rose Smelling Flowers" },
                    { 8, 100, 2, "Fifteen Green Planets" },
                    { 9, 105, 4, "A herd of Green Flowers" },
                    { 10, 132, 5, "Fifteen Rose Smelling Cars" },
                    { 11, 225, 9, "A herd of Purple Flowers" },
                    { 12, 144, 8, "A bunch of Large Flowers" },
                    { 13, 50, 8, "A herd of Bitter Buildings" },
                    { 14, 31, 6, "A bunch of Transparent Buildings" },
                    { 15, 201, 2, "Two Bitter Leopards" },
                    { 16, 248, 1, "A herd of Bitter Leopards" },
                    { 17, 164, 1, "Several Large Planets" },
                    { 18, 213, 3, "The Large Cars" },
                    { 19, 144, 8, "The Orange Flowers" },
                    { 20, 183, 2, "The Purple Buildings" },
                    { 21, 142, 3, "An army of Bitter Flowers" },
                    { 22, 132, 4, "Two Large Planets" },
                    { 23, 167, 4, "Two Purple Flowers" },
                    { 24, 200, 2, "The Rose Smelling Cars" },
                    { 25, 7, 3, "A herd of Large Buildings" },
                    { 26, 163, 8, "Fifteen Microscopic Planets" },
                    { 27, 127, 10, "Two Green Planets" },
                    { 28, 32, 5, "An army of Bitter Planets" },
                    { 29, 239, 7, "A herd of Rose Smelling Houses" },
                    { 30, 4, 2, "Two Rose Smelling Buildings" },
                    { 31, 110, 3, "The Large Cars" },
                    { 32, 145, 8, "The Microscopic Leopards" },
                    { 33, 21, 4, "An army of Bitter Cars" },
                    { 34, 10, 7, "Fifteen Rose Smelling Planets" },
                    { 35, 189, 7, "A bunch of Rose Smelling Buildings" },
                    { 36, 72, 5, "An army of Transparent Flowers" },
                    { 37, 11, 1, "The Transparent Flowers" },
                    { 38, 78, 6, "An army of Green Flowers" },
                    { 39, 243, 8, "The Microscopic Planets" },
                    { 40, 24, 9, "Fifteen Bitter Buildings" },
                    { 41, 82, 4, "Several Bitter Houses" },
                    { 42, 54, 4, "Fifteen Large Planets" },
                    { 43, 57, 2, "Fifteen Large Planets" },
                    { 44, 188, 3, "Fifteen Large Cars" },
                    { 45, 213, 1, "A herd of Microscopic Planets" },
                    { 46, 5, 5, "Fifteen Microscopic Planets" },
                    { 47, 54, 1, "Fifteen Orange Buildings" },
                    { 48, 100, 6, "Two Rose Smelling Houses" },
                    { 49, 51, 8, "A herd of Orange Leopards" },
                    { 50, 137, 9, "A bunch of Transparent Flowers" },
                    { 51, 77, 10, "A bunch of Rose Smelling Flowers" },
                    { 52, 68, 10, "The Transparent Buildings" },
                    { 53, 88, 7, "A herd of Microscopic Cars" },
                    { 54, 162, 3, "Fifteen Purple Cars" },
                    { 55, 134, 10, "An army of Orange Planets" },
                    { 56, 195, 8, "The Microscopic Buildings" },
                    { 57, 45, 4, "An army of Green Flowers" },
                    { 58, 112, 4, "A herd of Purple Leopards" },
                    { 59, 149, 10, "Two Bitter Buildings" },
                    { 60, 206, 8, "The Transparent Leopards" },
                    { 61, 249, 5, "The Green Flowers" },
                    { 62, 178, 4, "Two Transparent Planets" },
                    { 63, 48, 9, "Several Rose Smelling Cars" },
                    { 64, 168, 7, "A bunch of Green Planets" },
                    { 65, 2, 1, "A bunch of Large Cars" },
                    { 66, 127, 1, "An army of Orange Cars" },
                    { 67, 59, 8, "Two Purple Leopards" },
                    { 68, 74, 4, "An army of Bitter Cars" },
                    { 69, 117, 10, "Fifteen Green Cars" },
                    { 70, 15, 9, "An army of Green Leopards" },
                    { 71, 53, 2, "Fifteen Rose Smelling Flowers" },
                    { 72, 166, 2, "Two Large Flowers" },
                    { 73, 223, 4, "The Rose Smelling Buildings" },
                    { 74, 12, 1, "An army of Rose Smelling Leopards" },
                    { 75, 154, 5, "A bunch of Transparent Buildings" },
                    { 76, 138, 1, "An army of Large Flowers" },
                    { 77, 154, 8, "An army of Microscopic Flowers" },
                    { 78, 237, 2, "Fifteen Transparent Houses" },
                    { 79, 70, 6, "Fifteen Microscopic Planets" },
                    { 80, 97, 2, "A bunch of Transparent Planets" },
                    { 81, 47, 5, "Two Green Planets" },
                    { 82, 19, 10, "Fifteen Purple Buildings" },
                    { 83, 23, 1, "Fifteen Purple Buildings" },
                    { 84, 41, 4, "Several Rose Smelling Buildings" },
                    { 85, 243, 2, "Fifteen Transparent Flowers" },
                    { 86, 28, 3, "Fifteen Green Leopards" },
                    { 87, 164, 1, "Several Green Buildings" },
                    { 88, 108, 8, "An army of Large Planets" },
                    { 89, 116, 6, "The Green Cars" },
                    { 90, 35, 9, "Fifteen Rose Smelling Planets" },
                    { 91, 107, 4, "Several Transparent Planets" },
                    { 92, 17, 8, "An army of Purple Houses" },
                    { 93, 125, 6, "Two Green Planets" },
                    { 94, 84, 5, "Two Purple Cars" },
                    { 95, 199, 1, "An army of Microscopic Buildings" },
                    { 96, 196, 10, "Several Green Houses" },
                    { 97, 221, 8, "A bunch of Transparent Leopards" },
                    { 98, 98, 4, "Fifteen Bitter Houses" },
                    { 99, 54, 4, "An army of Rose Smelling Flowers" },
                    { 100, 118, 9, "An army of Large Cars" },
                    { 101, 56, 2, "A bunch of Rose Smelling Cars" },
                    { 102, 231, 5, "Two Orange Planets" },
                    { 103, 107, 7, "The Rose Smelling Cars" },
                    { 104, 217, 2, "Two Bitter Buildings" },
                    { 105, 229, 10, "The Green Buildings" },
                    { 106, 83, 4, "Fifteen Transparent Leopards" },
                    { 107, 184, 4, "A bunch of Green Leopards" },
                    { 108, 31, 7, "The Green Buildings" },
                    { 109, 120, 6, "Two Orange Leopards" },
                    { 110, 28, 6, "A herd of Rose Smelling Flowers" },
                    { 111, 13, 9, "Several Rose Smelling Flowers" },
                    { 112, 43, 7, "An army of Bitter Cars" },
                    { 113, 23, 9, "A bunch of Green Flowers" },
                    { 114, 132, 5, "Several Large Flowers" },
                    { 115, 28, 7, "A bunch of Large Houses" },
                    { 116, 25, 10, "A bunch of Bitter Buildings" },
                    { 117, 17, 6, "The Purple Houses" },
                    { 118, 208, 9, "Several Bitter Leopards" },
                    { 119, 44, 3, "An army of Rose Smelling Cars" },
                    { 120, 89, 9, "Fifteen Bitter Buildings" },
                    { 121, 224, 2, "The Green Leopards" },
                    { 122, 209, 1, "The Transparent Houses" },
                    { 123, 94, 1, "Several Transparent Flowers" },
                    { 124, 62, 10, "The Orange Houses" },
                    { 125, 20, 10, "Fifteen Purple Cars" },
                    { 126, 179, 4, "A bunch of Rose Smelling Houses" },
                    { 127, 120, 8, "Two Bitter Cars" },
                    { 128, 181, 4, "Fifteen Microscopic Planets" },
                    { 129, 131, 1, "A herd of Purple Flowers" },
                    { 130, 168, 5, "Several Purple Leopards" },
                    { 131, 98, 5, "Two Purple Houses" },
                    { 132, 129, 10, "A herd of Transparent Planets" },
                    { 133, 176, 8, "Several Orange Planets" },
                    { 134, 79, 1, "Several Transparent Leopards" },
                    { 135, 103, 9, "A bunch of Rose Smelling Flowers" },
                    { 136, 41, 4, "An army of Green Flowers" },
                    { 137, 194, 3, "A herd of Green Planets" },
                    { 138, 188, 7, "The Large Flowers" },
                    { 139, 17, 5, "A bunch of Microscopic Flowers" },
                    { 140, 232, 10, "The Bitter Flowers" },
                    { 141, 118, 3, "Two Purple Buildings" },
                    { 142, 156, 2, "The Bitter Flowers" },
                    { 143, 154, 5, "An army of Transparent Houses" },
                    { 144, 127, 9, "An army of Orange Leopards" },
                    { 145, 81, 2, "An army of Green Planets" },
                    { 146, 19, 4, "Two Rose Smelling Planets" },
                    { 147, 136, 10, "A bunch of Orange Buildings" },
                    { 148, 103, 1, "Two Purple Planets" },
                    { 149, 157, 5, "Two Transparent Leopards" },
                    { 150, 62, 10, "A herd of Transparent Cars" },
                    { 151, 120, 10, "Two Green Planets" },
                    { 152, 203, 9, "A herd of Green Houses" },
                    { 153, 157, 3, "The Transparent Planets" },
                    { 154, 150, 1, "A bunch of Bitter Houses" },
                    { 155, 219, 2, "A bunch of Rose Smelling Cars" },
                    { 156, 95, 6, "An army of Green Planets" },
                    { 157, 15, 9, "An army of Bitter Buildings" },
                    { 158, 244, 3, "An army of Transparent Buildings" },
                    { 159, 135, 7, "Two Bitter Flowers" },
                    { 160, 102, 6, "An army of Transparent Leopards" },
                    { 161, 2, 5, "The Microscopic Buildings" },
                    { 162, 237, 7, "An army of Microscopic Cars" },
                    { 163, 76, 2, "A bunch of Green Flowers" },
                    { 164, 160, 2, "Fifteen Bitter Planets" },
                    { 165, 239, 6, "An army of Purple Houses" },
                    { 166, 232, 10, "Several Transparent Planets" },
                    { 167, 66, 2, "Several Bitter Leopards" },
                    { 168, 96, 5, "A herd of Large Flowers" },
                    { 169, 166, 8, "A bunch of Large Leopards" },
                    { 170, 167, 9, "Two Purple Cars" },
                    { 171, 186, 5, "An army of Microscopic Planets" },
                    { 172, 202, 6, "A bunch of Microscopic Leopards" },
                    { 173, 193, 7, "A bunch of Rose Smelling Houses" },
                    { 174, 110, 8, "Several Purple Leopards" },
                    { 175, 116, 1, "A herd of Purple Leopards" },
                    { 176, 3, 4, "The Microscopic Cars" },
                    { 177, 84, 6, "A bunch of Orange Flowers" },
                    { 178, 134, 7, "Fifteen Rose Smelling Planets" },
                    { 179, 30, 4, "The Green Planets" },
                    { 180, 210, 7, "Two Transparent Planets" },
                    { 181, 41, 5, "Fifteen Large Buildings" },
                    { 182, 223, 3, "Fifteen Green Leopards" },
                    { 183, 211, 8, "A bunch of Orange Houses" },
                    { 184, 94, 8, "The Bitter Planets" },
                    { 185, 100, 8, "An army of Transparent Cars" },
                    { 186, 248, 8, "A herd of Transparent Flowers" },
                    { 187, 139, 6, "Several Large Buildings" },
                    { 188, 243, 5, "A bunch of Orange Houses" },
                    { 189, 247, 6, "Several Green Planets" },
                    { 190, 209, 2, "An army of Green Planets" },
                    { 191, 183, 3, "An army of Large Buildings" },
                    { 192, 41, 5, "Several Green Houses" },
                    { 193, 136, 3, "The Rose Smelling Leopards" },
                    { 194, 46, 5, "Fifteen Rose Smelling Planets" },
                    { 195, 168, 2, "Several Purple Leopards" },
                    { 196, 144, 2, "A herd of Transparent Flowers" },
                    { 197, 202, 8, "A herd of Green Buildings" },
                    { 198, 61, 1, "A bunch of Large Cars" },
                    { 199, 179, 6, "A bunch of Microscopic Houses" },
                    { 200, 71, 6, "Fifteen Purple Houses" },
                    { 201, 13, 1, "A bunch of Purple Houses" },
                    { 202, 61, 8, "Fifteen Microscopic Flowers" },
                    { 203, 229, 2, "Several Rose Smelling Flowers" },
                    { 204, 61, 8, "The Microscopic Leopards" },
                    { 205, 105, 2, "The Green Planets" },
                    { 206, 156, 6, "A bunch of Transparent Cars" },
                    { 207, 97, 3, "An army of Rose Smelling Flowers" },
                    { 208, 84, 10, "The Green Cars" },
                    { 209, 16, 6, "The Rose Smelling Planets" },
                    { 210, 179, 7, "A herd of Rose Smelling Buildings" },
                    { 211, 214, 10, "A herd of Bitter Flowers" },
                    { 212, 220, 9, "Several Rose Smelling Leopards" },
                    { 213, 200, 6, "Two Purple Houses" },
                    { 214, 138, 1, "A bunch of Purple Cars" },
                    { 215, 209, 6, "The Purple Buildings" },
                    { 216, 31, 5, "A bunch of Purple Cars" },
                    { 217, 227, 5, "Several Microscopic Buildings" },
                    { 218, 7, 7, "Several Transparent Leopards" },
                    { 219, 9, 9, "A bunch of Purple Planets" },
                    { 220, 198, 4, "The Microscopic Houses" },
                    { 221, 24, 7, "Several Bitter Leopards" },
                    { 222, 206, 6, "A bunch of Large Leopards" },
                    { 223, 17, 10, "An army of Orange Buildings" },
                    { 224, 112, 4, "Fifteen Microscopic Cars" },
                    { 225, 37, 10, "Two Transparent Cars" },
                    { 226, 80, 8, "A bunch of Orange Leopards" },
                    { 227, 136, 2, "A bunch of Microscopic Planets" },
                    { 228, 207, 3, "Two Orange Leopards" },
                    { 229, 21, 1, "A herd of Microscopic Flowers" },
                    { 230, 109, 3, "Two Green Houses" },
                    { 231, 87, 6, "Two Rose Smelling Planets" },
                    { 232, 77, 9, "Several Bitter Buildings" },
                    { 233, 80, 2, "A bunch of Green Cars" },
                    { 234, 198, 9, "Two Purple Flowers" },
                    { 235, 24, 7, "Fifteen Transparent Planets" },
                    { 236, 98, 3, "Fifteen Green Houses" },
                    { 237, 26, 4, "Several Large Flowers" },
                    { 238, 47, 7, "Several Orange Buildings" },
                    { 239, 133, 5, "An army of Bitter Flowers" },
                    { 240, 190, 7, "A herd of Purple Houses" },
                    { 241, 9, 4, "An army of Bitter Buildings" },
                    { 242, 62, 4, "A herd of Purple Houses" },
                    { 243, 176, 2, "A herd of Green Planets" },
                    { 244, 61, 8, "Two Bitter Houses" },
                    { 245, 10, 4, "An army of Orange Cars" },
                    { 246, 139, 6, "Several Bitter Planets" },
                    { 247, 22, 8, "The Rose Smelling Leopards" },
                    { 248, 187, 6, "A bunch of Purple Houses" },
                    { 249, 109, 10, "An army of Rose Smelling Buildings" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Books_author_id",
                table: "Books",
                column: "author_id");

            migrationBuilder.CreateIndex(
                name: "IX_Books_publisher_id",
                table: "Books",
                column: "publisher_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Books");

            migrationBuilder.DropTable(
                name: "Authors");

            migrationBuilder.DropTable(
                name: "Publishers");
        }
    }
}
