using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class one : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Publishers",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Publishers", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    first_name = table.Column<string>(type: "text", nullable: false),
                    last_name = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false),
                    PublisherId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_Publishers_PublisherId",
                        column: x => x.PublisherId,
                        principalTable: "Publishers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_books_authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Publishers",
                columns: new[] { "id", "name" },
                values: new object[,]
                {
                    { 1, "Penguin" },
                    { 2, "Random House" },
                    { 3, "Harper Collins" },
                    { 4, "Simon & Schuster" },
                    { 5, "Hachette" },
                    { 6, "Macmillan" },
                    { 7, "Bloomsbury" },
                    { 8, "Pearson" },
                    { 9, "Scholastic" }
                });

            migrationBuilder.InsertData(
                table: "authors",
                columns: new[] { "id", "email", "first_name", "last_name" },
                values: new object[,]
                {
                    { 1, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 2, "oprah.obama@tesla.com", "Oprah", "Obama" },
                    { 3, "donald.obama@theworld.ca", "Donald", "Obama" },
                    { 4, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 5, "elvis.winslet@nasa.org.us", "Elvis", "Winslet" },
                    { 6, "audrey.windsor@theworld.ca", "Audrey", "Windsor" },
                    { 7, "donald.winslet@google.com", "Donald", "Winslet" },
                    { 8, "jimi.hendrix@bbc.co.uk", "Jimi", "Hendrix" },
                    { 9, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 10, "charles.obama@gov.ru", "Charles", "Obama" },
                    { 11, "donald.windsor@tesla.com", "Donald", "Windsor" },
                    { 12, "elvis.hendrix@gov.ru", "Elvis", "Hendrix" },
                    { 13, "mick.trump@gov.nl", "Mick", "Trump" },
                    { 14, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 15, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 16, "barack.hepburn@gov.gr", "Barack", "Hepburn" },
                    { 17, "mick.windsor@gov.gr", "Mick", "Windsor" },
                    { 18, "audrey.middleton@gov.ru", "Audrey", "Middleton" },
                    { 19, "barack.jagger@gov.us", "Barack", "Jagger" },
                    { 20, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 21, "kate.winfrey@google.com", "Kate", "Winfrey" },
                    { 22, "mick.middleton@theworld.ca", "Mick", "Middleton" },
                    { 23, "charles.middleton@nasa.org.us", "Charles", "Middleton" },
                    { 24, "oprah.jagger@gov.gr", "Oprah", "Jagger" },
                    { 25, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 26, "kate.winslet@google.com", "Kate", "Winslet" },
                    { 27, "donald.presley@gov.gr", "Donald", "Presley" },
                    { 28, "donald.jagger@gov.gr", "Donald", "Jagger" },
                    { 29, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 30, "oprah.obama@bbc.co.uk", "Oprah", "Obama" },
                    { 31, "donald.jagger@something.com", "Donald", "Jagger" },
                    { 32, "audrey.hendrix@gov.ru", "Audrey", "Hendrix" },
                    { 33, "kate.winslet@theworld.ca", "Kate", "Winslet" },
                    { 34, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 35, "oprah.presley@bbc.co.uk", "Oprah", "Presley" },
                    { 36, "mick.windsor@gov.nl", "Mick", "Windsor" },
                    { 37, "jimi.middleton@bbc.co.uk", "Jimi", "Middleton" },
                    { 38, "kate.hendrix@bbc.co.uk", "Kate", "Hendrix" },
                    { 39, "oprah.hendrix@nasa.org.us", "Oprah", "Hendrix" },
                    { 40, "oprah.winslet@nasa.org.us", "Oprah", "Winslet" },
                    { 41, "mick.jagger@gov.us", "Mick", "Jagger" },
                    { 42, "mick.winfrey@bbc.co.uk", "Mick", "Winfrey" },
                    { 43, "elvis.trump@bbc.co.uk", "Elvis", "Trump" },
                    { 44, "donald.hepburn@nasa.org.us", "Donald", "Hepburn" },
                    { 45, "donald.hepburn@gov.nl", "Donald", "Hepburn" },
                    { 46, "donald.jagger@bbc.co.uk", "Donald", "Jagger" },
                    { 47, "jimi.obama@gov.ru", "Jimi", "Obama" },
                    { 48, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 49, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 50, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 51, "elvis.jagger@gov.ru", "Elvis", "Jagger" },
                    { 52, "audrey.winslet@tesla.com", "Audrey", "Winslet" },
                    { 53, "elvis.middleton@gov.us", "Elvis", "Middleton" },
                    { 54, "donald.windsor@tesla.com", "Donald", "Windsor" },
                    { 55, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 56, "charles.hendrix@gov.ru", "Charles", "Hendrix" },
                    { 57, "jimi.trump@nasa.org.us", "Jimi", "Trump" },
                    { 58, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 59, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 60, "oprah.trump@gov.ru", "Oprah", "Trump" },
                    { 61, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 62, "jimi.presley@gov.gr", "Jimi", "Presley" },
                    { 63, "mick.windsor@tesla.com", "Mick", "Windsor" },
                    { 64, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 65, "mick.jagger@gov.nl", "Mick", "Jagger" },
                    { 66, "elvis.hendrix@google.com", "Elvis", "Hendrix" },
                    { 67, "audrey.winfrey@gov.ru", "Audrey", "Winfrey" },
                    { 68, "jimi.obama@gov.ru", "Jimi", "Obama" },
                    { 69, "oprah.winfrey@something.com", "Oprah", "Winfrey" },
                    { 70, "charles.obama@gov.ru", "Charles", "Obama" },
                    { 71, "donald.hendrix@gov.gr", "Donald", "Hendrix" },
                    { 72, "kate.jagger@nasa.org.us", "Kate", "Jagger" },
                    { 73, "jimi.middleton@something.com", "Jimi", "Middleton" },
                    { 74, "charles.middleton@something.com", "Charles", "Middleton" },
                    { 75, "jimi.presley@bbc.co.uk", "Jimi", "Presley" },
                    { 76, "kate.presley@tesla.com", "Kate", "Presley" },
                    { 77, "oprah.windsor@gov.gr", "Oprah", "Windsor" },
                    { 78, "mick.winfrey@bbc.co.uk", "Mick", "Winfrey" },
                    { 79, "mick.middleton@gov.gr", "Mick", "Middleton" },
                    { 80, "jimi.winfrey@gov.us", "Jimi", "Winfrey" },
                    { 81, "oprah.trump@bbc.co.uk", "Oprah", "Trump" },
                    { 82, "barack.hendrix@nasa.org.us", "Barack", "Hendrix" },
                    { 83, "mick.hendrix@tesla.com", "Mick", "Hendrix" },
                    { 84, "charles.presley@tesla.com", "Charles", "Presley" },
                    { 85, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 86, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 87, "audrey.winslet@gov.nl", "Audrey", "Winslet" },
                    { 88, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 89, "charles.winslet@bbc.co.uk", "Charles", "Winslet" },
                    { 90, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 91, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 92, "donald.trump@gov.ru", "Donald", "Trump" },
                    { 93, "audrey.winfrey@theworld.ca", "Audrey", "Winfrey" },
                    { 94, "mick.presley@tesla.com", "Mick", "Presley" },
                    { 95, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 96, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 97, "mick.hendrix@gov.us", "Mick", "Hendrix" },
                    { 98, "audrey.hendrix@gov.us", "Audrey", "Hendrix" },
                    { 99, "jimi.hendrix@gov.nl", "Jimi", "Hendrix" },
                    { 100, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 101, "elvis.windsor@gov.gr", "Elvis", "Windsor" },
                    { 102, "audrey.trump@something.com", "Audrey", "Trump" },
                    { 103, "barack.windsor@gov.nl", "Barack", "Windsor" },
                    { 104, "kate.obama@something.com", "Kate", "Obama" },
                    { 105, "mick.trump@gov.nl", "Mick", "Trump" },
                    { 106, "jimi.obama@theworld.ca", "Jimi", "Obama" },
                    { 107, "charles.windsor@something.com", "Charles", "Windsor" },
                    { 108, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 109, "barack.windsor@bbc.co.uk", "Barack", "Windsor" },
                    { 110, "jimi.presley@something.com", "Jimi", "Presley" },
                    { 111, "charles.middleton@something.com", "Charles", "Middleton" },
                    { 112, "elvis.obama@something.com", "Elvis", "Obama" },
                    { 113, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 114, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 115, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 116, "jimi.jagger@gov.gr", "Jimi", "Jagger" },
                    { 117, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 118, "oprah.windsor@gov.gr", "Oprah", "Windsor" },
                    { 119, "charles.hepburn@gov.ru", "Charles", "Hepburn" },
                    { 120, "charles.middleton@google.com", "Charles", "Middleton" },
                    { 121, "donald.presley@nasa.org.us", "Donald", "Presley" },
                    { 122, "kate.winfrey@nasa.org.us", "Kate", "Winfrey" },
                    { 123, "kate.obama@google.com", "Kate", "Obama" },
                    { 124, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 125, "kate.winslet@google.com", "Kate", "Winslet" },
                    { 126, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 127, "elvis.obama@theworld.ca", "Elvis", "Obama" },
                    { 128, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 129, "donald.middleton@gov.us", "Donald", "Middleton" },
                    { 130, "barack.presley@google.com", "Barack", "Presley" },
                    { 131, "audrey.jagger@tesla.com", "Audrey", "Jagger" },
                    { 132, "oprah.hepburn@gov.nl", "Oprah", "Hepburn" },
                    { 133, "jimi.obama@something.com", "Jimi", "Obama" },
                    { 134, "kate.hepburn@gov.us", "Kate", "Hepburn" },
                    { 135, "barack.windsor@nasa.org.us", "Barack", "Windsor" },
                    { 136, "jimi.hendrix@gov.gr", "Jimi", "Hendrix" },
                    { 137, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 138, "charles.trump@gov.us", "Charles", "Trump" },
                    { 139, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 140, "mick.windsor@theworld.ca", "Mick", "Windsor" },
                    { 141, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 142, "barack.winslet@something.com", "Barack", "Winslet" },
                    { 143, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 144, "audrey.hepburn@something.com", "Audrey", "Hepburn" },
                    { 145, "audrey.trump@gov.gr", "Audrey", "Trump" },
                    { 146, "audrey.trump@gov.gr", "Audrey", "Trump" },
                    { 147, "barack.winfrey@nasa.org.us", "Barack", "Winfrey" },
                    { 148, "jimi.middleton@google.com", "Jimi", "Middleton" },
                    { 149, "audrey.hepburn@theworld.ca", "Audrey", "Hepburn" },
                    { 150, "oprah.presley@google.com", "Oprah", "Presley" },
                    { 151, "donald.windsor@gov.us", "Donald", "Windsor" },
                    { 152, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 153, "oprah.winfrey@gov.nl", "Oprah", "Winfrey" },
                    { 154, "audrey.presley@something.com", "Audrey", "Presley" },
                    { 155, "kate.obama@gov.us", "Kate", "Obama" },
                    { 156, "jimi.windsor@gov.us", "Jimi", "Windsor" },
                    { 157, "mick.hepburn@something.com", "Mick", "Hepburn" },
                    { 158, "elvis.middleton@gov.us", "Elvis", "Middleton" },
                    { 159, "barack.presley@bbc.co.uk", "Barack", "Presley" },
                    { 160, "donald.hepburn@tesla.com", "Donald", "Hepburn" },
                    { 161, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 162, "donald.presley@google.com", "Donald", "Presley" },
                    { 163, "charles.hendrix@gov.us", "Charles", "Hendrix" },
                    { 164, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 165, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 166, "oprah.obama@theworld.ca", "Oprah", "Obama" },
                    { 167, "charles.windsor@gov.ru", "Charles", "Windsor" },
                    { 168, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 169, "elvis.hepburn@theworld.ca", "Elvis", "Hepburn" },
                    { 170, "oprah.hepburn@theworld.ca", "Oprah", "Hepburn" },
                    { 171, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 172, "jimi.winslet@gov.us", "Jimi", "Winslet" },
                    { 173, "barack.middleton@bbc.co.uk", "Barack", "Middleton" },
                    { 174, "oprah.jagger@google.com", "Oprah", "Jagger" },
                    { 175, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 176, "charles.jagger@theworld.ca", "Charles", "Jagger" },
                    { 177, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 178, "donald.winslet@something.com", "Donald", "Winslet" },
                    { 179, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 180, "elvis.windsor@gov.ru", "Elvis", "Windsor" },
                    { 181, "barack.hendrix@bbc.co.uk", "Barack", "Hendrix" },
                    { 182, "mick.hepburn@gov.nl", "Mick", "Hepburn" },
                    { 183, "barack.trump@google.com", "Barack", "Trump" },
                    { 184, "oprah.trump@bbc.co.uk", "Oprah", "Trump" },
                    { 185, "barack.trump@theworld.ca", "Barack", "Trump" },
                    { 186, "charles.middleton@nasa.org.us", "Charles", "Middleton" },
                    { 187, "donald.presley@something.com", "Donald", "Presley" },
                    { 188, "kate.trump@google.com", "Kate", "Trump" },
                    { 189, "barack.jagger@theworld.ca", "Barack", "Jagger" },
                    { 190, "audrey.obama@google.com", "Audrey", "Obama" },
                    { 191, "donald.obama@bbc.co.uk", "Donald", "Obama" },
                    { 192, "mick.trump@theworld.ca", "Mick", "Trump" },
                    { 193, "audrey.winslet@nasa.org.us", "Audrey", "Winslet" },
                    { 194, "mick.hendrix@gov.us", "Mick", "Hendrix" },
                    { 195, "mick.middleton@gov.nl", "Mick", "Middleton" },
                    { 196, "barack.winfrey@gov.us", "Barack", "Winfrey" },
                    { 197, "audrey.trump@something.com", "Audrey", "Trump" },
                    { 198, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 199, "jimi.winfrey@google.com", "Jimi", "Winfrey" },
                    { 200, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 201, "oprah.trump@gov.us", "Oprah", "Trump" },
                    { 202, "donald.middleton@theworld.ca", "Donald", "Middleton" },
                    { 203, "mick.hepburn@gov.gr", "Mick", "Hepburn" },
                    { 204, "kate.presley@gov.us", "Kate", "Presley" },
                    { 205, "mick.jagger@gov.gr", "Mick", "Jagger" },
                    { 206, "oprah.hepburn@something.com", "Oprah", "Hepburn" },
                    { 207, "elvis.winfrey@gov.nl", "Elvis", "Winfrey" },
                    { 208, "audrey.presley@bbc.co.uk", "Audrey", "Presley" },
                    { 209, "charles.obama@gov.gr", "Charles", "Obama" },
                    { 210, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 211, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 212, "audrey.winfrey@gov.nl", "Audrey", "Winfrey" },
                    { 213, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 214, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 215, "mick.hendrix@something.com", "Mick", "Hendrix" },
                    { 216, "donald.winfrey@theworld.ca", "Donald", "Winfrey" },
                    { 217, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 218, "elvis.trump@gov.nl", "Elvis", "Trump" },
                    { 219, "barack.jagger@gov.us", "Barack", "Jagger" },
                    { 220, "jimi.trump@nasa.org.us", "Jimi", "Trump" },
                    { 221, "charles.presley@gov.ru", "Charles", "Presley" },
                    { 222, "barack.obama@bbc.co.uk", "Barack", "Obama" },
                    { 223, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 224, "mick.jagger@gov.gr", "Mick", "Jagger" },
                    { 225, "audrey.winslet@tesla.com", "Audrey", "Winslet" },
                    { 226, "kate.jagger@nasa.org.us", "Kate", "Jagger" },
                    { 227, "elvis.hepburn@nasa.org.us", "Elvis", "Hepburn" },
                    { 228, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 229, "jimi.winfrey@theworld.ca", "Jimi", "Winfrey" },
                    { 230, "kate.presley@tesla.com", "Kate", "Presley" },
                    { 231, "donald.presley@bbc.co.uk", "Donald", "Presley" },
                    { 232, "barack.winfrey@gov.nl", "Barack", "Winfrey" },
                    { 233, "jimi.obama@tesla.com", "Jimi", "Obama" },
                    { 234, "jimi.obama@google.com", "Jimi", "Obama" },
                    { 235, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 236, "charles.hendrix@bbc.co.uk", "Charles", "Hendrix" },
                    { 237, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 238, "donald.middleton@gov.gr", "Donald", "Middleton" },
                    { 239, "jimi.middleton@gov.nl", "Jimi", "Middleton" },
                    { 240, "oprah.trump@theworld.ca", "Oprah", "Trump" },
                    { 241, "audrey.presley@nasa.org.us", "Audrey", "Presley" },
                    { 242, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 243, "donald.windsor@gov.nl", "Donald", "Windsor" },
                    { 244, "barack.middleton@tesla.com", "Barack", "Middleton" },
                    { 245, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 246, "jimi.hendrix@gov.nl", "Jimi", "Hendrix" },
                    { 247, "charles.windsor@tesla.com", "Charles", "Windsor" },
                    { 248, "oprah.hendrix@something.com", "Oprah", "Hendrix" },
                    { 249, "charles.middleton@theworld.ca", "Charles", "Middleton" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "AuthorId", "PublisherId", "title" },
                values: new object[,]
                {
                    { 1, 107, 2, "Several Transparent Leopards" },
                    { 2, 55, 4, "A bunch of Bitter Flowers" },
                    { 3, 202, 5, "A herd of Microscopic Flowers" },
                    { 4, 113, 4, "Fifteen Bitter Flowers" },
                    { 5, 53, 7, "Several Green Cars" },
                    { 6, 147, 7, "An army of Large Buildings" },
                    { 7, 162, 3, "A bunch of Green Flowers" },
                    { 8, 231, 8, "Several Orange Cars" },
                    { 9, 32, 6, "A herd of Purple Leopards" },
                    { 10, 107, 3, "Two Transparent Leopards" },
                    { 11, 43, 6, "Fifteen Large Cars" },
                    { 12, 79, 9, "Several Purple Planets" },
                    { 13, 249, 7, "An army of Large Leopards" },
                    { 14, 188, 4, "A bunch of Large Planets" },
                    { 15, 37, 8, "Fifteen Green Cars" },
                    { 16, 37, 6, "A herd of Large Buildings" },
                    { 17, 197, 3, "Several Purple Houses" },
                    { 18, 183, 3, "An army of Microscopic Cars" },
                    { 19, 208, 5, "A herd of Microscopic Flowers" },
                    { 20, 1, 4, "Two Orange Cars" },
                    { 21, 157, 5, "A herd of Transparent Houses" },
                    { 22, 175, 8, "An army of Orange Leopards" },
                    { 23, 37, 4, "An army of Purple Leopards" },
                    { 24, 249, 8, "A herd of Transparent Cars" },
                    { 25, 30, 3, "An army of Rose Smelling Cars" },
                    { 26, 40, 6, "Several Transparent Cars" },
                    { 27, 13, 7, "An army of Large Buildings" },
                    { 28, 208, 9, "An army of Large Houses" },
                    { 29, 230, 4, "A herd of Green Planets" },
                    { 30, 16, 8, "Two Orange Buildings" },
                    { 31, 39, 1, "A bunch of Microscopic Leopards" },
                    { 32, 122, 8, "The Microscopic Cars" },
                    { 33, 191, 8, "A herd of Rose Smelling Leopards" },
                    { 34, 21, 9, "Two Transparent Buildings" },
                    { 35, 63, 8, "A herd of Rose Smelling Buildings" },
                    { 36, 173, 3, "A bunch of Microscopic Cars" },
                    { 37, 114, 9, "The Rose Smelling Buildings" },
                    { 38, 89, 1, "Several Bitter Cars" },
                    { 39, 248, 4, "Two Bitter Cars" },
                    { 40, 133, 5, "Two Bitter Flowers" },
                    { 41, 186, 4, "Fifteen Bitter Houses" },
                    { 42, 161, 5, "An army of Rose Smelling Planets" },
                    { 43, 142, 3, "A bunch of Transparent Buildings" },
                    { 44, 190, 9, "The Microscopic Cars" },
                    { 45, 85, 8, "The Purple Flowers" },
                    { 46, 80, 4, "A bunch of Purple Cars" },
                    { 47, 147, 1, "Fifteen Large Cars" },
                    { 48, 5, 4, "Two Bitter Planets" },
                    { 49, 50, 3, "An army of Large Planets" },
                    { 50, 45, 9, "A bunch of Microscopic Houses" },
                    { 51, 80, 5, "The Large Buildings" },
                    { 52, 125, 2, "Fifteen Orange Planets" },
                    { 53, 128, 8, "An army of Purple Flowers" },
                    { 54, 70, 1, "Two Orange Leopards" },
                    { 55, 222, 5, "An army of Transparent Leopards" },
                    { 56, 181, 1, "Two Bitter Buildings" },
                    { 57, 149, 4, "Two Rose Smelling Buildings" },
                    { 58, 20, 3, "A bunch of Microscopic Houses" },
                    { 59, 51, 8, "Two Purple Cars" },
                    { 60, 63, 3, "A herd of Rose Smelling Cars" },
                    { 61, 226, 3, "A bunch of Transparent Planets" },
                    { 62, 144, 5, "Fifteen Microscopic Cars" },
                    { 63, 167, 4, "Two Purple Cars" },
                    { 64, 51, 1, "The Transparent Houses" },
                    { 65, 213, 1, "Two Rose Smelling Buildings" },
                    { 66, 4, 2, "The Green Houses" },
                    { 67, 13, 7, "A herd of Rose Smelling Planets" },
                    { 68, 142, 7, "A bunch of Large Buildings" },
                    { 69, 144, 2, "The Purple Houses" },
                    { 70, 106, 8, "A herd of Bitter Flowers" },
                    { 71, 150, 3, "Two Green Flowers" },
                    { 72, 209, 1, "Fifteen Transparent Cars" },
                    { 73, 58, 1, "A herd of Rose Smelling Flowers" },
                    { 74, 94, 6, "The Bitter Houses" },
                    { 75, 161, 8, "The Transparent Flowers" },
                    { 76, 30, 9, "Fifteen Orange Houses" },
                    { 77, 70, 8, "A herd of Purple Buildings" },
                    { 78, 66, 5, "Two Large Buildings" },
                    { 79, 148, 6, "A herd of Orange Flowers" },
                    { 80, 88, 4, "A herd of Microscopic Leopards" },
                    { 81, 38, 9, "A herd of Orange Houses" },
                    { 82, 110, 6, "Several Rose Smelling Cars" },
                    { 83, 246, 6, "The Purple Planets" },
                    { 84, 120, 8, "Several Transparent Planets" },
                    { 85, 124, 3, "A bunch of Transparent Flowers" },
                    { 86, 230, 3, "A bunch of Microscopic Leopards" },
                    { 87, 227, 1, "Several Bitter Buildings" },
                    { 88, 231, 4, "A bunch of Microscopic Buildings" },
                    { 89, 237, 1, "The Green Flowers" },
                    { 90, 101, 1, "A bunch of Green Buildings" },
                    { 91, 95, 6, "The Transparent Leopards" },
                    { 92, 204, 7, "A herd of Green Leopards" },
                    { 93, 225, 1, "An army of Orange Flowers" },
                    { 94, 81, 8, "A herd of Transparent Leopards" },
                    { 95, 9, 1, "Several Green Flowers" },
                    { 96, 139, 6, "A bunch of Rose Smelling Flowers" },
                    { 97, 47, 6, "Fifteen Green Houses" },
                    { 98, 80, 4, "Fifteen Orange Houses" },
                    { 99, 149, 3, "A herd of Purple Buildings" },
                    { 100, 100, 3, "Several Large Flowers" },
                    { 101, 91, 4, "A herd of Purple Flowers" },
                    { 102, 230, 1, "Fifteen Purple Flowers" },
                    { 103, 16, 2, "Several Rose Smelling Planets" },
                    { 104, 77, 1, "Several Purple Planets" },
                    { 105, 200, 1, "A herd of Purple Houses" },
                    { 106, 5, 7, "Several Microscopic Planets" },
                    { 107, 107, 7, "An army of Transparent Houses" },
                    { 108, 29, 4, "An army of Purple Planets" },
                    { 109, 67, 8, "Two Green Buildings" },
                    { 110, 131, 7, "A bunch of Purple Planets" },
                    { 111, 164, 4, "The Microscopic Cars" },
                    { 112, 235, 8, "Several Large Houses" },
                    { 113, 11, 5, "An army of Green Buildings" },
                    { 114, 44, 4, "A herd of Rose Smelling Cars" },
                    { 115, 171, 5, "The Green Buildings" },
                    { 116, 245, 9, "A herd of Microscopic Flowers" },
                    { 117, 40, 3, "A herd of Green Leopards" },
                    { 118, 139, 3, "A herd of Rose Smelling Cars" },
                    { 119, 205, 5, "The Orange Buildings" },
                    { 120, 125, 9, "A herd of Bitter Cars" },
                    { 121, 186, 4, "Two Bitter Leopards" },
                    { 122, 155, 1, "The Bitter Buildings" },
                    { 123, 119, 6, "A herd of Orange Houses" },
                    { 124, 40, 8, "Several Green Cars" },
                    { 125, 146, 2, "Fifteen Rose Smelling Leopards" },
                    { 126, 95, 2, "Two Rose Smelling Houses" },
                    { 127, 236, 2, "A herd of Microscopic Houses" },
                    { 128, 171, 7, "A herd of Orange Flowers" },
                    { 129, 122, 1, "A herd of Transparent Leopards" },
                    { 130, 167, 4, "The Microscopic Buildings" },
                    { 131, 181, 9, "Two Green Flowers" },
                    { 132, 246, 9, "Several Purple Leopards" },
                    { 133, 49, 6, "A herd of Purple Houses" },
                    { 134, 7, 8, "A bunch of Transparent Flowers" },
                    { 135, 219, 7, "A bunch of Purple Planets" },
                    { 136, 5, 4, "An army of Microscopic Cars" },
                    { 137, 3, 6, "The Purple Flowers" },
                    { 138, 87, 5, "Two Orange Leopards" },
                    { 139, 56, 8, "A herd of Orange Buildings" },
                    { 140, 205, 7, "The Rose Smelling Buildings" },
                    { 141, 106, 9, "A bunch of Rose Smelling Flowers" },
                    { 142, 186, 7, "A bunch of Large Planets" },
                    { 143, 42, 4, "Several Bitter Flowers" },
                    { 144, 204, 5, "Several Transparent Buildings" },
                    { 145, 55, 3, "Several Large Flowers" },
                    { 146, 131, 1, "An army of Large Buildings" },
                    { 147, 59, 5, "Two Orange Planets" },
                    { 148, 179, 7, "A herd of Large Houses" },
                    { 149, 248, 7, "Several Bitter Buildings" },
                    { 150, 221, 9, "Fifteen Transparent Flowers" },
                    { 151, 85, 2, "A bunch of Large Buildings" },
                    { 152, 8, 7, "An army of Microscopic Leopards" },
                    { 153, 216, 2, "A bunch of Purple Cars" },
                    { 154, 241, 1, "An army of Large Houses" },
                    { 155, 199, 6, "Several Transparent Leopards" },
                    { 156, 5, 8, "A herd of Green Buildings" },
                    { 157, 4, 5, "Two Rose Smelling Buildings" },
                    { 158, 163, 6, "Two Purple Cars" },
                    { 159, 48, 4, "The Bitter Houses" },
                    { 160, 43, 2, "Two Green Leopards" },
                    { 161, 91, 9, "An army of Green Planets" },
                    { 162, 1, 8, "A bunch of Orange Houses" },
                    { 163, 165, 2, "The Rose Smelling Cars" },
                    { 164, 79, 1, "A herd of Orange Houses" },
                    { 165, 14, 5, "Several Large Cars" },
                    { 166, 149, 2, "Fifteen Transparent Buildings" },
                    { 167, 5, 6, "An army of Purple Leopards" },
                    { 168, 216, 2, "A bunch of Transparent Buildings" },
                    { 169, 123, 9, "A bunch of Bitter Cars" },
                    { 170, 114, 4, "A bunch of Green Planets" },
                    { 171, 83, 6, "A bunch of Purple Leopards" },
                    { 172, 171, 2, "A bunch of Microscopic Leopards" },
                    { 173, 152, 2, "A herd of Microscopic Houses" },
                    { 174, 94, 6, "The Purple Planets" },
                    { 175, 208, 9, "An army of Large Cars" },
                    { 176, 134, 7, "The Purple Cars" },
                    { 177, 23, 7, "Fifteen Purple Leopards" },
                    { 178, 20, 4, "Fifteen Rose Smelling Leopards" },
                    { 179, 225, 7, "Fifteen Orange Leopards" },
                    { 180, 12, 9, "A bunch of Orange Planets" },
                    { 181, 163, 1, "The Orange Buildings" },
                    { 182, 172, 2, "A herd of Microscopic Leopards" },
                    { 183, 232, 1, "A bunch of Rose Smelling Buildings" },
                    { 184, 190, 1, "The Microscopic Leopards" },
                    { 185, 234, 9, "A bunch of Purple Cars" },
                    { 186, 69, 7, "A herd of Transparent Leopards" },
                    { 187, 44, 6, "Several Bitter Buildings" },
                    { 188, 215, 4, "An army of Purple Buildings" },
                    { 189, 14, 7, "The Green Buildings" },
                    { 190, 74, 1, "A bunch of Rose Smelling Planets" },
                    { 191, 63, 3, "Two Transparent Leopards" },
                    { 192, 103, 1, "Fifteen Microscopic Buildings" },
                    { 193, 233, 2, "An army of Microscopic Leopards" },
                    { 194, 144, 9, "Two Orange Cars" },
                    { 195, 219, 4, "An army of Rose Smelling Buildings" },
                    { 196, 169, 7, "Several Transparent Houses" },
                    { 197, 167, 4, "A bunch of Large Leopards" },
                    { 198, 108, 2, "Several Green Planets" },
                    { 199, 27, 5, "A bunch of Orange Houses" },
                    { 200, 145, 6, "The Transparent Houses" },
                    { 201, 125, 6, "An army of Large Leopards" },
                    { 202, 228, 8, "Two Transparent Leopards" },
                    { 203, 5, 6, "An army of Green Planets" },
                    { 204, 88, 9, "The Purple Planets" },
                    { 205, 49, 5, "A bunch of Transparent Leopards" },
                    { 206, 200, 5, "Several Transparent Cars" },
                    { 207, 113, 1, "Fifteen Microscopic Leopards" },
                    { 208, 20, 3, "Fifteen Green Houses" },
                    { 209, 111, 5, "An army of Microscopic Leopards" },
                    { 210, 74, 3, "A bunch of Large Houses" },
                    { 211, 185, 1, "A herd of Large Leopards" },
                    { 212, 85, 4, "Two Green Houses" },
                    { 213, 138, 7, "A bunch of Orange Cars" },
                    { 214, 216, 4, "Several Orange Buildings" },
                    { 215, 146, 4, "A bunch of Purple Planets" },
                    { 216, 9, 2, "Fifteen Large Flowers" },
                    { 217, 31, 5, "A herd of Transparent Cars" },
                    { 218, 86, 5, "Fifteen Transparent Cars" },
                    { 219, 183, 3, "Fifteen Orange Houses" },
                    { 220, 139, 4, "Fifteen Bitter Leopards" },
                    { 221, 221, 5, "Two Bitter Leopards" },
                    { 222, 193, 1, "An army of Orange Planets" },
                    { 223, 48, 3, "Two Microscopic Buildings" },
                    { 224, 30, 6, "Fifteen Bitter Planets" },
                    { 225, 73, 4, "A herd of Large Cars" },
                    { 226, 160, 9, "A bunch of Orange Cars" },
                    { 227, 63, 2, "Fifteen Orange Leopards" },
                    { 228, 27, 3, "A bunch of Transparent Houses" },
                    { 229, 95, 8, "A bunch of Orange Buildings" },
                    { 230, 229, 1, "An army of Transparent Flowers" },
                    { 231, 238, 8, "A bunch of Microscopic Buildings" },
                    { 232, 76, 4, "A bunch of Large Buildings" },
                    { 233, 89, 7, "An army of Rose Smelling Houses" },
                    { 234, 194, 2, "The Microscopic Cars" },
                    { 235, 222, 9, "A herd of Large Planets" },
                    { 236, 133, 9, "Fifteen Transparent Leopards" },
                    { 237, 59, 1, "The Large Cars" },
                    { 238, 105, 8, "The Orange Planets" },
                    { 239, 213, 7, "Fifteen Purple Houses" },
                    { 240, 223, 6, "An army of Large Leopards" },
                    { 241, 174, 1, "Fifteen Microscopic Buildings" },
                    { 242, 145, 3, "A herd of Large Cars" },
                    { 243, 157, 2, "Several Purple Flowers" },
                    { 244, 23, 5, "A bunch of Orange Flowers" },
                    { 245, 106, 2, "Several Microscopic Houses" },
                    { 246, 119, 7, "Two Rose Smelling Leopards" },
                    { 247, 146, 8, "The Purple Leopards" },
                    { 248, 6, 5, "Several Transparent Leopards" },
                    { 249, 124, 3, "Several Transparent Leopards" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_books_AuthorId",
                table: "books",
                column: "AuthorId");

            migrationBuilder.CreateIndex(
                name: "IX_books_PublisherId",
                table: "books",
                column: "PublisherId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "Publishers");

            migrationBuilder.DropTable(
                name: "authors");
        }
    }
}
