using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class firstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    FirstName = table.Column<string>(type: "text", nullable: false),
                    LastName = table.Column<string>(type: "text", nullable: false),
                    Email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Books",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Books", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Books_Authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Authors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "Id", "Email", "FirstName", "LastName" },
                values: new object[,]
                {
                    { 1, "elvis.middleton@gov.us", "Elvis", "Middleton" },
                    { 2, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 3, "audrey.winfrey@google.com", "Audrey", "Winfrey" },
                    { 4, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 5, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 6, "donald.hepburn@gov.gr", "Donald", "Hepburn" },
                    { 7, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 8, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 9, "jimi.hendrix@theworld.ca", "Jimi", "Hendrix" },
                    { 10, "elvis.winfrey@google.com", "Elvis", "Winfrey" },
                    { 11, "mick.hendrix@something.com", "Mick", "Hendrix" },
                    { 12, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 13, "oprah.obama@theworld.ca", "Oprah", "Obama" },
                    { 14, "donald.trump@theworld.ca", "Donald", "Trump" },
                    { 15, "charles.windsor@gov.nl", "Charles", "Windsor" },
                    { 16, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 17, "mick.jagger@tesla.com", "Mick", "Jagger" },
                    { 18, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 19, "audrey.winslet@tesla.com", "Audrey", "Winslet" },
                    { 20, "oprah.trump@something.com", "Oprah", "Trump" },
                    { 21, "barack.hendrix@tesla.com", "Barack", "Hendrix" },
                    { 22, "mick.windsor@google.com", "Mick", "Windsor" },
                    { 23, "charles.jagger@nasa.org.us", "Charles", "Jagger" },
                    { 24, "barack.hendrix@gov.ru", "Barack", "Hendrix" },
                    { 25, "elvis.hendrix@nasa.org.us", "Elvis", "Hendrix" },
                    { 26, "audrey.hepburn@something.com", "Audrey", "Hepburn" },
                    { 27, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 28, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 29, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 30, "jimi.winfrey@theworld.ca", "Jimi", "Winfrey" },
                    { 31, "audrey.trump@bbc.co.uk", "Audrey", "Trump" },
                    { 32, "audrey.windsor@theworld.ca", "Audrey", "Windsor" },
                    { 33, "audrey.hendrix@bbc.co.uk", "Audrey", "Hendrix" },
                    { 34, "oprah.obama@gov.ru", "Oprah", "Obama" },
                    { 35, "audrey.jagger@theworld.ca", "Audrey", "Jagger" },
                    { 36, "oprah.presley@gov.us", "Oprah", "Presley" },
                    { 37, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 38, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 39, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 40, "barack.presley@something.com", "Barack", "Presley" },
                    { 41, "audrey.obama@bbc.co.uk", "Audrey", "Obama" },
                    { 42, "charles.presley@gov.us", "Charles", "Presley" },
                    { 43, "charles.hepburn@gov.ru", "Charles", "Hepburn" },
                    { 44, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 45, "charles.windsor@gov.gr", "Charles", "Windsor" },
                    { 46, "charles.jagger@gov.gr", "Charles", "Jagger" },
                    { 47, "audrey.middleton@something.com", "Audrey", "Middleton" },
                    { 48, "charles.middleton@gov.gr", "Charles", "Middleton" },
                    { 49, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 50, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 51, "oprah.windsor@google.com", "Oprah", "Windsor" },
                    { 52, "oprah.windsor@gov.us", "Oprah", "Windsor" },
                    { 53, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 54, "kate.hendrix@bbc.co.uk", "Kate", "Hendrix" },
                    { 55, "jimi.trump@gov.ru", "Jimi", "Trump" },
                    { 56, "charles.winfrey@gov.nl", "Charles", "Winfrey" },
                    { 57, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 58, "jimi.hendrix@google.com", "Jimi", "Hendrix" },
                    { 59, "barack.trump@theworld.ca", "Barack", "Trump" },
                    { 60, "mick.winslet@theworld.ca", "Mick", "Winslet" },
                    { 61, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 62, "donald.windsor@google.com", "Donald", "Windsor" },
                    { 63, "oprah.hepburn@tesla.com", "Oprah", "Hepburn" },
                    { 64, "jimi.presley@something.com", "Jimi", "Presley" },
                    { 65, "audrey.winslet@gov.ru", "Audrey", "Winslet" },
                    { 66, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 67, "oprah.middleton@nasa.org.us", "Oprah", "Middleton" },
                    { 68, "barack.presley@gov.ru", "Barack", "Presley" },
                    { 69, "elvis.middleton@google.com", "Elvis", "Middleton" },
                    { 70, "charles.middleton@google.com", "Charles", "Middleton" },
                    { 71, "barack.jagger@gov.nl", "Barack", "Jagger" },
                    { 72, "elvis.winslet@bbc.co.uk", "Elvis", "Winslet" },
                    { 73, "audrey.jagger@gov.us", "Audrey", "Jagger" },
                    { 74, "donald.obama@bbc.co.uk", "Donald", "Obama" },
                    { 75, "donald.obama@gov.us", "Donald", "Obama" },
                    { 76, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 77, "charles.winfrey@gov.nl", "Charles", "Winfrey" },
                    { 78, "charles.hendrix@gov.nl", "Charles", "Hendrix" },
                    { 79, "elvis.obama@gov.nl", "Elvis", "Obama" },
                    { 80, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 81, "mick.winslet@tesla.com", "Mick", "Winslet" },
                    { 82, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 83, "charles.hepburn@gov.gr", "Charles", "Hepburn" },
                    { 84, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 85, "barack.winslet@google.com", "Barack", "Winslet" },
                    { 86, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 87, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 88, "audrey.obama@gov.us", "Audrey", "Obama" },
                    { 89, "donald.middleton@theworld.ca", "Donald", "Middleton" },
                    { 90, "barack.hepburn@bbc.co.uk", "Barack", "Hepburn" },
                    { 91, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 92, "elvis.windsor@tesla.com", "Elvis", "Windsor" },
                    { 93, "jimi.jagger@gov.gr", "Jimi", "Jagger" },
                    { 94, "elvis.middleton@nasa.org.us", "Elvis", "Middleton" },
                    { 95, "oprah.jagger@something.com", "Oprah", "Jagger" },
                    { 96, "jimi.obama@gov.ru", "Jimi", "Obama" },
                    { 97, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 98, "charles.obama@something.com", "Charles", "Obama" },
                    { 99, "charles.winslet@gov.gr", "Charles", "Winslet" },
                    { 100, "elvis.hendrix@gov.ru", "Elvis", "Hendrix" },
                    { 101, "jimi.middleton@bbc.co.uk", "Jimi", "Middleton" },
                    { 102, "audrey.winslet@gov.us", "Audrey", "Winslet" },
                    { 103, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 104, "elvis.trump@gov.ru", "Elvis", "Trump" },
                    { 105, "jimi.middleton@gov.gr", "Jimi", "Middleton" },
                    { 106, "elvis.winfrey@gov.nl", "Elvis", "Winfrey" },
                    { 107, "donald.middleton@something.com", "Donald", "Middleton" },
                    { 108, "audrey.trump@bbc.co.uk", "Audrey", "Trump" },
                    { 109, "mick.hendrix@gov.ru", "Mick", "Hendrix" },
                    { 110, "barack.trump@gov.us", "Barack", "Trump" },
                    { 111, "mick.winfrey@theworld.ca", "Mick", "Winfrey" },
                    { 112, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 113, "jimi.winslet@gov.ru", "Jimi", "Winslet" },
                    { 114, "oprah.middleton@gov.gr", "Oprah", "Middleton" },
                    { 115, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 116, "kate.presley@google.com", "Kate", "Presley" },
                    { 117, "barack.presley@gov.nl", "Barack", "Presley" },
                    { 118, "audrey.jagger@nasa.org.us", "Audrey", "Jagger" },
                    { 119, "kate.presley@something.com", "Kate", "Presley" },
                    { 120, "donald.middleton@something.com", "Donald", "Middleton" },
                    { 121, "barack.winfrey@gov.gr", "Barack", "Winfrey" },
                    { 122, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 123, "kate.presley@gov.us", "Kate", "Presley" },
                    { 124, "jimi.winslet@gov.ru", "Jimi", "Winslet" },
                    { 125, "oprah.winslet@gov.ru", "Oprah", "Winslet" },
                    { 126, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 127, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 128, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 129, "charles.windsor@google.com", "Charles", "Windsor" },
                    { 130, "donald.winslet@theworld.ca", "Donald", "Winslet" },
                    { 131, "charles.presley@google.com", "Charles", "Presley" },
                    { 132, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 133, "charles.winslet@gov.gr", "Charles", "Winslet" },
                    { 134, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 135, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 136, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 137, "audrey.hendrix@something.com", "Audrey", "Hendrix" },
                    { 138, "donald.obama@bbc.co.uk", "Donald", "Obama" },
                    { 139, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 140, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 141, "mick.windsor@gov.ru", "Mick", "Windsor" },
                    { 142, "mick.obama@something.com", "Mick", "Obama" },
                    { 143, "barack.windsor@tesla.com", "Barack", "Windsor" },
                    { 144, "charles.middleton@theworld.ca", "Charles", "Middleton" },
                    { 145, "donald.winslet@theworld.ca", "Donald", "Winslet" },
                    { 146, "barack.jagger@nasa.org.us", "Barack", "Jagger" },
                    { 147, "elvis.jagger@gov.ru", "Elvis", "Jagger" },
                    { 148, "charles.winslet@gov.ru", "Charles", "Winslet" },
                    { 149, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 150, "audrey.winslet@gov.nl", "Audrey", "Winslet" },
                    { 151, "charles.trump@gov.ru", "Charles", "Trump" },
                    { 152, "audrey.windsor@bbc.co.uk", "Audrey", "Windsor" },
                    { 153, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 154, "kate.winslet@tesla.com", "Kate", "Winslet" },
                    { 155, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 156, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 157, "barack.hendrix@gov.gr", "Barack", "Hendrix" },
                    { 158, "donald.middleton@nasa.org.us", "Donald", "Middleton" },
                    { 159, "barack.middleton@bbc.co.uk", "Barack", "Middleton" },
                    { 160, "mick.presley@google.com", "Mick", "Presley" },
                    { 161, "audrey.middleton@nasa.org.us", "Audrey", "Middleton" },
                    { 162, "barack.obama@gov.gr", "Barack", "Obama" },
                    { 163, "donald.windsor@gov.nl", "Donald", "Windsor" },
                    { 164, "donald.windsor@gov.gr", "Donald", "Windsor" },
                    { 165, "kate.winslet@tesla.com", "Kate", "Winslet" },
                    { 166, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 167, "audrey.hendrix@something.com", "Audrey", "Hendrix" },
                    { 168, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 169, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 170, "elvis.jagger@nasa.org.us", "Elvis", "Jagger" },
                    { 171, "jimi.middleton@gov.ru", "Jimi", "Middleton" },
                    { 172, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 173, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 174, "oprah.winslet@nasa.org.us", "Oprah", "Winslet" },
                    { 175, "barack.windsor@nasa.org.us", "Barack", "Windsor" },
                    { 176, "oprah.winfrey@gov.gr", "Oprah", "Winfrey" },
                    { 177, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 178, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 179, "charles.presley@something.com", "Charles", "Presley" },
                    { 180, "barack.trump@gov.gr", "Barack", "Trump" },
                    { 181, "elvis.trump@gov.nl", "Elvis", "Trump" },
                    { 182, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 183, "donald.hendrix@gov.ru", "Donald", "Hendrix" },
                    { 184, "audrey.jagger@tesla.com", "Audrey", "Jagger" },
                    { 185, "audrey.obama@nasa.org.us", "Audrey", "Obama" },
                    { 186, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 187, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 188, "charles.presley@bbc.co.uk", "Charles", "Presley" },
                    { 189, "donald.obama@gov.gr", "Donald", "Obama" },
                    { 190, "charles.trump@gov.gr", "Charles", "Trump" },
                    { 191, "jimi.hendrix@nasa.org.us", "Jimi", "Hendrix" },
                    { 192, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 193, "jimi.obama@something.com", "Jimi", "Obama" },
                    { 194, "elvis.winfrey@something.com", "Elvis", "Winfrey" },
                    { 195, "barack.hendrix@gov.us", "Barack", "Hendrix" },
                    { 196, "kate.obama@tesla.com", "Kate", "Obama" },
                    { 197, "jimi.obama@tesla.com", "Jimi", "Obama" },
                    { 198, "barack.presley@nasa.org.us", "Barack", "Presley" },
                    { 199, "mick.hepburn@gov.gr", "Mick", "Hepburn" },
                    { 200, "barack.windsor@google.com", "Barack", "Windsor" },
                    { 201, "kate.presley@google.com", "Kate", "Presley" },
                    { 202, "barack.trump@gov.us", "Barack", "Trump" },
                    { 203, "mick.jagger@bbc.co.uk", "Mick", "Jagger" },
                    { 204, "audrey.jagger@gov.gr", "Audrey", "Jagger" },
                    { 205, "audrey.obama@tesla.com", "Audrey", "Obama" },
                    { 206, "charles.winfrey@gov.nl", "Charles", "Winfrey" },
                    { 207, "oprah.jagger@gov.us", "Oprah", "Jagger" },
                    { 208, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 209, "barack.winfrey@google.com", "Barack", "Winfrey" },
                    { 210, "donald.obama@theworld.ca", "Donald", "Obama" },
                    { 211, "jimi.winslet@gov.us", "Jimi", "Winslet" },
                    { 212, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 213, "barack.obama@gov.gr", "Barack", "Obama" },
                    { 214, "oprah.obama@something.com", "Oprah", "Obama" },
                    { 215, "charles.winfrey@theworld.ca", "Charles", "Winfrey" },
                    { 216, "jimi.obama@bbc.co.uk", "Jimi", "Obama" },
                    { 217, "oprah.hepburn@something.com", "Oprah", "Hepburn" },
                    { 218, "barack.windsor@gov.ru", "Barack", "Windsor" },
                    { 219, "oprah.winslet@gov.us", "Oprah", "Winslet" },
                    { 220, "audrey.windsor@tesla.com", "Audrey", "Windsor" },
                    { 221, "mick.winfrey@theworld.ca", "Mick", "Winfrey" },
                    { 222, "charles.middleton@gov.gr", "Charles", "Middleton" },
                    { 223, "barack.winslet@gov.ru", "Barack", "Winslet" },
                    { 224, "mick.hepburn@gov.ru", "Mick", "Hepburn" },
                    { 225, "donald.presley@google.com", "Donald", "Presley" },
                    { 226, "jimi.hepburn@theworld.ca", "Jimi", "Hepburn" },
                    { 227, "audrey.hendrix@tesla.com", "Audrey", "Hendrix" },
                    { 228, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 229, "barack.hepburn@nasa.org.us", "Barack", "Hepburn" },
                    { 230, "charles.winslet@gov.ru", "Charles", "Winslet" },
                    { 231, "jimi.middleton@theworld.ca", "Jimi", "Middleton" },
                    { 232, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 233, "mick.middleton@bbc.co.uk", "Mick", "Middleton" },
                    { 234, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 235, "charles.jagger@gov.us", "Charles", "Jagger" },
                    { 236, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 237, "jimi.obama@gov.gr", "Jimi", "Obama" },
                    { 238, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 239, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 240, "mick.obama@something.com", "Mick", "Obama" },
                    { 241, "jimi.obama@bbc.co.uk", "Jimi", "Obama" },
                    { 242, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 243, "audrey.presley@gov.gr", "Audrey", "Presley" },
                    { 244, "elvis.hendrix@bbc.co.uk", "Elvis", "Hendrix" },
                    { 245, "elvis.hepburn@google.com", "Elvis", "Hepburn" },
                    { 246, "audrey.winfrey@gov.ru", "Audrey", "Winfrey" },
                    { 247, "oprah.winslet@gov.nl", "Oprah", "Winslet" },
                    { 248, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 249, "kate.presley@nasa.org.us", "Kate", "Presley" }
                });

            migrationBuilder.InsertData(
                table: "Books",
                columns: new[] { "Id", "AuthorId", "Title" },
                values: new object[,]
                {
                    { 1, 86, "A herd of Bitter Cars" },
                    { 2, 79, "An army of Orange Houses" },
                    { 3, 113, "A bunch of Large Flowers" },
                    { 4, 35, "A herd of Bitter Houses" },
                    { 5, 33, "Fifteen Microscopic Flowers" },
                    { 6, 30, "The Orange Buildings" },
                    { 7, 233, "The Large Leopards" },
                    { 8, 43, "Two Microscopic Cars" },
                    { 9, 91, "Two Transparent Leopards" },
                    { 10, 140, "The Bitter Leopards" },
                    { 11, 228, "An army of Microscopic Buildings" },
                    { 12, 199, "A herd of Rose Smelling Leopards" },
                    { 13, 235, "Fifteen Orange Flowers" },
                    { 14, 53, "Several Transparent Flowers" },
                    { 15, 156, "A bunch of Large Cars" },
                    { 16, 179, "Two Rose Smelling Houses" },
                    { 17, 35, "Several Large Buildings" },
                    { 18, 119, "Two Transparent Houses" },
                    { 19, 113, "Fifteen Purple Houses" },
                    { 20, 130, "An army of Rose Smelling Cars" },
                    { 21, 52, "Two Bitter Leopards" },
                    { 22, 75, "An army of Large Planets" },
                    { 23, 210, "Fifteen Green Buildings" },
                    { 24, 135, "Several Large Leopards" },
                    { 25, 242, "Several Large Houses" },
                    { 26, 129, "A bunch of Green Houses" },
                    { 27, 52, "Two Green Flowers" },
                    { 28, 239, "The Large Planets" },
                    { 29, 57, "Two Microscopic Planets" },
                    { 30, 202, "Fifteen Large Cars" },
                    { 31, 172, "A bunch of Transparent Buildings" },
                    { 32, 169, "Two Orange Planets" },
                    { 33, 3, "Several Bitter Buildings" },
                    { 34, 181, "A bunch of Microscopic Planets" },
                    { 35, 14, "Two Transparent Leopards" },
                    { 36, 61, "Two Microscopic Houses" },
                    { 37, 225, "A bunch of Large Leopards" },
                    { 38, 141, "Fifteen Green Planets" },
                    { 39, 44, "A bunch of Rose Smelling Planets" },
                    { 40, 231, "Fifteen Green Leopards" },
                    { 41, 80, "A herd of Transparent Buildings" },
                    { 42, 192, "Fifteen Rose Smelling Planets" },
                    { 43, 34, "Two Rose Smelling Buildings" },
                    { 44, 239, "Fifteen Transparent Planets" },
                    { 45, 87, "An army of Purple Buildings" },
                    { 46, 20, "The Transparent Cars" },
                    { 47, 195, "Fifteen Transparent Buildings" },
                    { 48, 85, "Several Bitter Houses" },
                    { 49, 90, "A herd of Bitter Cars" },
                    { 50, 178, "A bunch of Purple Houses" },
                    { 51, 116, "An army of Rose Smelling Leopards" },
                    { 52, 18, "Two Large Houses" },
                    { 53, 187, "Two Microscopic Houses" },
                    { 54, 231, "The Purple Cars" },
                    { 55, 9, "An army of Rose Smelling Flowers" },
                    { 56, 128, "A herd of Rose Smelling Flowers" },
                    { 57, 238, "Fifteen Bitter Houses" },
                    { 58, 142, "A bunch of Rose Smelling Buildings" },
                    { 59, 160, "Several Bitter Flowers" },
                    { 60, 107, "Fifteen Rose Smelling Leopards" },
                    { 61, 175, "The Orange Leopards" },
                    { 62, 165, "A herd of Rose Smelling Planets" },
                    { 63, 36, "Two Microscopic Leopards" },
                    { 64, 4, "Two Purple Flowers" },
                    { 65, 57, "Several Purple Houses" },
                    { 66, 212, "The Green Cars" },
                    { 67, 69, "Fifteen Purple Planets" },
                    { 68, 88, "A bunch of Orange Leopards" },
                    { 69, 104, "An army of Bitter Planets" },
                    { 70, 148, "A bunch of Purple Leopards" },
                    { 71, 215, "Fifteen Green Buildings" },
                    { 72, 24, "A bunch of Large Cars" },
                    { 73, 67, "The Transparent Houses" },
                    { 74, 221, "The Bitter Cars" },
                    { 75, 215, "The Large Flowers" },
                    { 76, 236, "A bunch of Rose Smelling Houses" },
                    { 77, 242, "Several Rose Smelling Cars" },
                    { 78, 82, "An army of Bitter Buildings" },
                    { 79, 102, "The Large Cars" },
                    { 80, 2, "Fifteen Purple Leopards" },
                    { 81, 51, "The Microscopic Leopards" },
                    { 82, 249, "Two Large Planets" },
                    { 83, 112, "The Microscopic Cars" },
                    { 84, 244, "The Rose Smelling Leopards" },
                    { 85, 126, "A herd of Green Buildings" },
                    { 86, 167, "An army of Bitter Cars" },
                    { 87, 30, "A bunch of Orange Planets" },
                    { 88, 125, "A bunch of Rose Smelling Planets" },
                    { 89, 28, "A bunch of Green Cars" },
                    { 90, 192, "A bunch of Large Houses" },
                    { 91, 26, "A herd of Rose Smelling Houses" },
                    { 92, 209, "Fifteen Bitter Flowers" },
                    { 93, 29, "An army of Purple Cars" },
                    { 94, 101, "An army of Green Planets" },
                    { 95, 163, "Several Orange Cars" },
                    { 96, 233, "A herd of Green Cars" },
                    { 97, 47, "An army of Transparent Flowers" },
                    { 98, 136, "Several Green Buildings" },
                    { 99, 205, "Fifteen Large Leopards" },
                    { 100, 19, "The Microscopic Buildings" },
                    { 101, 196, "Two Large Houses" },
                    { 102, 129, "The Orange Flowers" },
                    { 103, 111, "A herd of Rose Smelling Houses" },
                    { 104, 26, "A bunch of Transparent Cars" },
                    { 105, 172, "A herd of Purple Buildings" },
                    { 106, 97, "Two Orange Cars" },
                    { 107, 62, "The Rose Smelling Planets" },
                    { 108, 203, "Fifteen Green Flowers" },
                    { 109, 177, "Two Bitter Flowers" },
                    { 110, 85, "An army of Rose Smelling Leopards" },
                    { 111, 57, "The Rose Smelling Leopards" },
                    { 112, 179, "Fifteen Microscopic Leopards" },
                    { 113, 84, "A bunch of Large Buildings" },
                    { 114, 97, "An army of Transparent Leopards" },
                    { 115, 225, "A bunch of Green Planets" },
                    { 116, 36, "The Rose Smelling Planets" },
                    { 117, 19, "A bunch of Microscopic Leopards" },
                    { 118, 65, "Several Transparent Buildings" },
                    { 119, 173, "The Green Houses" },
                    { 120, 140, "A herd of Orange Leopards" },
                    { 121, 41, "Several Transparent Cars" },
                    { 122, 144, "An army of Large Flowers" },
                    { 123, 241, "A herd of Large Planets" },
                    { 124, 51, "Several Orange Leopards" },
                    { 125, 29, "A herd of Orange Planets" },
                    { 126, 120, "A bunch of Rose Smelling Buildings" },
                    { 127, 197, "An army of Microscopic Leopards" },
                    { 128, 95, "Two Orange Leopards" },
                    { 129, 225, "A bunch of Orange Houses" },
                    { 130, 91, "Two Bitter Buildings" },
                    { 131, 173, "A bunch of Transparent Cars" },
                    { 132, 179, "Several Purple Cars" },
                    { 133, 4, "Several Bitter Cars" },
                    { 134, 222, "Several Transparent Leopards" },
                    { 135, 185, "Fifteen Large Buildings" },
                    { 136, 110, "Two Large Cars" },
                    { 137, 147, "An army of Orange Buildings" },
                    { 138, 233, "A bunch of Microscopic Buildings" },
                    { 139, 50, "An army of Rose Smelling Planets" },
                    { 140, 170, "A herd of Green Flowers" },
                    { 141, 75, "Two Rose Smelling Flowers" },
                    { 142, 90, "A bunch of Bitter Planets" },
                    { 143, 13, "Fifteen Microscopic Flowers" },
                    { 144, 58, "A herd of Rose Smelling Planets" },
                    { 145, 59, "An army of Purple Buildings" },
                    { 146, 74, "Fifteen Green Planets" },
                    { 147, 145, "Two Microscopic Flowers" },
                    { 148, 230, "The Green Cars" },
                    { 149, 81, "The Microscopic Planets" },
                    { 150, 63, "The Rose Smelling Planets" },
                    { 151, 190, "An army of Purple Cars" },
                    { 152, 153, "The Purple Leopards" },
                    { 153, 137, "Two Bitter Leopards" },
                    { 154, 131, "A herd of Microscopic Buildings" },
                    { 155, 146, "A bunch of Large Cars" },
                    { 156, 230, "A herd of Orange Flowers" },
                    { 157, 28, "A herd of Microscopic Flowers" },
                    { 158, 1, "A herd of Rose Smelling Planets" },
                    { 159, 214, "A bunch of Orange Leopards" },
                    { 160, 52, "A bunch of Large Houses" },
                    { 161, 217, "Fifteen Rose Smelling Planets" },
                    { 162, 190, "An army of Large Houses" },
                    { 163, 87, "Two Orange Cars" },
                    { 164, 184, "Two Orange Buildings" },
                    { 165, 32, "A herd of Microscopic Planets" },
                    { 166, 35, "Fifteen Transparent Leopards" },
                    { 167, 70, "A bunch of Orange Buildings" },
                    { 168, 57, "The Bitter Flowers" },
                    { 169, 105, "A herd of Transparent Buildings" },
                    { 170, 6, "Fifteen Rose Smelling Leopards" },
                    { 171, 204, "A herd of Bitter Planets" },
                    { 172, 123, "A herd of Microscopic Houses" },
                    { 173, 118, "Two Large Flowers" },
                    { 174, 95, "Several Orange Planets" },
                    { 175, 241, "Two Rose Smelling Cars" },
                    { 176, 124, "The Large Cars" },
                    { 177, 138, "An army of Orange Planets" },
                    { 178, 119, "An army of Purple Houses" },
                    { 179, 69, "Several Bitter Buildings" },
                    { 180, 32, "An army of Transparent Leopards" },
                    { 181, 181, "An army of Microscopic Leopards" },
                    { 182, 94, "Several Purple Cars" },
                    { 183, 220, "A bunch of Transparent Leopards" },
                    { 184, 22, "Fifteen Purple Buildings" },
                    { 185, 108, "A herd of Transparent Cars" },
                    { 186, 175, "An army of Bitter Cars" },
                    { 187, 43, "An army of Transparent Buildings" },
                    { 188, 11, "Two Rose Smelling Houses" },
                    { 189, 214, "An army of Transparent Leopards" },
                    { 190, 147, "Several Bitter Houses" },
                    { 191, 117, "Several Transparent Flowers" },
                    { 192, 100, "Fifteen Purple Buildings" },
                    { 193, 62, "Two Bitter Planets" },
                    { 194, 54, "Two Rose Smelling Flowers" },
                    { 195, 204, "Several Purple Houses" },
                    { 196, 148, "Several Rose Smelling Planets" },
                    { 197, 42, "An army of Rose Smelling Leopards" },
                    { 198, 245, "Fifteen Transparent Flowers" },
                    { 199, 181, "Several Bitter Planets" },
                    { 200, 129, "The Green Cars" },
                    { 201, 127, "A bunch of Bitter Planets" },
                    { 202, 43, "Several Bitter Buildings" },
                    { 203, 208, "The Rose Smelling Houses" },
                    { 204, 203, "A bunch of Transparent Houses" },
                    { 205, 110, "The Rose Smelling Houses" },
                    { 206, 48, "Fifteen Rose Smelling Cars" },
                    { 207, 231, "Several Rose Smelling Cars" },
                    { 208, 138, "An army of Bitter Houses" },
                    { 209, 34, "The Large Buildings" },
                    { 210, 54, "An army of Orange Leopards" },
                    { 211, 63, "A bunch of Purple Leopards" },
                    { 212, 233, "The Orange Buildings" },
                    { 213, 164, "An army of Green Houses" },
                    { 214, 16, "A bunch of Green Planets" },
                    { 215, 48, "An army of Large Houses" },
                    { 216, 70, "An army of Purple Planets" },
                    { 217, 11, "A bunch of Large Buildings" },
                    { 218, 130, "Several Bitter Buildings" },
                    { 219, 36, "A herd of Large Cars" },
                    { 220, 102, "Fifteen Large Leopards" },
                    { 221, 36, "Fifteen Bitter Flowers" },
                    { 222, 132, "The Microscopic Flowers" },
                    { 223, 67, "Fifteen Orange Flowers" },
                    { 224, 51, "A herd of Rose Smelling Leopards" },
                    { 225, 114, "The Microscopic Cars" },
                    { 226, 197, "A herd of Rose Smelling Buildings" },
                    { 227, 174, "Fifteen Microscopic Flowers" },
                    { 228, 103, "Two Purple Flowers" },
                    { 229, 140, "An army of Orange Leopards" },
                    { 230, 180, "Fifteen Large Planets" },
                    { 231, 98, "Fifteen Purple Planets" },
                    { 232, 111, "Several Green Cars" },
                    { 233, 134, "Several Rose Smelling Cars" },
                    { 234, 85, "A bunch of Bitter Flowers" },
                    { 235, 237, "A bunch of Rose Smelling Planets" },
                    { 236, 217, "A herd of Orange Buildings" },
                    { 237, 153, "A bunch of Orange Buildings" },
                    { 238, 78, "The Purple Flowers" },
                    { 239, 161, "The Orange Planets" },
                    { 240, 115, "Several Rose Smelling Buildings" },
                    { 241, 106, "The Bitter Planets" },
                    { 242, 141, "A bunch of Bitter Planets" },
                    { 243, 231, "An army of Green Leopards" },
                    { 244, 127, "Two Green Flowers" },
                    { 245, 162, "The Rose Smelling Planets" },
                    { 246, 183, "An army of Microscopic Houses" },
                    { 247, 63, "Several Bitter Houses" },
                    { 248, 195, "The Bitter Cars" },
                    { 249, 100, "Several Bitter Buildings" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Books_AuthorId",
                table: "Books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Books");

            migrationBuilder.DropTable(
                name: "Authors");
        }
    }
}
