// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.webapi.Data;

#nullable disable

namespace exercise.webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240909101203_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.webapi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.HasKey("Id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "audrey.obama@bbc.co.uk",
                            FirstName = "Audrey",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 2,
                            Email = "donald.hendrix@bbc.co.uk",
                            FirstName = "Donald",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 3,
                            Email = "donald.hepburn@tesla.com",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mick.trump@google.com",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 5,
                            Email = "charles.obama@gov.us",
                            FirstName = "Charles",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 6,
                            Email = "kate.windsor@tesla.com",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 7,
                            Email = "oprah.windsor@nasa.org.us",
                            FirstName = "Oprah",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 8,
                            Email = "kate.jagger@gov.ru",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 9,
                            Email = "kate.middleton@google.com",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 10,
                            Email = "kate.hendrix@tesla.com",
                            FirstName = "Kate",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 11,
                            Email = "barack.middleton@gov.gr",
                            FirstName = "Barack",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 12,
                            Email = "barack.middleton@gov.nl",
                            FirstName = "Barack",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 13,
                            Email = "jimi.windsor@theworld.ca",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 14,
                            Email = "kate.presley@gov.ru",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 15,
                            Email = "oprah.hendrix@gov.us",
                            FirstName = "Oprah",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 16,
                            Email = "kate.windsor@gov.gr",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 17,
                            Email = "kate.presley@google.com",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 18,
                            Email = "audrey.presley@bbc.co.uk",
                            FirstName = "Audrey",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 19,
                            Email = "oprah.trump@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 20,
                            Email = "charles.hepburn@theworld.ca",
                            FirstName = "Charles",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 21,
                            Email = "kate.middleton@gov.us",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 22,
                            Email = "kate.hepburn@gov.us",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 23,
                            Email = "audrey.jagger@theworld.ca",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 24,
                            Email = "jimi.middleton@google.com",
                            FirstName = "Jimi",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 25,
                            Email = "elvis.middleton@theworld.ca",
                            FirstName = "Elvis",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 26,
                            Email = "jimi.jagger@gov.us",
                            FirstName = "Jimi",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 27,
                            Email = "audrey.jagger@gov.gr",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 28,
                            Email = "oprah.jagger@tesla.com",
                            FirstName = "Oprah",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 29,
                            Email = "elvis.trump@tesla.com",
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 30,
                            Email = "oprah.winfrey@google.com",
                            FirstName = "Oprah",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 31,
                            Email = "oprah.middleton@bbc.co.uk",
                            FirstName = "Oprah",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 32,
                            Email = "elvis.middleton@gov.us",
                            FirstName = "Elvis",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 33,
                            Email = "audrey.hendrix@gov.ru",
                            FirstName = "Audrey",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 34,
                            Email = "kate.obama@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 35,
                            Email = "barack.presley@gov.nl",
                            FirstName = "Barack",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 36,
                            Email = "audrey.jagger@theworld.ca",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 37,
                            Email = "jimi.presley@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 38,
                            Email = "kate.hendrix@gov.gr",
                            FirstName = "Kate",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 39,
                            Email = "charles.obama@nasa.org.us",
                            FirstName = "Charles",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 40,
                            Email = "donald.jagger@gov.gr",
                            FirstName = "Donald",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 41,
                            Email = "barack.winslet@gov.us",
                            FirstName = "Barack",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 42,
                            Email = "kate.middleton@tesla.com",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 43,
                            Email = "jimi.windsor@gov.gr",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 44,
                            Email = "donald.winslet@gov.ru",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 45,
                            Email = "donald.winslet@tesla.com",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 46,
                            Email = "barack.hepburn@nasa.org.us",
                            FirstName = "Barack",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 47,
                            Email = "kate.winslet@something.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 48,
                            Email = "elvis.winfrey@tesla.com",
                            FirstName = "Elvis",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 49,
                            Email = "kate.hepburn@gov.us",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 50,
                            Email = "kate.windsor@tesla.com",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 51,
                            Email = "charles.hepburn@tesla.com",
                            FirstName = "Charles",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 52,
                            Email = "charles.winfrey@gov.gr",
                            FirstName = "Charles",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 53,
                            Email = "elvis.jagger@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 54,
                            Email = "kate.hendrix@something.com",
                            FirstName = "Kate",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 55,
                            Email = "oprah.winslet@gov.nl",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 56,
                            Email = "elvis.jagger@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 57,
                            Email = "mick.trump@gov.gr",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 58,
                            Email = "mick.windsor@something.com",
                            FirstName = "Mick",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 59,
                            Email = "donald.hepburn@gov.gr",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 60,
                            Email = "elvis.presley@tesla.com",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 61,
                            Email = "donald.middleton@google.com",
                            FirstName = "Donald",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 62,
                            Email = "oprah.winslet@bbc.co.uk",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 63,
                            Email = "jimi.windsor@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 64,
                            Email = "kate.trump@gov.us",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 65,
                            Email = "mick.obama@something.com",
                            FirstName = "Mick",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 66,
                            Email = "elvis.presley@tesla.com",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 67,
                            Email = "jimi.hepburn@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 68,
                            Email = "charles.jagger@gov.gr",
                            FirstName = "Charles",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 69,
                            Email = "kate.winfrey@tesla.com",
                            FirstName = "Kate",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 70,
                            Email = "kate.winslet@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 71,
                            Email = "audrey.winslet@gov.ru",
                            FirstName = "Audrey",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 72,
                            Email = "charles.winfrey@gov.ru",
                            FirstName = "Charles",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 73,
                            Email = "elvis.winslet@tesla.com",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 74,
                            Email = "mick.hendrix@tesla.com",
                            FirstName = "Mick",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 75,
                            Email = "kate.windsor@gov.us",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 76,
                            Email = "kate.trump@gov.nl",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 77,
                            Email = "elvis.trump@nasa.org.us",
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 78,
                            Email = "jimi.trump@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 79,
                            Email = "charles.winfrey@tesla.com",
                            FirstName = "Charles",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 80,
                            Email = "kate.presley@gov.nl",
                            FirstName = "Kate",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 81,
                            Email = "mick.hepburn@google.com",
                            FirstName = "Mick",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 82,
                            Email = "jimi.hendrix@theworld.ca",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 83,
                            Email = "kate.winslet@google.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 84,
                            Email = "jimi.presley@gov.gr",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 85,
                            Email = "mick.middleton@nasa.org.us",
                            FirstName = "Mick",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 86,
                            Email = "kate.obama@google.com",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 87,
                            Email = "audrey.middleton@gov.nl",
                            FirstName = "Audrey",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 88,
                            Email = "jimi.hepburn@nasa.org.us",
                            FirstName = "Jimi",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 89,
                            Email = "donald.winslet@gov.us",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 90,
                            Email = "charles.jagger@gov.nl",
                            FirstName = "Charles",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 91,
                            Email = "kate.trump@tesla.com",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 92,
                            Email = "mick.presley@gov.gr",
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 93,
                            Email = "barack.trump@google.com",
                            FirstName = "Barack",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 94,
                            Email = "donald.jagger@gov.ru",
                            FirstName = "Donald",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 95,
                            Email = "charles.winfrey@theworld.ca",
                            FirstName = "Charles",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 96,
                            Email = "charles.hendrix@gov.us",
                            FirstName = "Charles",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 97,
                            Email = "jimi.obama@gov.nl",
                            FirstName = "Jimi",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 98,
                            Email = "audrey.winfrey@gov.nl",
                            FirstName = "Audrey",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 99,
                            Email = "charles.presley@theworld.ca",
                            FirstName = "Charles",
                            LastName = "Presley"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 78,
                            PublisherId = 99,
                            Title = "Fifteen Microscopic Flowers"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 86,
                            PublisherId = 57,
                            Title = "Fifteen Transparent Leopards"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 46,
                            PublisherId = 48,
                            Title = "A bunch of Orange Houses"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 67,
                            PublisherId = 56,
                            Title = "Two Purple Planets"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 33,
                            PublisherId = 1,
                            Title = "An army of Orange Buildings"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 53,
                            PublisherId = 34,
                            Title = "Two Transparent Buildings"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 19,
                            PublisherId = 61,
                            Title = "Fifteen Large Leopards"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 59,
                            PublisherId = 62,
                            Title = "Several Large Flowers"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 89,
                            PublisherId = 14,
                            Title = "A herd of Large Buildings"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 75,
                            PublisherId = 80,
                            Title = "A bunch of Orange Buildings"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 27,
                            PublisherId = 52,
                            Title = "Several Bitter Flowers"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 43,
                            PublisherId = 66,
                            Title = "Fifteen Orange Cars"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 6,
                            PublisherId = 18,
                            Title = "The Orange Flowers"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 53,
                            PublisherId = 62,
                            Title = "A herd of Large Flowers"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 37,
                            PublisherId = 4,
                            Title = "A herd of Microscopic Houses"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 33,
                            PublisherId = 36,
                            Title = "A bunch of Bitter Houses"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 59,
                            PublisherId = 80,
                            Title = "An army of Purple Cars"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 53,
                            PublisherId = 21,
                            Title = "Two Large Flowers"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 48,
                            PublisherId = 24,
                            Title = "Two Green Flowers"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 30,
                            PublisherId = 79,
                            Title = "Two Purple Planets"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 62,
                            PublisherId = 60,
                            Title = "Several Green Flowers"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 84,
                            PublisherId = 26,
                            Title = "A herd of Purple Houses"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 78,
                            PublisherId = 89,
                            Title = "Fifteen Large Buildings"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 52,
                            PublisherId = 51,
                            Title = "Several Microscopic Flowers"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 13,
                            PublisherId = 48,
                            Title = "Two Microscopic Leopards"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 45,
                            PublisherId = 11,
                            Title = "A herd of Rose Smelling Flowers"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 77,
                            PublisherId = 75,
                            Title = "Several Green Houses"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 18,
                            PublisherId = 6,
                            Title = "Two Green Houses"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 48,
                            PublisherId = 8,
                            Title = "A herd of Green Cars"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 13,
                            PublisherId = 54,
                            Title = "The Purple Houses"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 72,
                            PublisherId = 93,
                            Title = "An army of Bitter Planets"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 38,
                            PublisherId = 87,
                            Title = "Several Green Leopards"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 81,
                            PublisherId = 71,
                            Title = "Two Microscopic Houses"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 33,
                            PublisherId = 30,
                            Title = "A bunch of Green Planets"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 3,
                            PublisherId = 76,
                            Title = "Fifteen Bitter Buildings"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 54,
                            PublisherId = 20,
                            Title = "Fifteen Purple Houses"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 77,
                            PublisherId = 94,
                            Title = "Two Large Houses"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 39,
                            PublisherId = 90,
                            Title = "A bunch of Bitter Planets"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 71,
                            PublisherId = 93,
                            Title = "The Purple Flowers"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 1,
                            PublisherId = 15,
                            Title = "Fifteen Large Cars"
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 84,
                            PublisherId = 30,
                            Title = "An army of Large Planets"
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 39,
                            PublisherId = 90,
                            Title = "A herd of Bitter Flowers"
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 34,
                            PublisherId = 56,
                            Title = "An army of Bitter Planets"
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 69,
                            PublisherId = 90,
                            Title = "A bunch of Green Planets"
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 90,
                            PublisherId = 30,
                            Title = "Fifteen Green Buildings"
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 64,
                            PublisherId = 39,
                            Title = "The Green Planets"
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 74,
                            PublisherId = 24,
                            Title = "An army of Transparent Flowers"
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 15,
                            PublisherId = 90,
                            Title = "Several Large Planets"
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 90,
                            PublisherId = 46,
                            Title = "Two Large Buildings"
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 13,
                            PublisherId = 82,
                            Title = "An army of Large Houses"
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 23,
                            PublisherId = 20,
                            Title = "Several Orange Buildings"
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 62,
                            PublisherId = 10,
                            Title = "Two Green Leopards"
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 26,
                            PublisherId = 77,
                            Title = "A herd of Microscopic Planets"
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 87,
                            PublisherId = 12,
                            Title = "Several Rose Smelling Leopards"
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 57,
                            PublisherId = 90,
                            Title = "Two Bitter Planets"
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 26,
                            PublisherId = 33,
                            Title = "Several Purple Buildings"
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 5,
                            PublisherId = 25,
                            Title = "The Green Houses"
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 23,
                            PublisherId = 61,
                            Title = "An army of Rose Smelling Planets"
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 83,
                            PublisherId = 43,
                            Title = "A bunch of Large Planets"
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 71,
                            PublisherId = 46,
                            Title = "A bunch of Large Cars"
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 26,
                            PublisherId = 53,
                            Title = "A bunch of Transparent Planets"
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 50,
                            PublisherId = 89,
                            Title = "The Rose Smelling Buildings"
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 8,
                            PublisherId = 20,
                            Title = "Fifteen Orange Cars"
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 12,
                            PublisherId = 90,
                            Title = "Two Green Planets"
                        },
                        new
                        {
                            Id = 65,
                            AuthorId = 55,
                            PublisherId = 91,
                            Title = "Two Green Buildings"
                        },
                        new
                        {
                            Id = 66,
                            AuthorId = 2,
                            PublisherId = 18,
                            Title = "The Purple Planets"
                        },
                        new
                        {
                            Id = 67,
                            AuthorId = 65,
                            PublisherId = 73,
                            Title = "Several Large Buildings"
                        },
                        new
                        {
                            Id = 68,
                            AuthorId = 53,
                            PublisherId = 70,
                            Title = "Several Green Cars"
                        },
                        new
                        {
                            Id = 69,
                            AuthorId = 10,
                            PublisherId = 95,
                            Title = "An army of Large Planets"
                        },
                        new
                        {
                            Id = 70,
                            AuthorId = 57,
                            PublisherId = 93,
                            Title = "An army of Large Houses"
                        },
                        new
                        {
                            Id = 71,
                            AuthorId = 74,
                            PublisherId = 17,
                            Title = "Two Bitter Planets"
                        },
                        new
                        {
                            Id = 72,
                            AuthorId = 81,
                            PublisherId = 99,
                            Title = "A bunch of Large Leopards"
                        },
                        new
                        {
                            Id = 73,
                            AuthorId = 70,
                            PublisherId = 75,
                            Title = "Several Purple Houses"
                        },
                        new
                        {
                            Id = 74,
                            AuthorId = 25,
                            PublisherId = 39,
                            Title = "An army of Orange Flowers"
                        },
                        new
                        {
                            Id = 75,
                            AuthorId = 65,
                            PublisherId = 26,
                            Title = "Two Purple Buildings"
                        },
                        new
                        {
                            Id = 76,
                            AuthorId = 42,
                            PublisherId = 99,
                            Title = "The Orange Flowers"
                        },
                        new
                        {
                            Id = 77,
                            AuthorId = 18,
                            PublisherId = 18,
                            Title = "A herd of Orange Flowers"
                        },
                        new
                        {
                            Id = 78,
                            AuthorId = 21,
                            PublisherId = 73,
                            Title = "The Green Buildings"
                        },
                        new
                        {
                            Id = 79,
                            AuthorId = 72,
                            PublisherId = 74,
                            Title = "An army of Rose Smelling Buildings"
                        },
                        new
                        {
                            Id = 80,
                            AuthorId = 76,
                            PublisherId = 63,
                            Title = "An army of Green Leopards"
                        },
                        new
                        {
                            Id = 81,
                            AuthorId = 99,
                            PublisherId = 84,
                            Title = "The Microscopic Flowers"
                        },
                        new
                        {
                            Id = 82,
                            AuthorId = 76,
                            PublisherId = 16,
                            Title = "A herd of Transparent Leopards"
                        },
                        new
                        {
                            Id = 83,
                            AuthorId = 91,
                            PublisherId = 37,
                            Title = "A bunch of Large Houses"
                        },
                        new
                        {
                            Id = 84,
                            AuthorId = 60,
                            PublisherId = 23,
                            Title = "Several Rose Smelling Flowers"
                        },
                        new
                        {
                            Id = 85,
                            AuthorId = 34,
                            PublisherId = 88,
                            Title = "Fifteen Microscopic Planets"
                        },
                        new
                        {
                            Id = 86,
                            AuthorId = 28,
                            PublisherId = 58,
                            Title = "Several Bitter Cars"
                        },
                        new
                        {
                            Id = 87,
                            AuthorId = 22,
                            PublisherId = 96,
                            Title = "The Large Leopards"
                        },
                        new
                        {
                            Id = 88,
                            AuthorId = 51,
                            PublisherId = 55,
                            Title = "Several Large Leopards"
                        },
                        new
                        {
                            Id = 89,
                            AuthorId = 36,
                            PublisherId = 28,
                            Title = "An army of Purple Leopards"
                        },
                        new
                        {
                            Id = 90,
                            AuthorId = 73,
                            PublisherId = 18,
                            Title = "Fifteen Purple Flowers"
                        },
                        new
                        {
                            Id = 91,
                            AuthorId = 66,
                            PublisherId = 64,
                            Title = "An army of Bitter Leopards"
                        },
                        new
                        {
                            Id = 92,
                            AuthorId = 33,
                            PublisherId = 66,
                            Title = "An army of Large Leopards"
                        },
                        new
                        {
                            Id = 93,
                            AuthorId = 58,
                            PublisherId = 76,
                            Title = "An army of Orange Buildings"
                        },
                        new
                        {
                            Id = 94,
                            AuthorId = 71,
                            PublisherId = 28,
                            Title = "The Green Flowers"
                        },
                        new
                        {
                            Id = 95,
                            AuthorId = 67,
                            PublisherId = 33,
                            Title = "Several Microscopic Leopards"
                        },
                        new
                        {
                            Id = 96,
                            AuthorId = 33,
                            PublisherId = 47,
                            Title = "A bunch of Purple Cars"
                        },
                        new
                        {
                            Id = 97,
                            AuthorId = 95,
                            PublisherId = 96,
                            Title = "Fifteen Green Houses"
                        },
                        new
                        {
                            Id = 98,
                            AuthorId = 17,
                            PublisherId = 53,
                            Title = "An army of Orange Houses"
                        },
                        new
                        {
                            Id = 99,
                            AuthorId = 53,
                            PublisherId = 25,
                            Title = "Fifteen Green Leopards"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.HasKey("Id");

                    b.ToTable("publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "oprah.winfrey@theworld.ca",
                            FirstName = "Oprah",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 2,
                            Email = "barack.jagger@tesla.com",
                            FirstName = "Barack",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 3,
                            Email = "barack.trump@gov.gr",
                            FirstName = "Barack",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 4,
                            Email = "barack.hepburn@gov.gr",
                            FirstName = "Barack",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 5,
                            Email = "audrey.jagger@gov.us",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 6,
                            Email = "kate.jagger@google.com",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 7,
                            Email = "donald.winslet@google.com",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 8,
                            Email = "kate.hepburn@gov.gr",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 9,
                            Email = "charles.hepburn@gov.nl",
                            FirstName = "Charles",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 10,
                            Email = "kate.middleton@theworld.ca",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 11,
                            Email = "kate.winfrey@something.com",
                            FirstName = "Kate",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 12,
                            Email = "audrey.hepburn@bbc.co.uk",
                            FirstName = "Audrey",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 13,
                            Email = "charles.trump@google.com",
                            FirstName = "Charles",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 14,
                            Email = "elvis.jagger@tesla.com",
                            FirstName = "Elvis",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 15,
                            Email = "donald.middleton@something.com",
                            FirstName = "Donald",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 16,
                            Email = "oprah.trump@bbc.co.uk",
                            FirstName = "Oprah",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 17,
                            Email = "kate.winslet@tesla.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 18,
                            Email = "kate.windsor@gov.nl",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 19,
                            Email = "audrey.middleton@gov.gr",
                            FirstName = "Audrey",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 20,
                            Email = "oprah.winslet@tesla.com",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 21,
                            Email = "elvis.hepburn@gov.gr",
                            FirstName = "Elvis",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 22,
                            Email = "charles.windsor@gov.ru",
                            FirstName = "Charles",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 23,
                            Email = "kate.hendrix@something.com",
                            FirstName = "Kate",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 24,
                            Email = "mick.winslet@gov.ru",
                            FirstName = "Mick",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 25,
                            Email = "charles.middleton@gov.us",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 26,
                            Email = "kate.winslet@something.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 27,
                            Email = "barack.obama@something.com",
                            FirstName = "Barack",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 28,
                            Email = "charles.winfrey@nasa.org.us",
                            FirstName = "Charles",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 29,
                            Email = "elvis.trump@gov.ru",
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 30,
                            Email = "kate.winslet@gov.nl",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 31,
                            Email = "kate.jagger@gov.ru",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 32,
                            Email = "jimi.winslet@tesla.com",
                            FirstName = "Jimi",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 33,
                            Email = "audrey.winfrey@theworld.ca",
                            FirstName = "Audrey",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 34,
                            Email = "charles.middleton@tesla.com",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 35,
                            Email = "audrey.obama@tesla.com",
                            FirstName = "Audrey",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 36,
                            Email = "jimi.windsor@gov.nl",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 37,
                            Email = "donald.middleton@nasa.org.us",
                            FirstName = "Donald",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 38,
                            Email = "jimi.jagger@gov.nl",
                            FirstName = "Jimi",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 39,
                            Email = "donald.obama@gov.gr",
                            FirstName = "Donald",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 40,
                            Email = "elvis.jagger@gov.nl",
                            FirstName = "Elvis",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 41,
                            Email = "kate.jagger@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 42,
                            Email = "kate.windsor@gov.gr",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 43,
                            Email = "donald.winslet@gov.nl",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 44,
                            Email = "donald.middleton@gov.us",
                            FirstName = "Donald",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 45,
                            Email = "kate.jagger@gov.nl",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 46,
                            Email = "kate.winslet@tesla.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 47,
                            Email = "mick.obama@bbc.co.uk",
                            FirstName = "Mick",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 48,
                            Email = "oprah.winfrey@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 49,
                            Email = "jimi.presley@gov.us",
                            FirstName = "Jimi",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 50,
                            Email = "oprah.trump@tesla.com",
                            FirstName = "Oprah",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 51,
                            Email = "donald.hepburn@something.com",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 52,
                            Email = "donald.hendrix@theworld.ca",
                            FirstName = "Donald",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 53,
                            Email = "barack.jagger@something.com",
                            FirstName = "Barack",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 54,
                            Email = "barack.winslet@gov.nl",
                            FirstName = "Barack",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 55,
                            Email = "kate.hepburn@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 56,
                            Email = "jimi.winfrey@gov.gr",
                            FirstName = "Jimi",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 57,
                            Email = "donald.trump@gov.gr",
                            FirstName = "Donald",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 58,
                            Email = "elvis.winslet@gov.us",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 59,
                            Email = "oprah.hepburn@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 60,
                            Email = "mick.middleton@bbc.co.uk",
                            FirstName = "Mick",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 61,
                            Email = "mick.winfrey@theworld.ca",
                            FirstName = "Mick",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 62,
                            Email = "kate.winslet@google.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 63,
                            Email = "jimi.trump@bbc.co.uk",
                            FirstName = "Jimi",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 64,
                            Email = "oprah.winfrey@something.com",
                            FirstName = "Oprah",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 65,
                            Email = "audrey.hepburn@gov.nl",
                            FirstName = "Audrey",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 66,
                            Email = "mick.winslet@gov.gr",
                            FirstName = "Mick",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 67,
                            Email = "kate.winfrey@bbc.co.uk",
                            FirstName = "Kate",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 68,
                            Email = "barack.presley@something.com",
                            FirstName = "Barack",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 69,
                            Email = "jimi.jagger@gov.us",
                            FirstName = "Jimi",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 70,
                            Email = "donald.winslet@tesla.com",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 71,
                            Email = "barack.winfrey@theworld.ca",
                            FirstName = "Barack",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 72,
                            Email = "jimi.hendrix@gov.ru",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 73,
                            Email = "kate.winfrey@theworld.ca",
                            FirstName = "Kate",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 74,
                            Email = "jimi.winfrey@tesla.com",
                            FirstName = "Jimi",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 75,
                            Email = "kate.windsor@google.com",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 76,
                            Email = "kate.windsor@gov.nl",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 77,
                            Email = "donald.winfrey@theworld.ca",
                            FirstName = "Donald",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 78,
                            Email = "donald.windsor@tesla.com",
                            FirstName = "Donald",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 79,
                            Email = "mick.hendrix@theworld.ca",
                            FirstName = "Mick",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 80,
                            Email = "elvis.presley@bbc.co.uk",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 81,
                            Email = "audrey.jagger@gov.gr",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 82,
                            Email = "charles.hepburn@gov.ru",
                            FirstName = "Charles",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 83,
                            Email = "mick.trump@something.com",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 84,
                            Email = "donald.trump@tesla.com",
                            FirstName = "Donald",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 85,
                            Email = "audrey.winslet@gov.us",
                            FirstName = "Audrey",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 86,
                            Email = "oprah.hepburn@google.com",
                            FirstName = "Oprah",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 87,
                            Email = "barack.hepburn@gov.gr",
                            FirstName = "Barack",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 88,
                            Email = "barack.trump@nasa.org.us",
                            FirstName = "Barack",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 89,
                            Email = "oprah.winfrey@gov.us",
                            FirstName = "Oprah",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 90,
                            Email = "charles.jagger@gov.nl",
                            FirstName = "Charles",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 91,
                            Email = "oprah.winfrey@nasa.org.us",
                            FirstName = "Oprah",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 92,
                            Email = "kate.hendrix@google.com",
                            FirstName = "Kate",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 93,
                            Email = "elvis.trump@theworld.ca",
                            FirstName = "Elvis",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 94,
                            Email = "donald.winslet@google.com",
                            FirstName = "Donald",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 95,
                            Email = "audrey.winslet@something.com",
                            FirstName = "Audrey",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 96,
                            Email = "kate.middleton@nasa.org.us",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 97,
                            Email = "oprah.hepburn@gov.gr",
                            FirstName = "Oprah",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 98,
                            Email = "mick.middleton@gov.nl",
                            FirstName = "Mick",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 99,
                            Email = "kate.winslet@gov.gr",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Book", b =>
                {
                    b.HasOne("exercise.webapi.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exercise.webapi.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId");

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("exercise.webapi.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("exercise.webapi.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
