using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    firstname = table.Column<string>(type: "text", nullable: false),
                    lastname = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "publishers",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_publishers", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    publisherid = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_publishers_publisherid",
                        column: x => x.publisherid,
                        principalTable: "publishers",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "AuthorBook",
                columns: table => new
                {
                    AuthorsId = table.Column<int>(type: "integer", nullable: false),
                    BooksId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_AuthorBook", x => new { x.AuthorsId, x.BooksId });
                    table.ForeignKey(
                        name: "FK_AuthorBook_authors_AuthorsId",
                        column: x => x.AuthorsId,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_AuthorBook_books_BooksId",
                        column: x => x.BooksId,
                        principalTable: "books",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "BookAuthors",
                columns: table => new
                {
                    bookid = table.Column<int>(type: "integer", nullable: false),
                    authorid = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BookAuthors", x => new { x.authorid, x.bookid });
                    table.ForeignKey(
                        name: "FK_BookAuthors_authors_authorid",
                        column: x => x.authorid,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_BookAuthors_books_bookid",
                        column: x => x.bookid,
                        principalTable: "books",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "authors",
                columns: new[] { "id", "email", "firstname", "lastname" },
                values: new object[,]
                {
                    { 1, "donald.winslet@something.com", "Donald", "Winslet" },
                    { 2, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 3, "audrey.winslet@gov.nl", "Audrey", "Winslet" },
                    { 4, "barack.winslet@nasa.org.us", "Barack", "Winslet" },
                    { 5, "oprah.trump@nasa.org.us", "Oprah", "Trump" },
                    { 6, "audrey.jagger@tesla.com", "Audrey", "Jagger" },
                    { 7, "oprah.hepburn@gov.ru", "Oprah", "Hepburn" },
                    { 8, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 9, "barack.trump@tesla.com", "Barack", "Trump" },
                    { 10, "barack.winfrey@gov.nl", "Barack", "Winfrey" },
                    { 11, "mick.hendrix@tesla.com", "Mick", "Hendrix" },
                    { 12, "mick.presley@gov.nl", "Mick", "Presley" },
                    { 13, "oprah.middleton@gov.ru", "Oprah", "Middleton" },
                    { 14, "donald.middleton@gov.gr", "Donald", "Middleton" },
                    { 15, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 16, "mick.obama@gov.nl", "Mick", "Obama" },
                    { 17, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 18, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 19, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 20, "elvis.winslet@gov.us", "Elvis", "Winslet" },
                    { 21, "audrey.jagger@nasa.org.us", "Audrey", "Jagger" },
                    { 22, "mick.winslet@nasa.org.us", "Mick", "Winslet" },
                    { 23, "oprah.jagger@gov.ru", "Oprah", "Jagger" },
                    { 24, "barack.winfrey@nasa.org.us", "Barack", "Winfrey" },
                    { 25, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 26, "barack.middleton@gov.us", "Barack", "Middleton" },
                    { 27, "oprah.jagger@gov.nl", "Oprah", "Jagger" },
                    { 28, "kate.obama@gov.us", "Kate", "Obama" },
                    { 29, "elvis.hendrix@google.com", "Elvis", "Hendrix" },
                    { 30, "donald.winfrey@something.com", "Donald", "Winfrey" },
                    { 31, "elvis.presley@bbc.co.uk", "Elvis", "Presley" },
                    { 32, "donald.jagger@theworld.ca", "Donald", "Jagger" },
                    { 33, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 34, "oprah.hepburn@gov.ru", "Oprah", "Hepburn" },
                    { 35, "donald.winslet@google.com", "Donald", "Winslet" },
                    { 36, "barack.hepburn@nasa.org.us", "Barack", "Hepburn" },
                    { 37, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 38, "donald.winfrey@something.com", "Donald", "Winfrey" },
                    { 39, "barack.middleton@google.com", "Barack", "Middleton" },
                    { 40, "elvis.presley@gov.gr", "Elvis", "Presley" },
                    { 41, "charles.winslet@something.com", "Charles", "Winslet" },
                    { 42, "kate.obama@tesla.com", "Kate", "Obama" },
                    { 43, "mick.hepburn@gov.gr", "Mick", "Hepburn" },
                    { 44, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 45, "audrey.windsor@gov.us", "Audrey", "Windsor" },
                    { 46, "donald.jagger@something.com", "Donald", "Jagger" },
                    { 47, "oprah.hepburn@google.com", "Oprah", "Hepburn" },
                    { 48, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 49, "mick.presley@bbc.co.uk", "Mick", "Presley" },
                    { 50, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 51, "elvis.trump@bbc.co.uk", "Elvis", "Trump" },
                    { 52, "elvis.presley@bbc.co.uk", "Elvis", "Presley" },
                    { 53, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 54, "audrey.windsor@bbc.co.uk", "Audrey", "Windsor" },
                    { 55, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 56, "elvis.obama@gov.nl", "Elvis", "Obama" },
                    { 57, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 58, "jimi.winslet@something.com", "Jimi", "Winslet" },
                    { 59, "barack.hepburn@nasa.org.us", "Barack", "Hepburn" },
                    { 60, "audrey.jagger@tesla.com", "Audrey", "Jagger" },
                    { 61, "charles.hendrix@google.com", "Charles", "Hendrix" },
                    { 62, "mick.hepburn@something.com", "Mick", "Hepburn" },
                    { 63, "barack.winfrey@tesla.com", "Barack", "Winfrey" },
                    { 64, "charles.obama@gov.ru", "Charles", "Obama" },
                    { 65, "oprah.winfrey@gov.us", "Oprah", "Winfrey" },
                    { 66, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 67, "barack.hendrix@gov.ru", "Barack", "Hendrix" },
                    { 68, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 69, "mick.middleton@gov.us", "Mick", "Middleton" },
                    { 70, "barack.winslet@gov.nl", "Barack", "Winslet" },
                    { 71, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 72, "kate.trump@gov.us", "Kate", "Trump" },
                    { 73, "mick.trump@something.com", "Mick", "Trump" },
                    { 74, "jimi.winfrey@bbc.co.uk", "Jimi", "Winfrey" },
                    { 75, "audrey.middleton@nasa.org.us", "Audrey", "Middleton" },
                    { 76, "elvis.hendrix@nasa.org.us", "Elvis", "Hendrix" },
                    { 77, "audrey.obama@nasa.org.us", "Audrey", "Obama" },
                    { 78, "elvis.trump@nasa.org.us", "Elvis", "Trump" },
                    { 79, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 80, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 81, "barack.trump@gov.us", "Barack", "Trump" },
                    { 82, "mick.winslet@gov.ru", "Mick", "Winslet" },
                    { 83, "elvis.presley@gov.nl", "Elvis", "Presley" },
                    { 84, "audrey.hepburn@tesla.com", "Audrey", "Hepburn" },
                    { 85, "donald.winslet@nasa.org.us", "Donald", "Winslet" },
                    { 86, "oprah.windsor@gov.us", "Oprah", "Windsor" },
                    { 87, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 88, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 89, "donald.winfrey@something.com", "Donald", "Winfrey" },
                    { 90, "elvis.trump@bbc.co.uk", "Elvis", "Trump" },
                    { 91, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 92, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 93, "donald.presley@something.com", "Donald", "Presley" },
                    { 94, "audrey.winfrey@gov.gr", "Audrey", "Winfrey" },
                    { 95, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 96, "jimi.trump@nasa.org.us", "Jimi", "Trump" },
                    { 97, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 98, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 99, "kate.trump@tesla.com", "Kate", "Trump" },
                    { 100, "barack.hendrix@gov.gr", "Barack", "Hendrix" },
                    { 101, "kate.hendrix@theworld.ca", "Kate", "Hendrix" },
                    { 102, "elvis.middleton@gov.ru", "Elvis", "Middleton" },
                    { 103, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 104, "kate.trump@bbc.co.uk", "Kate", "Trump" },
                    { 105, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 106, "elvis.trump@gov.nl", "Elvis", "Trump" },
                    { 107, "charles.obama@nasa.org.us", "Charles", "Obama" },
                    { 108, "barack.winslet@gov.gr", "Barack", "Winslet" },
                    { 109, "charles.winslet@gov.nl", "Charles", "Winslet" },
                    { 110, "audrey.winslet@theworld.ca", "Audrey", "Winslet" },
                    { 111, "audrey.presley@gov.nl", "Audrey", "Presley" },
                    { 112, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 113, "donald.hendrix@gov.us", "Donald", "Hendrix" },
                    { 114, "oprah.trump@bbc.co.uk", "Oprah", "Trump" },
                    { 115, "charles.jagger@theworld.ca", "Charles", "Jagger" },
                    { 116, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 117, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 118, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 119, "jimi.obama@gov.ru", "Jimi", "Obama" },
                    { 120, "oprah.winfrey@gov.us", "Oprah", "Winfrey" },
                    { 121, "donald.presley@bbc.co.uk", "Donald", "Presley" },
                    { 122, "mick.hendrix@nasa.org.us", "Mick", "Hendrix" },
                    { 123, "oprah.windsor@gov.ru", "Oprah", "Windsor" },
                    { 124, "audrey.hepburn@something.com", "Audrey", "Hepburn" },
                    { 125, "jimi.winslet@theworld.ca", "Jimi", "Winslet" },
                    { 126, "jimi.middleton@google.com", "Jimi", "Middleton" },
                    { 127, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 128, "donald.middleton@bbc.co.uk", "Donald", "Middleton" },
                    { 129, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 130, "oprah.winfrey@gov.gr", "Oprah", "Winfrey" },
                    { 131, "audrey.trump@bbc.co.uk", "Audrey", "Trump" },
                    { 132, "barack.hendrix@gov.gr", "Barack", "Hendrix" },
                    { 133, "elvis.jagger@tesla.com", "Elvis", "Jagger" },
                    { 134, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 135, "donald.obama@gov.us", "Donald", "Obama" },
                    { 136, "elvis.hepburn@gov.gr", "Elvis", "Hepburn" },
                    { 137, "donald.jagger@theworld.ca", "Donald", "Jagger" },
                    { 138, "audrey.obama@gov.ru", "Audrey", "Obama" },
                    { 139, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 140, "barack.hepburn@google.com", "Barack", "Hepburn" },
                    { 141, "elvis.windsor@bbc.co.uk", "Elvis", "Windsor" },
                    { 142, "mick.winslet@theworld.ca", "Mick", "Winslet" },
                    { 143, "jimi.hepburn@bbc.co.uk", "Jimi", "Hepburn" },
                    { 144, "jimi.hepburn@google.com", "Jimi", "Hepburn" },
                    { 145, "donald.winfrey@something.com", "Donald", "Winfrey" },
                    { 146, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 147, "mick.obama@gov.us", "Mick", "Obama" },
                    { 148, "kate.winfrey@tesla.com", "Kate", "Winfrey" },
                    { 149, "charles.jagger@gov.nl", "Charles", "Jagger" },
                    { 150, "charles.presley@something.com", "Charles", "Presley" },
                    { 151, "mick.winslet@google.com", "Mick", "Winslet" },
                    { 152, "barack.obama@bbc.co.uk", "Barack", "Obama" },
                    { 153, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 154, "donald.windsor@gov.gr", "Donald", "Windsor" },
                    { 155, "elvis.presley@gov.gr", "Elvis", "Presley" },
                    { 156, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 157, "elvis.trump@google.com", "Elvis", "Trump" },
                    { 158, "oprah.obama@something.com", "Oprah", "Obama" },
                    { 159, "barack.presley@gov.nl", "Barack", "Presley" },
                    { 160, "donald.trump@something.com", "Donald", "Trump" },
                    { 161, "elvis.hendrix@tesla.com", "Elvis", "Hendrix" },
                    { 162, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 163, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 164, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 165, "kate.trump@tesla.com", "Kate", "Trump" },
                    { 166, "charles.presley@theworld.ca", "Charles", "Presley" },
                    { 167, "oprah.winfrey@theworld.ca", "Oprah", "Winfrey" },
                    { 168, "jimi.obama@google.com", "Jimi", "Obama" },
                    { 169, "oprah.winslet@nasa.org.us", "Oprah", "Winslet" },
                    { 170, "mick.trump@gov.ru", "Mick", "Trump" },
                    { 171, "mick.winfrey@google.com", "Mick", "Winfrey" },
                    { 172, "mick.winslet@gov.nl", "Mick", "Winslet" },
                    { 173, "barack.jagger@tesla.com", "Barack", "Jagger" },
                    { 174, "donald.winslet@bbc.co.uk", "Donald", "Winslet" },
                    { 175, "donald.obama@gov.ru", "Donald", "Obama" },
                    { 176, "charles.obama@google.com", "Charles", "Obama" },
                    { 177, "donald.presley@gov.nl", "Donald", "Presley" },
                    { 178, "kate.middleton@nasa.org.us", "Kate", "Middleton" },
                    { 179, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 180, "audrey.jagger@bbc.co.uk", "Audrey", "Jagger" },
                    { 181, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 182, "audrey.winfrey@gov.us", "Audrey", "Winfrey" },
                    { 183, "kate.obama@gov.us", "Kate", "Obama" },
                    { 184, "mick.trump@tesla.com", "Mick", "Trump" },
                    { 185, "jimi.windsor@bbc.co.uk", "Jimi", "Windsor" },
                    { 186, "jimi.jagger@gov.ru", "Jimi", "Jagger" },
                    { 187, "jimi.presley@google.com", "Jimi", "Presley" },
                    { 188, "audrey.winslet@gov.nl", "Audrey", "Winslet" },
                    { 189, "barack.windsor@bbc.co.uk", "Barack", "Windsor" },
                    { 190, "oprah.middleton@something.com", "Oprah", "Middleton" },
                    { 191, "charles.obama@theworld.ca", "Charles", "Obama" },
                    { 192, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 193, "barack.trump@gov.nl", "Barack", "Trump" },
                    { 194, "barack.obama@google.com", "Barack", "Obama" },
                    { 195, "oprah.hendrix@gov.nl", "Oprah", "Hendrix" },
                    { 196, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 197, "mick.obama@gov.nl", "Mick", "Obama" },
                    { 198, "charles.windsor@google.com", "Charles", "Windsor" },
                    { 199, "oprah.hendrix@something.com", "Oprah", "Hendrix" },
                    { 200, "jimi.hepburn@gov.nl", "Jimi", "Hepburn" },
                    { 201, "audrey.obama@google.com", "Audrey", "Obama" },
                    { 202, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 203, "charles.presley@google.com", "Charles", "Presley" },
                    { 204, "elvis.hendrix@something.com", "Elvis", "Hendrix" },
                    { 205, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 206, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 207, "charles.presley@google.com", "Charles", "Presley" },
                    { 208, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 209, "barack.windsor@tesla.com", "Barack", "Windsor" },
                    { 210, "charles.jagger@theworld.ca", "Charles", "Jagger" },
                    { 211, "kate.presley@gov.us", "Kate", "Presley" },
                    { 212, "jimi.windsor@bbc.co.uk", "Jimi", "Windsor" },
                    { 213, "audrey.obama@gov.gr", "Audrey", "Obama" },
                    { 214, "elvis.jagger@bbc.co.uk", "Elvis", "Jagger" },
                    { 215, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 216, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 217, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 218, "oprah.middleton@gov.ru", "Oprah", "Middleton" },
                    { 219, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 220, "mick.trump@tesla.com", "Mick", "Trump" },
                    { 221, "jimi.middleton@bbc.co.uk", "Jimi", "Middleton" },
                    { 222, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 223, "mick.winfrey@gov.nl", "Mick", "Winfrey" },
                    { 224, "audrey.trump@nasa.org.us", "Audrey", "Trump" },
                    { 225, "elvis.obama@theworld.ca", "Elvis", "Obama" },
                    { 226, "oprah.winfrey@bbc.co.uk", "Oprah", "Winfrey" },
                    { 227, "barack.winfrey@gov.us", "Barack", "Winfrey" },
                    { 228, "donald.obama@bbc.co.uk", "Donald", "Obama" },
                    { 229, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 230, "audrey.winfrey@gov.ru", "Audrey", "Winfrey" },
                    { 231, "elvis.jagger@google.com", "Elvis", "Jagger" },
                    { 232, "jimi.trump@gov.ru", "Jimi", "Trump" },
                    { 233, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 234, "jimi.middleton@something.com", "Jimi", "Middleton" },
                    { 235, "jimi.obama@gov.us", "Jimi", "Obama" },
                    { 236, "donald.trump@nasa.org.us", "Donald", "Trump" },
                    { 237, "charles.trump@bbc.co.uk", "Charles", "Trump" },
                    { 238, "audrey.middleton@google.com", "Audrey", "Middleton" },
                    { 239, "elvis.windsor@bbc.co.uk", "Elvis", "Windsor" },
                    { 240, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 241, "elvis.winslet@gov.gr", "Elvis", "Winslet" },
                    { 242, "donald.hendrix@gov.ru", "Donald", "Hendrix" },
                    { 243, "barack.jagger@nasa.org.us", "Barack", "Jagger" },
                    { 244, "donald.hendrix@tesla.com", "Donald", "Hendrix" },
                    { 245, "barack.hendrix@gov.ru", "Barack", "Hendrix" },
                    { 246, "donald.winfrey@gov.us", "Donald", "Winfrey" },
                    { 247, "donald.obama@tesla.com", "Donald", "Obama" },
                    { 248, "jimi.windsor@gov.ru", "Jimi", "Windsor" },
                    { 249, "audrey.hepburn@gov.us", "Audrey", "Hepburn" }
                });

            migrationBuilder.InsertData(
                table: "publishers",
                columns: new[] { "id", "name" },
                values: new object[,]
                {
                    { 1, "Fifteen Orange Flowers" },
                    { 2, "Several Large Leopards" },
                    { 3, "Several Microscopic Leopards" },
                    { 4, "A bunch of Orange Planets" },
                    { 5, "Two Large Flowers" },
                    { 6, "The Microscopic Planets" },
                    { 7, "Fifteen Purple Cars" },
                    { 8, "Fifteen Orange Buildings" },
                    { 9, "A herd of Green Leopards" },
                    { 10, "A bunch of Green Leopards" },
                    { 11, "A herd of Rose Smelling Planets" },
                    { 12, "A herd of Bitter Houses" },
                    { 13, "Several Green Buildings" },
                    { 14, "Several Microscopic Cars" },
                    { 15, "A bunch of Microscopic Buildings" },
                    { 16, "The Purple Cars" },
                    { 17, "An army of Bitter Leopards" },
                    { 18, "A herd of Green Leopards" },
                    { 19, "The Bitter Leopards" },
                    { 20, "A herd of Bitter Cars" },
                    { 21, "An army of Bitter Buildings" },
                    { 22, "Several Orange Planets" },
                    { 23, "An army of Bitter Flowers" },
                    { 24, "The Bitter Flowers" },
                    { 25, "A herd of Transparent Buildings" },
                    { 26, "An army of Purple Cars" },
                    { 27, "Two Rose Smelling Planets" },
                    { 28, "Two Green Leopards" },
                    { 29, "A bunch of Green Houses" },
                    { 30, "Several Bitter Houses" },
                    { 31, "Several Rose Smelling Buildings" },
                    { 32, "Two Orange Buildings" },
                    { 33, "A bunch of Green Planets" },
                    { 34, "A herd of Bitter Flowers" },
                    { 35, "The Green Flowers" },
                    { 36, "Several Orange Planets" },
                    { 37, "Fifteen Green Planets" },
                    { 38, "A bunch of Bitter Flowers" },
                    { 39, "Two Bitter Cars" },
                    { 40, "An army of Rose Smelling Flowers" },
                    { 41, "A bunch of Green Cars" },
                    { 42, "Several Rose Smelling Cars" },
                    { 43, "Fifteen Rose Smelling Flowers" },
                    { 44, "A herd of Purple Buildings" },
                    { 45, "A herd of Bitter Buildings" },
                    { 46, "A herd of Bitter Buildings" },
                    { 47, "The Microscopic Leopards" },
                    { 48, "A herd of Large Leopards" },
                    { 49, "The Rose Smelling Cars" },
                    { 50, "The Microscopic Cars" },
                    { 51, "A bunch of Orange Flowers" },
                    { 52, "An army of Microscopic Flowers" },
                    { 53, "A herd of Transparent Houses" },
                    { 54, "An army of Green Houses" },
                    { 55, "An army of Transparent Planets" },
                    { 56, "Several Purple Cars" },
                    { 57, "Several Large Leopards" },
                    { 58, "The Orange Houses" },
                    { 59, "A bunch of Transparent Flowers" },
                    { 60, "A herd of Microscopic Houses" },
                    { 61, "Two Bitter Leopards" },
                    { 62, "Several Bitter Flowers" },
                    { 63, "Two Microscopic Cars" },
                    { 64, "A herd of Purple Flowers" },
                    { 65, "A bunch of Orange Buildings" },
                    { 66, "The Purple Houses" },
                    { 67, "An army of Transparent Cars" },
                    { 68, "An army of Large Planets" },
                    { 69, "The Orange Houses" },
                    { 70, "An army of Microscopic Flowers" },
                    { 71, "A bunch of Purple Cars" },
                    { 72, "A herd of Purple Houses" },
                    { 73, "A bunch of Bitter Flowers" },
                    { 74, "The Microscopic Buildings" },
                    { 75, "A bunch of Large Leopards" },
                    { 76, "An army of Bitter Leopards" },
                    { 77, "Fifteen Green Leopards" },
                    { 78, "The Green Buildings" },
                    { 79, "An army of Transparent Planets" },
                    { 80, "The Bitter Buildings" },
                    { 81, "Several Transparent Cars" },
                    { 82, "A herd of Transparent Planets" },
                    { 83, "The Transparent Houses" },
                    { 84, "A bunch of Purple Cars" },
                    { 85, "A bunch of Large Leopards" },
                    { 86, "Several Microscopic Cars" },
                    { 87, "Two Bitter Flowers" },
                    { 88, "Fifteen Microscopic Leopards" },
                    { 89, "A herd of Microscopic Buildings" },
                    { 90, "Two Green Buildings" },
                    { 91, "Several Orange Cars" },
                    { 92, "A bunch of Large Cars" },
                    { 93, "Two Green Planets" },
                    { 94, "A bunch of Microscopic Leopards" },
                    { 95, "Fifteen Green Cars" },
                    { 96, "Fifteen Microscopic Flowers" },
                    { 97, "Two Green Buildings" },
                    { 98, "Two Microscopic Planets" },
                    { 99, "A herd of Bitter Cars" },
                    { 100, "The Green Leopards" },
                    { 101, "An army of Green Houses" },
                    { 102, "Fifteen Microscopic Cars" },
                    { 103, "Several Large Leopards" },
                    { 104, "A herd of Transparent Flowers" },
                    { 105, "Fifteen Purple Cars" },
                    { 106, "An army of Transparent Buildings" },
                    { 107, "The Microscopic Houses" },
                    { 108, "Fifteen Microscopic Flowers" },
                    { 109, "A herd of Large Buildings" },
                    { 110, "A bunch of Microscopic Flowers" },
                    { 111, "A herd of Microscopic Buildings" },
                    { 112, "Several Purple Planets" },
                    { 113, "An army of Transparent Houses" },
                    { 114, "A herd of Green Flowers" },
                    { 115, "The Transparent Buildings" },
                    { 116, "The Rose Smelling Buildings" },
                    { 117, "Fifteen Bitter Planets" },
                    { 118, "Fifteen Green Buildings" },
                    { 119, "A bunch of Purple Buildings" },
                    { 120, "Fifteen Purple Planets" },
                    { 121, "The Large Planets" },
                    { 122, "Fifteen Purple Flowers" },
                    { 123, "Two Bitter Cars" },
                    { 124, "A bunch of Rose Smelling Leopards" },
                    { 125, "A herd of Large Buildings" },
                    { 126, "Two Orange Leopards" },
                    { 127, "An army of Rose Smelling Cars" },
                    { 128, "Fifteen Rose Smelling Buildings" },
                    { 129, "The Purple Houses" },
                    { 130, "The Transparent Houses" },
                    { 131, "Two Bitter Planets" },
                    { 132, "Two Green Leopards" },
                    { 133, "Several Rose Smelling Buildings" },
                    { 134, "Several Rose Smelling Buildings" },
                    { 135, "A bunch of Orange Buildings" },
                    { 136, "The Orange Planets" },
                    { 137, "A herd of Green Buildings" },
                    { 138, "Two Bitter Leopards" },
                    { 139, "The Green Leopards" },
                    { 140, "A herd of Rose Smelling Buildings" },
                    { 141, "Fifteen Purple Planets" },
                    { 142, "A herd of Orange Cars" },
                    { 143, "A herd of Microscopic Cars" },
                    { 144, "A bunch of Bitter Buildings" },
                    { 145, "Several Green Planets" },
                    { 146, "The Purple Houses" },
                    { 147, "The Rose Smelling Flowers" },
                    { 148, "The Transparent Flowers" },
                    { 149, "The Large Buildings" },
                    { 150, "Two Bitter Planets" },
                    { 151, "A bunch of Green Leopards" },
                    { 152, "Two Orange Buildings" },
                    { 153, "A herd of Transparent Flowers" },
                    { 154, "A herd of Large Flowers" },
                    { 155, "Fifteen Large Planets" },
                    { 156, "Fifteen Transparent Houses" },
                    { 157, "Two Purple Houses" },
                    { 158, "Fifteen Purple Buildings" },
                    { 159, "The Green Leopards" },
                    { 160, "A bunch of Bitter Flowers" },
                    { 161, "An army of Green Buildings" },
                    { 162, "A bunch of Orange Cars" },
                    { 163, "Several Microscopic Planets" },
                    { 164, "The Purple Leopards" },
                    { 165, "Fifteen Microscopic Flowers" },
                    { 166, "Fifteen Green Flowers" },
                    { 167, "Several Green Leopards" },
                    { 168, "The Rose Smelling Houses" },
                    { 169, "Several Transparent Buildings" },
                    { 170, "Several Transparent Planets" },
                    { 171, "An army of Purple Buildings" },
                    { 172, "A bunch of Bitter Buildings" },
                    { 173, "The Transparent Leopards" },
                    { 174, "Several Microscopic Houses" },
                    { 175, "Fifteen Green Houses" },
                    { 176, "A bunch of Large Houses" },
                    { 177, "A herd of Microscopic Planets" },
                    { 178, "A herd of Green Flowers" },
                    { 179, "Two Rose Smelling Planets" },
                    { 180, "Several Bitter Buildings" },
                    { 181, "A bunch of Bitter Cars" },
                    { 182, "A bunch of Purple Leopards" },
                    { 183, "The Purple Houses" },
                    { 184, "An army of Rose Smelling Flowers" },
                    { 185, "Fifteen Orange Houses" },
                    { 186, "A herd of Rose Smelling Leopards" },
                    { 187, "A bunch of Bitter Leopards" },
                    { 188, "A herd of Orange Leopards" },
                    { 189, "A herd of Microscopic Planets" },
                    { 190, "Several Rose Smelling Flowers" },
                    { 191, "A bunch of Bitter Leopards" },
                    { 192, "A herd of Microscopic Planets" },
                    { 193, "A herd of Purple Planets" },
                    { 194, "Two Purple Leopards" },
                    { 195, "An army of Orange Leopards" },
                    { 196, "An army of Large Flowers" },
                    { 197, "The Green Buildings" },
                    { 198, "A herd of Green Cars" },
                    { 199, "Several Transparent Planets" },
                    { 200, "A herd of Orange Leopards" },
                    { 201, "The Bitter Houses" },
                    { 202, "An army of Green Flowers" },
                    { 203, "An army of Transparent Leopards" },
                    { 204, "The Large Houses" },
                    { 205, "Several Large Houses" },
                    { 206, "Fifteen Purple Cars" },
                    { 207, "Fifteen Purple Flowers" },
                    { 208, "Fifteen Purple Leopards" },
                    { 209, "A bunch of Large Buildings" },
                    { 210, "A herd of Purple Houses" },
                    { 211, "A herd of Bitter Leopards" },
                    { 212, "Fifteen Large Buildings" },
                    { 213, "A bunch of Large Cars" },
                    { 214, "Two Purple Flowers" },
                    { 215, "Two Large Planets" },
                    { 216, "Fifteen Green Leopards" },
                    { 217, "A herd of Microscopic Flowers" },
                    { 218, "An army of Purple Buildings" },
                    { 219, "Fifteen Purple Cars" },
                    { 220, "Several Purple Flowers" },
                    { 221, "A bunch of Rose Smelling Buildings" },
                    { 222, "Several Orange Flowers" },
                    { 223, "An army of Purple Buildings" },
                    { 224, "Two Transparent Planets" },
                    { 225, "An army of Orange Planets" },
                    { 226, "A herd of Purple Flowers" },
                    { 227, "A bunch of Rose Smelling Houses" },
                    { 228, "Two Large Planets" },
                    { 229, "A bunch of Microscopic Leopards" },
                    { 230, "The Large Buildings" },
                    { 231, "Two Transparent Cars" },
                    { 232, "A herd of Large Buildings" },
                    { 233, "Several Orange Buildings" },
                    { 234, "Several Rose Smelling Planets" },
                    { 235, "Several Large Planets" },
                    { 236, "An army of Large Cars" },
                    { 237, "A herd of Microscopic Buildings" },
                    { 238, "A bunch of Microscopic Flowers" },
                    { 239, "Two Transparent Houses" },
                    { 240, "Several Transparent Buildings" },
                    { 241, "Fifteen Microscopic Cars" },
                    { 242, "Two Large Houses" },
                    { 243, "Fifteen Orange Cars" },
                    { 244, "A herd of Microscopic Buildings" },
                    { 245, "Several Purple Flowers" },
                    { 246, "The Purple Planets" },
                    { 247, "Two Purple Leopards" },
                    { 248, "A herd of Transparent Houses" },
                    { 249, "Several Transparent Cars" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "publisherid", "title" },
                values: new object[,]
                {
                    { 1, 185, "A herd of Transparent Flowers" },
                    { 2, 178, "Two Green Leopards" },
                    { 3, 100, "Two Large Flowers" },
                    { 4, 135, "A herd of Transparent Houses" },
                    { 5, 55, "A herd of Green Houses" },
                    { 6, 43, "An army of Purple Buildings" },
                    { 7, 114, "The Rose Smelling Planets" },
                    { 8, 25, "The Orange Buildings" },
                    { 9, 175, "Two Bitter Houses" },
                    { 10, 154, "An army of Rose Smelling Buildings" },
                    { 11, 224, "Several Microscopic Flowers" },
                    { 12, 143, "Several Green Flowers" },
                    { 13, 31, "A bunch of Transparent Cars" },
                    { 14, 155, "An army of Large Houses" },
                    { 15, 19, "Two Purple Buildings" },
                    { 16, 224, "Several Rose Smelling Leopards" },
                    { 17, 57, "Fifteen Bitter Cars" },
                    { 18, 228, "Two Purple Cars" },
                    { 19, 225, "Several Orange Flowers" },
                    { 20, 78, "The Microscopic Leopards" },
                    { 21, 213, "Two Rose Smelling Flowers" },
                    { 22, 237, "The Orange Planets" },
                    { 23, 108, "Several Purple Cars" },
                    { 24, 131, "A bunch of Rose Smelling Flowers" },
                    { 25, 218, "An army of Rose Smelling Leopards" },
                    { 26, 91, "The Microscopic Planets" },
                    { 27, 95, "A herd of Green Cars" },
                    { 28, 30, "A herd of Microscopic Flowers" },
                    { 29, 223, "The Rose Smelling Leopards" },
                    { 30, 168, "Two Rose Smelling Flowers" },
                    { 31, 148, "An army of Rose Smelling Planets" },
                    { 32, 239, "An army of Microscopic Flowers" },
                    { 33, 238, "Several Large Houses" },
                    { 34, 130, "The Rose Smelling Planets" },
                    { 35, 152, "A herd of Orange Flowers" },
                    { 36, 127, "Two Purple Houses" },
                    { 37, 78, "The Transparent Houses" },
                    { 38, 136, "The Rose Smelling Cars" },
                    { 39, 39, "The Orange Planets" },
                    { 40, 196, "The Transparent Cars" },
                    { 41, 169, "An army of Orange Flowers" },
                    { 42, 207, "A bunch of Orange Buildings" },
                    { 43, 47, "A bunch of Orange Houses" },
                    { 44, 69, "A herd of Bitter Buildings" },
                    { 45, 77, "An army of Transparent Flowers" },
                    { 46, 173, "Two Microscopic Cars" },
                    { 47, 11, "An army of Rose Smelling Planets" },
                    { 48, 245, "Two Bitter Cars" },
                    { 49, 53, "Several Transparent Buildings" },
                    { 50, 162, "The Bitter Flowers" },
                    { 51, 81, "Two Large Houses" },
                    { 52, 81, "A bunch of Bitter Cars" },
                    { 53, 97, "Several Rose Smelling Planets" },
                    { 54, 171, "An army of Orange Leopards" },
                    { 55, 185, "Fifteen Microscopic Cars" },
                    { 56, 8, "The Transparent Houses" },
                    { 57, 200, "An army of Bitter Cars" },
                    { 58, 44, "Fifteen Rose Smelling Cars" },
                    { 59, 83, "An army of Large Houses" },
                    { 60, 218, "A herd of Purple Flowers" },
                    { 61, 219, "A herd of Green Planets" },
                    { 62, 129, "The Transparent Leopards" },
                    { 63, 64, "A bunch of Bitter Buildings" },
                    { 64, 135, "A bunch of Transparent Cars" },
                    { 65, 164, "The Transparent Buildings" },
                    { 66, 127, "A bunch of Orange Cars" },
                    { 67, 55, "A bunch of Transparent Leopards" },
                    { 68, 217, "Several Orange Planets" },
                    { 69, 148, "Fifteen Bitter Buildings" },
                    { 70, 85, "The Large Leopards" },
                    { 71, 192, "A bunch of Orange Flowers" },
                    { 72, 80, "Several Purple Houses" },
                    { 73, 96, "An army of Rose Smelling Buildings" },
                    { 74, 47, "The Large Leopards" },
                    { 75, 150, "The Purple Houses" },
                    { 76, 197, "Several Rose Smelling Leopards" },
                    { 77, 2, "A herd of Bitter Cars" },
                    { 78, 154, "A bunch of Purple Houses" },
                    { 79, 139, "Fifteen Orange Buildings" },
                    { 80, 178, "Two Large Cars" },
                    { 81, 136, "Fifteen Microscopic Houses" },
                    { 82, 76, "The Green Buildings" },
                    { 83, 187, "A bunch of Large Planets" },
                    { 84, 101, "Several Microscopic Flowers" },
                    { 85, 246, "Two Orange Leopards" },
                    { 86, 178, "Two Bitter Buildings" },
                    { 87, 63, "Several Green Cars" },
                    { 88, 155, "A bunch of Microscopic Houses" },
                    { 89, 120, "A bunch of Purple Planets" },
                    { 90, 22, "Two Purple Houses" },
                    { 91, 249, "A herd of Rose Smelling Cars" },
                    { 92, 246, "A herd of Green Leopards" },
                    { 93, 170, "Several Microscopic Flowers" },
                    { 94, 123, "A bunch of Purple Buildings" },
                    { 95, 227, "Two Bitter Houses" },
                    { 96, 229, "A herd of Purple Leopards" },
                    { 97, 92, "The Purple Cars" },
                    { 98, 18, "An army of Microscopic Flowers" },
                    { 99, 131, "Several Rose Smelling Houses" },
                    { 100, 172, "The Green Houses" },
                    { 101, 105, "Two Bitter Flowers" },
                    { 102, 8, "Two Orange Leopards" },
                    { 103, 19, "Several Bitter Buildings" },
                    { 104, 178, "Several Orange Buildings" },
                    { 105, 189, "Fifteen Large Houses" },
                    { 106, 168, "Two Microscopic Leopards" },
                    { 107, 212, "A bunch of Transparent Cars" },
                    { 108, 219, "Fifteen Bitter Leopards" },
                    { 109, 181, "A bunch of Purple Leopards" },
                    { 110, 54, "Two Bitter Buildings" },
                    { 111, 237, "Fifteen Large Flowers" },
                    { 112, 40, "Fifteen Large Flowers" },
                    { 113, 164, "An army of Bitter Houses" },
                    { 114, 226, "A herd of Rose Smelling Cars" },
                    { 115, 198, "A herd of Orange Flowers" },
                    { 116, 154, "A herd of Orange Planets" },
                    { 117, 4, "A herd of Transparent Buildings" },
                    { 118, 78, "Two Bitter Leopards" },
                    { 119, 227, "The Microscopic Houses" },
                    { 120, 175, "Several Transparent Leopards" },
                    { 121, 162, "Two Bitter Cars" },
                    { 122, 171, "The Orange Buildings" },
                    { 123, 185, "Two Purple Leopards" },
                    { 124, 159, "The Green Leopards" },
                    { 125, 220, "The Rose Smelling Houses" },
                    { 126, 139, "An army of Large Flowers" },
                    { 127, 93, "A bunch of Orange Leopards" },
                    { 128, 13, "An army of Transparent Leopards" },
                    { 129, 165, "An army of Green Flowers" },
                    { 130, 89, "A herd of Microscopic Houses" },
                    { 131, 110, "Two Orange Flowers" },
                    { 132, 133, "The Large Cars" },
                    { 133, 62, "Fifteen Bitter Houses" },
                    { 134, 14, "A bunch of Large Cars" },
                    { 135, 60, "A bunch of Rose Smelling Flowers" },
                    { 136, 84, "A bunch of Large Buildings" },
                    { 137, 140, "The Rose Smelling Buildings" },
                    { 138, 139, "A bunch of Microscopic Planets" },
                    { 139, 117, "A herd of Transparent Cars" },
                    { 140, 44, "Several Large Houses" },
                    { 141, 219, "Fifteen Orange Leopards" },
                    { 142, 55, "An army of Rose Smelling Houses" },
                    { 143, 150, "A herd of Large Flowers" },
                    { 144, 206, "A herd of Large Leopards" },
                    { 145, 192, "Several Purple Planets" },
                    { 146, 182, "A herd of Bitter Cars" },
                    { 147, 104, "A herd of Purple Buildings" },
                    { 148, 150, "Fifteen Purple Cars" },
                    { 149, 71, "A bunch of Orange Flowers" },
                    { 150, 59, "A herd of Orange Houses" },
                    { 151, 85, "A herd of Microscopic Houses" },
                    { 152, 189, "An army of Rose Smelling Houses" },
                    { 153, 117, "The Purple Flowers" },
                    { 154, 153, "Several Purple Cars" },
                    { 155, 94, "A bunch of Orange Planets" },
                    { 156, 26, "The Rose Smelling Buildings" },
                    { 157, 200, "Several Rose Smelling Houses" },
                    { 158, 65, "An army of Purple Flowers" },
                    { 159, 140, "A herd of Bitter Leopards" },
                    { 160, 104, "Two Green Cars" },
                    { 161, 153, "The Orange Buildings" },
                    { 162, 177, "Two Rose Smelling Buildings" },
                    { 163, 17, "Several Rose Smelling Buildings" },
                    { 164, 111, "A herd of Large Planets" },
                    { 165, 154, "An army of Green Flowers" },
                    { 166, 148, "A bunch of Orange Leopards" },
                    { 167, 104, "Fifteen Microscopic Planets" },
                    { 168, 96, "Several Purple Buildings" },
                    { 169, 189, "A bunch of Green Buildings" },
                    { 170, 60, "The Transparent Leopards" },
                    { 171, 136, "Two Microscopic Planets" },
                    { 172, 1, "The Green Houses" },
                    { 173, 53, "Fifteen Rose Smelling Cars" },
                    { 174, 98, "The Microscopic Cars" },
                    { 175, 34, "The Transparent Leopards" },
                    { 176, 50, "A bunch of Green Flowers" },
                    { 177, 130, "Two Rose Smelling Houses" },
                    { 178, 74, "Several Transparent Leopards" },
                    { 179, 3, "Fifteen Purple Cars" },
                    { 180, 9, "The Transparent Cars" },
                    { 181, 142, "Two Rose Smelling Buildings" },
                    { 182, 165, "A herd of Rose Smelling Flowers" },
                    { 183, 247, "Several Orange Flowers" },
                    { 184, 62, "Fifteen Microscopic Houses" },
                    { 185, 134, "Several Rose Smelling Leopards" },
                    { 186, 137, "Fifteen Orange Flowers" },
                    { 187, 220, "The Microscopic Houses" },
                    { 188, 89, "The Large Cars" },
                    { 189, 22, "The Transparent Leopards" },
                    { 190, 145, "A herd of Green Leopards" },
                    { 191, 207, "Fifteen Purple Flowers" },
                    { 192, 118, "Two Bitter Leopards" },
                    { 193, 51, "A herd of Orange Cars" },
                    { 194, 90, "The Large Leopards" },
                    { 195, 47, "Several Purple Buildings" },
                    { 196, 198, "Two Green Flowers" },
                    { 197, 140, "A herd of Purple Cars" },
                    { 198, 86, "Several Rose Smelling Houses" },
                    { 199, 40, "A bunch of Bitter Leopards" },
                    { 200, 172, "An army of Purple Cars" },
                    { 201, 238, "Several Large Planets" },
                    { 202, 49, "Fifteen Purple Houses" },
                    { 203, 211, "A bunch of Large Cars" },
                    { 204, 21, "Fifteen Rose Smelling Buildings" },
                    { 205, 183, "Fifteen Microscopic Buildings" },
                    { 206, 3, "The Rose Smelling Houses" },
                    { 207, 11, "A herd of Bitter Leopards" },
                    { 208, 102, "Fifteen Rose Smelling Buildings" },
                    { 209, 9, "Two Purple Planets" },
                    { 210, 87, "Several Transparent Leopards" },
                    { 211, 232, "An army of Bitter Houses" },
                    { 212, 161, "A herd of Orange Houses" },
                    { 213, 210, "A herd of Large Leopards" },
                    { 214, 37, "Two Large Planets" },
                    { 215, 41, "Two Large Planets" },
                    { 216, 246, "The Green Planets" },
                    { 217, 101, "Two Large Cars" },
                    { 218, 131, "An army of Bitter Planets" },
                    { 219, 33, "An army of Large Leopards" },
                    { 220, 157, "Fifteen Microscopic Buildings" },
                    { 221, 178, "Several Large Buildings" },
                    { 222, 118, "Several Large Flowers" },
                    { 223, 187, "Fifteen Transparent Buildings" },
                    { 224, 217, "Fifteen Large Buildings" },
                    { 225, 151, "The Green Leopards" },
                    { 226, 199, "A herd of Bitter Planets" },
                    { 227, 136, "A herd of Purple Planets" },
                    { 228, 62, "A bunch of Transparent Buildings" },
                    { 229, 107, "The Microscopic Leopards" },
                    { 230, 103, "An army of Large Flowers" },
                    { 231, 152, "A bunch of Rose Smelling Buildings" },
                    { 232, 246, "A bunch of Large Buildings" },
                    { 233, 128, "Fifteen Rose Smelling Buildings" },
                    { 234, 111, "An army of Purple Cars" },
                    { 235, 107, "The Large Planets" },
                    { 236, 115, "Two Purple Planets" },
                    { 237, 112, "Fifteen Orange Planets" },
                    { 238, 17, "The Green Buildings" },
                    { 239, 133, "A bunch of Green Houses" },
                    { 240, 32, "Two Green Houses" },
                    { 241, 97, "A herd of Transparent Planets" },
                    { 242, 161, "The Green Buildings" },
                    { 243, 126, "The Orange Buildings" },
                    { 244, 48, "The Purple Flowers" },
                    { 245, 94, "Fifteen Transparent Houses" },
                    { 246, 110, "Two Rose Smelling Planets" },
                    { 247, 218, "The Large Flowers" },
                    { 248, 82, "An army of Microscopic Leopards" },
                    { 249, 186, "The Microscopic Planets" }
                });

            migrationBuilder.InsertData(
                table: "BookAuthors",
                columns: new[] { "authorid", "bookid" },
                values: new object[] { 1, 1 });

            migrationBuilder.CreateIndex(
                name: "IX_AuthorBook_BooksId",
                table: "AuthorBook",
                column: "BooksId");

            migrationBuilder.CreateIndex(
                name: "IX_BookAuthors_bookid",
                table: "BookAuthors",
                column: "bookid");

            migrationBuilder.CreateIndex(
                name: "IX_books_publisherid",
                table: "books",
                column: "publisherid");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "AuthorBook");

            migrationBuilder.DropTable(
                name: "BookAuthors");

            migrationBuilder.DropTable(
                name: "authors");

            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "publishers");
        }
    }
}
