using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class createdAuthor : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "author",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    first_name = table.Column<string>(type: "text", nullable: false),
                    last_name = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_author", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "publisher",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false),
                    contact_details = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_publisher", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "book",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    author_id = table.Column<int>(type: "integer", nullable: false),
                    publisher_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_book", x => x.id);
                    table.ForeignKey(
                        name: "FK_book_author_author_id",
                        column: x => x.author_id,
                        principalTable: "author",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_book_publisher_publisher_id",
                        column: x => x.publisher_id,
                        principalTable: "publisher",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "author",
                columns: new[] { "id", "email", "first_name", "last_name" },
                values: new object[,]
                {
                    { 1, "audrey.trump@bbc.co.uk", "Audrey", "Trump" },
                    { 2, "mick.windsor@bbc.co.uk", "Mick", "Windsor" },
                    { 3, "barack.winslet@theworld.ca", "Barack", "Winslet" },
                    { 4, "barack.hepburn@theworld.ca", "Barack", "Hepburn" },
                    { 5, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 6, "barack.middleton@theworld.ca", "Barack", "Middleton" },
                    { 7, "charles.windsor@gov.nl", "Charles", "Windsor" },
                    { 8, "mick.hepburn@nasa.org.us", "Mick", "Hepburn" },
                    { 9, "donald.winfrey@theworld.ca", "Donald", "Winfrey" },
                    { 10, "kate.hepburn@nasa.org.us", "Kate", "Hepburn" },
                    { 11, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 12, "charles.middleton@gov.gr", "Charles", "Middleton" },
                    { 13, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 14, "oprah.obama@nasa.org.us", "Oprah", "Obama" },
                    { 15, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 16, "jimi.presley@google.com", "Jimi", "Presley" },
                    { 17, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 18, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 19, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 20, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 21, "donald.presley@gov.ru", "Donald", "Presley" },
                    { 22, "kate.trump@tesla.com", "Kate", "Trump" },
                    { 23, "kate.obama@something.com", "Kate", "Obama" },
                    { 24, "jimi.windsor@gov.nl", "Jimi", "Windsor" },
                    { 25, "jimi.hepburn@nasa.org.us", "Jimi", "Hepburn" },
                    { 26, "charles.jagger@gov.us", "Charles", "Jagger" },
                    { 27, "barack.presley@gov.nl", "Barack", "Presley" },
                    { 28, "donald.trump@gov.gr", "Donald", "Trump" },
                    { 29, "jimi.presley@gov.ru", "Jimi", "Presley" },
                    { 30, "mick.winfrey@gov.gr", "Mick", "Winfrey" },
                    { 31, "oprah.trump@google.com", "Oprah", "Trump" },
                    { 32, "audrey.middleton@tesla.com", "Audrey", "Middleton" },
                    { 33, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 34, "mick.winfrey@gov.gr", "Mick", "Winfrey" },
                    { 35, "mick.trump@gov.gr", "Mick", "Trump" },
                    { 36, "oprah.trump@tesla.com", "Oprah", "Trump" },
                    { 37, "jimi.middleton@something.com", "Jimi", "Middleton" },
                    { 38, "mick.obama@google.com", "Mick", "Obama" },
                    { 39, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 40, "jimi.presley@gov.us", "Jimi", "Presley" },
                    { 41, "donald.presley@gov.ru", "Donald", "Presley" },
                    { 42, "barack.hendrix@bbc.co.uk", "Barack", "Hendrix" },
                    { 43, "donald.winslet@gov.us", "Donald", "Winslet" },
                    { 44, "charles.windsor@gov.us", "Charles", "Windsor" },
                    { 45, "donald.hepburn@gov.nl", "Donald", "Hepburn" },
                    { 46, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 47, "donald.presley@bbc.co.uk", "Donald", "Presley" },
                    { 48, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 49, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 50, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 51, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 52, "donald.trump@gov.us", "Donald", "Trump" },
                    { 53, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 54, "oprah.winslet@google.com", "Oprah", "Winslet" },
                    { 55, "barack.winfrey@gov.us", "Barack", "Winfrey" },
                    { 56, "mick.jagger@gov.nl", "Mick", "Jagger" },
                    { 57, "elvis.jagger@nasa.org.us", "Elvis", "Jagger" },
                    { 58, "oprah.winfrey@something.com", "Oprah", "Winfrey" },
                    { 59, "oprah.hendrix@google.com", "Oprah", "Hendrix" },
                    { 60, "donald.hendrix@something.com", "Donald", "Hendrix" },
                    { 61, "donald.presley@bbc.co.uk", "Donald", "Presley" },
                    { 62, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 63, "elvis.obama@tesla.com", "Elvis", "Obama" },
                    { 64, "audrey.middleton@google.com", "Audrey", "Middleton" },
                    { 65, "oprah.hendrix@gov.ru", "Oprah", "Hendrix" },
                    { 66, "barack.jagger@google.com", "Barack", "Jagger" },
                    { 67, "audrey.winslet@google.com", "Audrey", "Winslet" },
                    { 68, "donald.presley@gov.us", "Donald", "Presley" },
                    { 69, "kate.middleton@tesla.com", "Kate", "Middleton" },
                    { 70, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 71, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 72, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 73, "donald.hendrix@theworld.ca", "Donald", "Hendrix" },
                    { 74, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 75, "oprah.presley@gov.us", "Oprah", "Presley" },
                    { 76, "mick.winslet@tesla.com", "Mick", "Winslet" },
                    { 77, "audrey.winslet@gov.ru", "Audrey", "Winslet" },
                    { 78, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 79, "donald.trump@tesla.com", "Donald", "Trump" },
                    { 80, "barack.obama@theworld.ca", "Barack", "Obama" },
                    { 81, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 82, "jimi.hepburn@something.com", "Jimi", "Hepburn" },
                    { 83, "oprah.presley@nasa.org.us", "Oprah", "Presley" },
                    { 84, "mick.obama@gov.nl", "Mick", "Obama" },
                    { 85, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 86, "charles.hepburn@gov.us", "Charles", "Hepburn" },
                    { 87, "jimi.windsor@nasa.org.us", "Jimi", "Windsor" },
                    { 88, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 89, "barack.winslet@something.com", "Barack", "Winslet" },
                    { 90, "jimi.trump@theworld.ca", "Jimi", "Trump" },
                    { 91, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 92, "elvis.middleton@nasa.org.us", "Elvis", "Middleton" },
                    { 93, "audrey.trump@nasa.org.us", "Audrey", "Trump" },
                    { 94, "oprah.obama@gov.ru", "Oprah", "Obama" },
                    { 95, "kate.winfrey@bbc.co.uk", "Kate", "Winfrey" },
                    { 96, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 97, "oprah.trump@gov.gr", "Oprah", "Trump" },
                    { 98, "donald.presley@something.com", "Donald", "Presley" },
                    { 99, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 100, "donald.jagger@tesla.com", "Donald", "Jagger" },
                    { 101, "audrey.presley@gov.us", "Audrey", "Presley" },
                    { 102, "mick.winfrey@theworld.ca", "Mick", "Winfrey" },
                    { 103, "charles.presley@bbc.co.uk", "Charles", "Presley" },
                    { 104, "oprah.winslet@tesla.com", "Oprah", "Winslet" },
                    { 105, "barack.jagger@gov.ru", "Barack", "Jagger" },
                    { 106, "elvis.obama@google.com", "Elvis", "Obama" },
                    { 107, "elvis.presley@gov.gr", "Elvis", "Presley" },
                    { 108, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 109, "mick.presley@gov.gr", "Mick", "Presley" },
                    { 110, "jimi.hendrix@theworld.ca", "Jimi", "Hendrix" },
                    { 111, "barack.obama@tesla.com", "Barack", "Obama" },
                    { 112, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 113, "elvis.obama@gov.us", "Elvis", "Obama" },
                    { 114, "oprah.obama@google.com", "Oprah", "Obama" },
                    { 115, "oprah.winslet@gov.nl", "Oprah", "Winslet" },
                    { 116, "donald.middleton@gov.ru", "Donald", "Middleton" },
                    { 117, "mick.windsor@tesla.com", "Mick", "Windsor" },
                    { 118, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 119, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 120, "barack.presley@theworld.ca", "Barack", "Presley" },
                    { 121, "jimi.middleton@gov.ru", "Jimi", "Middleton" },
                    { 122, "audrey.presley@gov.ru", "Audrey", "Presley" },
                    { 123, "charles.middleton@gov.gr", "Charles", "Middleton" },
                    { 124, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 125, "oprah.winslet@gov.nl", "Oprah", "Winslet" },
                    { 126, "barack.presley@nasa.org.us", "Barack", "Presley" },
                    { 127, "barack.presley@theworld.ca", "Barack", "Presley" },
                    { 128, "mick.hepburn@tesla.com", "Mick", "Hepburn" },
                    { 129, "charles.trump@gov.us", "Charles", "Trump" },
                    { 130, "audrey.middleton@something.com", "Audrey", "Middleton" },
                    { 131, "jimi.obama@something.com", "Jimi", "Obama" },
                    { 132, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 133, "audrey.hepburn@tesla.com", "Audrey", "Hepburn" },
                    { 134, "kate.presley@gov.nl", "Kate", "Presley" },
                    { 135, "mick.middleton@bbc.co.uk", "Mick", "Middleton" },
                    { 136, "oprah.winslet@bbc.co.uk", "Oprah", "Winslet" },
                    { 137, "jimi.hepburn@something.com", "Jimi", "Hepburn" },
                    { 138, "mick.hepburn@google.com", "Mick", "Hepburn" },
                    { 139, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 140, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 141, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 142, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 143, "donald.middleton@gov.us", "Donald", "Middleton" },
                    { 144, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 145, "audrey.jagger@gov.nl", "Audrey", "Jagger" },
                    { 146, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 147, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 148, "donald.presley@gov.nl", "Donald", "Presley" },
                    { 149, "elvis.middleton@gov.us", "Elvis", "Middleton" },
                    { 150, "audrey.hepburn@bbc.co.uk", "Audrey", "Hepburn" },
                    { 151, "audrey.middleton@theworld.ca", "Audrey", "Middleton" },
                    { 152, "audrey.hendrix@google.com", "Audrey", "Hendrix" },
                    { 153, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 154, "kate.trump@google.com", "Kate", "Trump" },
                    { 155, "barack.windsor@theworld.ca", "Barack", "Windsor" },
                    { 156, "kate.obama@something.com", "Kate", "Obama" },
                    { 157, "donald.winfrey@gov.gr", "Donald", "Winfrey" },
                    { 158, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 159, "charles.winslet@bbc.co.uk", "Charles", "Winslet" },
                    { 160, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 161, "audrey.presley@google.com", "Audrey", "Presley" },
                    { 162, "elvis.presley@gov.ru", "Elvis", "Presley" },
                    { 163, "elvis.obama@tesla.com", "Elvis", "Obama" },
                    { 164, "charles.hendrix@tesla.com", "Charles", "Hendrix" },
                    { 165, "charles.obama@gov.us", "Charles", "Obama" },
                    { 166, "jimi.hendrix@something.com", "Jimi", "Hendrix" },
                    { 167, "kate.trump@tesla.com", "Kate", "Trump" },
                    { 168, "kate.trump@something.com", "Kate", "Trump" },
                    { 169, "donald.middleton@gov.gr", "Donald", "Middleton" },
                    { 170, "barack.middleton@something.com", "Barack", "Middleton" },
                    { 171, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 172, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 173, "donald.windsor@google.com", "Donald", "Windsor" },
                    { 174, "charles.winfrey@nasa.org.us", "Charles", "Winfrey" },
                    { 175, "charles.hendrix@gov.gr", "Charles", "Hendrix" },
                    { 176, "audrey.windsor@something.com", "Audrey", "Windsor" },
                    { 177, "oprah.winfrey@gov.ru", "Oprah", "Winfrey" },
                    { 178, "audrey.trump@tesla.com", "Audrey", "Trump" },
                    { 179, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 180, "oprah.jagger@nasa.org.us", "Oprah", "Jagger" },
                    { 181, "elvis.windsor@gov.nl", "Elvis", "Windsor" },
                    { 182, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 183, "oprah.obama@gov.nl", "Oprah", "Obama" },
                    { 184, "jimi.trump@google.com", "Jimi", "Trump" },
                    { 185, "barack.hepburn@gov.ru", "Barack", "Hepburn" },
                    { 186, "donald.middleton@something.com", "Donald", "Middleton" },
                    { 187, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 188, "oprah.presley@gov.ru", "Oprah", "Presley" },
                    { 189, "kate.middleton@gov.us", "Kate", "Middleton" },
                    { 190, "donald.presley@gov.nl", "Donald", "Presley" },
                    { 191, "donald.obama@google.com", "Donald", "Obama" },
                    { 192, "donald.windsor@gov.ru", "Donald", "Windsor" },
                    { 193, "jimi.obama@tesla.com", "Jimi", "Obama" },
                    { 194, "elvis.winslet@gov.nl", "Elvis", "Winslet" },
                    { 195, "barack.winfrey@something.com", "Barack", "Winfrey" },
                    { 196, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 197, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 198, "donald.hepburn@tesla.com", "Donald", "Hepburn" },
                    { 199, "donald.middleton@theworld.ca", "Donald", "Middleton" },
                    { 200, "elvis.hendrix@gov.gr", "Elvis", "Hendrix" },
                    { 201, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 202, "donald.trump@gov.gr", "Donald", "Trump" },
                    { 203, "oprah.winslet@tesla.com", "Oprah", "Winslet" },
                    { 204, "mick.hepburn@tesla.com", "Mick", "Hepburn" },
                    { 205, "kate.obama@google.com", "Kate", "Obama" },
                    { 206, "elvis.winfrey@something.com", "Elvis", "Winfrey" },
                    { 207, "barack.hepburn@gov.ru", "Barack", "Hepburn" },
                    { 208, "charles.obama@google.com", "Charles", "Obama" },
                    { 209, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 210, "charles.middleton@something.com", "Charles", "Middleton" },
                    { 211, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 212, "mick.winslet@something.com", "Mick", "Winslet" },
                    { 213, "jimi.jagger@bbc.co.uk", "Jimi", "Jagger" },
                    { 214, "elvis.windsor@gov.us", "Elvis", "Windsor" },
                    { 215, "audrey.winfrey@gov.us", "Audrey", "Winfrey" },
                    { 216, "barack.windsor@google.com", "Barack", "Windsor" },
                    { 217, "jimi.jagger@gov.us", "Jimi", "Jagger" },
                    { 218, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 219, "barack.winslet@theworld.ca", "Barack", "Winslet" },
                    { 220, "donald.hendrix@tesla.com", "Donald", "Hendrix" },
                    { 221, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 222, "mick.hepburn@theworld.ca", "Mick", "Hepburn" },
                    { 223, "oprah.presley@something.com", "Oprah", "Presley" },
                    { 224, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 225, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 226, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 227, "barack.windsor@gov.gr", "Barack", "Windsor" },
                    { 228, "mick.presley@gov.nl", "Mick", "Presley" },
                    { 229, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 230, "kate.winslet@tesla.com", "Kate", "Winslet" },
                    { 231, "mick.hepburn@nasa.org.us", "Mick", "Hepburn" },
                    { 232, "jimi.windsor@nasa.org.us", "Jimi", "Windsor" },
                    { 233, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 234, "barack.hepburn@tesla.com", "Barack", "Hepburn" },
                    { 235, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 236, "donald.windsor@tesla.com", "Donald", "Windsor" },
                    { 237, "barack.trump@gov.ru", "Barack", "Trump" },
                    { 238, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 239, "donald.winslet@gov.ru", "Donald", "Winslet" },
                    { 240, "oprah.jagger@theworld.ca", "Oprah", "Jagger" },
                    { 241, "audrey.winslet@nasa.org.us", "Audrey", "Winslet" },
                    { 242, "donald.trump@theworld.ca", "Donald", "Trump" },
                    { 243, "jimi.obama@bbc.co.uk", "Jimi", "Obama" },
                    { 244, "elvis.winfrey@google.com", "Elvis", "Winfrey" },
                    { 245, "mick.middleton@nasa.org.us", "Mick", "Middleton" },
                    { 246, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 247, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 248, "mick.presley@gov.gr", "Mick", "Presley" },
                    { 249, "charles.hepburn@gov.nl", "Charles", "Hepburn" }
                });

            migrationBuilder.InsertData(
                table: "publisher",
                columns: new[] { "id", "contact_details", "name" },
                values: new object[,]
                {
                    { 1, "microscopic@gov.us", "Flowers A herd of" },
                    { 2, "purple@gov.us", "Houses The" },
                    { 3, "orange@gov.ru", "Planets A herd of" },
                    { 4, "green@gov.gr", "Leopards A bunch of" },
                    { 5, "orange@tesla.com", "Leopards The" },
                    { 6, "green@tesla.com", "Planets Several" },
                    { 7, "green@gov.nl", "Cars The" },
                    { 8, "green@bbc.co.uk", "Buildings Several" },
                    { 9, "green@google.com", "Leopards Two" },
                    { 10, "orange@gov.ru", "Cars The" },
                    { 11, "microscopic@tesla.com", "Buildings Two" },
                    { 12, "transparent@gov.ru", "Cars A herd of" },
                    { 13, "large@gov.gr", "Buildings A herd of" },
                    { 14, "bitter@google.com", "Houses A bunch of" },
                    { 15, "purple@google.com", "Cars Fifteen" },
                    { 16, "rose smelling@gov.nl", "Houses An army of" },
                    { 17, "bitter@nasa.org.us", "Flowers Two" },
                    { 18, "purple@gov.gr", "Cars Fifteen" },
                    { 19, "microscopic@nasa.org.us", "Houses Several" },
                    { 20, "rose smelling@bbc.co.uk", "Houses An army of" },
                    { 21, "rose smelling@nasa.org.us", "Planets An army of" },
                    { 22, "orange@nasa.org.us", "Flowers An army of" },
                    { 23, "large@gov.ru", "Leopards A bunch of" },
                    { 24, "green@gov.ru", "Cars The" },
                    { 25, "bitter@theworld.ca", "Flowers Fifteen" },
                    { 26, "microscopic@nasa.org.us", "Houses Fifteen" },
                    { 27, "rose smelling@tesla.com", "Leopards A bunch of" },
                    { 28, "transparent@theworld.ca", "Buildings A herd of" },
                    { 29, "purple@gov.ru", "Cars An army of" },
                    { 30, "purple@something.com", "Flowers Two" },
                    { 31, "transparent@gov.ru", "Cars Fifteen" },
                    { 32, "rose smelling@google.com", "Leopards A bunch of" },
                    { 33, "microscopic@gov.gr", "Planets Several" },
                    { 34, "purple@tesla.com", "Flowers An army of" },
                    { 35, "bitter@tesla.com", "Flowers Two" },
                    { 36, "bitter@tesla.com", "Cars The" },
                    { 37, "transparent@nasa.org.us", "Buildings Two" },
                    { 38, "bitter@gov.us", "Planets An army of" },
                    { 39, "transparent@gov.us", "Buildings Two" },
                    { 40, "purple@something.com", "Planets A bunch of" },
                    { 41, "transparent@gov.us", "Leopards The" },
                    { 42, "bitter@something.com", "Flowers The" },
                    { 43, "rose smelling@gov.nl", "Flowers An army of" },
                    { 44, "transparent@tesla.com", "Leopards Two" },
                    { 45, "transparent@nasa.org.us", "Leopards The" },
                    { 46, "bitter@gov.us", "Planets An army of" },
                    { 47, "microscopic@google.com", "Cars Several" },
                    { 48, "green@bbc.co.uk", "Planets The" },
                    { 49, "large@google.com", "Flowers Two" },
                    { 50, "transparent@nasa.org.us", "Planets An army of" },
                    { 51, "orange@gov.ru", "Houses Several" },
                    { 52, "purple@theworld.ca", "Planets Two" },
                    { 53, "rose smelling@gov.ru", "Cars Two" },
                    { 54, "bitter@google.com", "Leopards Several" },
                    { 55, "microscopic@tesla.com", "Leopards Two" },
                    { 56, "green@something.com", "Buildings The" },
                    { 57, "green@gov.ru", "Buildings A bunch of" },
                    { 58, "rose smelling@gov.gr", "Leopards An army of" },
                    { 59, "orange@something.com", "Leopards A herd of" },
                    { 60, "purple@gov.gr", "Planets The" },
                    { 61, "orange@gov.gr", "Leopards Several" },
                    { 62, "green@bbc.co.uk", "Flowers A bunch of" },
                    { 63, "orange@gov.us", "Leopards Several" },
                    { 64, "purple@nasa.org.us", "Leopards The" },
                    { 65, "bitter@gov.us", "Cars The" },
                    { 66, "purple@nasa.org.us", "Houses A bunch of" },
                    { 67, "green@theworld.ca", "Leopards The" },
                    { 68, "bitter@google.com", "Buildings An army of" },
                    { 69, "green@gov.us", "Leopards Two" },
                    { 70, "large@bbc.co.uk", "Flowers Several" },
                    { 71, "large@gov.us", "Cars Two" },
                    { 72, "green@gov.us", "Flowers A bunch of" },
                    { 73, "transparent@gov.gr", "Leopards Fifteen" },
                    { 74, "purple@tesla.com", "Leopards A bunch of" },
                    { 75, "bitter@gov.ru", "Planets Two" },
                    { 76, "green@nasa.org.us", "Cars Several" },
                    { 77, "large@tesla.com", "Cars Fifteen" },
                    { 78, "large@nasa.org.us", "Houses Fifteen" },
                    { 79, "microscopic@something.com", "Cars A herd of" },
                    { 80, "purple@gov.ru", "Leopards A bunch of" },
                    { 81, "orange@nasa.org.us", "Leopards A bunch of" },
                    { 82, "green@something.com", "Planets An army of" },
                    { 83, "transparent@tesla.com", "Houses A bunch of" },
                    { 84, "bitter@bbc.co.uk", "Houses The" },
                    { 85, "orange@gov.nl", "Flowers Fifteen" },
                    { 86, "orange@theworld.ca", "Cars An army of" },
                    { 87, "orange@nasa.org.us", "Houses Fifteen" },
                    { 88, "green@tesla.com", "Planets The" },
                    { 89, "orange@gov.nl", "Leopards Fifteen" },
                    { 90, "bitter@bbc.co.uk", "Houses Two" },
                    { 91, "bitter@gov.nl", "Cars The" },
                    { 92, "large@gov.us", "Flowers An army of" },
                    { 93, "rose smelling@theworld.ca", "Planets A herd of" },
                    { 94, "rose smelling@something.com", "Flowers Several" },
                    { 95, "rose smelling@gov.nl", "Planets A bunch of" },
                    { 96, "bitter@gov.nl", "Leopards A bunch of" },
                    { 97, "rose smelling@nasa.org.us", "Leopards Two" },
                    { 98, "orange@tesla.com", "Flowers A bunch of" },
                    { 99, "green@nasa.org.us", "Houses A herd of" },
                    { 100, "bitter@gov.gr", "Houses A herd of" },
                    { 101, "rose smelling@google.com", "Buildings Two" },
                    { 102, "transparent@nasa.org.us", "Flowers Fifteen" },
                    { 103, "bitter@gov.us", "Planets An army of" },
                    { 104, "large@bbc.co.uk", "Planets Two" },
                    { 105, "rose smelling@bbc.co.uk", "Buildings A herd of" },
                    { 106, "rose smelling@google.com", "Buildings An army of" },
                    { 107, "orange@theworld.ca", "Houses Fifteen" },
                    { 108, "microscopic@bbc.co.uk", "Leopards Fifteen" },
                    { 109, "large@theworld.ca", "Buildings An army of" },
                    { 110, "transparent@theworld.ca", "Planets An army of" },
                    { 111, "green@google.com", "Leopards The" },
                    { 112, "large@theworld.ca", "Buildings The" },
                    { 113, "purple@google.com", "Leopards A bunch of" },
                    { 114, "transparent@gov.us", "Flowers Several" },
                    { 115, "orange@gov.nl", "Leopards Fifteen" },
                    { 116, "purple@theworld.ca", "Leopards Several" },
                    { 117, "microscopic@gov.us", "Cars An army of" },
                    { 118, "bitter@gov.gr", "Houses Several" },
                    { 119, "bitter@gov.us", "Buildings Two" },
                    { 120, "large@tesla.com", "Cars The" },
                    { 121, "large@nasa.org.us", "Buildings A herd of" },
                    { 122, "green@theworld.ca", "Cars An army of" },
                    { 123, "orange@gov.us", "Buildings An army of" },
                    { 124, "large@nasa.org.us", "Buildings Two" },
                    { 125, "purple@bbc.co.uk", "Flowers Two" },
                    { 126, "orange@gov.ru", "Houses The" },
                    { 127, "orange@gov.gr", "Cars An army of" },
                    { 128, "purple@gov.ru", "Flowers Fifteen" },
                    { 129, "microscopic@google.com", "Houses Two" },
                    { 130, "orange@something.com", "Flowers Two" },
                    { 131, "large@gov.gr", "Buildings Several" },
                    { 132, "transparent@bbc.co.uk", "Leopards An army of" },
                    { 133, "microscopic@gov.nl", "Leopards Two" },
                    { 134, "rose smelling@gov.us", "Cars A bunch of" },
                    { 135, "microscopic@gov.ru", "Buildings A herd of" },
                    { 136, "large@google.com", "Houses The" },
                    { 137, "orange@gov.nl", "Leopards An army of" },
                    { 138, "purple@gov.gr", "Buildings Several" },
                    { 139, "large@tesla.com", "Planets Two" },
                    { 140, "transparent@something.com", "Buildings Several" },
                    { 141, "microscopic@gov.gr", "Leopards Two" },
                    { 142, "microscopic@gov.us", "Houses An army of" },
                    { 143, "bitter@bbc.co.uk", "Buildings Fifteen" },
                    { 144, "transparent@gov.gr", "Cars Fifteen" },
                    { 145, "purple@theworld.ca", "Planets A herd of" },
                    { 146, "large@gov.nl", "Buildings Several" },
                    { 147, "rose smelling@gov.nl", "Buildings Two" },
                    { 148, "purple@gov.gr", "Buildings A herd of" },
                    { 149, "transparent@theworld.ca", "Buildings An army of" },
                    { 150, "green@tesla.com", "Cars Several" },
                    { 151, "rose smelling@bbc.co.uk", "Leopards A herd of" },
                    { 152, "microscopic@tesla.com", "Planets Two" },
                    { 153, "rose smelling@gov.us", "Leopards A bunch of" },
                    { 154, "large@theworld.ca", "Flowers The" },
                    { 155, "bitter@something.com", "Leopards An army of" },
                    { 156, "orange@tesla.com", "Buildings An army of" },
                    { 157, "orange@gov.us", "Houses A herd of" },
                    { 158, "green@gov.nl", "Leopards The" },
                    { 159, "microscopic@gov.us", "Leopards A herd of" },
                    { 160, "large@nasa.org.us", "Cars Several" },
                    { 161, "large@gov.gr", "Flowers An army of" },
                    { 162, "transparent@google.com", "Cars Several" },
                    { 163, "transparent@google.com", "Buildings Two" },
                    { 164, "microscopic@theworld.ca", "Houses An army of" },
                    { 165, "rose smelling@google.com", "Cars A herd of" },
                    { 166, "microscopic@nasa.org.us", "Leopards The" },
                    { 167, "purple@gov.nl", "Houses The" },
                    { 168, "transparent@tesla.com", "Planets A bunch of" },
                    { 169, "purple@gov.gr", "Planets A herd of" },
                    { 170, "rose smelling@something.com", "Houses Several" },
                    { 171, "purple@something.com", "Cars A herd of" },
                    { 172, "rose smelling@gov.us", "Planets An army of" },
                    { 173, "microscopic@nasa.org.us", "Planets Several" },
                    { 174, "microscopic@tesla.com", "Buildings The" },
                    { 175, "microscopic@tesla.com", "Houses Several" },
                    { 176, "microscopic@theworld.ca", "Houses A herd of" },
                    { 177, "large@gov.gr", "Planets The" },
                    { 178, "purple@theworld.ca", "Buildings A herd of" },
                    { 179, "bitter@tesla.com", "Buildings The" },
                    { 180, "transparent@nasa.org.us", "Planets Fifteen" },
                    { 181, "purple@gov.ru", "Leopards A herd of" },
                    { 182, "green@gov.nl", "Planets An army of" },
                    { 183, "purple@gov.ru", "Cars Two" },
                    { 184, "purple@gov.nl", "Leopards An army of" },
                    { 185, "microscopic@gov.ru", "Buildings Two" },
                    { 186, "large@tesla.com", "Cars Fifteen" },
                    { 187, "rose smelling@gov.nl", "Leopards The" },
                    { 188, "large@tesla.com", "Cars A herd of" },
                    { 189, "rose smelling@bbc.co.uk", "Planets A bunch of" },
                    { 190, "rose smelling@google.com", "Cars Several" },
                    { 191, "purple@nasa.org.us", "Cars An army of" },
                    { 192, "large@google.com", "Houses Several" },
                    { 193, "purple@google.com", "Leopards Fifteen" },
                    { 194, "green@tesla.com", "Leopards A herd of" },
                    { 195, "large@gov.nl", "Houses Several" },
                    { 196, "bitter@nasa.org.us", "Planets An army of" },
                    { 197, "green@nasa.org.us", "Flowers Several" },
                    { 198, "orange@gov.nl", "Cars Two" },
                    { 199, "green@gov.ru", "Planets An army of" },
                    { 200, "large@gov.gr", "Flowers A bunch of" },
                    { 201, "rose smelling@nasa.org.us", "Houses A bunch of" },
                    { 202, "orange@something.com", "Planets Two" },
                    { 203, "rose smelling@gov.ru", "Houses Fifteen" },
                    { 204, "microscopic@bbc.co.uk", "Houses A bunch of" },
                    { 205, "purple@tesla.com", "Planets Two" },
                    { 206, "transparent@gov.nl", "Buildings An army of" },
                    { 207, "green@something.com", "Cars Several" },
                    { 208, "microscopic@gov.nl", "Flowers Several" },
                    { 209, "purple@gov.ru", "Leopards The" },
                    { 210, "purple@google.com", "Leopards The" },
                    { 211, "rose smelling@something.com", "Buildings Fifteen" },
                    { 212, "transparent@bbc.co.uk", "Cars Several" },
                    { 213, "microscopic@google.com", "Flowers A bunch of" },
                    { 214, "purple@gov.nl", "Houses Fifteen" },
                    { 215, "green@theworld.ca", "Leopards A bunch of" },
                    { 216, "orange@tesla.com", "Planets A bunch of" },
                    { 217, "rose smelling@gov.ru", "Planets Fifteen" },
                    { 218, "orange@gov.us", "Leopards A herd of" },
                    { 219, "large@google.com", "Cars Fifteen" },
                    { 220, "large@bbc.co.uk", "Buildings Fifteen" },
                    { 221, "green@gov.nl", "Flowers Fifteen" },
                    { 222, "microscopic@theworld.ca", "Cars Several" },
                    { 223, "green@something.com", "Flowers Two" },
                    { 224, "purple@gov.ru", "Planets Several" },
                    { 225, "orange@theworld.ca", "Buildings An army of" },
                    { 226, "bitter@theworld.ca", "Cars An army of" },
                    { 227, "microscopic@gov.nl", "Flowers The" },
                    { 228, "bitter@nasa.org.us", "Cars Several" },
                    { 229, "purple@bbc.co.uk", "Cars Several" },
                    { 230, "rose smelling@gov.nl", "Flowers A herd of" },
                    { 231, "microscopic@nasa.org.us", "Houses The" },
                    { 232, "purple@gov.gr", "Houses Fifteen" },
                    { 233, "purple@bbc.co.uk", "Planets An army of" },
                    { 234, "bitter@nasa.org.us", "Houses Two" },
                    { 235, "bitter@nasa.org.us", "Leopards Two" },
                    { 236, "purple@theworld.ca", "Houses A bunch of" },
                    { 237, "green@tesla.com", "Buildings Fifteen" },
                    { 238, "rose smelling@gov.nl", "Planets A herd of" },
                    { 239, "bitter@google.com", "Cars A herd of" },
                    { 240, "rose smelling@gov.ru", "Planets Fifteen" },
                    { 241, "purple@theworld.ca", "Flowers A bunch of" },
                    { 242, "orange@gov.us", "Cars Fifteen" },
                    { 243, "green@nasa.org.us", "Planets Two" },
                    { 244, "green@nasa.org.us", "Cars Fifteen" },
                    { 245, "rose smelling@nasa.org.us", "Leopards Fifteen" },
                    { 246, "large@tesla.com", "Flowers A bunch of" },
                    { 247, "transparent@something.com", "Flowers An army of" },
                    { 248, "orange@tesla.com", "Planets A herd of" },
                    { 249, "large@google.com", "Planets The" }
                });

            migrationBuilder.InsertData(
                table: "book",
                columns: new[] { "id", "author_id", "publisher_id", "title" },
                values: new object[,]
                {
                    { 1, 237, 26, "Fifteen Large Leopards" },
                    { 2, 168, 191, "Fifteen Orange Houses" },
                    { 3, 200, 150, "The Transparent Houses" },
                    { 4, 81, 65, "Fifteen Transparent Houses" },
                    { 5, 236, 195, "The Purple Houses" },
                    { 6, 1, 24, "A herd of Orange Buildings" },
                    { 7, 156, 177, "A herd of Orange Buildings" },
                    { 8, 39, 139, "Two Transparent Buildings" },
                    { 9, 200, 93, "An army of Purple Cars" },
                    { 10, 43, 144, "Several Purple Buildings" },
                    { 11, 36, 32, "Two Green Leopards" },
                    { 12, 33, 60, "Several Purple Planets" },
                    { 13, 162, 81, "A bunch of Bitter Flowers" },
                    { 14, 196, 206, "Fifteen Purple Leopards" },
                    { 15, 201, 16, "An army of Rose Smelling Planets" },
                    { 16, 2, 136, "An army of Green Planets" },
                    { 17, 156, 232, "Two Transparent Houses" },
                    { 18, 149, 36, "A bunch of Rose Smelling Buildings" },
                    { 19, 64, 244, "An army of Large Cars" },
                    { 20, 24, 109, "A herd of Rose Smelling Houses" },
                    { 21, 184, 23, "A herd of Microscopic Flowers" },
                    { 22, 109, 109, "Fifteen Purple Buildings" },
                    { 23, 208, 14, "Several Green Buildings" },
                    { 24, 146, 213, "Fifteen Microscopic Cars" },
                    { 25, 10, 175, "Several Transparent Leopards" },
                    { 26, 219, 119, "A herd of Green Cars" },
                    { 27, 225, 110, "The Large Houses" },
                    { 28, 53, 5, "An army of Microscopic Leopards" },
                    { 29, 240, 74, "Several Transparent Planets" },
                    { 30, 20, 46, "An army of Microscopic Houses" },
                    { 31, 102, 219, "Several Purple Houses" },
                    { 32, 23, 61, "Two Purple Houses" },
                    { 33, 84, 80, "A bunch of Bitter Flowers" },
                    { 34, 3, 41, "A herd of Transparent Leopards" },
                    { 35, 185, 106, "The Transparent Planets" },
                    { 36, 173, 232, "The Rose Smelling Buildings" },
                    { 37, 49, 8, "Several Rose Smelling Planets" },
                    { 38, 180, 157, "The Purple Cars" },
                    { 39, 191, 54, "A herd of Transparent Planets" },
                    { 40, 163, 238, "Two Microscopic Cars" },
                    { 41, 228, 22, "The Large Planets" },
                    { 42, 104, 224, "Several Green Leopards" },
                    { 43, 7, 4, "Several Microscopic Flowers" },
                    { 44, 137, 132, "A bunch of Large Flowers" },
                    { 45, 35, 212, "An army of Purple Planets" },
                    { 46, 139, 225, "A herd of Large Houses" },
                    { 47, 206, 163, "An army of Large Planets" },
                    { 48, 38, 89, "Several Bitter Buildings" },
                    { 49, 15, 174, "Several Transparent Cars" },
                    { 50, 203, 116, "Several Transparent Buildings" },
                    { 51, 112, 63, "The Microscopic Flowers" },
                    { 52, 225, 224, "Fifteen Orange Cars" },
                    { 53, 119, 89, "The Transparent Houses" },
                    { 54, 118, 196, "Fifteen Orange Leopards" },
                    { 55, 214, 62, "Several Green Leopards" },
                    { 56, 107, 214, "Fifteen Large Buildings" },
                    { 57, 244, 196, "An army of Large Cars" },
                    { 58, 111, 143, "An army of Orange Cars" },
                    { 59, 217, 243, "A bunch of Microscopic Buildings" },
                    { 60, 71, 95, "An army of Transparent Cars" },
                    { 61, 33, 168, "A herd of Bitter Buildings" },
                    { 62, 56, 249, "Several Rose Smelling Leopards" },
                    { 63, 15, 45, "Two Green Planets" },
                    { 64, 121, 202, "Fifteen Microscopic Houses" },
                    { 65, 8, 6, "The Purple Houses" },
                    { 66, 225, 163, "The Orange Cars" },
                    { 67, 183, 216, "Several Purple Leopards" },
                    { 68, 57, 74, "Two Purple Leopards" },
                    { 69, 149, 66, "Fifteen Green Flowers" },
                    { 70, 72, 39, "A bunch of Purple Cars" },
                    { 71, 34, 132, "A herd of Transparent Cars" },
                    { 72, 154, 106, "Two Orange Cars" },
                    { 73, 214, 155, "Several Green Planets" },
                    { 74, 148, 152, "A herd of Microscopic Flowers" },
                    { 75, 38, 147, "Fifteen Rose Smelling Planets" },
                    { 76, 227, 185, "A herd of Bitter Cars" },
                    { 77, 193, 228, "Several Rose Smelling Buildings" },
                    { 78, 142, 106, "Several Microscopic Leopards" },
                    { 79, 17, 149, "Two Bitter Houses" },
                    { 80, 188, 177, "Fifteen Bitter Buildings" },
                    { 81, 20, 66, "The Bitter Cars" },
                    { 82, 200, 181, "Two Rose Smelling Houses" },
                    { 83, 50, 102, "An army of Transparent Leopards" },
                    { 84, 73, 228, "An army of Bitter Leopards" },
                    { 85, 235, 155, "Several Rose Smelling Flowers" },
                    { 86, 62, 240, "An army of Large Flowers" },
                    { 87, 119, 49, "An army of Microscopic Houses" },
                    { 88, 4, 143, "Several Orange Cars" },
                    { 89, 151, 151, "The Microscopic Buildings" },
                    { 90, 106, 149, "A bunch of Bitter Buildings" },
                    { 91, 76, 232, "Fifteen Microscopic Buildings" },
                    { 92, 81, 238, "An army of Orange Houses" },
                    { 93, 67, 123, "The Bitter Buildings" },
                    { 94, 35, 40, "Two Transparent Planets" },
                    { 95, 135, 39, "Fifteen Transparent Leopards" },
                    { 96, 219, 232, "Several Bitter Buildings" },
                    { 97, 110, 144, "Fifteen Large Houses" },
                    { 98, 139, 114, "The Microscopic Buildings" },
                    { 99, 93, 226, "An army of Bitter Leopards" },
                    { 100, 215, 184, "Two Microscopic Planets" },
                    { 101, 115, 86, "Several Purple Planets" },
                    { 102, 105, 111, "A bunch of Bitter Flowers" },
                    { 103, 75, 136, "An army of Large Flowers" },
                    { 104, 65, 68, "An army of Green Leopards" },
                    { 105, 25, 28, "A herd of Transparent Planets" },
                    { 106, 69, 240, "An army of Rose Smelling Houses" },
                    { 107, 207, 99, "Fifteen Bitter Houses" },
                    { 108, 95, 187, "Several Bitter Buildings" },
                    { 109, 198, 89, "A herd of Rose Smelling Leopards" },
                    { 110, 229, 15, "Fifteen Green Houses" },
                    { 111, 247, 214, "An army of Green Houses" },
                    { 112, 29, 1, "The Large Buildings" },
                    { 113, 12, 248, "The Green Flowers" },
                    { 114, 225, 52, "An army of Purple Flowers" },
                    { 115, 137, 22, "A bunch of Purple Planets" },
                    { 116, 185, 56, "An army of Rose Smelling Planets" },
                    { 117, 143, 137, "Fifteen Purple Houses" },
                    { 118, 199, 102, "Two Green Houses" },
                    { 119, 48, 61, "Several Transparent Buildings" },
                    { 120, 134, 168, "The Large Houses" },
                    { 121, 91, 60, "A bunch of Microscopic Buildings" },
                    { 122, 168, 116, "A herd of Large Leopards" },
                    { 123, 141, 1, "Two Rose Smelling Cars" },
                    { 124, 181, 34, "Fifteen Orange Flowers" },
                    { 125, 128, 32, "The Microscopic Houses" },
                    { 126, 249, 216, "A herd of Microscopic Leopards" },
                    { 127, 227, 146, "A herd of Transparent Cars" },
                    { 128, 139, 3, "Several Bitter Planets" },
                    { 129, 10, 33, "An army of Green Houses" },
                    { 130, 40, 232, "A bunch of Orange Houses" },
                    { 131, 128, 111, "A herd of Microscopic Leopards" },
                    { 132, 27, 164, "Several Purple Houses" },
                    { 133, 237, 179, "An army of Microscopic Leopards" },
                    { 134, 146, 168, "Two Rose Smelling Cars" },
                    { 135, 127, 48, "The Orange Leopards" },
                    { 136, 65, 205, "The Microscopic Leopards" },
                    { 137, 127, 200, "A bunch of Transparent Houses" },
                    { 138, 161, 163, "A bunch of Green Cars" },
                    { 139, 103, 176, "The Large Flowers" },
                    { 140, 200, 168, "An army of Large Houses" },
                    { 141, 82, 198, "Fifteen Large Houses" },
                    { 142, 50, 122, "Two Large Houses" },
                    { 143, 140, 143, "A herd of Purple Cars" },
                    { 144, 133, 211, "A herd of Rose Smelling Leopards" },
                    { 145, 185, 230, "A bunch of Bitter Planets" },
                    { 146, 49, 67, "A bunch of Purple Houses" },
                    { 147, 217, 56, "Fifteen Orange Buildings" },
                    { 148, 178, 109, "Fifteen Rose Smelling Leopards" },
                    { 149, 8, 93, "Fifteen Purple Flowers" },
                    { 150, 34, 102, "A herd of Large Planets" },
                    { 151, 159, 148, "The Green Planets" },
                    { 152, 228, 209, "A herd of Large Cars" },
                    { 153, 144, 186, "An army of Green Houses" },
                    { 154, 64, 205, "Fifteen Orange Leopards" },
                    { 155, 235, 214, "The Orange Houses" },
                    { 156, 189, 113, "An army of Transparent Houses" },
                    { 157, 53, 165, "Fifteen Purple Houses" },
                    { 158, 91, 198, "Several Transparent Planets" },
                    { 159, 40, 193, "The Microscopic Leopards" },
                    { 160, 173, 210, "A bunch of Transparent Planets" },
                    { 161, 137, 66, "The Transparent Flowers" },
                    { 162, 32, 137, "An army of Green Cars" },
                    { 163, 187, 57, "Fifteen Microscopic Flowers" },
                    { 164, 52, 183, "The Transparent Houses" },
                    { 165, 72, 14, "The Orange Cars" },
                    { 166, 177, 232, "Fifteen Rose Smelling Houses" },
                    { 167, 152, 198, "A bunch of Transparent Buildings" },
                    { 168, 161, 23, "A bunch of Bitter Cars" },
                    { 169, 168, 79, "An army of Orange Buildings" },
                    { 170, 102, 28, "A herd of Bitter Flowers" },
                    { 171, 57, 126, "Two Large Flowers" },
                    { 172, 223, 143, "Two Green Leopards" },
                    { 173, 5, 165, "The Microscopic Buildings" },
                    { 174, 110, 137, "A bunch of Rose Smelling Cars" },
                    { 175, 204, 217, "A herd of Microscopic Leopards" },
                    { 176, 215, 237, "Two Green Buildings" },
                    { 177, 119, 12, "A bunch of Purple Leopards" },
                    { 178, 189, 99, "A bunch of Transparent Leopards" },
                    { 179, 131, 10, "Several Rose Smelling Cars" },
                    { 180, 191, 230, "Two Microscopic Flowers" },
                    { 181, 202, 106, "A bunch of Microscopic Planets" },
                    { 182, 61, 30, "The Microscopic Planets" },
                    { 183, 5, 71, "The Bitter Flowers" },
                    { 184, 69, 103, "An army of Green Houses" },
                    { 185, 74, 67, "The Bitter Buildings" },
                    { 186, 221, 239, "Two Orange Planets" },
                    { 187, 55, 5, "An army of Purple Cars" },
                    { 188, 120, 54, "Two Green Flowers" },
                    { 189, 168, 140, "A herd of Microscopic Planets" },
                    { 190, 10, 226, "A bunch of Transparent Leopards" },
                    { 191, 230, 33, "An army of Orange Planets" },
                    { 192, 234, 93, "Two Rose Smelling Leopards" },
                    { 193, 246, 132, "The Rose Smelling Flowers" },
                    { 194, 164, 109, "An army of Transparent Planets" },
                    { 195, 61, 73, "The Rose Smelling Cars" },
                    { 196, 241, 144, "An army of Transparent Leopards" },
                    { 197, 172, 189, "Fifteen Green Cars" },
                    { 198, 96, 240, "Fifteen Large Buildings" },
                    { 199, 199, 220, "Several Green Cars" },
                    { 200, 78, 15, "An army of Large Houses" },
                    { 201, 218, 1, "Two Microscopic Planets" },
                    { 202, 203, 89, "A herd of Rose Smelling Houses" },
                    { 203, 119, 77, "Several Green Planets" },
                    { 204, 174, 222, "Several Purple Planets" },
                    { 205, 4, 210, "A bunch of Green Flowers" },
                    { 206, 216, 92, "Fifteen Transparent Cars" },
                    { 207, 99, 50, "An army of Rose Smelling Buildings" },
                    { 208, 210, 187, "Fifteen Green Houses" },
                    { 209, 218, 81, "A bunch of Rose Smelling Buildings" },
                    { 210, 105, 243, "Fifteen Large Leopards" },
                    { 211, 147, 38, "The Bitter Buildings" },
                    { 212, 74, 246, "The Rose Smelling Cars" },
                    { 213, 37, 33, "The Rose Smelling Houses" },
                    { 214, 199, 168, "An army of Orange Planets" },
                    { 215, 226, 234, "An army of Green Buildings" },
                    { 216, 70, 89, "Several Orange Buildings" },
                    { 217, 48, 249, "An army of Rose Smelling Flowers" },
                    { 218, 240, 176, "Two Transparent Cars" },
                    { 219, 33, 28, "Fifteen Rose Smelling Leopards" },
                    { 220, 158, 164, "An army of Large Leopards" },
                    { 221, 42, 218, "A bunch of Green Houses" },
                    { 222, 195, 127, "Fifteen Green Buildings" },
                    { 223, 151, 72, "A herd of Purple Houses" },
                    { 224, 83, 215, "The Microscopic Cars" },
                    { 225, 118, 198, "Several Rose Smelling Leopards" },
                    { 226, 76, 237, "Several Bitter Leopards" },
                    { 227, 93, 118, "Two Bitter Houses" },
                    { 228, 47, 211, "A herd of Bitter Flowers" },
                    { 229, 135, 46, "Several Bitter Houses" },
                    { 230, 85, 124, "An army of Bitter Planets" },
                    { 231, 110, 43, "The Rose Smelling Houses" },
                    { 232, 118, 144, "Fifteen Green Flowers" },
                    { 233, 147, 212, "Fifteen Green Planets" },
                    { 234, 156, 133, "A bunch of Orange Buildings" },
                    { 235, 85, 109, "An army of Green Buildings" },
                    { 236, 69, 234, "An army of Purple Leopards" },
                    { 237, 101, 27, "A herd of Bitter Cars" },
                    { 238, 225, 167, "An army of Orange Houses" },
                    { 239, 207, 164, "A herd of Green Cars" },
                    { 240, 156, 25, "A herd of Orange Cars" },
                    { 241, 93, 149, "An army of Green Houses" },
                    { 242, 80, 98, "An army of Purple Flowers" },
                    { 243, 158, 231, "The Purple Houses" },
                    { 244, 171, 194, "Two Orange Buildings" },
                    { 245, 14, 211, "Two Green Flowers" },
                    { 246, 46, 86, "The Purple Buildings" },
                    { 247, 201, 150, "Fifteen Rose Smelling Planets" },
                    { 248, 171, 42, "The Orange Cars" },
                    { 249, 55, 248, "A bunch of Microscopic Leopards" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_book_author_id",
                table: "book",
                column: "author_id");

            migrationBuilder.CreateIndex(
                name: "IX_book_publisher_id",
                table: "book",
                column: "publisher_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "book");

            migrationBuilder.DropTable(
                name: "author");

            migrationBuilder.DropTable(
                name: "publisher");
        }
    }
}
