using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class _123 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    first_name = table.Column<string>(type: "text", nullable: false),
                    last_name = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "publisher",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_publisher", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    fk_author_id = table.Column<int>(type: "integer", nullable: false),
                    fk_publisher_id = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_authors_fk_author_id",
                        column: x => x.fk_author_id,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_books_publisher_fk_publisher_id",
                        column: x => x.fk_publisher_id,
                        principalTable: "publisher",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "authors",
                columns: new[] { "id", "email", "first_name", "last_name" },
                values: new object[,]
                {
                    { 1, "kate.hepburn@nasa.org.us", "Kate", "Hepburn" },
                    { 2, "elvis.winslet@tesla.com", "Elvis", "Winslet" },
                    { 3, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 4, "jimi.winfrey@nasa.org.us", "Jimi", "Winfrey" },
                    { 5, "barack.windsor@gov.nl", "Barack", "Windsor" },
                    { 6, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 7, "barack.jagger@nasa.org.us", "Barack", "Jagger" },
                    { 8, "barack.middleton@gov.nl", "Barack", "Middleton" },
                    { 9, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 10, "kate.trump@gov.us", "Kate", "Trump" },
                    { 11, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 12, "kate.hepburn@gov.us", "Kate", "Hepburn" },
                    { 13, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 14, "kate.winslet@gov.us", "Kate", "Winslet" },
                    { 15, "audrey.windsor@bbc.co.uk", "Audrey", "Windsor" },
                    { 16, "barack.winslet@google.com", "Barack", "Winslet" },
                    { 17, "oprah.windsor@theworld.ca", "Oprah", "Windsor" },
                    { 18, "donald.windsor@bbc.co.uk", "Donald", "Windsor" },
                    { 19, "jimi.hendrix@tesla.com", "Jimi", "Hendrix" },
                    { 20, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 21, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 22, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 23, "kate.winslet@theworld.ca", "Kate", "Winslet" },
                    { 24, "donald.hendrix@theworld.ca", "Donald", "Hendrix" },
                    { 25, "elvis.trump@something.com", "Elvis", "Trump" },
                    { 26, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 27, "elvis.hendrix@theworld.ca", "Elvis", "Hendrix" },
                    { 28, "elvis.jagger@bbc.co.uk", "Elvis", "Jagger" },
                    { 29, "donald.jagger@gov.nl", "Donald", "Jagger" },
                    { 30, "oprah.windsor@google.com", "Oprah", "Windsor" },
                    { 31, "oprah.obama@google.com", "Oprah", "Obama" },
                    { 32, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 33, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 34, "barack.middleton@google.com", "Barack", "Middleton" },
                    { 35, "elvis.hepburn@google.com", "Elvis", "Hepburn" },
                    { 36, "audrey.presley@something.com", "Audrey", "Presley" },
                    { 37, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 38, "mick.hendrix@gov.gr", "Mick", "Hendrix" },
                    { 39, "audrey.windsor@gov.gr", "Audrey", "Windsor" },
                    { 40, "mick.presley@theworld.ca", "Mick", "Presley" },
                    { 41, "mick.middleton@nasa.org.us", "Mick", "Middleton" },
                    { 42, "kate.middleton@nasa.org.us", "Kate", "Middleton" },
                    { 43, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 44, "charles.hepburn@theworld.ca", "Charles", "Hepburn" },
                    { 45, "mick.winslet@google.com", "Mick", "Winslet" },
                    { 46, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 47, "charles.obama@gov.gr", "Charles", "Obama" },
                    { 48, "donald.hepburn@theworld.ca", "Donald", "Hepburn" },
                    { 49, "jimi.jagger@google.com", "Jimi", "Jagger" },
                    { 50, "elvis.winfrey@tesla.com", "Elvis", "Winfrey" },
                    { 51, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 52, "elvis.hendrix@something.com", "Elvis", "Hendrix" },
                    { 53, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 54, "elvis.presley@nasa.org.us", "Elvis", "Presley" },
                    { 55, "jimi.hendrix@gov.ru", "Jimi", "Hendrix" },
                    { 56, "oprah.windsor@gov.ru", "Oprah", "Windsor" },
                    { 57, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 58, "charles.presley@nasa.org.us", "Charles", "Presley" },
                    { 59, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 60, "elvis.winfrey@gov.gr", "Elvis", "Winfrey" },
                    { 61, "kate.trump@gov.us", "Kate", "Trump" },
                    { 62, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 63, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 64, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 65, "charles.winfrey@bbc.co.uk", "Charles", "Winfrey" },
                    { 66, "mick.middleton@gov.us", "Mick", "Middleton" },
                    { 67, "jimi.presley@tesla.com", "Jimi", "Presley" },
                    { 68, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 69, "audrey.jagger@theworld.ca", "Audrey", "Jagger" },
                    { 70, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 71, "kate.trump@something.com", "Kate", "Trump" },
                    { 72, "barack.jagger@tesla.com", "Barack", "Jagger" },
                    { 73, "donald.windsor@bbc.co.uk", "Donald", "Windsor" },
                    { 74, "donald.trump@nasa.org.us", "Donald", "Trump" },
                    { 75, "charles.jagger@bbc.co.uk", "Charles", "Jagger" },
                    { 76, "donald.winfrey@tesla.com", "Donald", "Winfrey" },
                    { 77, "mick.trump@gov.us", "Mick", "Trump" },
                    { 78, "barack.trump@tesla.com", "Barack", "Trump" },
                    { 79, "oprah.winfrey@tesla.com", "Oprah", "Winfrey" },
                    { 80, "charles.hepburn@gov.us", "Charles", "Hepburn" },
                    { 81, "audrey.obama@tesla.com", "Audrey", "Obama" },
                    { 82, "mick.winslet@nasa.org.us", "Mick", "Winslet" },
                    { 83, "barack.obama@bbc.co.uk", "Barack", "Obama" },
                    { 84, "oprah.trump@bbc.co.uk", "Oprah", "Trump" },
                    { 85, "charles.winslet@bbc.co.uk", "Charles", "Winslet" },
                    { 86, "mick.presley@gov.us", "Mick", "Presley" },
                    { 87, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 88, "mick.presley@nasa.org.us", "Mick", "Presley" },
                    { 89, "barack.obama@theworld.ca", "Barack", "Obama" },
                    { 90, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 91, "mick.presley@nasa.org.us", "Mick", "Presley" },
                    { 92, "barack.hendrix@google.com", "Barack", "Hendrix" },
                    { 93, "oprah.middleton@bbc.co.uk", "Oprah", "Middleton" },
                    { 94, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 95, "audrey.middleton@google.com", "Audrey", "Middleton" },
                    { 96, "elvis.jagger@gov.nl", "Elvis", "Jagger" },
                    { 97, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 98, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 99, "mick.winfrey@gov.ru", "Mick", "Winfrey" },
                    { 100, "charles.presley@theworld.ca", "Charles", "Presley" },
                    { 101, "donald.hepburn@gov.gr", "Donald", "Hepburn" },
                    { 102, "barack.jagger@google.com", "Barack", "Jagger" },
                    { 103, "mick.winslet@theworld.ca", "Mick", "Winslet" },
                    { 104, "jimi.presley@gov.us", "Jimi", "Presley" },
                    { 105, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 106, "audrey.winfrey@google.com", "Audrey", "Winfrey" },
                    { 107, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 108, "mick.windsor@gov.nl", "Mick", "Windsor" },
                    { 109, "elvis.jagger@gov.gr", "Elvis", "Jagger" },
                    { 110, "donald.obama@something.com", "Donald", "Obama" },
                    { 111, "kate.winslet@gov.us", "Kate", "Winslet" },
                    { 112, "mick.hepburn@tesla.com", "Mick", "Hepburn" },
                    { 113, "kate.hendrix@gov.ru", "Kate", "Hendrix" },
                    { 114, "jimi.middleton@gov.gr", "Jimi", "Middleton" },
                    { 115, "charles.middleton@tesla.com", "Charles", "Middleton" },
                    { 116, "audrey.presley@something.com", "Audrey", "Presley" },
                    { 117, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 118, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 119, "charles.trump@nasa.org.us", "Charles", "Trump" },
                    { 120, "barack.hepburn@gov.us", "Barack", "Hepburn" },
                    { 121, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 122, "barack.presley@gov.nl", "Barack", "Presley" },
                    { 123, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 124, "mick.middleton@gov.ru", "Mick", "Middleton" },
                    { 125, "donald.trump@nasa.org.us", "Donald", "Trump" },
                    { 126, "jimi.hepburn@tesla.com", "Jimi", "Hepburn" },
                    { 127, "donald.winfrey@gov.ru", "Donald", "Winfrey" },
                    { 128, "mick.hendrix@gov.ru", "Mick", "Hendrix" },
                    { 129, "jimi.hendrix@gov.nl", "Jimi", "Hendrix" },
                    { 130, "charles.jagger@bbc.co.uk", "Charles", "Jagger" },
                    { 131, "barack.middleton@gov.nl", "Barack", "Middleton" },
                    { 132, "donald.trump@gov.us", "Donald", "Trump" },
                    { 133, "mick.presley@gov.gr", "Mick", "Presley" },
                    { 134, "oprah.presley@something.com", "Oprah", "Presley" },
                    { 135, "donald.presley@google.com", "Donald", "Presley" },
                    { 136, "kate.obama@tesla.com", "Kate", "Obama" },
                    { 137, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 138, "barack.windsor@gov.ru", "Barack", "Windsor" },
                    { 139, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 140, "barack.hendrix@gov.us", "Barack", "Hendrix" },
                    { 141, "barack.middleton@gov.us", "Barack", "Middleton" },
                    { 142, "donald.trump@bbc.co.uk", "Donald", "Trump" },
                    { 143, "charles.hepburn@theworld.ca", "Charles", "Hepburn" },
                    { 144, "oprah.winslet@theworld.ca", "Oprah", "Winslet" },
                    { 145, "kate.hepburn@theworld.ca", "Kate", "Hepburn" },
                    { 146, "audrey.windsor@google.com", "Audrey", "Windsor" },
                    { 147, "elvis.middleton@gov.ru", "Elvis", "Middleton" },
                    { 148, "barack.windsor@theworld.ca", "Barack", "Windsor" },
                    { 149, "kate.presley@gov.us", "Kate", "Presley" },
                    { 150, "elvis.obama@theworld.ca", "Elvis", "Obama" },
                    { 151, "mick.trump@gov.us", "Mick", "Trump" },
                    { 152, "mick.winfrey@tesla.com", "Mick", "Winfrey" },
                    { 153, "donald.jagger@gov.gr", "Donald", "Jagger" },
                    { 154, "jimi.winfrey@bbc.co.uk", "Jimi", "Winfrey" },
                    { 155, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 156, "barack.hendrix@gov.gr", "Barack", "Hendrix" },
                    { 157, "elvis.presley@tesla.com", "Elvis", "Presley" },
                    { 158, "charles.presley@theworld.ca", "Charles", "Presley" },
                    { 159, "oprah.middleton@google.com", "Oprah", "Middleton" },
                    { 160, "oprah.winfrey@bbc.co.uk", "Oprah", "Winfrey" },
                    { 161, "mick.jagger@gov.ru", "Mick", "Jagger" },
                    { 162, "donald.trump@gov.us", "Donald", "Trump" },
                    { 163, "audrey.windsor@gov.nl", "Audrey", "Windsor" },
                    { 164, "mick.middleton@bbc.co.uk", "Mick", "Middleton" },
                    { 165, "audrey.middleton@theworld.ca", "Audrey", "Middleton" },
                    { 166, "jimi.hepburn@google.com", "Jimi", "Hepburn" },
                    { 167, "charles.obama@bbc.co.uk", "Charles", "Obama" },
                    { 168, "mick.winfrey@tesla.com", "Mick", "Winfrey" },
                    { 169, "jimi.winslet@gov.gr", "Jimi", "Winslet" },
                    { 170, "oprah.hepburn@tesla.com", "Oprah", "Hepburn" },
                    { 171, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 172, "barack.trump@gov.nl", "Barack", "Trump" },
                    { 173, "jimi.hendrix@something.com", "Jimi", "Hendrix" },
                    { 174, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 175, "oprah.middleton@nasa.org.us", "Oprah", "Middleton" },
                    { 176, "elvis.winfrey@bbc.co.uk", "Elvis", "Winfrey" },
                    { 177, "oprah.trump@theworld.ca", "Oprah", "Trump" },
                    { 178, "audrey.obama@gov.us", "Audrey", "Obama" },
                    { 179, "jimi.hepburn@bbc.co.uk", "Jimi", "Hepburn" },
                    { 180, "jimi.hepburn@google.com", "Jimi", "Hepburn" },
                    { 181, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 182, "charles.middleton@gov.ru", "Charles", "Middleton" },
                    { 183, "oprah.windsor@gov.nl", "Oprah", "Windsor" },
                    { 184, "elvis.trump@gov.nl", "Elvis", "Trump" },
                    { 185, "donald.winslet@gov.gr", "Donald", "Winslet" },
                    { 186, "kate.winslet@gov.us", "Kate", "Winslet" },
                    { 187, "mick.obama@tesla.com", "Mick", "Obama" },
                    { 188, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 189, "barack.presley@gov.us", "Barack", "Presley" },
                    { 190, "oprah.obama@bbc.co.uk", "Oprah", "Obama" },
                    { 191, "jimi.obama@something.com", "Jimi", "Obama" },
                    { 192, "donald.jagger@gov.ru", "Donald", "Jagger" },
                    { 193, "audrey.middleton@something.com", "Audrey", "Middleton" },
                    { 194, "mick.jagger@nasa.org.us", "Mick", "Jagger" },
                    { 195, "charles.hendrix@nasa.org.us", "Charles", "Hendrix" },
                    { 196, "barack.trump@gov.nl", "Barack", "Trump" },
                    { 197, "barack.windsor@gov.gr", "Barack", "Windsor" },
                    { 198, "kate.winfrey@google.com", "Kate", "Winfrey" },
                    { 199, "oprah.winfrey@bbc.co.uk", "Oprah", "Winfrey" },
                    { 200, "audrey.hendrix@google.com", "Audrey", "Hendrix" },
                    { 201, "jimi.trump@google.com", "Jimi", "Trump" },
                    { 202, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 203, "elvis.hendrix@bbc.co.uk", "Elvis", "Hendrix" },
                    { 204, "donald.winslet@tesla.com", "Donald", "Winslet" },
                    { 205, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 206, "charles.winslet@something.com", "Charles", "Winslet" },
                    { 207, "elvis.hendrix@tesla.com", "Elvis", "Hendrix" },
                    { 208, "donald.hepburn@theworld.ca", "Donald", "Hepburn" },
                    { 209, "jimi.trump@gov.ru", "Jimi", "Trump" },
                    { 210, "mick.middleton@tesla.com", "Mick", "Middleton" },
                    { 211, "mick.jagger@nasa.org.us", "Mick", "Jagger" },
                    { 212, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 213, "audrey.hepburn@something.com", "Audrey", "Hepburn" },
                    { 214, "elvis.hepburn@gov.nl", "Elvis", "Hepburn" },
                    { 215, "jimi.hepburn@nasa.org.us", "Jimi", "Hepburn" },
                    { 216, "jimi.hepburn@something.com", "Jimi", "Hepburn" },
                    { 217, "jimi.obama@gov.nl", "Jimi", "Obama" },
                    { 218, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 219, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 220, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 221, "kate.winfrey@nasa.org.us", "Kate", "Winfrey" },
                    { 222, "elvis.hendrix@gov.nl", "Elvis", "Hendrix" },
                    { 223, "elvis.windsor@google.com", "Elvis", "Windsor" },
                    { 224, "kate.presley@bbc.co.uk", "Kate", "Presley" },
                    { 225, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 226, "donald.trump@something.com", "Donald", "Trump" },
                    { 227, "barack.trump@gov.us", "Barack", "Trump" },
                    { 228, "barack.winfrey@google.com", "Barack", "Winfrey" },
                    { 229, "elvis.windsor@google.com", "Elvis", "Windsor" },
                    { 230, "jimi.hendrix@nasa.org.us", "Jimi", "Hendrix" },
                    { 231, "oprah.windsor@theworld.ca", "Oprah", "Windsor" },
                    { 232, "oprah.windsor@something.com", "Oprah", "Windsor" },
                    { 233, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 234, "audrey.hendrix@tesla.com", "Audrey", "Hendrix" },
                    { 235, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 236, "jimi.presley@gov.ru", "Jimi", "Presley" },
                    { 237, "mick.hepburn@something.com", "Mick", "Hepburn" },
                    { 238, "audrey.hendrix@gov.ru", "Audrey", "Hendrix" },
                    { 239, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 240, "elvis.presley@something.com", "Elvis", "Presley" },
                    { 241, "audrey.windsor@gov.gr", "Audrey", "Windsor" },
                    { 242, "jimi.windsor@something.com", "Jimi", "Windsor" },
                    { 243, "charles.hendrix@something.com", "Charles", "Hendrix" },
                    { 244, "oprah.middleton@google.com", "Oprah", "Middleton" },
                    { 245, "donald.winslet@gov.us", "Donald", "Winslet" },
                    { 246, "donald.winfrey@nasa.org.us", "Donald", "Winfrey" },
                    { 247, "kate.obama@gov.nl", "Kate", "Obama" },
                    { 248, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 249, "barack.winfrey@gov.nl", "Barack", "Winfrey" }
                });

            migrationBuilder.InsertData(
                table: "publisher",
                columns: new[] { "id", "name" },
                values: new object[,]
                {
                    { 1, "Black Book Group" },
                    { 2, "Harper Book Group" },
                    { 3, "Black Webster" },
                    { 4, "Black Library" },
                    { 5, "Black Book Group" },
                    { 6, "Hachette Webster" },
                    { 7, "Penguin Collins" },
                    { 8, "Hachette Publishers" },
                    { 9, "Harper Collins" },
                    { 10, "Hachette Publishers" },
                    { 11, "Macmillan Random House" },
                    { 12, "Macmillan Publishers" },
                    { 13, "Hachette Webster" },
                    { 14, "Black Collins" },
                    { 15, "Merriam Library" },
                    { 16, "Penguin Random House" },
                    { 17, "Hachette Collins" },
                    { 18, "Merriam Library" },
                    { 19, "Hachette Library" },
                    { 20, "Black Random House" },
                    { 21, "Penguin Webster" },
                    { 22, "Black Collins" },
                    { 23, "Black Random House" },
                    { 24, "Macmillan Collins" },
                    { 25, "Macmillan Webster" },
                    { 26, "Penguin Random House" },
                    { 27, "Merriam Library" },
                    { 28, "Penguin Random House" },
                    { 29, "Black Random House" },
                    { 30, "Macmillan Collins" },
                    { 31, "Macmillan Book Group" },
                    { 32, "Macmillan Library" },
                    { 33, "Penguin Collins" },
                    { 34, "Black Random House" },
                    { 35, "Black Publishers" },
                    { 36, "Black Collins" },
                    { 37, "Macmillan Book Group" },
                    { 38, "Merriam Publishers" },
                    { 39, "Black Random House" },
                    { 40, "Macmillan Collins" },
                    { 41, "Merriam Publishers" },
                    { 42, "Harper Collins" },
                    { 43, "Merriam Book Group" },
                    { 44, "Macmillan Collins" },
                    { 45, "Harper Random House" },
                    { 46, "Macmillan Collins" },
                    { 47, "Harper Random House" },
                    { 48, "Harper Random House" },
                    { 49, "Macmillan Webster" },
                    { 50, "Harper Webster" },
                    { 51, "Merriam Collins" },
                    { 52, "Penguin Library" },
                    { 53, "Penguin Collins" },
                    { 54, "Black Library" },
                    { 55, "Penguin Collins" },
                    { 56, "Merriam Webster" },
                    { 57, "Hachette Webster" },
                    { 58, "Harper Publishers" },
                    { 59, "Harper Collins" },
                    { 60, "Black Collins" },
                    { 61, "Harper Collins" },
                    { 62, "Harper Webster" },
                    { 63, "Harper Webster" },
                    { 64, "Penguin Collins" },
                    { 65, "Macmillan Publishers" },
                    { 66, "Hachette Library" },
                    { 67, "Merriam Library" },
                    { 68, "Hachette Random House" },
                    { 69, "Harper Book Group" },
                    { 70, "Harper Random House" },
                    { 71, "Merriam Publishers" },
                    { 72, "Merriam Book Group" },
                    { 73, "Black Random House" },
                    { 74, "Black Collins" },
                    { 75, "Black Random House" },
                    { 76, "Black Book Group" },
                    { 77, "Merriam Collins" },
                    { 78, "Penguin Library" },
                    { 79, "Macmillan Publishers" },
                    { 80, "Black Random House" },
                    { 81, "Black Book Group" },
                    { 82, "Hachette Book Group" },
                    { 83, "Hachette Publishers" },
                    { 84, "Merriam Publishers" },
                    { 85, "Penguin Random House" },
                    { 86, "Hachette Book Group" },
                    { 87, "Macmillan Library" },
                    { 88, "Macmillan Random House" },
                    { 89, "Black Library" },
                    { 90, "Macmillan Library" },
                    { 91, "Harper Webster" },
                    { 92, "Merriam Webster" },
                    { 93, "Macmillan Collins" },
                    { 94, "Black Library" },
                    { 95, "Penguin Webster" },
                    { 96, "Black Random House" },
                    { 97, "Hachette Collins" },
                    { 98, "Black Book Group" },
                    { 99, "Macmillan Library" },
                    { 100, "Penguin Book Group" },
                    { 101, "Harper Book Group" },
                    { 102, "Black Collins" },
                    { 103, "Black Publishers" },
                    { 104, "Harper Random House" },
                    { 105, "Macmillan Webster" },
                    { 106, "Harper Collins" },
                    { 107, "Hachette Publishers" },
                    { 108, "Black Book Group" },
                    { 109, "Hachette Publishers" },
                    { 110, "Black Random House" },
                    { 111, "Penguin Publishers" },
                    { 112, "Penguin Random House" },
                    { 113, "Penguin Collins" },
                    { 114, "Merriam Collins" },
                    { 115, "Hachette Collins" },
                    { 116, "Macmillan Collins" },
                    { 117, "Black Collins" },
                    { 118, "Harper Book Group" },
                    { 119, "Macmillan Collins" },
                    { 120, "Macmillan Collins" },
                    { 121, "Harper Library" },
                    { 122, "Macmillan Webster" },
                    { 123, "Harper Webster" },
                    { 124, "Harper Publishers" },
                    { 125, "Hachette Collins" },
                    { 126, "Hachette Random House" },
                    { 127, "Macmillan Collins" },
                    { 128, "Hachette Publishers" },
                    { 129, "Merriam Publishers" },
                    { 130, "Harper Random House" },
                    { 131, "Black Book Group" },
                    { 132, "Harper Publishers" },
                    { 133, "Merriam Random House" },
                    { 134, "Hachette Library" },
                    { 135, "Black Webster" },
                    { 136, "Penguin Book Group" },
                    { 137, "Penguin Random House" },
                    { 138, "Harper Collins" },
                    { 139, "Black Publishers" },
                    { 140, "Penguin Publishers" },
                    { 141, "Penguin Webster" },
                    { 142, "Harper Collins" },
                    { 143, "Merriam Random House" },
                    { 144, "Macmillan Webster" },
                    { 145, "Hachette Random House" },
                    { 146, "Black Publishers" },
                    { 147, "Black Library" },
                    { 148, "Merriam Collins" },
                    { 149, "Macmillan Collins" },
                    { 150, "Penguin Publishers" },
                    { 151, "Hachette Book Group" },
                    { 152, "Penguin Library" },
                    { 153, "Hachette Book Group" },
                    { 154, "Hachette Collins" },
                    { 155, "Harper Library" },
                    { 156, "Merriam Webster" },
                    { 157, "Macmillan Library" },
                    { 158, "Black Collins" },
                    { 159, "Hachette Library" },
                    { 160, "Black Webster" },
                    { 161, "Black Collins" },
                    { 162, "Macmillan Collins" },
                    { 163, "Merriam Publishers" },
                    { 164, "Hachette Publishers" },
                    { 165, "Penguin Collins" },
                    { 166, "Merriam Library" },
                    { 167, "Hachette Publishers" },
                    { 168, "Penguin Book Group" },
                    { 169, "Harper Book Group" },
                    { 170, "Black Random House" },
                    { 171, "Harper Random House" },
                    { 172, "Harper Collins" },
                    { 173, "Harper Publishers" },
                    { 174, "Macmillan Random House" },
                    { 175, "Black Book Group" },
                    { 176, "Penguin Random House" },
                    { 177, "Penguin Publishers" },
                    { 178, "Macmillan Webster" },
                    { 179, "Hachette Publishers" },
                    { 180, "Harper Random House" },
                    { 181, "Black Book Group" },
                    { 182, "Penguin Webster" },
                    { 183, "Hachette Book Group" },
                    { 184, "Merriam Random House" },
                    { 185, "Black Library" },
                    { 186, "Macmillan Book Group" },
                    { 187, "Black Library" },
                    { 188, "Black Library" },
                    { 189, "Black Publishers" },
                    { 190, "Macmillan Random House" },
                    { 191, "Black Collins" },
                    { 192, "Black Webster" },
                    { 193, "Macmillan Webster" },
                    { 194, "Black Publishers" },
                    { 195, "Penguin Random House" },
                    { 196, "Penguin Book Group" },
                    { 197, "Penguin Webster" },
                    { 198, "Harper Book Group" },
                    { 199, "Penguin Random House" },
                    { 200, "Black Library" },
                    { 201, "Black Book Group" },
                    { 202, "Penguin Random House" },
                    { 203, "Penguin Webster" },
                    { 204, "Hachette Publishers" },
                    { 205, "Merriam Webster" },
                    { 206, "Harper Webster" },
                    { 207, "Harper Publishers" },
                    { 208, "Black Webster" },
                    { 209, "Hachette Library" },
                    { 210, "Black Publishers" },
                    { 211, "Macmillan Publishers" },
                    { 212, "Merriam Collins" },
                    { 213, "Black Collins" },
                    { 214, "Hachette Webster" },
                    { 215, "Hachette Random House" },
                    { 216, "Black Collins" },
                    { 217, "Hachette Book Group" },
                    { 218, "Merriam Book Group" },
                    { 219, "Macmillan Book Group" },
                    { 220, "Merriam Publishers" },
                    { 221, "Black Webster" },
                    { 222, "Hachette Library" },
                    { 223, "Harper Library" },
                    { 224, "Hachette Library" },
                    { 225, "Hachette Library" },
                    { 226, "Black Book Group" },
                    { 227, "Macmillan Webster" },
                    { 228, "Macmillan Webster" },
                    { 229, "Macmillan Collins" },
                    { 230, "Macmillan Random House" },
                    { 231, "Hachette Book Group" },
                    { 232, "Harper Book Group" },
                    { 233, "Penguin Random House" },
                    { 234, "Merriam Book Group" },
                    { 235, "Black Webster" },
                    { 236, "Macmillan Book Group" },
                    { 237, "Penguin Book Group" },
                    { 238, "Harper Publishers" },
                    { 239, "Merriam Publishers" },
                    { 240, "Harper Random House" },
                    { 241, "Hachette Webster" },
                    { 242, "Harper Book Group" },
                    { 243, "Hachette Library" },
                    { 244, "Hachette Random House" },
                    { 245, "Black Library" },
                    { 246, "Harper Collins" },
                    { 247, "Harper Webster" },
                    { 248, "Macmillan Collins" },
                    { 249, "Black Book Group" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "fk_author_id", "fk_publisher_id", "title" },
                values: new object[,]
                {
                    { 1, 45, 152, "A bunch of Green Buildings" },
                    { 2, 77, 223, "A herd of Large Flowers" },
                    { 3, 151, 223, "An army of Orange Planets" },
                    { 4, 112, 171, "Several Large Houses" },
                    { 5, 64, 1, "Fifteen Large Flowers" },
                    { 6, 30, 62, "An army of Orange Houses" },
                    { 7, 62, 13, "Fifteen Microscopic Leopards" },
                    { 8, 18, 230, "Fifteen Bitter Cars" },
                    { 9, 51, 229, "A herd of Large Buildings" },
                    { 10, 200, 133, "A herd of Large Planets" },
                    { 11, 102, 118, "A herd of Transparent Houses" },
                    { 12, 47, 87, "Fifteen Bitter Cars" },
                    { 13, 11, 1, "An army of Transparent Buildings" },
                    { 14, 134, 218, "A bunch of Microscopic Cars" },
                    { 15, 39, 183, "An army of Bitter Flowers" },
                    { 16, 155, 179, "Two Large Leopards" },
                    { 17, 93, 149, "An army of Microscopic Buildings" },
                    { 18, 198, 3, "Several Rose Smelling Leopards" },
                    { 19, 89, 23, "Fifteen Microscopic Buildings" },
                    { 20, 42, 20, "An army of Green Planets" },
                    { 21, 173, 220, "An army of Bitter Leopards" },
                    { 22, 236, 243, "A bunch of Rose Smelling Leopards" },
                    { 23, 19, 205, "A herd of Purple Buildings" },
                    { 24, 38, 77, "An army of Microscopic Cars" },
                    { 25, 126, 196, "Fifteen Green Houses" },
                    { 26, 244, 65, "A bunch of Transparent Flowers" },
                    { 27, 17, 226, "Several Microscopic Planets" },
                    { 28, 240, 187, "Several Large Cars" },
                    { 29, 199, 193, "Two Large Flowers" },
                    { 30, 108, 175, "The Purple Cars" },
                    { 31, 97, 97, "A herd of Rose Smelling Houses" },
                    { 32, 198, 41, "A bunch of Bitter Planets" },
                    { 33, 215, 67, "A herd of Microscopic Leopards" },
                    { 34, 123, 157, "An army of Transparent Houses" },
                    { 35, 164, 4, "The Large Houses" },
                    { 36, 95, 154, "Several Large Leopards" },
                    { 37, 236, 141, "The Orange Buildings" },
                    { 38, 67, 140, "A herd of Green Houses" },
                    { 39, 205, 166, "Several Transparent Buildings" },
                    { 40, 18, 85, "A bunch of Bitter Flowers" },
                    { 41, 47, 183, "Several Rose Smelling Buildings" },
                    { 42, 51, 131, "The Orange Leopards" },
                    { 43, 22, 133, "Two Purple Buildings" },
                    { 44, 208, 70, "The Purple Planets" },
                    { 45, 110, 197, "A herd of Bitter Planets" },
                    { 46, 232, 150, "A bunch of Rose Smelling Flowers" },
                    { 47, 70, 97, "Fifteen Green Leopards" },
                    { 48, 169, 205, "The Green Houses" },
                    { 49, 121, 119, "An army of Rose Smelling Houses" },
                    { 50, 37, 58, "Two Green Cars" },
                    { 51, 106, 68, "A bunch of Large Leopards" },
                    { 52, 65, 207, "Fifteen Purple Houses" },
                    { 53, 246, 69, "A herd of Rose Smelling Flowers" },
                    { 54, 35, 111, "A herd of Microscopic Planets" },
                    { 55, 114, 119, "Fifteen Large Houses" },
                    { 56, 30, 100, "Fifteen Bitter Cars" },
                    { 57, 224, 45, "An army of Orange Cars" },
                    { 58, 80, 237, "Two Green Leopards" },
                    { 59, 145, 5, "An army of Bitter Flowers" },
                    { 60, 45, 53, "A herd of Purple Flowers" },
                    { 61, 200, 197, "The Orange Flowers" },
                    { 62, 82, 203, "The Microscopic Cars" },
                    { 63, 164, 131, "An army of Rose Smelling Flowers" },
                    { 64, 27, 18, "Two Bitter Planets" },
                    { 65, 145, 135, "A herd of Green Leopards" },
                    { 66, 170, 53, "Fifteen Rose Smelling Cars" },
                    { 67, 213, 111, "Fifteen Bitter Houses" },
                    { 68, 120, 8, "Several Microscopic Cars" },
                    { 69, 79, 27, "A herd of Purple Buildings" },
                    { 70, 99, 183, "Fifteen Large Flowers" },
                    { 71, 126, 94, "An army of Green Leopards" },
                    { 72, 19, 86, "The Transparent Houses" },
                    { 73, 110, 53, "A bunch of Orange Buildings" },
                    { 74, 181, 133, "Two Purple Cars" },
                    { 75, 96, 112, "Two Rose Smelling Flowers" },
                    { 76, 82, 175, "The Purple Buildings" },
                    { 77, 130, 240, "An army of Microscopic Houses" },
                    { 78, 149, 216, "A herd of Large Cars" },
                    { 79, 180, 81, "The Large Cars" },
                    { 80, 13, 131, "The Green Houses" },
                    { 81, 161, 198, "A herd of Green Leopards" },
                    { 82, 28, 186, "Several Green Houses" },
                    { 83, 248, 107, "An army of Orange Planets" },
                    { 84, 158, 154, "Two Purple Planets" },
                    { 85, 40, 249, "Two Bitter Houses" },
                    { 86, 80, 20, "A herd of Orange Houses" },
                    { 87, 113, 70, "An army of Purple Planets" },
                    { 88, 5, 100, "A bunch of Rose Smelling Planets" },
                    { 89, 24, 21, "An army of Bitter Cars" },
                    { 90, 34, 3, "A bunch of Transparent Leopards" },
                    { 91, 207, 40, "A bunch of Large Planets" },
                    { 92, 45, 25, "Fifteen Large Flowers" },
                    { 93, 212, 31, "A bunch of Large Buildings" },
                    { 94, 32, 130, "Several Purple Houses" },
                    { 95, 42, 84, "A bunch of Orange Houses" },
                    { 96, 163, 164, "A bunch of Rose Smelling Leopards" },
                    { 97, 36, 8, "A herd of Microscopic Flowers" },
                    { 98, 138, 138, "Fifteen Bitter Planets" },
                    { 99, 178, 70, "An army of Large Cars" },
                    { 100, 215, 42, "A herd of Large Houses" },
                    { 101, 161, 2, "Several Purple Planets" },
                    { 102, 55, 225, "Fifteen Large Flowers" },
                    { 103, 103, 131, "Fifteen Green Leopards" },
                    { 104, 78, 228, "Two Microscopic Buildings" },
                    { 105, 31, 182, "A herd of Orange Planets" },
                    { 106, 242, 11, "Two Purple Flowers" },
                    { 107, 129, 71, "Two Microscopic Buildings" },
                    { 108, 74, 100, "Fifteen Microscopic Cars" },
                    { 109, 93, 211, "An army of Purple Buildings" },
                    { 110, 70, 45, "A herd of Microscopic Flowers" },
                    { 111, 217, 177, "A herd of Purple Flowers" },
                    { 112, 9, 23, "A bunch of Rose Smelling Leopards" },
                    { 113, 76, 187, "An army of Transparent Buildings" },
                    { 114, 5, 115, "The Green Houses" },
                    { 115, 146, 90, "Two Purple Buildings" },
                    { 116, 60, 159, "An army of Green Houses" },
                    { 117, 224, 220, "Two Rose Smelling Flowers" },
                    { 118, 218, 226, "Several Rose Smelling Flowers" },
                    { 119, 12, 32, "A bunch of Bitter Flowers" },
                    { 120, 241, 239, "The Orange Flowers" },
                    { 121, 4, 140, "Two Green Flowers" },
                    { 122, 55, 49, "An army of Purple Buildings" },
                    { 123, 84, 3, "Several Transparent Flowers" },
                    { 124, 248, 132, "A bunch of Bitter Cars" },
                    { 125, 159, 125, "A herd of Green Planets" },
                    { 126, 30, 24, "An army of Orange Buildings" },
                    { 127, 219, 104, "Two Orange Leopards" },
                    { 128, 111, 85, "Fifteen Microscopic Houses" },
                    { 129, 93, 244, "An army of Bitter Cars" },
                    { 130, 103, 40, "Two Orange Flowers" },
                    { 131, 94, 11, "The Large Flowers" },
                    { 132, 114, 16, "A bunch of Orange Flowers" },
                    { 133, 225, 191, "A herd of Rose Smelling Leopards" },
                    { 134, 166, 214, "An army of Bitter Cars" },
                    { 135, 181, 69, "A herd of Microscopic Planets" },
                    { 136, 16, 189, "The Rose Smelling Leopards" },
                    { 137, 123, 160, "A bunch of Microscopic Houses" },
                    { 138, 209, 21, "The Bitter Houses" },
                    { 139, 22, 52, "An army of Purple Flowers" },
                    { 140, 120, 172, "Fifteen Transparent Leopards" },
                    { 141, 57, 224, "A herd of Microscopic Leopards" },
                    { 142, 139, 164, "Two Purple Cars" },
                    { 143, 146, 183, "Fifteen Microscopic Planets" },
                    { 144, 181, 78, "Fifteen Rose Smelling Houses" },
                    { 145, 81, 203, "Several Microscopic Planets" },
                    { 146, 65, 112, "A herd of Purple Flowers" },
                    { 147, 10, 13, "A herd of Green Flowers" },
                    { 148, 115, 2, "Several Green Leopards" },
                    { 149, 103, 94, "A bunch of Microscopic Leopards" },
                    { 150, 231, 155, "A herd of Microscopic Flowers" },
                    { 151, 3, 51, "Several Large Cars" },
                    { 152, 248, 236, "An army of Orange Leopards" },
                    { 153, 18, 182, "Two Microscopic Planets" },
                    { 154, 2, 155, "Two Transparent Cars" },
                    { 155, 236, 30, "Several Bitter Leopards" },
                    { 156, 168, 161, "Fifteen Microscopic Buildings" },
                    { 157, 220, 18, "Several Orange Leopards" },
                    { 158, 180, 248, "A herd of Rose Smelling Planets" },
                    { 159, 131, 54, "Fifteen Bitter Flowers" },
                    { 160, 157, 113, "A bunch of Large Houses" },
                    { 161, 239, 221, "A herd of Orange Houses" },
                    { 162, 166, 61, "Fifteen Rose Smelling Leopards" },
                    { 163, 146, 229, "An army of Green Leopards" },
                    { 164, 136, 85, "Several Transparent Houses" },
                    { 165, 214, 160, "A bunch of Orange Houses" },
                    { 166, 81, 1, "A herd of Purple Cars" },
                    { 167, 207, 240, "Two Microscopic Flowers" },
                    { 168, 94, 210, "A bunch of Orange Flowers" },
                    { 169, 166, 81, "A bunch of Microscopic Planets" },
                    { 170, 224, 90, "An army of Rose Smelling Buildings" },
                    { 171, 99, 42, "Two Green Leopards" },
                    { 172, 63, 175, "A herd of Transparent Houses" },
                    { 173, 132, 56, "A bunch of Large Planets" },
                    { 174, 172, 205, "The Microscopic Leopards" },
                    { 175, 216, 204, "An army of Orange Buildings" },
                    { 176, 72, 56, "An army of Large Buildings" },
                    { 177, 73, 231, "Two Rose Smelling Cars" },
                    { 178, 135, 63, "A bunch of Green Planets" },
                    { 179, 124, 229, "A bunch of Transparent Leopards" },
                    { 180, 117, 222, "Several Orange Flowers" },
                    { 181, 189, 80, "A bunch of Green Leopards" },
                    { 182, 62, 228, "A herd of Large Cars" },
                    { 183, 123, 28, "An army of Large Flowers" },
                    { 184, 73, 246, "Fifteen Transparent Buildings" },
                    { 185, 81, 40, "A bunch of Rose Smelling Flowers" },
                    { 186, 247, 201, "Two Green Flowers" },
                    { 187, 175, 109, "The Rose Smelling Buildings" },
                    { 188, 160, 188, "Two Large Buildings" },
                    { 189, 77, 224, "Fifteen Bitter Houses" },
                    { 190, 4, 244, "A herd of Transparent Planets" },
                    { 191, 211, 62, "The Bitter Leopards" },
                    { 192, 230, 69, "Fifteen Transparent Planets" },
                    { 193, 122, 248, "An army of Microscopic Houses" },
                    { 194, 201, 155, "A bunch of Bitter Leopards" },
                    { 195, 56, 58, "Several Bitter Houses" },
                    { 196, 3, 5, "A bunch of Purple Cars" },
                    { 197, 243, 141, "A bunch of Transparent Planets" },
                    { 198, 70, 132, "A herd of Microscopic Leopards" },
                    { 199, 187, 169, "A herd of Large Buildings" },
                    { 200, 21, 184, "The Microscopic Houses" },
                    { 201, 48, 226, "Several Purple Buildings" },
                    { 202, 225, 68, "An army of Orange Flowers" },
                    { 203, 172, 125, "Two Rose Smelling Buildings" },
                    { 204, 112, 141, "The Large Houses" },
                    { 205, 28, 53, "Fifteen Bitter Buildings" },
                    { 206, 194, 213, "Two Large Leopards" },
                    { 207, 249, 138, "Two Transparent Flowers" },
                    { 208, 240, 143, "Several Large Leopards" },
                    { 209, 190, 1, "A herd of Large Buildings" },
                    { 210, 42, 74, "A herd of Green Buildings" },
                    { 211, 236, 200, "An army of Rose Smelling Houses" },
                    { 212, 1, 164, "An army of Transparent Flowers" },
                    { 213, 148, 12, "Fifteen Rose Smelling Houses" },
                    { 214, 80, 187, "Two Microscopic Leopards" },
                    { 215, 61, 172, "Fifteen Green Cars" },
                    { 216, 97, 66, "An army of Rose Smelling Leopards" },
                    { 217, 145, 92, "An army of Rose Smelling Flowers" },
                    { 218, 35, 174, "An army of Orange Houses" },
                    { 219, 107, 36, "Several Bitter Cars" },
                    { 220, 1, 102, "A herd of Transparent Planets" },
                    { 221, 141, 126, "Several Transparent Cars" },
                    { 222, 52, 73, "Fifteen Purple Cars" },
                    { 223, 117, 149, "An army of Orange Buildings" },
                    { 224, 204, 61, "Fifteen Microscopic Cars" },
                    { 225, 23, 33, "Several Microscopic Planets" },
                    { 226, 69, 57, "Several Microscopic Planets" },
                    { 227, 48, 198, "Two Transparent Planets" },
                    { 228, 217, 78, "A herd of Purple Planets" },
                    { 229, 25, 176, "A herd of Purple Buildings" },
                    { 230, 59, 166, "An army of Large Buildings" },
                    { 231, 113, 11, "Two Large Cars" },
                    { 232, 64, 41, "An army of Green Houses" },
                    { 233, 219, 213, "Two Microscopic Cars" },
                    { 234, 212, 160, "A herd of Orange Leopards" },
                    { 235, 231, 60, "Several Green Flowers" },
                    { 236, 183, 188, "A bunch of Large Leopards" },
                    { 237, 19, 8, "The Green Cars" },
                    { 238, 21, 216, "Several Green Houses" },
                    { 239, 69, 178, "A herd of Large Cars" },
                    { 240, 123, 174, "Two Microscopic Cars" },
                    { 241, 205, 104, "A herd of Transparent Buildings" },
                    { 242, 20, 177, "The Large Houses" },
                    { 243, 218, 22, "Fifteen Transparent Houses" },
                    { 244, 13, 194, "An army of Rose Smelling Houses" },
                    { 245, 48, 84, "The Rose Smelling Cars" },
                    { 246, 126, 57, "A bunch of Bitter Buildings" },
                    { 247, 20, 121, "The Orange Flowers" },
                    { 248, 62, 124, "Fifteen Purple Planets" },
                    { 249, 197, 219, "Several Microscopic Flowers" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_books_fk_author_id",
                table: "books",
                column: "fk_author_id");

            migrationBuilder.CreateIndex(
                name: "IX_books_fk_publisher_id",
                table: "books",
                column: "fk_publisher_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "authors");

            migrationBuilder.DropTable(
                name: "publisher");
        }
    }
}
