using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Author",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    firstname = table.Column<string>(type: "text", nullable: false),
                    lastname = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Author", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "Book",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Book", x => x.id);
                    table.ForeignKey(
                        name: "FK_Book_Author_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Author",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Author",
                columns: new[] { "id", "email", "firstname", "lastname" },
                values: new object[,]
                {
                    { 1, "audrey.obama@nasa.org.us", "Audrey", "Obama" },
                    { 2, "charles.hendrix@gov.gr", "Charles", "Hendrix" },
                    { 3, "donald.obama@gov.nl", "Donald", "Obama" },
                    { 4, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 5, "kate.presley@bbc.co.uk", "Kate", "Presley" },
                    { 6, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 7, "barack.obama@nasa.org.us", "Barack", "Obama" },
                    { 8, "elvis.winfrey@google.com", "Elvis", "Winfrey" },
                    { 9, "audrey.hepburn@gov.nl", "Audrey", "Hepburn" },
                    { 10, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 11, "charles.obama@google.com", "Charles", "Obama" },
                    { 12, "barack.trump@gov.ru", "Barack", "Trump" },
                    { 13, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 14, "barack.trump@gov.gr", "Barack", "Trump" },
                    { 15, "mick.middleton@tesla.com", "Mick", "Middleton" },
                    { 16, "charles.middleton@gov.ru", "Charles", "Middleton" },
                    { 17, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 18, "donald.middleton@gov.ru", "Donald", "Middleton" },
                    { 19, "donald.hendrix@gov.gr", "Donald", "Hendrix" },
                    { 20, "oprah.obama@nasa.org.us", "Oprah", "Obama" },
                    { 21, "oprah.windsor@something.com", "Oprah", "Windsor" },
                    { 22, "elvis.winfrey@nasa.org.us", "Elvis", "Winfrey" },
                    { 23, "jimi.middleton@gov.nl", "Jimi", "Middleton" },
                    { 24, "elvis.obama@gov.nl", "Elvis", "Obama" },
                    { 25, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 26, "elvis.presley@gov.nl", "Elvis", "Presley" },
                    { 27, "kate.middleton@nasa.org.us", "Kate", "Middleton" },
                    { 28, "donald.winslet@google.com", "Donald", "Winslet" },
                    { 29, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 30, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 31, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 32, "barack.obama@theworld.ca", "Barack", "Obama" },
                    { 33, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 34, "jimi.hepburn@gov.gr", "Jimi", "Hepburn" },
                    { 35, "barack.winfrey@nasa.org.us", "Barack", "Winfrey" },
                    { 36, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 37, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 38, "oprah.hepburn@google.com", "Oprah", "Hepburn" },
                    { 39, "barack.trump@tesla.com", "Barack", "Trump" },
                    { 40, "charles.hepburn@google.com", "Charles", "Hepburn" },
                    { 41, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 42, "jimi.presley@nasa.org.us", "Jimi", "Presley" },
                    { 43, "donald.winfrey@gov.nl", "Donald", "Winfrey" },
                    { 44, "jimi.hepburn@gov.nl", "Jimi", "Hepburn" },
                    { 45, "donald.trump@gov.us", "Donald", "Trump" },
                    { 46, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 47, "elvis.middleton@theworld.ca", "Elvis", "Middleton" },
                    { 48, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 49, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 50, "kate.winfrey@bbc.co.uk", "Kate", "Winfrey" },
                    { 51, "charles.obama@something.com", "Charles", "Obama" },
                    { 52, "oprah.obama@google.com", "Oprah", "Obama" },
                    { 53, "audrey.hepburn@bbc.co.uk", "Audrey", "Hepburn" },
                    { 54, "charles.jagger@gov.gr", "Charles", "Jagger" },
                    { 55, "mick.winslet@google.com", "Mick", "Winslet" },
                    { 56, "oprah.obama@gov.gr", "Oprah", "Obama" },
                    { 57, "audrey.winslet@gov.gr", "Audrey", "Winslet" },
                    { 58, "donald.trump@gov.ru", "Donald", "Trump" },
                    { 59, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 60, "barack.winfrey@something.com", "Barack", "Winfrey" },
                    { 61, "mick.obama@google.com", "Mick", "Obama" },
                    { 62, "mick.jagger@tesla.com", "Mick", "Jagger" },
                    { 63, "jimi.obama@gov.gr", "Jimi", "Obama" },
                    { 64, "mick.winslet@tesla.com", "Mick", "Winslet" },
                    { 65, "jimi.jagger@gov.gr", "Jimi", "Jagger" },
                    { 66, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 67, "elvis.winslet@theworld.ca", "Elvis", "Winslet" },
                    { 68, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 69, "oprah.winslet@nasa.org.us", "Oprah", "Winslet" },
                    { 70, "audrey.winslet@something.com", "Audrey", "Winslet" },
                    { 71, "audrey.presley@gov.ru", "Audrey", "Presley" },
                    { 72, "oprah.winslet@bbc.co.uk", "Oprah", "Winslet" },
                    { 73, "kate.obama@something.com", "Kate", "Obama" },
                    { 74, "elvis.winfrey@something.com", "Elvis", "Winfrey" },
                    { 75, "barack.winfrey@something.com", "Barack", "Winfrey" },
                    { 76, "kate.jagger@gov.us", "Kate", "Jagger" },
                    { 77, "charles.jagger@gov.nl", "Charles", "Jagger" },
                    { 78, "barack.jagger@tesla.com", "Barack", "Jagger" },
                    { 79, "donald.presley@theworld.ca", "Donald", "Presley" },
                    { 80, "mick.windsor@bbc.co.uk", "Mick", "Windsor" },
                    { 81, "charles.winslet@bbc.co.uk", "Charles", "Winslet" },
                    { 82, "mick.hepburn@theworld.ca", "Mick", "Hepburn" },
                    { 83, "audrey.hendrix@gov.nl", "Audrey", "Hendrix" },
                    { 84, "barack.hendrix@bbc.co.uk", "Barack", "Hendrix" },
                    { 85, "audrey.presley@theworld.ca", "Audrey", "Presley" },
                    { 86, "mick.presley@tesla.com", "Mick", "Presley" },
                    { 87, "mick.presley@gov.nl", "Mick", "Presley" },
                    { 88, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 89, "mick.obama@bbc.co.uk", "Mick", "Obama" },
                    { 90, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 91, "jimi.hendrix@tesla.com", "Jimi", "Hendrix" },
                    { 92, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 93, "audrey.hendrix@theworld.ca", "Audrey", "Hendrix" },
                    { 94, "audrey.winfrey@gov.gr", "Audrey", "Winfrey" },
                    { 95, "donald.windsor@nasa.org.us", "Donald", "Windsor" },
                    { 96, "jimi.presley@gov.gr", "Jimi", "Presley" },
                    { 97, "oprah.hendrix@tesla.com", "Oprah", "Hendrix" },
                    { 98, "elvis.presley@gov.us", "Elvis", "Presley" },
                    { 99, "donald.trump@gov.gr", "Donald", "Trump" },
                    { 100, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 101, "oprah.trump@theworld.ca", "Oprah", "Trump" },
                    { 102, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 103, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 104, "jimi.middleton@gov.gr", "Jimi", "Middleton" },
                    { 105, "jimi.winslet@bbc.co.uk", "Jimi", "Winslet" },
                    { 106, "jimi.hepburn@theworld.ca", "Jimi", "Hepburn" },
                    { 107, "jimi.windsor@tesla.com", "Jimi", "Windsor" },
                    { 108, "charles.hepburn@theworld.ca", "Charles", "Hepburn" },
                    { 109, "donald.presley@something.com", "Donald", "Presley" },
                    { 110, "mick.trump@theworld.ca", "Mick", "Trump" },
                    { 111, "jimi.jagger@something.com", "Jimi", "Jagger" },
                    { 112, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 113, "charles.presley@gov.us", "Charles", "Presley" },
                    { 114, "barack.hendrix@gov.ru", "Barack", "Hendrix" },
                    { 115, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 116, "jimi.windsor@gov.gr", "Jimi", "Windsor" },
                    { 117, "oprah.trump@gov.ru", "Oprah", "Trump" },
                    { 118, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 119, "mick.obama@bbc.co.uk", "Mick", "Obama" },
                    { 120, "barack.hendrix@theworld.ca", "Barack", "Hendrix" },
                    { 121, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 122, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 123, "barack.hepburn@bbc.co.uk", "Barack", "Hepburn" },
                    { 124, "audrey.hepburn@gov.gr", "Audrey", "Hepburn" },
                    { 125, "kate.windsor@theworld.ca", "Kate", "Windsor" },
                    { 126, "elvis.winslet@gov.us", "Elvis", "Winslet" },
                    { 127, "mick.hendrix@gov.nl", "Mick", "Hendrix" },
                    { 128, "charles.winslet@something.com", "Charles", "Winslet" },
                    { 129, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 130, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 131, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 132, "audrey.winslet@theworld.ca", "Audrey", "Winslet" },
                    { 133, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 134, "audrey.presley@tesla.com", "Audrey", "Presley" },
                    { 135, "oprah.jagger@nasa.org.us", "Oprah", "Jagger" },
                    { 136, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 137, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 138, "oprah.presley@gov.us", "Oprah", "Presley" },
                    { 139, "audrey.windsor@gov.nl", "Audrey", "Windsor" },
                    { 140, "donald.winslet@gov.nl", "Donald", "Winslet" },
                    { 141, "mick.hepburn@google.com", "Mick", "Hepburn" },
                    { 142, "jimi.trump@something.com", "Jimi", "Trump" },
                    { 143, "barack.presley@google.com", "Barack", "Presley" },
                    { 144, "oprah.presley@tesla.com", "Oprah", "Presley" },
                    { 145, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 146, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 147, "jimi.winfrey@gov.us", "Jimi", "Winfrey" },
                    { 148, "mick.jagger@something.com", "Mick", "Jagger" },
                    { 149, "oprah.trump@google.com", "Oprah", "Trump" },
                    { 150, "audrey.winfrey@gov.ru", "Audrey", "Winfrey" },
                    { 151, "elvis.windsor@theworld.ca", "Elvis", "Windsor" },
                    { 152, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 153, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 154, "jimi.winslet@theworld.ca", "Jimi", "Winslet" },
                    { 155, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 156, "charles.hepburn@tesla.com", "Charles", "Hepburn" },
                    { 157, "charles.middleton@gov.gr", "Charles", "Middleton" },
                    { 158, "jimi.jagger@gov.gr", "Jimi", "Jagger" },
                    { 159, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 160, "kate.trump@google.com", "Kate", "Trump" },
                    { 161, "jimi.obama@gov.gr", "Jimi", "Obama" },
                    { 162, "oprah.middleton@bbc.co.uk", "Oprah", "Middleton" },
                    { 163, "audrey.middleton@gov.ru", "Audrey", "Middleton" },
                    { 164, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 165, "charles.winfrey@gov.ru", "Charles", "Winfrey" },
                    { 166, "audrey.windsor@something.com", "Audrey", "Windsor" },
                    { 167, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 168, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 169, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 170, "elvis.middleton@gov.ru", "Elvis", "Middleton" },
                    { 171, "audrey.trump@google.com", "Audrey", "Trump" },
                    { 172, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 173, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 174, "charles.winslet@gov.us", "Charles", "Winslet" },
                    { 175, "oprah.winfrey@nasa.org.us", "Oprah", "Winfrey" },
                    { 176, "audrey.hepburn@tesla.com", "Audrey", "Hepburn" },
                    { 177, "elvis.windsor@gov.ru", "Elvis", "Windsor" },
                    { 178, "charles.winfrey@theworld.ca", "Charles", "Winfrey" },
                    { 179, "jimi.hendrix@tesla.com", "Jimi", "Hendrix" },
                    { 180, "audrey.middleton@theworld.ca", "Audrey", "Middleton" },
                    { 181, "audrey.winslet@tesla.com", "Audrey", "Winslet" },
                    { 182, "barack.presley@theworld.ca", "Barack", "Presley" },
                    { 183, "oprah.hendrix@theworld.ca", "Oprah", "Hendrix" },
                    { 184, "charles.winfrey@gov.nl", "Charles", "Winfrey" },
                    { 185, "donald.middleton@gov.gr", "Donald", "Middleton" },
                    { 186, "donald.hendrix@google.com", "Donald", "Hendrix" },
                    { 187, "barack.obama@nasa.org.us", "Barack", "Obama" },
                    { 188, "audrey.jagger@bbc.co.uk", "Audrey", "Jagger" },
                    { 189, "elvis.hendrix@google.com", "Elvis", "Hendrix" },
                    { 190, "mick.hendrix@bbc.co.uk", "Mick", "Hendrix" },
                    { 191, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 192, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 193, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 194, "jimi.presley@gov.us", "Jimi", "Presley" },
                    { 195, "donald.winslet@gov.us", "Donald", "Winslet" },
                    { 196, "elvis.windsor@theworld.ca", "Elvis", "Windsor" },
                    { 197, "mick.obama@gov.gr", "Mick", "Obama" },
                    { 198, "charles.presley@google.com", "Charles", "Presley" },
                    { 199, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 200, "donald.jagger@bbc.co.uk", "Donald", "Jagger" },
                    { 201, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 202, "oprah.winfrey@tesla.com", "Oprah", "Winfrey" },
                    { 203, "oprah.winslet@something.com", "Oprah", "Winslet" },
                    { 204, "mick.presley@theworld.ca", "Mick", "Presley" },
                    { 205, "kate.winfrey@gov.gr", "Kate", "Winfrey" },
                    { 206, "oprah.jagger@gov.ru", "Oprah", "Jagger" },
                    { 207, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 208, "barack.jagger@theworld.ca", "Barack", "Jagger" },
                    { 209, "oprah.hendrix@gov.nl", "Oprah", "Hendrix" },
                    { 210, "jimi.hendrix@nasa.org.us", "Jimi", "Hendrix" },
                    { 211, "kate.winfrey@google.com", "Kate", "Winfrey" },
                    { 212, "oprah.presley@nasa.org.us", "Oprah", "Presley" },
                    { 213, "audrey.middleton@bbc.co.uk", "Audrey", "Middleton" },
                    { 214, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 215, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 216, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 217, "jimi.hendrix@google.com", "Jimi", "Hendrix" },
                    { 218, "jimi.windsor@google.com", "Jimi", "Windsor" },
                    { 219, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 220, "elvis.winslet@gov.ru", "Elvis", "Winslet" },
                    { 221, "jimi.hendrix@gov.us", "Jimi", "Hendrix" },
                    { 222, "elvis.trump@google.com", "Elvis", "Trump" },
                    { 223, "charles.windsor@bbc.co.uk", "Charles", "Windsor" },
                    { 224, "donald.hendrix@google.com", "Donald", "Hendrix" },
                    { 225, "barack.middleton@gov.gr", "Barack", "Middleton" },
                    { 226, "oprah.hepburn@google.com", "Oprah", "Hepburn" },
                    { 227, "elvis.middleton@google.com", "Elvis", "Middleton" },
                    { 228, "mick.hepburn@something.com", "Mick", "Hepburn" },
                    { 229, "jimi.winfrey@theworld.ca", "Jimi", "Winfrey" },
                    { 230, "barack.winslet@bbc.co.uk", "Barack", "Winslet" },
                    { 231, "charles.presley@nasa.org.us", "Charles", "Presley" },
                    { 232, "elvis.middleton@gov.gr", "Elvis", "Middleton" },
                    { 233, "oprah.hendrix@gov.gr", "Oprah", "Hendrix" },
                    { 234, "kate.presley@gov.nl", "Kate", "Presley" },
                    { 235, "kate.obama@something.com", "Kate", "Obama" },
                    { 236, "jimi.obama@gov.gr", "Jimi", "Obama" },
                    { 237, "elvis.middleton@gov.nl", "Elvis", "Middleton" },
                    { 238, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 239, "oprah.hendrix@gov.gr", "Oprah", "Hendrix" },
                    { 240, "donald.windsor@gov.ru", "Donald", "Windsor" },
                    { 241, "audrey.winslet@nasa.org.us", "Audrey", "Winslet" },
                    { 242, "donald.trump@gov.nl", "Donald", "Trump" },
                    { 243, "elvis.hepburn@bbc.co.uk", "Elvis", "Hepburn" },
                    { 244, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 245, "jimi.obama@theworld.ca", "Jimi", "Obama" },
                    { 246, "barack.hendrix@nasa.org.us", "Barack", "Hendrix" },
                    { 247, "mick.obama@google.com", "Mick", "Obama" },
                    { 248, "elvis.obama@gov.ru", "Elvis", "Obama" },
                    { 249, "jimi.winslet@gov.nl", "Jimi", "Winslet" }
                });

            migrationBuilder.InsertData(
                table: "Book",
                columns: new[] { "id", "AuthorId", "title" },
                values: new object[,]
                {
                    { 1, 23, "The Microscopic Buildings" },
                    { 2, 205, "Several Transparent Leopards" },
                    { 3, 238, "A bunch of Large Flowers" },
                    { 4, 88, "Two Transparent Flowers" },
                    { 5, 28, "An army of Large Houses" },
                    { 6, 99, "A herd of Orange Planets" },
                    { 7, 165, "Several Purple Planets" },
                    { 8, 161, "A bunch of Orange Leopards" },
                    { 9, 221, "A herd of Purple Planets" },
                    { 10, 67, "Two Rose Smelling Houses" },
                    { 11, 28, "A bunch of Purple Buildings" },
                    { 12, 26, "A bunch of Large Cars" },
                    { 13, 41, "The Rose Smelling Cars" },
                    { 14, 131, "A bunch of Purple Houses" },
                    { 15, 145, "A herd of Transparent Houses" },
                    { 16, 209, "The Green Buildings" },
                    { 17, 84, "Two Transparent Houses" },
                    { 18, 95, "Two Green Houses" },
                    { 19, 245, "Fifteen Large Houses" },
                    { 20, 12, "Fifteen Orange Buildings" },
                    { 21, 169, "Two Bitter Houses" },
                    { 22, 111, "The Rose Smelling Houses" },
                    { 23, 69, "A bunch of Bitter Planets" },
                    { 24, 215, "Several Bitter Planets" },
                    { 25, 206, "An army of Purple Planets" },
                    { 26, 81, "Several Green Cars" },
                    { 27, 200, "A herd of Green Flowers" },
                    { 28, 21, "Two Orange Planets" },
                    { 29, 115, "The Rose Smelling Leopards" },
                    { 30, 29, "An army of Transparent Buildings" },
                    { 31, 226, "A bunch of Microscopic Planets" },
                    { 32, 137, "Several Rose Smelling Houses" },
                    { 33, 144, "Fifteen Rose Smelling Buildings" },
                    { 34, 35, "Two Transparent Buildings" },
                    { 35, 77, "A herd of Microscopic Leopards" },
                    { 36, 91, "The Green Leopards" },
                    { 37, 233, "The Orange Leopards" },
                    { 38, 101, "An army of Transparent Cars" },
                    { 39, 30, "Several Purple Leopards" },
                    { 40, 246, "The Green Buildings" },
                    { 41, 240, "A bunch of Purple Cars" },
                    { 42, 187, "Several Microscopic Planets" },
                    { 43, 152, "The Transparent Buildings" },
                    { 44, 144, "A bunch of Orange Buildings" },
                    { 45, 158, "Several Rose Smelling Buildings" },
                    { 46, 112, "An army of Green Planets" },
                    { 47, 3, "Several Microscopic Cars" },
                    { 48, 147, "A herd of Purple Planets" },
                    { 49, 192, "A bunch of Purple Cars" },
                    { 50, 29, "An army of Purple Buildings" },
                    { 51, 32, "The Large Flowers" },
                    { 52, 241, "The Microscopic Leopards" },
                    { 53, 211, "A herd of Transparent Houses" },
                    { 54, 6, "An army of Bitter Buildings" },
                    { 55, 128, "Several Green Buildings" },
                    { 56, 191, "Several Green Buildings" },
                    { 57, 249, "A herd of Bitter Planets" },
                    { 58, 141, "Two Bitter Houses" },
                    { 59, 211, "Fifteen Microscopic Cars" },
                    { 60, 51, "Fifteen Purple Cars" },
                    { 61, 236, "Two Green Buildings" },
                    { 62, 21, "Several Orange Cars" },
                    { 63, 27, "A bunch of Transparent Flowers" },
                    { 64, 111, "Several Large Planets" },
                    { 65, 235, "Two Bitter Buildings" },
                    { 66, 118, "Two Orange Houses" },
                    { 67, 175, "A bunch of Large Leopards" },
                    { 68, 187, "A herd of Orange Leopards" },
                    { 69, 219, "The Rose Smelling Flowers" },
                    { 70, 48, "A bunch of Transparent Flowers" },
                    { 71, 133, "The Microscopic Cars" },
                    { 72, 25, "Several Large Buildings" },
                    { 73, 198, "The Orange Buildings" },
                    { 74, 155, "Several Bitter Planets" },
                    { 75, 106, "Two Microscopic Cars" },
                    { 76, 216, "A bunch of Transparent Buildings" },
                    { 77, 55, "Two Rose Smelling Houses" },
                    { 78, 178, "Several Transparent Planets" },
                    { 79, 42, "A herd of Bitter Leopards" },
                    { 80, 99, "A herd of Orange Leopards" },
                    { 81, 176, "Several Large Planets" },
                    { 82, 227, "Two Rose Smelling Buildings" },
                    { 83, 241, "An army of Purple Leopards" },
                    { 84, 19, "Two Green Buildings" },
                    { 85, 248, "A bunch of Transparent Cars" },
                    { 86, 239, "The Green Houses" },
                    { 87, 188, "Two Orange Buildings" },
                    { 88, 143, "Fifteen Rose Smelling Flowers" },
                    { 89, 115, "Fifteen Orange Flowers" },
                    { 90, 170, "A herd of Microscopic Cars" },
                    { 91, 74, "The Large Cars" },
                    { 92, 180, "An army of Rose Smelling Leopards" },
                    { 93, 229, "The Rose Smelling Cars" },
                    { 94, 116, "Two Green Leopards" },
                    { 95, 96, "A herd of Rose Smelling Buildings" },
                    { 96, 69, "A bunch of Large Cars" },
                    { 97, 35, "Fifteen Orange Buildings" },
                    { 98, 204, "Fifteen Rose Smelling Planets" },
                    { 99, 159, "Several Bitter Flowers" },
                    { 100, 156, "An army of Bitter Houses" },
                    { 101, 79, "Fifteen Transparent Houses" },
                    { 102, 70, "A bunch of Transparent Flowers" },
                    { 103, 10, "A herd of Rose Smelling Houses" },
                    { 104, 19, "A bunch of Microscopic Leopards" },
                    { 105, 165, "An army of Green Flowers" },
                    { 106, 179, "Fifteen Bitter Planets" },
                    { 107, 216, "A herd of Rose Smelling Buildings" },
                    { 108, 209, "The Rose Smelling Leopards" },
                    { 109, 158, "The Orange Buildings" },
                    { 110, 96, "A herd of Green Leopards" },
                    { 111, 219, "A bunch of Large Flowers" },
                    { 112, 49, "The Green Planets" },
                    { 113, 143, "An army of Rose Smelling Leopards" },
                    { 114, 158, "A bunch of Rose Smelling Leopards" },
                    { 115, 237, "Several Green Planets" },
                    { 116, 225, "Several Bitter Houses" },
                    { 117, 131, "Several Large Leopards" },
                    { 118, 104, "Several Purple Planets" },
                    { 119, 120, "An army of Bitter Cars" },
                    { 120, 129, "A herd of Purple Flowers" },
                    { 121, 141, "Fifteen Transparent Flowers" },
                    { 122, 238, "A bunch of Orange Buildings" },
                    { 123, 154, "A herd of Purple Houses" },
                    { 124, 100, "The Purple Leopards" },
                    { 125, 117, "Several Transparent Buildings" },
                    { 126, 69, "A bunch of Transparent Flowers" },
                    { 127, 181, "Fifteen Bitter Leopards" },
                    { 128, 136, "A herd of Large Planets" },
                    { 129, 65, "A bunch of Transparent Planets" },
                    { 130, 189, "Two Transparent Leopards" },
                    { 131, 150, "A herd of Orange Cars" },
                    { 132, 153, "The Orange Houses" },
                    { 133, 87, "Several Green Leopards" },
                    { 134, 228, "A herd of Orange Cars" },
                    { 135, 231, "Several Microscopic Leopards" },
                    { 136, 236, "An army of Green Leopards" },
                    { 137, 158, "A bunch of Microscopic Cars" },
                    { 138, 32, "An army of Purple Buildings" },
                    { 139, 222, "Two Purple Planets" },
                    { 140, 180, "A herd of Orange Planets" },
                    { 141, 17, "The Purple Cars" },
                    { 142, 176, "A bunch of Large Flowers" },
                    { 143, 149, "The Microscopic Leopards" },
                    { 144, 156, "Fifteen Large Flowers" },
                    { 145, 149, "Two Rose Smelling Leopards" },
                    { 146, 105, "A bunch of Microscopic Planets" },
                    { 147, 225, "Two Orange Flowers" },
                    { 148, 167, "The Bitter Planets" },
                    { 149, 114, "An army of Bitter Leopards" },
                    { 150, 48, "An army of Purple Houses" },
                    { 151, 122, "The Rose Smelling Leopards" },
                    { 152, 221, "The Orange Flowers" },
                    { 153, 20, "A bunch of Rose Smelling Cars" },
                    { 154, 164, "A herd of Green Cars" },
                    { 155, 3, "The Transparent Cars" },
                    { 156, 92, "Two Transparent Leopards" },
                    { 157, 94, "The Bitter Flowers" },
                    { 158, 211, "Several Rose Smelling Cars" },
                    { 159, 223, "Several Rose Smelling Houses" },
                    { 160, 2, "Fifteen Transparent Planets" },
                    { 161, 247, "An army of Microscopic Houses" },
                    { 162, 75, "Several Microscopic Cars" },
                    { 163, 113, "An army of Purple Houses" },
                    { 164, 245, "The Purple Houses" },
                    { 165, 237, "A bunch of Transparent Buildings" },
                    { 166, 159, "Fifteen Bitter Flowers" },
                    { 167, 53, "Two Bitter Flowers" },
                    { 168, 8, "Two Green Cars" },
                    { 169, 141, "A herd of Green Houses" },
                    { 170, 56, "A herd of Microscopic Leopards" },
                    { 171, 249, "A bunch of Large Leopards" },
                    { 172, 218, "A bunch of Orange Houses" },
                    { 173, 133, "A bunch of Large Buildings" },
                    { 174, 171, "Fifteen Bitter Buildings" },
                    { 175, 147, "An army of Bitter Buildings" },
                    { 176, 125, "Two Large Planets" },
                    { 177, 88, "Two Rose Smelling Buildings" },
                    { 178, 71, "Fifteen Bitter Houses" },
                    { 179, 192, "Several Transparent Flowers" },
                    { 180, 163, "A herd of Green Planets" },
                    { 181, 191, "Fifteen Green Cars" },
                    { 182, 141, "The Bitter Flowers" },
                    { 183, 209, "The Orange Leopards" },
                    { 184, 56, "A bunch of Green Cars" },
                    { 185, 20, "Several Purple Houses" },
                    { 186, 78, "An army of Bitter Buildings" },
                    { 187, 171, "A bunch of Large Cars" },
                    { 188, 65, "The Purple Leopards" },
                    { 189, 2, "An army of Purple Flowers" },
                    { 190, 76, "A herd of Purple Buildings" },
                    { 191, 182, "An army of Green Buildings" },
                    { 192, 38, "Two Green Flowers" },
                    { 193, 4, "An army of Transparent Houses" },
                    { 194, 43, "Several Purple Leopards" },
                    { 195, 203, "An army of Green Flowers" },
                    { 196, 22, "A herd of Transparent Cars" },
                    { 197, 141, "Two Transparent Houses" },
                    { 198, 86, "A bunch of Transparent Planets" },
                    { 199, 132, "An army of Large Leopards" },
                    { 200, 115, "The Large Houses" },
                    { 201, 50, "An army of Rose Smelling Houses" },
                    { 202, 116, "Several Bitter Buildings" },
                    { 203, 246, "A herd of Bitter Houses" },
                    { 204, 123, "Fifteen Purple Leopards" },
                    { 205, 249, "A herd of Purple Planets" },
                    { 206, 190, "The Microscopic Cars" },
                    { 207, 182, "Fifteen Microscopic Cars" },
                    { 208, 60, "Two Rose Smelling Leopards" },
                    { 209, 28, "Two Microscopic Planets" },
                    { 210, 217, "An army of Large Planets" },
                    { 211, 113, "A bunch of Green Flowers" },
                    { 212, 76, "The Microscopic Cars" },
                    { 213, 37, "A bunch of Green Buildings" },
                    { 214, 208, "A herd of Green Houses" },
                    { 215, 199, "Several Microscopic Cars" },
                    { 216, 232, "Several Green Planets" },
                    { 217, 29, "An army of Transparent Planets" },
                    { 218, 85, "Fifteen Purple Planets" },
                    { 219, 69, "An army of Green Planets" },
                    { 220, 10, "Two Large Leopards" },
                    { 221, 33, "A herd of Rose Smelling Flowers" },
                    { 222, 17, "Fifteen Bitter Buildings" },
                    { 223, 125, "A herd of Transparent Planets" },
                    { 224, 201, "The Orange Planets" },
                    { 225, 241, "Several Transparent Cars" },
                    { 226, 190, "A bunch of Microscopic Planets" },
                    { 227, 208, "Fifteen Orange Buildings" },
                    { 228, 64, "Several Large Planets" },
                    { 229, 101, "An army of Rose Smelling Cars" },
                    { 230, 177, "Two Rose Smelling Buildings" },
                    { 231, 40, "Two Green Planets" },
                    { 232, 38, "A herd of Orange Cars" },
                    { 233, 109, "The Purple Cars" },
                    { 234, 217, "An army of Rose Smelling Leopards" },
                    { 235, 19, "The Transparent Planets" },
                    { 236, 114, "Two Bitter Cars" },
                    { 237, 185, "Several Bitter Flowers" },
                    { 238, 218, "A bunch of Bitter Houses" },
                    { 239, 55, "Two Microscopic Cars" },
                    { 240, 132, "A herd of Orange Planets" },
                    { 241, 131, "Fifteen Purple Cars" },
                    { 242, 81, "Two Purple Buildings" },
                    { 243, 201, "Two Microscopic Buildings" },
                    { 244, 134, "Two Large Buildings" },
                    { 245, 107, "A bunch of Green Leopards" },
                    { 246, 129, "Two Microscopic Planets" },
                    { 247, 159, "The Rose Smelling Cars" },
                    { 248, 65, "The Orange Buildings" },
                    { 249, 174, "An army of Transparent Leopards" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Book_AuthorId",
                table: "Book",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Book");

            migrationBuilder.DropTable(
                name: "Author");
        }
    }
}
