using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    FirstName = table.Column<string>(type: "text", nullable: false),
                    LastName = table.Column<string>(type: "text", nullable: false),
                    Email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Books",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Books", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Books_Authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Authors",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "Id", "Email", "FirstName", "LastName" },
                values: new object[,]
                {
                    { 1, "elvis.winslet@nasa.org.us", "Elvis", "Winslet" },
                    { 2, "kate.hepburn@gov.us", "Kate", "Hepburn" },
                    { 3, "charles.hepburn@google.com", "Charles", "Hepburn" },
                    { 4, "barack.trump@gov.ru", "Barack", "Trump" },
                    { 5, "mick.obama@google.com", "Mick", "Obama" },
                    { 6, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 7, "jimi.hendrix@bbc.co.uk", "Jimi", "Hendrix" },
                    { 8, "barack.jagger@google.com", "Barack", "Jagger" },
                    { 9, "mick.hepburn@nasa.org.us", "Mick", "Hepburn" },
                    { 10, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 11, "elvis.hendrix@something.com", "Elvis", "Hendrix" },
                    { 12, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 13, "kate.trump@tesla.com", "Kate", "Trump" },
                    { 14, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 15, "barack.hendrix@gov.ru", "Barack", "Hendrix" },
                    { 16, "mick.hendrix@gov.nl", "Mick", "Hendrix" },
                    { 17, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 18, "audrey.hendrix@google.com", "Audrey", "Hendrix" },
                    { 19, "elvis.jagger@gov.ru", "Elvis", "Jagger" },
                    { 20, "charles.presley@something.com", "Charles", "Presley" },
                    { 21, "jimi.hepburn@gov.gr", "Jimi", "Hepburn" },
                    { 22, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 23, "jimi.winfrey@theworld.ca", "Jimi", "Winfrey" },
                    { 24, "mick.presley@bbc.co.uk", "Mick", "Presley" },
                    { 25, "donald.presley@something.com", "Donald", "Presley" },
                    { 26, "donald.winslet@nasa.org.us", "Donald", "Winslet" },
                    { 27, "oprah.hepburn@bbc.co.uk", "Oprah", "Hepburn" },
                    { 28, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 29, "charles.windsor@gov.ru", "Charles", "Windsor" },
                    { 30, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 31, "kate.obama@gov.us", "Kate", "Obama" },
                    { 32, "oprah.presley@bbc.co.uk", "Oprah", "Presley" },
                    { 33, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 34, "mick.trump@google.com", "Mick", "Trump" },
                    { 35, "kate.middleton@theworld.ca", "Kate", "Middleton" },
                    { 36, "elvis.obama@google.com", "Elvis", "Obama" },
                    { 37, "mick.winslet@theworld.ca", "Mick", "Winslet" },
                    { 38, "audrey.winfrey@gov.us", "Audrey", "Winfrey" },
                    { 39, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 40, "jimi.jagger@bbc.co.uk", "Jimi", "Jagger" },
                    { 41, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 42, "charles.jagger@gov.ru", "Charles", "Jagger" },
                    { 43, "charles.hepburn@gov.ru", "Charles", "Hepburn" },
                    { 44, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 45, "barack.presley@gov.us", "Barack", "Presley" },
                    { 46, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 47, "donald.hendrix@something.com", "Donald", "Hendrix" },
                    { 48, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 49, "donald.obama@gov.nl", "Donald", "Obama" },
                    { 50, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 51, "kate.obama@google.com", "Kate", "Obama" },
                    { 52, "oprah.winslet@gov.ru", "Oprah", "Winslet" },
                    { 53, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 54, "jimi.winfrey@theworld.ca", "Jimi", "Winfrey" },
                    { 55, "barack.presley@something.com", "Barack", "Presley" },
                    { 56, "elvis.hepburn@something.com", "Elvis", "Hepburn" },
                    { 57, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 58, "audrey.hendrix@gov.us", "Audrey", "Hendrix" },
                    { 59, "mick.winfrey@google.com", "Mick", "Winfrey" },
                    { 60, "charles.presley@nasa.org.us", "Charles", "Presley" },
                    { 61, "kate.winfrey@tesla.com", "Kate", "Winfrey" },
                    { 62, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 63, "kate.obama@google.com", "Kate", "Obama" },
                    { 64, "oprah.hendrix@gov.us", "Oprah", "Hendrix" },
                    { 65, "charles.windsor@theworld.ca", "Charles", "Windsor" },
                    { 66, "jimi.trump@bbc.co.uk", "Jimi", "Trump" },
                    { 67, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 68, "barack.middleton@theworld.ca", "Barack", "Middleton" },
                    { 69, "mick.windsor@gov.gr", "Mick", "Windsor" },
                    { 70, "kate.windsor@gov.gr", "Kate", "Windsor" },
                    { 71, "kate.jagger@gov.ru", "Kate", "Jagger" },
                    { 72, "barack.hepburn@gov.nl", "Barack", "Hepburn" },
                    { 73, "barack.jagger@theworld.ca", "Barack", "Jagger" },
                    { 74, "elvis.obama@gov.ru", "Elvis", "Obama" },
                    { 75, "barack.windsor@bbc.co.uk", "Barack", "Windsor" },
                    { 76, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 77, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 78, "donald.winfrey@gov.us", "Donald", "Winfrey" },
                    { 79, "kate.obama@google.com", "Kate", "Obama" },
                    { 80, "jimi.hepburn@theworld.ca", "Jimi", "Hepburn" },
                    { 81, "audrey.obama@tesla.com", "Audrey", "Obama" },
                    { 82, "charles.hepburn@tesla.com", "Charles", "Hepburn" },
                    { 83, "elvis.jagger@gov.us", "Elvis", "Jagger" },
                    { 84, "barack.winfrey@something.com", "Barack", "Winfrey" },
                    { 85, "mick.middleton@gov.nl", "Mick", "Middleton" },
                    { 86, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 87, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 88, "donald.hendrix@something.com", "Donald", "Hendrix" },
                    { 89, "mick.hendrix@nasa.org.us", "Mick", "Hendrix" },
                    { 90, "audrey.trump@gov.nl", "Audrey", "Trump" },
                    { 91, "barack.winfrey@theworld.ca", "Barack", "Winfrey" },
                    { 92, "kate.hepburn@nasa.org.us", "Kate", "Hepburn" },
                    { 93, "barack.hepburn@gov.us", "Barack", "Hepburn" },
                    { 94, "mick.obama@gov.gr", "Mick", "Obama" },
                    { 95, "charles.winslet@gov.nl", "Charles", "Winslet" },
                    { 96, "charles.obama@bbc.co.uk", "Charles", "Obama" },
                    { 97, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 98, "jimi.hepburn@google.com", "Jimi", "Hepburn" },
                    { 99, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 100, "jimi.obama@gov.us", "Jimi", "Obama" },
                    { 101, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 102, "mick.obama@nasa.org.us", "Mick", "Obama" },
                    { 103, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 104, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 105, "charles.jagger@gov.gr", "Charles", "Jagger" },
                    { 106, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 107, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 108, "jimi.obama@gov.ru", "Jimi", "Obama" },
                    { 109, "donald.middleton@gov.nl", "Donald", "Middleton" },
                    { 110, "kate.winslet@nasa.org.us", "Kate", "Winslet" },
                    { 111, "oprah.middleton@something.com", "Oprah", "Middleton" },
                    { 112, "mick.jagger@nasa.org.us", "Mick", "Jagger" },
                    { 113, "mick.presley@something.com", "Mick", "Presley" },
                    { 114, "barack.winslet@gov.us", "Barack", "Winslet" },
                    { 115, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 116, "donald.trump@gov.nl", "Donald", "Trump" },
                    { 117, "elvis.middleton@theworld.ca", "Elvis", "Middleton" },
                    { 118, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 119, "donald.windsor@gov.ru", "Donald", "Windsor" },
                    { 120, "jimi.winfrey@gov.gr", "Jimi", "Winfrey" },
                    { 121, "barack.obama@gov.us", "Barack", "Obama" },
                    { 122, "audrey.hepburn@tesla.com", "Audrey", "Hepburn" },
                    { 123, "kate.trump@something.com", "Kate", "Trump" },
                    { 124, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 125, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 126, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 127, "charles.windsor@theworld.ca", "Charles", "Windsor" },
                    { 128, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 129, "elvis.presley@google.com", "Elvis", "Presley" },
                    { 130, "charles.hepburn@gov.gr", "Charles", "Hepburn" },
                    { 131, "audrey.obama@tesla.com", "Audrey", "Obama" },
                    { 132, "elvis.middleton@gov.gr", "Elvis", "Middleton" },
                    { 133, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 134, "kate.trump@google.com", "Kate", "Trump" },
                    { 135, "barack.windsor@gov.ru", "Barack", "Windsor" },
                    { 136, "charles.winfrey@something.com", "Charles", "Winfrey" },
                    { 137, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 138, "kate.presley@gov.us", "Kate", "Presley" },
                    { 139, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 140, "audrey.hendrix@gov.gr", "Audrey", "Hendrix" },
                    { 141, "audrey.middleton@gov.ru", "Audrey", "Middleton" },
                    { 142, "elvis.trump@gov.gr", "Elvis", "Trump" },
                    { 143, "mick.obama@nasa.org.us", "Mick", "Obama" },
                    { 144, "charles.windsor@gov.us", "Charles", "Windsor" },
                    { 145, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 146, "kate.presley@gov.us", "Kate", "Presley" },
                    { 147, "mick.middleton@gov.gr", "Mick", "Middleton" },
                    { 148, "charles.winfrey@gov.gr", "Charles", "Winfrey" },
                    { 149, "jimi.trump@theworld.ca", "Jimi", "Trump" },
                    { 150, "jimi.winfrey@something.com", "Jimi", "Winfrey" },
                    { 151, "mick.obama@gov.gr", "Mick", "Obama" },
                    { 152, "oprah.winfrey@theworld.ca", "Oprah", "Winfrey" },
                    { 153, "elvis.windsor@gov.ru", "Elvis", "Windsor" },
                    { 154, "donald.hepburn@bbc.co.uk", "Donald", "Hepburn" },
                    { 155, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 156, "charles.obama@gov.gr", "Charles", "Obama" },
                    { 157, "mick.windsor@gov.gr", "Mick", "Windsor" },
                    { 158, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 159, "kate.middleton@gov.ru", "Kate", "Middleton" },
                    { 160, "kate.middleton@gov.us", "Kate", "Middleton" },
                    { 161, "barack.jagger@gov.ru", "Barack", "Jagger" },
                    { 162, "charles.winslet@gov.us", "Charles", "Winslet" },
                    { 163, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 164, "charles.windsor@gov.ru", "Charles", "Windsor" },
                    { 165, "donald.winslet@tesla.com", "Donald", "Winslet" },
                    { 166, "kate.obama@google.com", "Kate", "Obama" },
                    { 167, "mick.hendrix@gov.gr", "Mick", "Hendrix" },
                    { 168, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 169, "kate.middleton@gov.ru", "Kate", "Middleton" },
                    { 170, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 171, "elvis.winslet@gov.ru", "Elvis", "Winslet" },
                    { 172, "barack.hendrix@nasa.org.us", "Barack", "Hendrix" },
                    { 173, "charles.hepburn@something.com", "Charles", "Hepburn" },
                    { 174, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 175, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 176, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 177, "barack.hepburn@theworld.ca", "Barack", "Hepburn" },
                    { 178, "oprah.obama@gov.ru", "Oprah", "Obama" },
                    { 179, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 180, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 181, "oprah.winfrey@theworld.ca", "Oprah", "Winfrey" },
                    { 182, "jimi.presley@gov.gr", "Jimi", "Presley" },
                    { 183, "elvis.winslet@gov.nl", "Elvis", "Winslet" },
                    { 184, "barack.presley@gov.ru", "Barack", "Presley" },
                    { 185, "charles.obama@gov.gr", "Charles", "Obama" },
                    { 186, "charles.middleton@bbc.co.uk", "Charles", "Middleton" },
                    { 187, "elvis.hepburn@something.com", "Elvis", "Hepburn" },
                    { 188, "jimi.jagger@nasa.org.us", "Jimi", "Jagger" },
                    { 189, "donald.trump@gov.ru", "Donald", "Trump" },
                    { 190, "mick.hendrix@something.com", "Mick", "Hendrix" },
                    { 191, "mick.windsor@gov.ru", "Mick", "Windsor" },
                    { 192, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 193, "charles.hendrix@gov.ru", "Charles", "Hendrix" },
                    { 194, "jimi.middleton@nasa.org.us", "Jimi", "Middleton" },
                    { 195, "mick.middleton@tesla.com", "Mick", "Middleton" },
                    { 196, "audrey.winslet@nasa.org.us", "Audrey", "Winslet" },
                    { 197, "barack.winslet@theworld.ca", "Barack", "Winslet" },
                    { 198, "donald.presley@theworld.ca", "Donald", "Presley" },
                    { 199, "audrey.winslet@google.com", "Audrey", "Winslet" },
                    { 200, "barack.middleton@tesla.com", "Barack", "Middleton" },
                    { 201, "barack.trump@something.com", "Barack", "Trump" },
                    { 202, "barack.obama@theworld.ca", "Barack", "Obama" },
                    { 203, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 204, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 205, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 206, "audrey.presley@theworld.ca", "Audrey", "Presley" },
                    { 207, "audrey.winslet@something.com", "Audrey", "Winslet" },
                    { 208, "jimi.hepburn@google.com", "Jimi", "Hepburn" },
                    { 209, "mick.middleton@gov.us", "Mick", "Middleton" },
                    { 210, "audrey.middleton@gov.ru", "Audrey", "Middleton" },
                    { 211, "barack.winslet@gov.nl", "Barack", "Winslet" },
                    { 212, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 213, "charles.jagger@tesla.com", "Charles", "Jagger" },
                    { 214, "oprah.jagger@gov.us", "Oprah", "Jagger" },
                    { 215, "audrey.presley@gov.ru", "Audrey", "Presley" },
                    { 216, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 217, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 218, "charles.winslet@something.com", "Charles", "Winslet" },
                    { 219, "donald.trump@nasa.org.us", "Donald", "Trump" },
                    { 220, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 221, "barack.presley@gov.gr", "Barack", "Presley" },
                    { 222, "audrey.winfrey@theworld.ca", "Audrey", "Winfrey" },
                    { 223, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 224, "barack.windsor@gov.nl", "Barack", "Windsor" },
                    { 225, "elvis.hepburn@google.com", "Elvis", "Hepburn" },
                    { 226, "elvis.presley@nasa.org.us", "Elvis", "Presley" },
                    { 227, "charles.winslet@bbc.co.uk", "Charles", "Winslet" },
                    { 228, "oprah.winfrey@theworld.ca", "Oprah", "Winfrey" },
                    { 229, "jimi.winfrey@bbc.co.uk", "Jimi", "Winfrey" },
                    { 230, "kate.winslet@bbc.co.uk", "Kate", "Winslet" },
                    { 231, "barack.windsor@gov.us", "Barack", "Windsor" },
                    { 232, "kate.hendrix@gov.us", "Kate", "Hendrix" },
                    { 233, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 234, "kate.hendrix@theworld.ca", "Kate", "Hendrix" },
                    { 235, "audrey.hendrix@gov.nl", "Audrey", "Hendrix" },
                    { 236, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 237, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 238, "mick.trump@nasa.org.us", "Mick", "Trump" },
                    { 239, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 240, "barack.winfrey@bbc.co.uk", "Barack", "Winfrey" },
                    { 241, "donald.middleton@gov.ru", "Donald", "Middleton" },
                    { 242, "charles.trump@nasa.org.us", "Charles", "Trump" },
                    { 243, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 244, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 245, "oprah.hendrix@google.com", "Oprah", "Hendrix" },
                    { 246, "charles.winslet@nasa.org.us", "Charles", "Winslet" },
                    { 247, "mick.windsor@gov.gr", "Mick", "Windsor" },
                    { 248, "kate.winslet@google.com", "Kate", "Winslet" },
                    { 249, "charles.presley@nasa.org.us", "Charles", "Presley" }
                });

            migrationBuilder.InsertData(
                table: "Books",
                columns: new[] { "Id", "AuthorId", "Title" },
                values: new object[,]
                {
                    { 1, 203, "Several Orange Buildings" },
                    { 2, 67, "A herd of Purple Flowers" },
                    { 3, 167, "Fifteen Purple Flowers" },
                    { 4, 183, "An army of Orange Buildings" },
                    { 5, 63, "Two Green Flowers" },
                    { 6, 71, "Several Large Leopards" },
                    { 7, 167, "Two Bitter Buildings" },
                    { 8, 137, "An army of Microscopic Buildings" },
                    { 9, 202, "An army of Transparent Planets" },
                    { 10, 79, "An army of Large Flowers" },
                    { 11, 153, "Two Transparent Buildings" },
                    { 12, 44, "Fifteen Bitter Houses" },
                    { 13, 140, "Two Rose Smelling Cars" },
                    { 14, 202, "Several Rose Smelling Planets" },
                    { 15, 188, "Fifteen Bitter Cars" },
                    { 16, 167, "An army of Microscopic Flowers" },
                    { 17, 129, "The Large Flowers" },
                    { 18, 191, "An army of Green Leopards" },
                    { 19, 240, "Several Purple Leopards" },
                    { 20, 130, "Fifteen Transparent Flowers" },
                    { 21, 93, "Several Bitter Flowers" },
                    { 22, 34, "A herd of Bitter Buildings" },
                    { 23, 142, "Two Orange Buildings" },
                    { 24, 195, "A bunch of Large Buildings" },
                    { 25, 39, "Several Purple Leopards" },
                    { 26, 114, "A bunch of Large Cars" },
                    { 27, 54, "Several Purple Leopards" },
                    { 28, 71, "An army of Orange Cars" },
                    { 29, 233, "Several Orange Houses" },
                    { 30, 42, "Fifteen Bitter Houses" },
                    { 31, 61, "A bunch of Large Buildings" },
                    { 32, 240, "The Orange Houses" },
                    { 33, 138, "Fifteen Transparent Planets" },
                    { 34, 149, "An army of Large Flowers" },
                    { 35, 193, "Several Green Houses" },
                    { 36, 235, "A herd of Rose Smelling Buildings" },
                    { 37, 216, "A bunch of Microscopic Cars" },
                    { 38, 125, "The Transparent Flowers" },
                    { 39, 184, "A herd of Bitter Planets" },
                    { 40, 26, "A herd of Purple Leopards" },
                    { 41, 22, "An army of Rose Smelling Cars" },
                    { 42, 165, "A herd of Green Houses" },
                    { 43, 204, "A herd of Bitter Leopards" },
                    { 44, 95, "Two Purple Flowers" },
                    { 45, 14, "Several Bitter Houses" },
                    { 46, 130, "Several Transparent Cars" },
                    { 47, 106, "An army of Transparent Planets" },
                    { 48, 52, "Fifteen Green Cars" },
                    { 49, 21, "A bunch of Purple Buildings" },
                    { 50, 14, "A herd of Orange Leopards" },
                    { 51, 159, "Two Bitter Leopards" },
                    { 52, 123, "Fifteen Purple Leopards" },
                    { 53, 15, "An army of Orange Houses" },
                    { 54, 14, "The Bitter Houses" },
                    { 55, 177, "The Purple Planets" },
                    { 56, 158, "Several Orange Houses" },
                    { 57, 89, "A bunch of Green Leopards" },
                    { 58, 141, "A bunch of Transparent Houses" },
                    { 59, 67, "Fifteen Transparent Leopards" },
                    { 60, 35, "A bunch of Transparent Planets" },
                    { 61, 223, "Several Rose Smelling Cars" },
                    { 62, 93, "An army of Orange Planets" },
                    { 63, 102, "Two Microscopic Cars" },
                    { 64, 128, "Two Transparent Leopards" },
                    { 65, 4, "A herd of Orange Buildings" },
                    { 66, 196, "A herd of Rose Smelling Leopards" },
                    { 67, 85, "A bunch of Large Buildings" },
                    { 68, 103, "Several Bitter Planets" },
                    { 69, 98, "A bunch of Green Leopards" },
                    { 70, 167, "An army of Purple Buildings" },
                    { 71, 102, "The Green Buildings" },
                    { 72, 92, "A bunch of Purple Buildings" },
                    { 73, 27, "An army of Microscopic Flowers" },
                    { 74, 1, "Several Transparent Planets" },
                    { 75, 32, "The Green Planets" },
                    { 76, 28, "An army of Transparent Flowers" },
                    { 77, 176, "Fifteen Large Flowers" },
                    { 78, 245, "Several Large Leopards" },
                    { 79, 1, "An army of Microscopic Cars" },
                    { 80, 45, "Several Bitter Flowers" },
                    { 81, 189, "An army of Orange Buildings" },
                    { 82, 178, "The Orange Houses" },
                    { 83, 135, "The Transparent Cars" },
                    { 84, 4, "Several Purple Cars" },
                    { 85, 155, "Fifteen Purple Cars" },
                    { 86, 24, "A bunch of Large Leopards" },
                    { 87, 183, "The Transparent Leopards" },
                    { 88, 114, "A herd of Large Cars" },
                    { 89, 169, "An army of Transparent Cars" },
                    { 90, 37, "Fifteen Bitter Flowers" },
                    { 91, 41, "A herd of Large Buildings" },
                    { 92, 62, "A herd of Purple Flowers" },
                    { 93, 113, "Two Orange Leopards" },
                    { 94, 52, "A bunch of Orange Houses" },
                    { 95, 175, "Several Purple Buildings" },
                    { 96, 63, "Two Transparent Flowers" },
                    { 97, 147, "The Large Cars" },
                    { 98, 193, "An army of Microscopic Leopards" },
                    { 99, 246, "Two Purple Planets" },
                    { 100, 127, "A bunch of Orange Cars" },
                    { 101, 222, "A bunch of Rose Smelling Buildings" },
                    { 102, 78, "Several Green Planets" },
                    { 103, 23, "Fifteen Orange Buildings" },
                    { 104, 66, "An army of Transparent Leopards" },
                    { 105, 104, "A herd of Transparent Flowers" },
                    { 106, 141, "A herd of Microscopic Leopards" },
                    { 107, 141, "The Orange Planets" },
                    { 108, 16, "An army of Bitter Houses" },
                    { 109, 59, "A bunch of Large Houses" },
                    { 110, 137, "Two Bitter Houses" },
                    { 111, 97, "Two Transparent Cars" },
                    { 112, 247, "The Bitter Cars" },
                    { 113, 201, "The Rose Smelling Planets" },
                    { 114, 194, "An army of Bitter Houses" },
                    { 115, 127, "Two Large Houses" },
                    { 116, 30, "Several Orange Buildings" },
                    { 117, 19, "The Transparent Planets" },
                    { 118, 33, "The Transparent Planets" },
                    { 119, 129, "A bunch of Bitter Flowers" },
                    { 120, 154, "A herd of Bitter Cars" },
                    { 121, 6, "Several Bitter Planets" },
                    { 122, 50, "A herd of Orange Cars" },
                    { 123, 211, "Fifteen Microscopic Houses" },
                    { 124, 88, "A herd of Transparent Cars" },
                    { 125, 134, "An army of Transparent Planets" },
                    { 126, 248, "A herd of Microscopic Planets" },
                    { 127, 195, "Two Purple Buildings" },
                    { 128, 54, "Two Orange Buildings" },
                    { 129, 10, "Two Green Buildings" },
                    { 130, 35, "Several Purple Leopards" },
                    { 131, 244, "An army of Purple Planets" },
                    { 132, 166, "A bunch of Transparent Leopards" },
                    { 133, 119, "A herd of Rose Smelling Houses" },
                    { 134, 202, "The Large Flowers" },
                    { 135, 148, "A herd of Large Leopards" },
                    { 136, 193, "A herd of Bitter Leopards" },
                    { 137, 118, "The Bitter Houses" },
                    { 138, 18, "An army of Microscopic Houses" },
                    { 139, 28, "The Transparent Planets" },
                    { 140, 14, "A bunch of Microscopic Flowers" },
                    { 141, 198, "Fifteen Large Buildings" },
                    { 142, 179, "A bunch of Orange Leopards" },
                    { 143, 48, "Two Purple Houses" },
                    { 144, 111, "The Orange Leopards" },
                    { 145, 247, "A herd of Microscopic Buildings" },
                    { 146, 88, "Two Green Planets" },
                    { 147, 206, "Fifteen Green Leopards" },
                    { 148, 169, "A bunch of Green Cars" },
                    { 149, 71, "An army of Rose Smelling Buildings" },
                    { 150, 104, "A herd of Microscopic Buildings" },
                    { 151, 156, "A bunch of Rose Smelling Buildings" },
                    { 152, 103, "The Transparent Cars" },
                    { 153, 214, "Fifteen Bitter Flowers" },
                    { 154, 105, "The Orange Planets" },
                    { 155, 85, "The Rose Smelling Planets" },
                    { 156, 174, "The Rose Smelling Leopards" },
                    { 157, 88, "Fifteen Large Cars" },
                    { 158, 112, "A herd of Green Flowers" },
                    { 159, 130, "Two Orange Leopards" },
                    { 160, 134, "Fifteen Purple Buildings" },
                    { 161, 209, "The Microscopic Cars" },
                    { 162, 244, "A herd of Purple Flowers" },
                    { 163, 162, "Several Transparent Buildings" },
                    { 164, 18, "A bunch of Microscopic Buildings" },
                    { 165, 154, "Two Bitter Buildings" },
                    { 166, 245, "Fifteen Bitter Houses" },
                    { 167, 217, "Fifteen Orange Planets" },
                    { 168, 3, "Fifteen Transparent Planets" },
                    { 169, 36, "A bunch of Microscopic Houses" },
                    { 170, 238, "A bunch of Rose Smelling Houses" },
                    { 171, 242, "The Purple Buildings" },
                    { 172, 9, "A bunch of Bitter Cars" },
                    { 173, 46, "A herd of Purple Planets" },
                    { 174, 186, "Fifteen Orange Buildings" },
                    { 175, 72, "An army of Purple Houses" },
                    { 176, 243, "A herd of Green Planets" },
                    { 177, 185, "An army of Orange Houses" },
                    { 178, 191, "Fifteen Purple Flowers" },
                    { 179, 34, "An army of Microscopic Houses" },
                    { 180, 232, "A bunch of Microscopic Houses" },
                    { 181, 36, "A herd of Orange Planets" },
                    { 182, 84, "Fifteen Green Buildings" },
                    { 183, 128, "Fifteen Purple Houses" },
                    { 184, 197, "Two Purple Planets" },
                    { 185, 128, "An army of Green Leopards" },
                    { 186, 118, "Fifteen Large Flowers" },
                    { 187, 54, "A bunch of Rose Smelling Cars" },
                    { 188, 4, "Two Large Flowers" },
                    { 189, 220, "The Bitter Flowers" },
                    { 190, 245, "Two Green Leopards" },
                    { 191, 221, "An army of Microscopic Cars" },
                    { 192, 12, "An army of Green Buildings" },
                    { 193, 4, "Fifteen Microscopic Buildings" },
                    { 194, 25, "Two Green Buildings" },
                    { 195, 50, "The Purple Leopards" },
                    { 196, 206, "Fifteen Rose Smelling Houses" },
                    { 197, 11, "An army of Green Houses" },
                    { 198, 200, "A bunch of Green Buildings" },
                    { 199, 218, "A bunch of Rose Smelling Flowers" },
                    { 200, 195, "A bunch of Bitter Buildings" },
                    { 201, 61, "The Rose Smelling Buildings" },
                    { 202, 101, "Fifteen Microscopic Planets" },
                    { 203, 218, "A herd of Purple Leopards" },
                    { 204, 64, "Several Orange Planets" },
                    { 205, 9, "Fifteen Bitter Leopards" },
                    { 206, 144, "An army of Green Cars" },
                    { 207, 81, "The Bitter Leopards" },
                    { 208, 80, "Several Transparent Cars" },
                    { 209, 152, "Two Purple Leopards" },
                    { 210, 158, "The Purple Flowers" },
                    { 211, 226, "A bunch of Green Leopards" },
                    { 212, 15, "A herd of Purple Cars" },
                    { 213, 242, "An army of Large Houses" },
                    { 214, 180, "An army of Purple Flowers" },
                    { 215, 42, "A bunch of Purple Planets" },
                    { 216, 229, "An army of Bitter Houses" },
                    { 217, 241, "The Rose Smelling Houses" },
                    { 218, 226, "Fifteen Microscopic Planets" },
                    { 219, 104, "The Green Planets" },
                    { 220, 79, "A bunch of Orange Leopards" },
                    { 221, 174, "Fifteen Transparent Buildings" },
                    { 222, 122, "The Green Buildings" },
                    { 223, 117, "Several Purple Planets" },
                    { 224, 51, "Several Orange Leopards" },
                    { 225, 247, "Fifteen Large Cars" },
                    { 226, 172, "A herd of Green Flowers" },
                    { 227, 186, "A herd of Large Planets" },
                    { 228, 62, "Fifteen Purple Buildings" },
                    { 229, 117, "A herd of Large Leopards" },
                    { 230, 83, "Two Transparent Cars" },
                    { 231, 172, "Fifteen Bitter Houses" },
                    { 232, 98, "A bunch of Green Buildings" },
                    { 233, 166, "A bunch of Purple Buildings" },
                    { 234, 89, "Several Transparent Houses" },
                    { 235, 108, "A bunch of Rose Smelling Cars" },
                    { 236, 152, "A herd of Microscopic Cars" },
                    { 237, 171, "Two Bitter Leopards" },
                    { 238, 232, "Several Rose Smelling Houses" },
                    { 239, 222, "Two Orange Houses" },
                    { 240, 75, "The Orange Flowers" },
                    { 241, 86, "A bunch of Rose Smelling Flowers" },
                    { 242, 145, "An army of Bitter Planets" },
                    { 243, 38, "Two Orange Leopards" },
                    { 244, 164, "Two Transparent Buildings" },
                    { 245, 99, "Fifteen Purple Flowers" },
                    { 246, 176, "Fifteen Purple Cars" },
                    { 247, 76, "Several Rose Smelling Houses" },
                    { 248, 46, "The Orange Planets" },
                    { 249, 178, "A herd of Large Houses" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Books_AuthorId",
                table: "Books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Books");

            migrationBuilder.DropTable(
                name: "Authors");
        }
    }
}
