using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    firstname = table.Column<string>(type: "text", nullable: false),
                    lastname = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "Books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Books", x => x.id);
                    table.ForeignKey(
                        name: "FK_Books_Authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "Authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Authors",
                columns: new[] { "id", "email", "firstname", "lastname" },
                values: new object[,]
                {
                    { 1, "kate.obama@google.com", "Kate", "Obama" },
                    { 2, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 3, "donald.jagger@gov.us", "Donald", "Jagger" },
                    { 4, "kate.winslet@tesla.com", "Kate", "Winslet" },
                    { 5, "donald.hepburn@bbc.co.uk", "Donald", "Hepburn" },
                    { 6, "oprah.jagger@tesla.com", "Oprah", "Jagger" },
                    { 7, "oprah.windsor@bbc.co.uk", "Oprah", "Windsor" },
                    { 8, "kate.trump@gov.gr", "Kate", "Trump" },
                    { 9, "barack.jagger@google.com", "Barack", "Jagger" },
                    { 10, "jimi.hendrix@gov.gr", "Jimi", "Hendrix" },
                    { 11, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 12, "donald.obama@gov.ru", "Donald", "Obama" },
                    { 13, "audrey.winslet@gov.us", "Audrey", "Winslet" },
                    { 14, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 15, "audrey.presley@google.com", "Audrey", "Presley" },
                    { 16, "audrey.presley@bbc.co.uk", "Audrey", "Presley" },
                    { 17, "audrey.jagger@gov.nl", "Audrey", "Jagger" },
                    { 18, "oprah.winslet@theworld.ca", "Oprah", "Winslet" },
                    { 19, "charles.presley@theworld.ca", "Charles", "Presley" },
                    { 20, "kate.trump@gov.us", "Kate", "Trump" },
                    { 21, "jimi.presley@google.com", "Jimi", "Presley" },
                    { 22, "charles.winslet@something.com", "Charles", "Winslet" },
                    { 23, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 24, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 25, "mick.presley@something.com", "Mick", "Presley" },
                    { 26, "oprah.trump@nasa.org.us", "Oprah", "Trump" },
                    { 27, "kate.hepburn@nasa.org.us", "Kate", "Hepburn" },
                    { 28, "donald.hendrix@gov.ru", "Donald", "Hendrix" },
                    { 29, "kate.hepburn@gov.nl", "Kate", "Hepburn" },
                    { 30, "audrey.winslet@gov.gr", "Audrey", "Winslet" },
                    { 31, "barack.hendrix@gov.gr", "Barack", "Hendrix" },
                    { 32, "audrey.middleton@google.com", "Audrey", "Middleton" },
                    { 33, "barack.hendrix@bbc.co.uk", "Barack", "Hendrix" },
                    { 34, "donald.trump@tesla.com", "Donald", "Trump" },
                    { 35, "oprah.winslet@gov.ru", "Oprah", "Winslet" },
                    { 36, "barack.winslet@gov.nl", "Barack", "Winslet" },
                    { 37, "barack.hendrix@gov.gr", "Barack", "Hendrix" },
                    { 38, "oprah.hepburn@tesla.com", "Oprah", "Hepburn" },
                    { 39, "audrey.presley@theworld.ca", "Audrey", "Presley" },
                    { 40, "kate.presley@gov.us", "Kate", "Presley" },
                    { 41, "mick.hendrix@theworld.ca", "Mick", "Hendrix" },
                    { 42, "elvis.obama@gov.nl", "Elvis", "Obama" },
                    { 43, "jimi.presley@gov.ru", "Jimi", "Presley" },
                    { 44, "charles.jagger@theworld.ca", "Charles", "Jagger" },
                    { 45, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 46, "jimi.winfrey@gov.us", "Jimi", "Winfrey" },
                    { 47, "elvis.presley@tesla.com", "Elvis", "Presley" },
                    { 48, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 49, "barack.hendrix@theworld.ca", "Barack", "Hendrix" },
                    { 50, "jimi.hendrix@tesla.com", "Jimi", "Hendrix" },
                    { 51, "mick.winslet@gov.nl", "Mick", "Winslet" },
                    { 52, "oprah.trump@gov.gr", "Oprah", "Trump" },
                    { 53, "oprah.jagger@tesla.com", "Oprah", "Jagger" },
                    { 54, "audrey.middleton@gov.gr", "Audrey", "Middleton" },
                    { 55, "audrey.hendrix@google.com", "Audrey", "Hendrix" },
                    { 56, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 57, "barack.winfrey@something.com", "Barack", "Winfrey" },
                    { 58, "donald.obama@gov.us", "Donald", "Obama" },
                    { 59, "jimi.jagger@gov.nl", "Jimi", "Jagger" },
                    { 60, "barack.presley@bbc.co.uk", "Barack", "Presley" },
                    { 61, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 62, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 63, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 64, "charles.winfrey@nasa.org.us", "Charles", "Winfrey" },
                    { 65, "donald.trump@something.com", "Donald", "Trump" },
                    { 66, "barack.hepburn@gov.us", "Barack", "Hepburn" },
                    { 67, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 68, "kate.trump@gov.us", "Kate", "Trump" },
                    { 69, "oprah.jagger@nasa.org.us", "Oprah", "Jagger" },
                    { 70, "kate.hepburn@bbc.co.uk", "Kate", "Hepburn" },
                    { 71, "elvis.presley@nasa.org.us", "Elvis", "Presley" },
                    { 72, "oprah.hepburn@gov.us", "Oprah", "Hepburn" },
                    { 73, "kate.winslet@gov.us", "Kate", "Winslet" },
                    { 74, "barack.jagger@google.com", "Barack", "Jagger" },
                    { 75, "jimi.obama@nasa.org.us", "Jimi", "Obama" },
                    { 76, "barack.winslet@tesla.com", "Barack", "Winslet" },
                    { 77, "oprah.trump@bbc.co.uk", "Oprah", "Trump" },
                    { 78, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 79, "donald.winslet@gov.us", "Donald", "Winslet" },
                    { 80, "barack.trump@theworld.ca", "Barack", "Trump" },
                    { 81, "jimi.windsor@gov.nl", "Jimi", "Windsor" },
                    { 82, "jimi.jagger@gov.gr", "Jimi", "Jagger" },
                    { 83, "kate.middleton@nasa.org.us", "Kate", "Middleton" },
                    { 84, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 85, "mick.trump@google.com", "Mick", "Trump" },
                    { 86, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 87, "elvis.windsor@gov.ru", "Elvis", "Windsor" },
                    { 88, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 89, "charles.middleton@gov.us", "Charles", "Middleton" },
                    { 90, "barack.presley@something.com", "Barack", "Presley" },
                    { 91, "audrey.jagger@tesla.com", "Audrey", "Jagger" },
                    { 92, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 93, "audrey.trump@gov.nl", "Audrey", "Trump" },
                    { 94, "kate.presley@gov.nl", "Kate", "Presley" },
                    { 95, "elvis.middleton@something.com", "Elvis", "Middleton" },
                    { 96, "oprah.windsor@google.com", "Oprah", "Windsor" },
                    { 97, "jimi.winslet@bbc.co.uk", "Jimi", "Winslet" },
                    { 98, "kate.middleton@google.com", "Kate", "Middleton" },
                    { 99, "audrey.obama@gov.gr", "Audrey", "Obama" },
                    { 100, "audrey.presley@theworld.ca", "Audrey", "Presley" },
                    { 101, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 102, "oprah.hepburn@nasa.org.us", "Oprah", "Hepburn" },
                    { 103, "barack.winslet@something.com", "Barack", "Winslet" },
                    { 104, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 105, "kate.hendrix@gov.nl", "Kate", "Hendrix" },
                    { 106, "jimi.presley@theworld.ca", "Jimi", "Presley" },
                    { 107, "mick.trump@gov.nl", "Mick", "Trump" },
                    { 108, "kate.winslet@something.com", "Kate", "Winslet" },
                    { 109, "oprah.winslet@theworld.ca", "Oprah", "Winslet" },
                    { 110, "charles.winfrey@theworld.ca", "Charles", "Winfrey" },
                    { 111, "elvis.obama@gov.ru", "Elvis", "Obama" },
                    { 112, "kate.winfrey@gov.ru", "Kate", "Winfrey" },
                    { 113, "barack.jagger@gov.nl", "Barack", "Jagger" },
                    { 114, "audrey.jagger@tesla.com", "Audrey", "Jagger" },
                    { 115, "kate.hepburn@google.com", "Kate", "Hepburn" },
                    { 116, "kate.jagger@gov.nl", "Kate", "Jagger" },
                    { 117, "charles.hepburn@gov.nl", "Charles", "Hepburn" },
                    { 118, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 119, "audrey.jagger@something.com", "Audrey", "Jagger" },
                    { 120, "jimi.hendrix@google.com", "Jimi", "Hendrix" },
                    { 121, "barack.obama@gov.nl", "Barack", "Obama" },
                    { 122, "kate.trump@gov.us", "Kate", "Trump" },
                    { 123, "mick.obama@something.com", "Mick", "Obama" },
                    { 124, "oprah.winfrey@bbc.co.uk", "Oprah", "Winfrey" },
                    { 125, "jimi.winslet@nasa.org.us", "Jimi", "Winslet" },
                    { 126, "audrey.middleton@bbc.co.uk", "Audrey", "Middleton" },
                    { 127, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 128, "kate.winfrey@something.com", "Kate", "Winfrey" },
                    { 129, "donald.jagger@tesla.com", "Donald", "Jagger" },
                    { 130, "audrey.obama@google.com", "Audrey", "Obama" },
                    { 131, "donald.hepburn@bbc.co.uk", "Donald", "Hepburn" },
                    { 132, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 133, "barack.presley@bbc.co.uk", "Barack", "Presley" },
                    { 134, "elvis.hendrix@gov.us", "Elvis", "Hendrix" },
                    { 135, "donald.middleton@nasa.org.us", "Donald", "Middleton" },
                    { 136, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 137, "kate.hendrix@google.com", "Kate", "Hendrix" },
                    { 138, "donald.obama@bbc.co.uk", "Donald", "Obama" },
                    { 139, "donald.hepburn@bbc.co.uk", "Donald", "Hepburn" },
                    { 140, "charles.obama@tesla.com", "Charles", "Obama" },
                    { 141, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 142, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 143, "mick.winfrey@theworld.ca", "Mick", "Winfrey" },
                    { 144, "oprah.winslet@theworld.ca", "Oprah", "Winslet" },
                    { 145, "elvis.presley@google.com", "Elvis", "Presley" },
                    { 146, "barack.presley@gov.us", "Barack", "Presley" },
                    { 147, "charles.trump@gov.ru", "Charles", "Trump" },
                    { 148, "jimi.winfrey@google.com", "Jimi", "Winfrey" },
                    { 149, "jimi.jagger@something.com", "Jimi", "Jagger" },
                    { 150, "audrey.trump@gov.gr", "Audrey", "Trump" },
                    { 151, "mick.winfrey@something.com", "Mick", "Winfrey" },
                    { 152, "barack.windsor@gov.gr", "Barack", "Windsor" },
                    { 153, "charles.presley@gov.ru", "Charles", "Presley" },
                    { 154, "oprah.winfrey@gov.us", "Oprah", "Winfrey" },
                    { 155, "mick.winfrey@bbc.co.uk", "Mick", "Winfrey" },
                    { 156, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 157, "charles.hendrix@gov.gr", "Charles", "Hendrix" },
                    { 158, "kate.presley@theworld.ca", "Kate", "Presley" },
                    { 159, "oprah.winfrey@something.com", "Oprah", "Winfrey" },
                    { 160, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 161, "mick.jagger@gov.ru", "Mick", "Jagger" },
                    { 162, "charles.winslet@gov.gr", "Charles", "Winslet" },
                    { 163, "barack.hendrix@tesla.com", "Barack", "Hendrix" },
                    { 164, "jimi.jagger@something.com", "Jimi", "Jagger" },
                    { 165, "donald.windsor@nasa.org.us", "Donald", "Windsor" },
                    { 166, "charles.middleton@tesla.com", "Charles", "Middleton" },
                    { 167, "elvis.middleton@gov.ru", "Elvis", "Middleton" },
                    { 168, "elvis.winfrey@gov.gr", "Elvis", "Winfrey" },
                    { 169, "jimi.hepburn@bbc.co.uk", "Jimi", "Hepburn" },
                    { 170, "audrey.hendrix@gov.gr", "Audrey", "Hendrix" },
                    { 171, "elvis.presley@gov.nl", "Elvis", "Presley" },
                    { 172, "mick.winfrey@gov.us", "Mick", "Winfrey" },
                    { 173, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 174, "audrey.windsor@tesla.com", "Audrey", "Windsor" },
                    { 175, "barack.windsor@google.com", "Barack", "Windsor" },
                    { 176, "elvis.trump@google.com", "Elvis", "Trump" },
                    { 177, "elvis.obama@bbc.co.uk", "Elvis", "Obama" },
                    { 178, "mick.windsor@gov.ru", "Mick", "Windsor" },
                    { 179, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 180, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 181, "donald.trump@gov.nl", "Donald", "Trump" },
                    { 182, "elvis.presley@gov.ru", "Elvis", "Presley" },
                    { 183, "charles.winfrey@gov.us", "Charles", "Winfrey" },
                    { 184, "donald.hepburn@gov.gr", "Donald", "Hepburn" },
                    { 185, "audrey.presley@nasa.org.us", "Audrey", "Presley" },
                    { 186, "charles.hepburn@bbc.co.uk", "Charles", "Hepburn" },
                    { 187, "jimi.obama@theworld.ca", "Jimi", "Obama" },
                    { 188, "kate.hendrix@tesla.com", "Kate", "Hendrix" },
                    { 189, "jimi.hendrix@something.com", "Jimi", "Hendrix" },
                    { 190, "oprah.presley@something.com", "Oprah", "Presley" },
                    { 191, "oprah.middleton@gov.nl", "Oprah", "Middleton" },
                    { 192, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 193, "barack.winslet@gov.gr", "Barack", "Winslet" },
                    { 194, "kate.obama@something.com", "Kate", "Obama" },
                    { 195, "charles.winfrey@tesla.com", "Charles", "Winfrey" },
                    { 196, "barack.middleton@nasa.org.us", "Barack", "Middleton" },
                    { 197, "audrey.winslet@something.com", "Audrey", "Winslet" },
                    { 198, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 199, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 200, "elvis.windsor@bbc.co.uk", "Elvis", "Windsor" },
                    { 201, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 202, "oprah.trump@google.com", "Oprah", "Trump" },
                    { 203, "barack.obama@gov.gr", "Barack", "Obama" },
                    { 204, "charles.middleton@theworld.ca", "Charles", "Middleton" },
                    { 205, "kate.winslet@gov.us", "Kate", "Winslet" },
                    { 206, "barack.winfrey@gov.us", "Barack", "Winfrey" },
                    { 207, "oprah.winslet@nasa.org.us", "Oprah", "Winslet" },
                    { 208, "audrey.hepburn@gov.ru", "Audrey", "Hepburn" },
                    { 209, "donald.jagger@google.com", "Donald", "Jagger" },
                    { 210, "audrey.middleton@nasa.org.us", "Audrey", "Middleton" },
                    { 211, "barack.windsor@tesla.com", "Barack", "Windsor" },
                    { 212, "audrey.winslet@google.com", "Audrey", "Winslet" },
                    { 213, "barack.hendrix@gov.ru", "Barack", "Hendrix" },
                    { 214, "kate.obama@something.com", "Kate", "Obama" },
                    { 215, "barack.trump@bbc.co.uk", "Barack", "Trump" },
                    { 216, "kate.presley@something.com", "Kate", "Presley" },
                    { 217, "mick.hepburn@nasa.org.us", "Mick", "Hepburn" },
                    { 218, "mick.obama@theworld.ca", "Mick", "Obama" },
                    { 219, "donald.hepburn@gov.nl", "Donald", "Hepburn" },
                    { 220, "audrey.winfrey@theworld.ca", "Audrey", "Winfrey" },
                    { 221, "elvis.middleton@gov.gr", "Elvis", "Middleton" },
                    { 222, "mick.trump@google.com", "Mick", "Trump" },
                    { 223, "mick.hepburn@theworld.ca", "Mick", "Hepburn" },
                    { 224, "kate.winfrey@nasa.org.us", "Kate", "Winfrey" },
                    { 225, "oprah.winslet@gov.gr", "Oprah", "Winslet" },
                    { 226, "charles.winfrey@gov.ru", "Charles", "Winfrey" },
                    { 227, "charles.presley@theworld.ca", "Charles", "Presley" },
                    { 228, "charles.winfrey@tesla.com", "Charles", "Winfrey" },
                    { 229, "elvis.obama@gov.gr", "Elvis", "Obama" },
                    { 230, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 231, "jimi.trump@nasa.org.us", "Jimi", "Trump" },
                    { 232, "barack.winslet@gov.ru", "Barack", "Winslet" },
                    { 233, "donald.hendrix@tesla.com", "Donald", "Hendrix" },
                    { 234, "elvis.winfrey@gov.ru", "Elvis", "Winfrey" },
                    { 235, "oprah.presley@tesla.com", "Oprah", "Presley" },
                    { 236, "charles.windsor@theworld.ca", "Charles", "Windsor" },
                    { 237, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 238, "kate.middleton@google.com", "Kate", "Middleton" },
                    { 239, "charles.winslet@bbc.co.uk", "Charles", "Winslet" },
                    { 240, "donald.jagger@nasa.org.us", "Donald", "Jagger" },
                    { 241, "barack.hepburn@gov.nl", "Barack", "Hepburn" },
                    { 242, "oprah.hepburn@bbc.co.uk", "Oprah", "Hepburn" },
                    { 243, "donald.winfrey@gov.nl", "Donald", "Winfrey" },
                    { 244, "elvis.hendrix@google.com", "Elvis", "Hendrix" },
                    { 245, "jimi.windsor@theworld.ca", "Jimi", "Windsor" },
                    { 246, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 247, "oprah.windsor@gov.gr", "Oprah", "Windsor" },
                    { 248, "barack.windsor@something.com", "Barack", "Windsor" },
                    { 249, "oprah.jagger@gov.ru", "Oprah", "Jagger" }
                });

            migrationBuilder.InsertData(
                table: "Books",
                columns: new[] { "id", "AuthorId", "title" },
                values: new object[,]
                {
                    { 1, 106, "An army of Bitter Cars" },
                    { 2, 177, "A herd of Transparent Cars" },
                    { 3, 105, "A herd of Transparent Planets" },
                    { 4, 113, "A bunch of Rose Smelling Leopards" },
                    { 5, 204, "A herd of Rose Smelling Cars" },
                    { 6, 48, "Fifteen Transparent Cars" },
                    { 7, 20, "A herd of Large Flowers" },
                    { 8, 156, "Two Microscopic Buildings" },
                    { 9, 213, "An army of Rose Smelling Buildings" },
                    { 10, 198, "Two Rose Smelling Leopards" },
                    { 11, 232, "A bunch of Purple Flowers" },
                    { 12, 105, "A bunch of Rose Smelling Planets" },
                    { 13, 10, "The Purple Flowers" },
                    { 14, 141, "Fifteen Purple Houses" },
                    { 15, 71, "A herd of Rose Smelling Leopards" },
                    { 16, 76, "The Green Houses" },
                    { 17, 229, "Two Green Planets" },
                    { 18, 71, "A herd of Purple Leopards" },
                    { 19, 247, "A herd of Transparent Cars" },
                    { 20, 166, "A bunch of Large Leopards" },
                    { 21, 41, "Several Rose Smelling Houses" },
                    { 22, 162, "Two Large Flowers" },
                    { 23, 1, "Two Rose Smelling Houses" },
                    { 24, 34, "A herd of Bitter Planets" },
                    { 25, 63, "The Bitter Leopards" },
                    { 26, 75, "Several Rose Smelling Houses" },
                    { 27, 167, "The Rose Smelling Flowers" },
                    { 28, 95, "A bunch of Transparent Planets" },
                    { 29, 136, "A bunch of Rose Smelling Buildings" },
                    { 30, 199, "Two Large Flowers" },
                    { 31, 132, "The Rose Smelling Houses" },
                    { 32, 67, "The Rose Smelling Buildings" },
                    { 33, 196, "A bunch of Microscopic Buildings" },
                    { 34, 24, "An army of Microscopic Houses" },
                    { 35, 54, "Two Transparent Buildings" },
                    { 36, 91, "Fifteen Purple Buildings" },
                    { 37, 48, "A herd of Green Flowers" },
                    { 38, 101, "An army of Orange Buildings" },
                    { 39, 131, "Fifteen Large Buildings" },
                    { 40, 195, "Fifteen Bitter Leopards" },
                    { 41, 176, "Two Transparent Flowers" },
                    { 42, 168, "A bunch of Orange Cars" },
                    { 43, 52, "Two Large Buildings" },
                    { 44, 99, "Several Bitter Houses" },
                    { 45, 7, "The Bitter Leopards" },
                    { 46, 5, "Several Purple Houses" },
                    { 47, 72, "Several Bitter Flowers" },
                    { 48, 9, "The Microscopic Buildings" },
                    { 49, 10, "Two Bitter Houses" },
                    { 50, 142, "An army of Large Leopards" },
                    { 51, 66, "The Orange Flowers" },
                    { 52, 143, "A bunch of Large Buildings" },
                    { 53, 86, "Several Purple Cars" },
                    { 54, 185, "A herd of Bitter Flowers" },
                    { 55, 30, "A herd of Microscopic Planets" },
                    { 56, 67, "A bunch of Purple Flowers" },
                    { 57, 93, "A bunch of Rose Smelling Flowers" },
                    { 58, 80, "Several Transparent Cars" },
                    { 59, 79, "An army of Purple Leopards" },
                    { 60, 216, "Two Purple Flowers" },
                    { 61, 141, "Several Large Buildings" },
                    { 62, 42, "Fifteen Rose Smelling Cars" },
                    { 63, 180, "Fifteen Purple Cars" },
                    { 64, 25, "An army of Rose Smelling Planets" },
                    { 65, 175, "A bunch of Purple Buildings" },
                    { 66, 7, "Two Bitter Houses" },
                    { 67, 159, "Two Microscopic Cars" },
                    { 68, 219, "A herd of Large Flowers" },
                    { 69, 227, "A bunch of Orange Leopards" },
                    { 70, 186, "Several Green Houses" },
                    { 71, 91, "Fifteen Purple Cars" },
                    { 72, 18, "An army of Green Cars" },
                    { 73, 87, "The Green Leopards" },
                    { 74, 180, "An army of Purple Houses" },
                    { 75, 41, "Several Bitter Cars" },
                    { 76, 239, "Two Large Houses" },
                    { 77, 207, "A herd of Green Buildings" },
                    { 78, 136, "A bunch of Orange Buildings" },
                    { 79, 17, "An army of Rose Smelling Flowers" },
                    { 80, 30, "Fifteen Orange Houses" },
                    { 81, 185, "The Transparent Planets" },
                    { 82, 176, "A bunch of Green Leopards" },
                    { 83, 6, "The Rose Smelling Planets" },
                    { 84, 159, "An army of Orange Houses" },
                    { 85, 189, "A herd of Green Cars" },
                    { 86, 132, "The Bitter Houses" },
                    { 87, 249, "Two Microscopic Planets" },
                    { 88, 199, "A herd of Green Houses" },
                    { 89, 83, "A bunch of Transparent Houses" },
                    { 90, 56, "A bunch of Green Buildings" },
                    { 91, 174, "Several Green Buildings" },
                    { 92, 239, "Several Transparent Leopards" },
                    { 93, 136, "Fifteen Bitter Leopards" },
                    { 94, 94, "An army of Green Leopards" },
                    { 95, 163, "Several Microscopic Buildings" },
                    { 96, 115, "Fifteen Rose Smelling Houses" },
                    { 97, 122, "A herd of Transparent Buildings" },
                    { 98, 190, "Several Large Cars" },
                    { 99, 203, "Fifteen Bitter Cars" },
                    { 100, 56, "A herd of Microscopic Leopards" },
                    { 101, 231, "A bunch of Rose Smelling Flowers" },
                    { 102, 210, "Several Purple Leopards" },
                    { 103, 229, "Fifteen Large Houses" },
                    { 104, 9, "Several Purple Planets" },
                    { 105, 55, "A bunch of Transparent Planets" },
                    { 106, 41, "A herd of Rose Smelling Flowers" },
                    { 107, 75, "Fifteen Orange Planets" },
                    { 108, 39, "Several Orange Houses" },
                    { 109, 237, "Two Microscopic Flowers" },
                    { 110, 11, "A herd of Green Buildings" },
                    { 111, 164, "A herd of Orange Cars" },
                    { 112, 150, "An army of Bitter Flowers" },
                    { 113, 107, "Two Microscopic Planets" },
                    { 114, 20, "An army of Green Leopards" },
                    { 115, 26, "An army of Bitter Houses" },
                    { 116, 72, "An army of Large Cars" },
                    { 117, 213, "A herd of Green Leopards" },
                    { 118, 182, "A herd of Transparent Cars" },
                    { 119, 215, "Fifteen Purple Planets" },
                    { 120, 123, "A bunch of Large Leopards" },
                    { 121, 107, "A bunch of Green Leopards" },
                    { 122, 71, "Two Rose Smelling Leopards" },
                    { 123, 137, "Two Rose Smelling Cars" },
                    { 124, 18, "A herd of Purple Buildings" },
                    { 125, 220, "The Rose Smelling Cars" },
                    { 126, 220, "Fifteen Purple Houses" },
                    { 127, 159, "Fifteen Microscopic Leopards" },
                    { 128, 103, "A herd of Orange Planets" },
                    { 129, 193, "A herd of Rose Smelling Buildings" },
                    { 130, 198, "A bunch of Microscopic Cars" },
                    { 131, 141, "A herd of Rose Smelling Houses" },
                    { 132, 242, "Two Orange Houses" },
                    { 133, 199, "The Microscopic Flowers" },
                    { 134, 169, "Several Rose Smelling Houses" },
                    { 135, 16, "A herd of Purple Leopards" },
                    { 136, 178, "Fifteen Purple Leopards" },
                    { 137, 244, "Several Purple Buildings" },
                    { 138, 133, "Several Transparent Buildings" },
                    { 139, 2, "The Bitter Houses" },
                    { 140, 176, "Several Large Flowers" },
                    { 141, 116, "Several Purple Flowers" },
                    { 142, 223, "The Microscopic Planets" },
                    { 143, 194, "A herd of Purple Flowers" },
                    { 144, 128, "A bunch of Microscopic Planets" },
                    { 145, 81, "The Bitter Houses" },
                    { 146, 232, "A bunch of Transparent Flowers" },
                    { 147, 43, "A bunch of Orange Leopards" },
                    { 148, 80, "Two Bitter Planets" },
                    { 149, 151, "Two Microscopic Buildings" },
                    { 150, 218, "A herd of Transparent Houses" },
                    { 151, 176, "An army of Orange Buildings" },
                    { 152, 11, "Several Microscopic Cars" },
                    { 153, 139, "Two Large Houses" },
                    { 154, 92, "A bunch of Rose Smelling Cars" },
                    { 155, 99, "The Large Flowers" },
                    { 156, 92, "A bunch of Transparent Flowers" },
                    { 157, 229, "A bunch of Purple Planets" },
                    { 158, 124, "Several Microscopic Cars" },
                    { 159, 155, "Fifteen Green Flowers" },
                    { 160, 54, "The Purple Houses" },
                    { 161, 123, "A herd of Green Flowers" },
                    { 162, 88, "An army of Transparent Houses" },
                    { 163, 159, "A bunch of Transparent Cars" },
                    { 164, 200, "Fifteen Orange Leopards" },
                    { 165, 40, "Fifteen Rose Smelling Leopards" },
                    { 166, 20, "Two Purple Leopards" },
                    { 167, 205, "The Transparent Houses" },
                    { 168, 156, "An army of Orange Flowers" },
                    { 169, 243, "Fifteen Green Cars" },
                    { 170, 183, "An army of Green Planets" },
                    { 171, 164, "A bunch of Green Planets" },
                    { 172, 154, "An army of Purple Cars" },
                    { 173, 50, "A bunch of Rose Smelling Houses" },
                    { 174, 60, "The Purple Houses" },
                    { 175, 174, "A herd of Microscopic Planets" },
                    { 176, 131, "An army of Bitter Buildings" },
                    { 177, 148, "An army of Large Planets" },
                    { 178, 119, "An army of Transparent Buildings" },
                    { 179, 214, "An army of Rose Smelling Planets" },
                    { 180, 68, "The Rose Smelling Cars" },
                    { 181, 90, "The Bitter Flowers" },
                    { 182, 168, "Several Green Flowers" },
                    { 183, 29, "An army of Microscopic Planets" },
                    { 184, 209, "The Microscopic Buildings" },
                    { 185, 31, "A herd of Purple Flowers" },
                    { 186, 183, "Fifteen Purple Houses" },
                    { 187, 30, "An army of Green Planets" },
                    { 188, 184, "The Purple Leopards" },
                    { 189, 34, "An army of Bitter Buildings" },
                    { 190, 236, "The Orange Planets" },
                    { 191, 235, "Several Large Houses" },
                    { 192, 74, "Several Orange Cars" },
                    { 193, 242, "Fifteen Orange Planets" },
                    { 194, 235, "Fifteen Purple Flowers" },
                    { 195, 93, "An army of Green Houses" },
                    { 196, 24, "The Orange Leopards" },
                    { 197, 100, "An army of Rose Smelling Flowers" },
                    { 198, 178, "The Purple Flowers" },
                    { 199, 52, "The Purple Planets" },
                    { 200, 151, "Several Large Planets" },
                    { 201, 168, "The Transparent Buildings" },
                    { 202, 113, "A herd of Large Houses" },
                    { 203, 237, "A bunch of Rose Smelling Flowers" },
                    { 204, 92, "A bunch of Large Planets" },
                    { 205, 147, "Fifteen Rose Smelling Buildings" },
                    { 206, 212, "An army of Large Leopards" },
                    { 207, 37, "An army of Purple Cars" },
                    { 208, 92, "Fifteen Green Cars" },
                    { 209, 99, "Two Bitter Houses" },
                    { 210, 210, "The Green Cars" },
                    { 211, 194, "Fifteen Rose Smelling Flowers" },
                    { 212, 66, "Two Green Buildings" },
                    { 213, 52, "An army of Bitter Leopards" },
                    { 214, 152, "An army of Microscopic Cars" },
                    { 215, 100, "Two Large Houses" },
                    { 216, 153, "An army of Purple Flowers" },
                    { 217, 37, "An army of Bitter Leopards" },
                    { 218, 176, "The Purple Flowers" },
                    { 219, 138, "An army of Purple Buildings" },
                    { 220, 142, "An army of Bitter Planets" },
                    { 221, 44, "An army of Microscopic Planets" },
                    { 222, 178, "A bunch of Rose Smelling Leopards" },
                    { 223, 229, "Several Transparent Leopards" },
                    { 224, 95, "Two Bitter Cars" },
                    { 225, 247, "Fifteen Rose Smelling Cars" },
                    { 226, 66, "Fifteen Bitter Planets" },
                    { 227, 156, "Two Large Planets" },
                    { 228, 247, "A herd of Purple Houses" },
                    { 229, 96, "Several Green Leopards" },
                    { 230, 178, "An army of Transparent Planets" },
                    { 231, 85, "Two Transparent Leopards" },
                    { 232, 102, "Several Green Buildings" },
                    { 233, 203, "A bunch of Large Flowers" },
                    { 234, 14, "Fifteen Purple Flowers" },
                    { 235, 174, "An army of Bitter Leopards" },
                    { 236, 213, "Fifteen Large Planets" },
                    { 237, 84, "A bunch of Green Houses" },
                    { 238, 16, "Several Orange Leopards" },
                    { 239, 26, "Several Large Houses" },
                    { 240, 92, "A herd of Transparent Planets" },
                    { 241, 220, "Two Large Houses" },
                    { 242, 100, "An army of Large Planets" },
                    { 243, 66, "A herd of Transparent Houses" },
                    { 244, 186, "Several Microscopic Flowers" },
                    { 245, 175, "An army of Large Planets" },
                    { 246, 115, "The Transparent Buildings" },
                    { 247, 105, "The Orange Flowers" },
                    { 248, 16, "A herd of Transparent Planets" },
                    { 249, 86, "An army of Rose Smelling Buildings" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Books_AuthorId",
                table: "Books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Books");

            migrationBuilder.DropTable(
                name: "Authors");
        }
    }
}
