using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class John : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    firstname = table.Column<string>(type: "text", nullable: false),
                    lastname = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "authors",
                columns: new[] { "id", "email", "firstname", "lastname" },
                values: new object[,]
                {
                    { 1, "elvis.hepburn@something.com", "Elvis", "Hepburn" },
                    { 2, "kate.middleton@gov.us", "Kate", "Middleton" },
                    { 3, "mick.hendrix@theworld.ca", "Mick", "Hendrix" },
                    { 4, "elvis.jagger@gov.nl", "Elvis", "Jagger" },
                    { 5, "donald.hepburn@gov.ru", "Donald", "Hepburn" },
                    { 6, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 7, "jimi.winslet@bbc.co.uk", "Jimi", "Winslet" },
                    { 8, "kate.windsor@nasa.org.us", "Kate", "Windsor" },
                    { 9, "oprah.hepburn@gov.ru", "Oprah", "Hepburn" },
                    { 10, "audrey.middleton@theworld.ca", "Audrey", "Middleton" },
                    { 11, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 12, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 13, "oprah.trump@gov.us", "Oprah", "Trump" },
                    { 14, "barack.hepburn@nasa.org.us", "Barack", "Hepburn" },
                    { 15, "audrey.winfrey@gov.gr", "Audrey", "Winfrey" },
                    { 16, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 17, "charles.hendrix@google.com", "Charles", "Hendrix" },
                    { 18, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 19, "barack.middleton@gov.gr", "Barack", "Middleton" },
                    { 20, "charles.trump@gov.nl", "Charles", "Trump" },
                    { 21, "audrey.winslet@tesla.com", "Audrey", "Winslet" },
                    { 22, "oprah.hendrix@google.com", "Oprah", "Hendrix" },
                    { 23, "barack.obama@gov.nl", "Barack", "Obama" },
                    { 24, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 25, "donald.trump@tesla.com", "Donald", "Trump" },
                    { 26, "kate.hepburn@something.com", "Kate", "Hepburn" },
                    { 27, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 28, "donald.hendrix@gov.nl", "Donald", "Hendrix" },
                    { 29, "donald.trump@google.com", "Donald", "Trump" },
                    { 30, "kate.obama@theworld.ca", "Kate", "Obama" },
                    { 31, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 32, "audrey.jagger@theworld.ca", "Audrey", "Jagger" },
                    { 33, "oprah.trump@gov.gr", "Oprah", "Trump" },
                    { 34, "charles.middleton@gov.ru", "Charles", "Middleton" },
                    { 35, "charles.obama@tesla.com", "Charles", "Obama" },
                    { 36, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 37, "barack.presley@google.com", "Barack", "Presley" },
                    { 38, "jimi.winfrey@theworld.ca", "Jimi", "Winfrey" },
                    { 39, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 40, "jimi.middleton@gov.ru", "Jimi", "Middleton" },
                    { 41, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 42, "jimi.hendrix@tesla.com", "Jimi", "Hendrix" },
                    { 43, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 44, "audrey.jagger@bbc.co.uk", "Audrey", "Jagger" },
                    { 45, "donald.hepburn@gov.ru", "Donald", "Hepburn" },
                    { 46, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 47, "charles.hendrix@tesla.com", "Charles", "Hendrix" },
                    { 48, "elvis.obama@something.com", "Elvis", "Obama" },
                    { 49, "mick.middleton@google.com", "Mick", "Middleton" },
                    { 50, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 51, "kate.hendrix@bbc.co.uk", "Kate", "Hendrix" },
                    { 52, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 53, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 54, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 55, "jimi.middleton@gov.gr", "Jimi", "Middleton" },
                    { 56, "audrey.jagger@gov.ru", "Audrey", "Jagger" },
                    { 57, "oprah.middleton@theworld.ca", "Oprah", "Middleton" },
                    { 58, "oprah.obama@gov.us", "Oprah", "Obama" },
                    { 59, "oprah.hepburn@google.com", "Oprah", "Hepburn" },
                    { 60, "audrey.windsor@gov.ru", "Audrey", "Windsor" },
                    { 61, "donald.presley@gov.us", "Donald", "Presley" },
                    { 62, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 63, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 64, "mick.middleton@gov.ru", "Mick", "Middleton" },
                    { 65, "elvis.windsor@theworld.ca", "Elvis", "Windsor" },
                    { 66, "jimi.winfrey@nasa.org.us", "Jimi", "Winfrey" },
                    { 67, "elvis.middleton@google.com", "Elvis", "Middleton" },
                    { 68, "elvis.jagger@gov.ru", "Elvis", "Jagger" },
                    { 69, "charles.hendrix@gov.us", "Charles", "Hendrix" },
                    { 70, "kate.windsor@bbc.co.uk", "Kate", "Windsor" },
                    { 71, "barack.trump@gov.us", "Barack", "Trump" },
                    { 72, "elvis.presley@tesla.com", "Elvis", "Presley" },
                    { 73, "oprah.hendrix@tesla.com", "Oprah", "Hendrix" },
                    { 74, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 75, "oprah.windsor@gov.ru", "Oprah", "Windsor" },
                    { 76, "audrey.middleton@theworld.ca", "Audrey", "Middleton" },
                    { 77, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 78, "elvis.winslet@something.com", "Elvis", "Winslet" },
                    { 79, "donald.winslet@bbc.co.uk", "Donald", "Winslet" },
                    { 80, "mick.winslet@bbc.co.uk", "Mick", "Winslet" },
                    { 81, "audrey.hendrix@google.com", "Audrey", "Hendrix" },
                    { 82, "charles.middleton@nasa.org.us", "Charles", "Middleton" },
                    { 83, "oprah.hepburn@google.com", "Oprah", "Hepburn" },
                    { 84, "oprah.windsor@something.com", "Oprah", "Windsor" },
                    { 85, "elvis.winslet@bbc.co.uk", "Elvis", "Winslet" },
                    { 86, "jimi.trump@google.com", "Jimi", "Trump" },
                    { 87, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 88, "donald.windsor@gov.ru", "Donald", "Windsor" },
                    { 89, "kate.windsor@gov.nl", "Kate", "Windsor" },
                    { 90, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 91, "donald.trump@gov.ru", "Donald", "Trump" },
                    { 92, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 93, "kate.winslet@google.com", "Kate", "Winslet" },
                    { 94, "elvis.winslet@something.com", "Elvis", "Winslet" },
                    { 95, "elvis.jagger@gov.us", "Elvis", "Jagger" },
                    { 96, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 97, "mick.hendrix@theworld.ca", "Mick", "Hendrix" },
                    { 98, "kate.winfrey@theworld.ca", "Kate", "Winfrey" },
                    { 99, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 100, "barack.hepburn@tesla.com", "Barack", "Hepburn" },
                    { 101, "charles.jagger@tesla.com", "Charles", "Jagger" },
                    { 102, "barack.presley@gov.us", "Barack", "Presley" },
                    { 103, "jimi.middleton@tesla.com", "Jimi", "Middleton" },
                    { 104, "donald.winslet@nasa.org.us", "Donald", "Winslet" },
                    { 105, "audrey.jagger@something.com", "Audrey", "Jagger" },
                    { 106, "audrey.trump@gov.gr", "Audrey", "Trump" },
                    { 107, "donald.presley@gov.ru", "Donald", "Presley" },
                    { 108, "donald.hepburn@bbc.co.uk", "Donald", "Hepburn" },
                    { 109, "kate.hepburn@gov.gr", "Kate", "Hepburn" },
                    { 110, "mick.jagger@gov.nl", "Mick", "Jagger" },
                    { 111, "audrey.winslet@gov.nl", "Audrey", "Winslet" },
                    { 112, "charles.jagger@theworld.ca", "Charles", "Jagger" },
                    { 113, "kate.trump@gov.ru", "Kate", "Trump" },
                    { 114, "jimi.middleton@google.com", "Jimi", "Middleton" },
                    { 115, "audrey.windsor@gov.ru", "Audrey", "Windsor" },
                    { 116, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 117, "charles.winslet@theworld.ca", "Charles", "Winslet" },
                    { 118, "jimi.hepburn@gov.us", "Jimi", "Hepburn" },
                    { 119, "donald.hendrix@bbc.co.uk", "Donald", "Hendrix" },
                    { 120, "kate.trump@google.com", "Kate", "Trump" },
                    { 121, "barack.hendrix@google.com", "Barack", "Hendrix" },
                    { 122, "jimi.hepburn@gov.gr", "Jimi", "Hepburn" },
                    { 123, "audrey.obama@something.com", "Audrey", "Obama" },
                    { 124, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 125, "charles.hendrix@theworld.ca", "Charles", "Hendrix" },
                    { 126, "audrey.hepburn@gov.nl", "Audrey", "Hepburn" },
                    { 127, "barack.trump@gov.gr", "Barack", "Trump" },
                    { 128, "jimi.middleton@gov.us", "Jimi", "Middleton" },
                    { 129, "mick.middleton@something.com", "Mick", "Middleton" },
                    { 130, "barack.hepburn@theworld.ca", "Barack", "Hepburn" },
                    { 131, "donald.hepburn@gov.us", "Donald", "Hepburn" },
                    { 132, "barack.obama@something.com", "Barack", "Obama" },
                    { 133, "oprah.winfrey@theworld.ca", "Oprah", "Winfrey" },
                    { 134, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 135, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 136, "jimi.windsor@something.com", "Jimi", "Windsor" },
                    { 137, "mick.obama@gov.us", "Mick", "Obama" },
                    { 138, "oprah.windsor@tesla.com", "Oprah", "Windsor" },
                    { 139, "barack.winfrey@gov.ru", "Barack", "Winfrey" },
                    { 140, "audrey.middleton@tesla.com", "Audrey", "Middleton" },
                    { 141, "mick.jagger@something.com", "Mick", "Jagger" },
                    { 142, "charles.winslet@theworld.ca", "Charles", "Winslet" },
                    { 143, "jimi.winslet@tesla.com", "Jimi", "Winslet" },
                    { 144, "audrey.trump@nasa.org.us", "Audrey", "Trump" },
                    { 145, "elvis.presley@gov.ru", "Elvis", "Presley" },
                    { 146, "audrey.hendrix@gov.us", "Audrey", "Hendrix" },
                    { 147, "mick.winslet@gov.nl", "Mick", "Winslet" },
                    { 148, "barack.hendrix@something.com", "Barack", "Hendrix" },
                    { 149, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 150, "elvis.obama@theworld.ca", "Elvis", "Obama" },
                    { 151, "charles.winfrey@something.com", "Charles", "Winfrey" },
                    { 152, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 153, "oprah.obama@nasa.org.us", "Oprah", "Obama" },
                    { 154, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 155, "oprah.hepburn@something.com", "Oprah", "Hepburn" },
                    { 156, "donald.obama@tesla.com", "Donald", "Obama" },
                    { 157, "donald.winfrey@gov.ru", "Donald", "Winfrey" },
                    { 158, "donald.winfrey@nasa.org.us", "Donald", "Winfrey" },
                    { 159, "elvis.hendrix@bbc.co.uk", "Elvis", "Hendrix" },
                    { 160, "oprah.windsor@tesla.com", "Oprah", "Windsor" },
                    { 161, "oprah.middleton@gov.ru", "Oprah", "Middleton" },
                    { 162, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 163, "audrey.trump@tesla.com", "Audrey", "Trump" },
                    { 164, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 165, "barack.middleton@tesla.com", "Barack", "Middleton" },
                    { 166, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 167, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 168, "mick.trump@nasa.org.us", "Mick", "Trump" },
                    { 169, "audrey.winfrey@gov.us", "Audrey", "Winfrey" },
                    { 170, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 171, "donald.hepburn@nasa.org.us", "Donald", "Hepburn" },
                    { 172, "jimi.windsor@tesla.com", "Jimi", "Windsor" },
                    { 173, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 174, "elvis.jagger@something.com", "Elvis", "Jagger" },
                    { 175, "charles.middleton@gov.nl", "Charles", "Middleton" },
                    { 176, "charles.presley@gov.nl", "Charles", "Presley" },
                    { 177, "audrey.jagger@google.com", "Audrey", "Jagger" },
                    { 178, "kate.middleton@tesla.com", "Kate", "Middleton" },
                    { 179, "donald.obama@gov.gr", "Donald", "Obama" },
                    { 180, "mick.winfrey@nasa.org.us", "Mick", "Winfrey" },
                    { 181, "charles.trump@nasa.org.us", "Charles", "Trump" },
                    { 182, "barack.winfrey@nasa.org.us", "Barack", "Winfrey" },
                    { 183, "elvis.hepburn@tesla.com", "Elvis", "Hepburn" },
                    { 184, "kate.winfrey@gov.us", "Kate", "Winfrey" },
                    { 185, "audrey.windsor@theworld.ca", "Audrey", "Windsor" },
                    { 186, "elvis.obama@google.com", "Elvis", "Obama" },
                    { 187, "barack.hepburn@gov.nl", "Barack", "Hepburn" },
                    { 188, "audrey.presley@gov.ru", "Audrey", "Presley" },
                    { 189, "barack.hendrix@gov.nl", "Barack", "Hendrix" },
                    { 190, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 191, "charles.obama@theworld.ca", "Charles", "Obama" },
                    { 192, "barack.winslet@google.com", "Barack", "Winslet" },
                    { 193, "audrey.trump@gov.us", "Audrey", "Trump" },
                    { 194, "charles.trump@gov.gr", "Charles", "Trump" },
                    { 195, "barack.obama@gov.nl", "Barack", "Obama" },
                    { 196, "donald.obama@tesla.com", "Donald", "Obama" },
                    { 197, "elvis.jagger@gov.gr", "Elvis", "Jagger" },
                    { 198, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 199, "kate.jagger@theworld.ca", "Kate", "Jagger" },
                    { 200, "kate.hepburn@gov.ru", "Kate", "Hepburn" },
                    { 201, "elvis.winfrey@gov.ru", "Elvis", "Winfrey" },
                    { 202, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 203, "mick.windsor@gov.gr", "Mick", "Windsor" },
                    { 204, "donald.middleton@bbc.co.uk", "Donald", "Middleton" },
                    { 205, "donald.hendrix@gov.ru", "Donald", "Hendrix" },
                    { 206, "kate.trump@google.com", "Kate", "Trump" },
                    { 207, "barack.obama@gov.us", "Barack", "Obama" },
                    { 208, "jimi.windsor@gov.nl", "Jimi", "Windsor" },
                    { 209, "barack.obama@gov.ru", "Barack", "Obama" },
                    { 210, "donald.trump@nasa.org.us", "Donald", "Trump" },
                    { 211, "barack.trump@gov.gr", "Barack", "Trump" },
                    { 212, "audrey.winslet@tesla.com", "Audrey", "Winslet" },
                    { 213, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 214, "charles.winslet@gov.us", "Charles", "Winslet" },
                    { 215, "audrey.presley@gov.nl", "Audrey", "Presley" },
                    { 216, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 217, "audrey.hepburn@gov.us", "Audrey", "Hepburn" },
                    { 218, "mick.presley@gov.us", "Mick", "Presley" },
                    { 219, "elvis.obama@bbc.co.uk", "Elvis", "Obama" },
                    { 220, "kate.presley@nasa.org.us", "Kate", "Presley" },
                    { 221, "jimi.hepburn@nasa.org.us", "Jimi", "Hepburn" },
                    { 222, "mick.winslet@theworld.ca", "Mick", "Winslet" },
                    { 223, "jimi.jagger@bbc.co.uk", "Jimi", "Jagger" },
                    { 224, "kate.winslet@gov.ru", "Kate", "Winslet" },
                    { 225, "elvis.presley@bbc.co.uk", "Elvis", "Presley" },
                    { 226, "elvis.windsor@bbc.co.uk", "Elvis", "Windsor" },
                    { 227, "elvis.winfrey@something.com", "Elvis", "Winfrey" },
                    { 228, "donald.presley@gov.ru", "Donald", "Presley" },
                    { 229, "audrey.winfrey@tesla.com", "Audrey", "Winfrey" },
                    { 230, "donald.winslet@something.com", "Donald", "Winslet" },
                    { 231, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 232, "barack.obama@gov.us", "Barack", "Obama" },
                    { 233, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 234, "charles.winfrey@bbc.co.uk", "Charles", "Winfrey" },
                    { 235, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 236, "jimi.hepburn@gov.ru", "Jimi", "Hepburn" },
                    { 237, "audrey.trump@tesla.com", "Audrey", "Trump" },
                    { 238, "oprah.hendrix@tesla.com", "Oprah", "Hendrix" },
                    { 239, "barack.jagger@gov.us", "Barack", "Jagger" },
                    { 240, "elvis.windsor@gov.gr", "Elvis", "Windsor" },
                    { 241, "jimi.jagger@gov.us", "Jimi", "Jagger" },
                    { 242, "mick.jagger@nasa.org.us", "Mick", "Jagger" },
                    { 243, "barack.windsor@gov.ru", "Barack", "Windsor" },
                    { 244, "donald.hendrix@google.com", "Donald", "Hendrix" },
                    { 245, "elvis.trump@bbc.co.uk", "Elvis", "Trump" },
                    { 246, "kate.winslet@theworld.ca", "Kate", "Winslet" },
                    { 247, "jimi.middleton@gov.nl", "Jimi", "Middleton" },
                    { 248, "charles.obama@gov.us", "Charles", "Obama" },
                    { 249, "kate.trump@gov.gr", "Kate", "Trump" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "AuthorId", "title" },
                values: new object[,]
                {
                    { 1, 168, "A bunch of Microscopic Houses" },
                    { 2, 62, "A herd of Microscopic Cars" },
                    { 3, 65, "Fifteen Green Cars" },
                    { 4, 104, "A herd of Purple Leopards" },
                    { 5, 116, "Fifteen Transparent Leopards" },
                    { 6, 108, "Two Purple Flowers" },
                    { 7, 167, "Several Orange Leopards" },
                    { 8, 207, "Several Purple Leopards" },
                    { 9, 109, "A herd of Bitter Planets" },
                    { 10, 89, "Fifteen Microscopic Planets" },
                    { 11, 23, "A herd of Green Flowers" },
                    { 12, 89, "Fifteen Transparent Buildings" },
                    { 13, 9, "A bunch of Large Planets" },
                    { 14, 157, "A bunch of Microscopic Leopards" },
                    { 15, 179, "A herd of Purple Leopards" },
                    { 16, 140, "An army of Green Planets" },
                    { 17, 180, "The Purple Flowers" },
                    { 18, 220, "Several Transparent Cars" },
                    { 19, 126, "Two Transparent Cars" },
                    { 20, 222, "Two Microscopic Houses" },
                    { 21, 26, "A bunch of Microscopic Leopards" },
                    { 22, 17, "Two Large Flowers" },
                    { 23, 71, "An army of Bitter Houses" },
                    { 24, 17, "Several Rose Smelling Leopards" },
                    { 25, 55, "A herd of Orange Buildings" },
                    { 26, 213, "The Orange Planets" },
                    { 27, 148, "A herd of Green Leopards" },
                    { 28, 238, "Several Large Flowers" },
                    { 29, 88, "Several Purple Houses" },
                    { 30, 126, "A bunch of Transparent Houses" },
                    { 31, 112, "Fifteen Transparent Houses" },
                    { 32, 34, "Several Microscopic Buildings" },
                    { 33, 95, "The Rose Smelling Houses" },
                    { 34, 142, "Two Green Cars" },
                    { 35, 154, "An army of Transparent Cars" },
                    { 36, 133, "Fifteen Rose Smelling Leopards" },
                    { 37, 58, "The Microscopic Houses" },
                    { 38, 213, "A bunch of Rose Smelling Leopards" },
                    { 39, 216, "Fifteen Transparent Leopards" },
                    { 40, 69, "Fifteen Purple Buildings" },
                    { 41, 86, "The Purple Cars" },
                    { 42, 192, "Several Orange Flowers" },
                    { 43, 200, "Several Transparent Leopards" },
                    { 44, 232, "A bunch of Transparent Buildings" },
                    { 45, 154, "Several Green Cars" },
                    { 46, 236, "A bunch of Rose Smelling Leopards" },
                    { 47, 84, "A bunch of Rose Smelling Flowers" },
                    { 48, 109, "A bunch of Microscopic Leopards" },
                    { 49, 1, "Two Large Cars" },
                    { 50, 8, "Fifteen Microscopic Leopards" },
                    { 51, 241, "A herd of Orange Houses" },
                    { 52, 213, "The Green Leopards" },
                    { 53, 238, "Several Microscopic Houses" },
                    { 54, 225, "Fifteen Transparent Buildings" },
                    { 55, 20, "An army of Rose Smelling Leopards" },
                    { 56, 40, "A bunch of Green Flowers" },
                    { 57, 159, "Two Orange Cars" },
                    { 58, 128, "Several Large Planets" },
                    { 59, 123, "A bunch of Microscopic Leopards" },
                    { 60, 90, "A bunch of Purple Buildings" },
                    { 61, 79, "A herd of Bitter Buildings" },
                    { 62, 241, "An army of Purple Planets" },
                    { 63, 98, "Fifteen Orange Planets" },
                    { 64, 54, "Fifteen Large Flowers" },
                    { 65, 153, "An army of Bitter Leopards" },
                    { 66, 110, "A herd of Orange Leopards" },
                    { 67, 198, "The Large Planets" },
                    { 68, 114, "An army of Microscopic Cars" },
                    { 69, 180, "Two Large Cars" },
                    { 70, 58, "An army of Transparent Planets" },
                    { 71, 91, "The Purple Cars" },
                    { 72, 44, "Several Orange Houses" },
                    { 73, 248, "Several Orange Planets" },
                    { 74, 80, "Two Transparent Leopards" },
                    { 75, 12, "The Bitter Cars" },
                    { 76, 119, "A herd of Orange Flowers" },
                    { 77, 61, "A bunch of Green Buildings" },
                    { 78, 246, "An army of Green Buildings" },
                    { 79, 125, "A herd of Purple Cars" },
                    { 80, 74, "An army of Bitter Houses" },
                    { 81, 55, "Several Purple Cars" },
                    { 82, 115, "Fifteen Purple Cars" },
                    { 83, 59, "Fifteen Rose Smelling Cars" },
                    { 84, 135, "Two Purple Planets" },
                    { 85, 132, "An army of Orange Leopards" },
                    { 86, 247, "A herd of Transparent Buildings" },
                    { 87, 12, "Several Orange Houses" },
                    { 88, 223, "Fifteen Rose Smelling Flowers" },
                    { 89, 100, "A bunch of Orange Houses" },
                    { 90, 140, "Fifteen Bitter Flowers" },
                    { 91, 104, "An army of Purple Flowers" },
                    { 92, 161, "Several Large Leopards" },
                    { 93, 87, "An army of Microscopic Houses" },
                    { 94, 199, "A bunch of Purple Planets" },
                    { 95, 123, "Two Microscopic Houses" },
                    { 96, 128, "Two Microscopic Flowers" },
                    { 97, 245, "Fifteen Rose Smelling Flowers" },
                    { 98, 149, "Several Microscopic Planets" },
                    { 99, 194, "The Orange Buildings" },
                    { 100, 52, "A herd of Bitter Buildings" },
                    { 101, 235, "A herd of Orange Planets" },
                    { 102, 198, "Two Large Leopards" },
                    { 103, 234, "Two Green Planets" },
                    { 104, 54, "A bunch of Microscopic Flowers" },
                    { 105, 223, "A bunch of Green Cars" },
                    { 106, 4, "Fifteen Large Leopards" },
                    { 107, 184, "An army of Microscopic Leopards" },
                    { 108, 56, "An army of Green Buildings" },
                    { 109, 125, "Two Large Buildings" },
                    { 110, 94, "A bunch of Transparent Flowers" },
                    { 111, 122, "A herd of Orange Cars" },
                    { 112, 1, "A herd of Microscopic Buildings" },
                    { 113, 146, "Two Bitter Buildings" },
                    { 114, 17, "Several Rose Smelling Houses" },
                    { 115, 167, "An army of Orange Buildings" },
                    { 116, 53, "A herd of Orange Cars" },
                    { 117, 170, "An army of Purple Planets" },
                    { 118, 55, "Fifteen Purple Cars" },
                    { 119, 160, "An army of Microscopic Planets" },
                    { 120, 63, "A bunch of Microscopic Buildings" },
                    { 121, 244, "Several Transparent Leopards" },
                    { 122, 157, "Several Green Planets" },
                    { 123, 112, "Two Orange Flowers" },
                    { 124, 166, "Two Green Houses" },
                    { 125, 115, "A herd of Orange Houses" },
                    { 126, 244, "The Transparent Planets" },
                    { 127, 60, "An army of Purple Leopards" },
                    { 128, 194, "An army of Microscopic Buildings" },
                    { 129, 130, "A herd of Purple Planets" },
                    { 130, 89, "Fifteen Green Buildings" },
                    { 131, 42, "The Bitter Leopards" },
                    { 132, 202, "The Large Buildings" },
                    { 133, 199, "Two Purple Planets" },
                    { 134, 142, "A herd of Bitter Cars" },
                    { 135, 82, "The Transparent Houses" },
                    { 136, 126, "The Orange Cars" },
                    { 137, 93, "An army of Green Flowers" },
                    { 138, 28, "The Transparent Buildings" },
                    { 139, 227, "A bunch of Bitter Planets" },
                    { 140, 70, "The Large Planets" },
                    { 141, 3, "An army of Microscopic Planets" },
                    { 142, 52, "The Large Flowers" },
                    { 143, 199, "Two Transparent Flowers" },
                    { 144, 83, "Several Green Leopards" },
                    { 145, 64, "An army of Transparent Flowers" },
                    { 146, 96, "An army of Purple Cars" },
                    { 147, 188, "Several Bitter Cars" },
                    { 148, 48, "Two Orange Leopards" },
                    { 149, 101, "An army of Bitter Cars" },
                    { 150, 157, "An army of Rose Smelling Houses" },
                    { 151, 96, "Fifteen Microscopic Planets" },
                    { 152, 247, "Several Rose Smelling Houses" },
                    { 153, 20, "Two Transparent Leopards" },
                    { 154, 81, "The Transparent Buildings" },
                    { 155, 206, "A bunch of Rose Smelling Flowers" },
                    { 156, 7, "A herd of Transparent Houses" },
                    { 157, 242, "The Bitter Leopards" },
                    { 158, 22, "A bunch of Rose Smelling Cars" },
                    { 159, 89, "Several Purple Buildings" },
                    { 160, 37, "Several Microscopic Houses" },
                    { 161, 221, "Several Orange Planets" },
                    { 162, 84, "A bunch of Bitter Buildings" },
                    { 163, 10, "A bunch of Purple Flowers" },
                    { 164, 193, "A herd of Green Houses" },
                    { 165, 73, "A herd of Microscopic Planets" },
                    { 166, 43, "A bunch of Purple Planets" },
                    { 167, 50, "Several Orange Buildings" },
                    { 168, 211, "The Green Cars" },
                    { 169, 134, "The Orange Leopards" },
                    { 170, 147, "An army of Green Flowers" },
                    { 171, 195, "The Green Buildings" },
                    { 172, 46, "A herd of Orange Planets" },
                    { 173, 86, "The Orange Planets" },
                    { 174, 46, "Several Green Flowers" },
                    { 175, 44, "Several Microscopic Leopards" },
                    { 176, 21, "Several Rose Smelling Buildings" },
                    { 177, 73, "Fifteen Large Houses" },
                    { 178, 97, "Fifteen Microscopic Planets" },
                    { 179, 88, "The Bitter Houses" },
                    { 180, 43, "A herd of Microscopic Flowers" },
                    { 181, 244, "An army of Large Cars" },
                    { 182, 34, "Two Rose Smelling Buildings" },
                    { 183, 163, "Two Transparent Flowers" },
                    { 184, 121, "Two Green Buildings" },
                    { 185, 205, "An army of Large Houses" },
                    { 186, 89, "An army of Bitter Planets" },
                    { 187, 161, "Two Orange Flowers" },
                    { 188, 179, "A herd of Microscopic Planets" },
                    { 189, 199, "A herd of Transparent Planets" },
                    { 190, 218, "Two Microscopic Buildings" },
                    { 191, 166, "The Orange Houses" },
                    { 192, 105, "Fifteen Orange Leopards" },
                    { 193, 86, "An army of Large Houses" },
                    { 194, 219, "The Purple Buildings" },
                    { 195, 71, "The Large Cars" },
                    { 196, 209, "Two Bitter Planets" },
                    { 197, 48, "A herd of Rose Smelling Houses" },
                    { 198, 48, "Several Rose Smelling Leopards" },
                    { 199, 171, "Several Bitter Planets" },
                    { 200, 130, "An army of Transparent Planets" },
                    { 201, 126, "Fifteen Rose Smelling Leopards" },
                    { 202, 2, "The Large Cars" },
                    { 203, 52, "The Transparent Leopards" },
                    { 204, 238, "Several Orange Buildings" },
                    { 205, 217, "A herd of Microscopic Flowers" },
                    { 206, 217, "An army of Rose Smelling Houses" },
                    { 207, 124, "Several Transparent Leopards" },
                    { 208, 14, "Several Microscopic Buildings" },
                    { 209, 240, "Several Green Cars" },
                    { 210, 186, "Fifteen Rose Smelling Flowers" },
                    { 211, 233, "The Microscopic Planets" },
                    { 212, 161, "An army of Rose Smelling Leopards" },
                    { 213, 87, "Two Green Planets" },
                    { 214, 183, "A bunch of Large Leopards" },
                    { 215, 109, "Two Purple Cars" },
                    { 216, 184, "The Rose Smelling Cars" },
                    { 217, 240, "Two Orange Houses" },
                    { 218, 52, "An army of Purple Flowers" },
                    { 219, 9, "A herd of Large Planets" },
                    { 220, 174, "An army of Large Flowers" },
                    { 221, 221, "Fifteen Purple Cars" },
                    { 222, 7, "A herd of Purple Leopards" },
                    { 223, 141, "Two Bitter Buildings" },
                    { 224, 244, "A bunch of Rose Smelling Planets" },
                    { 225, 31, "Several Orange Flowers" },
                    { 226, 238, "The Green Buildings" },
                    { 227, 52, "Several Transparent Buildings" },
                    { 228, 17, "Two Microscopic Flowers" },
                    { 229, 63, "A bunch of Large Flowers" },
                    { 230, 82, "Several Purple Cars" },
                    { 231, 199, "A bunch of Green Houses" },
                    { 232, 94, "A bunch of Rose Smelling Houses" },
                    { 233, 155, "Several Orange Flowers" },
                    { 234, 70, "A herd of Orange Buildings" },
                    { 235, 193, "An army of Rose Smelling Houses" },
                    { 236, 90, "A herd of Microscopic Houses" },
                    { 237, 208, "An army of Green Buildings" },
                    { 238, 159, "Fifteen Rose Smelling Houses" },
                    { 239, 154, "A herd of Purple Buildings" },
                    { 240, 194, "Several Large Leopards" },
                    { 241, 184, "An army of Green Flowers" },
                    { 242, 235, "An army of Rose Smelling Houses" },
                    { 243, 110, "A herd of Microscopic Leopards" },
                    { 244, 96, "An army of Purple Planets" },
                    { 245, 62, "Several Transparent Flowers" },
                    { 246, 117, "A herd of Bitter Cars" },
                    { 247, 135, "A herd of Green Leopards" },
                    { 248, 201, "Fifteen Purple Flowers" },
                    { 249, 154, "The Green Buildings" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_books_AuthorId",
                table: "books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "authors");
        }
    }
}
