using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace exercise.webapi.Migrations
{
    /// <inheritdoc />
    public partial class FirstMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "authors",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    firstname = table.Column<string>(type: "text", nullable: false),
                    lastname = table.Column<string>(type: "text", nullable: false),
                    email = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_authors", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "books",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    title = table.Column<string>(type: "text", nullable: false),
                    AuthorId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_books", x => x.id);
                    table.ForeignKey(
                        name: "FK_books_authors_AuthorId",
                        column: x => x.AuthorId,
                        principalTable: "authors",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "authors",
                columns: new[] { "id", "email", "firstname", "lastname" },
                values: new object[,]
                {
                    { 1, "audrey.jagger@something.com", "Audrey", "Jagger" },
                    { 2, "jimi.hepburn@gov.nl", "Jimi", "Hepburn" },
                    { 3, "donald.winfrey@google.com", "Donald", "Winfrey" },
                    { 4, "jimi.winslet@something.com", "Jimi", "Winslet" },
                    { 5, "elvis.winslet@google.com", "Elvis", "Winslet" },
                    { 6, "jimi.trump@theworld.ca", "Jimi", "Trump" },
                    { 7, "donald.presley@gov.gr", "Donald", "Presley" },
                    { 8, "elvis.windsor@gov.gr", "Elvis", "Windsor" },
                    { 9, "charles.windsor@nasa.org.us", "Charles", "Windsor" },
                    { 10, "barack.trump@gov.ru", "Barack", "Trump" },
                    { 11, "audrey.obama@theworld.ca", "Audrey", "Obama" },
                    { 12, "kate.obama@bbc.co.uk", "Kate", "Obama" },
                    { 13, "audrey.winslet@theworld.ca", "Audrey", "Winslet" },
                    { 14, "audrey.windsor@google.com", "Audrey", "Windsor" },
                    { 15, "oprah.presley@theworld.ca", "Oprah", "Presley" },
                    { 16, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 17, "charles.hepburn@something.com", "Charles", "Hepburn" },
                    { 18, "donald.winslet@gov.nl", "Donald", "Winslet" },
                    { 19, "audrey.middleton@google.com", "Audrey", "Middleton" },
                    { 20, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 21, "barack.obama@nasa.org.us", "Barack", "Obama" },
                    { 22, "elvis.middleton@bbc.co.uk", "Elvis", "Middleton" },
                    { 23, "barack.hepburn@gov.nl", "Barack", "Hepburn" },
                    { 24, "mick.middleton@tesla.com", "Mick", "Middleton" },
                    { 25, "elvis.winslet@gov.ru", "Elvis", "Winslet" },
                    { 26, "kate.winslet@gov.gr", "Kate", "Winslet" },
                    { 27, "donald.obama@gov.nl", "Donald", "Obama" },
                    { 28, "donald.obama@nasa.org.us", "Donald", "Obama" },
                    { 29, "kate.windsor@google.com", "Kate", "Windsor" },
                    { 30, "oprah.hepburn@theworld.ca", "Oprah", "Hepburn" },
                    { 31, "kate.trump@gov.nl", "Kate", "Trump" },
                    { 32, "jimi.trump@nasa.org.us", "Jimi", "Trump" },
                    { 33, "mick.middleton@tesla.com", "Mick", "Middleton" },
                    { 34, "audrey.hendrix@google.com", "Audrey", "Hendrix" },
                    { 35, "kate.windsor@tesla.com", "Kate", "Windsor" },
                    { 36, "oprah.windsor@gov.nl", "Oprah", "Windsor" },
                    { 37, "barack.trump@tesla.com", "Barack", "Trump" },
                    { 38, "mick.middleton@gov.gr", "Mick", "Middleton" },
                    { 39, "audrey.trump@theworld.ca", "Audrey", "Trump" },
                    { 40, "oprah.hendrix@bbc.co.uk", "Oprah", "Hendrix" },
                    { 41, "mick.winslet@gov.us", "Mick", "Winslet" },
                    { 42, "barack.trump@gov.us", "Barack", "Trump" },
                    { 43, "barack.hendrix@theworld.ca", "Barack", "Hendrix" },
                    { 44, "kate.windsor@something.com", "Kate", "Windsor" },
                    { 45, "audrey.obama@nasa.org.us", "Audrey", "Obama" },
                    { 46, "jimi.winfrey@tesla.com", "Jimi", "Winfrey" },
                    { 47, "elvis.windsor@bbc.co.uk", "Elvis", "Windsor" },
                    { 48, "elvis.jagger@gov.gr", "Elvis", "Jagger" },
                    { 49, "donald.presley@nasa.org.us", "Donald", "Presley" },
                    { 50, "kate.jagger@bbc.co.uk", "Kate", "Jagger" },
                    { 51, "barack.jagger@something.com", "Barack", "Jagger" },
                    { 52, "oprah.hepburn@google.com", "Oprah", "Hepburn" },
                    { 53, "oprah.windsor@theworld.ca", "Oprah", "Windsor" },
                    { 54, "donald.winfrey@gov.gr", "Donald", "Winfrey" },
                    { 55, "barack.hepburn@bbc.co.uk", "Barack", "Hepburn" },
                    { 56, "elvis.windsor@something.com", "Elvis", "Windsor" },
                    { 57, "kate.winfrey@google.com", "Kate", "Winfrey" },
                    { 58, "audrey.hepburn@bbc.co.uk", "Audrey", "Hepburn" },
                    { 59, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 60, "kate.presley@something.com", "Kate", "Presley" },
                    { 61, "donald.middleton@gov.nl", "Donald", "Middleton" },
                    { 62, "kate.middleton@something.com", "Kate", "Middleton" },
                    { 63, "elvis.windsor@gov.gr", "Elvis", "Windsor" },
                    { 64, "oprah.jagger@gov.us", "Oprah", "Jagger" },
                    { 65, "kate.middleton@gov.us", "Kate", "Middleton" },
                    { 66, "elvis.hepburn@bbc.co.uk", "Elvis", "Hepburn" },
                    { 67, "audrey.trump@gov.ru", "Audrey", "Trump" },
                    { 68, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 69, "audrey.hepburn@google.com", "Audrey", "Hepburn" },
                    { 70, "barack.trump@something.com", "Barack", "Trump" },
                    { 71, "charles.winfrey@gov.nl", "Charles", "Winfrey" },
                    { 72, "elvis.middleton@bbc.co.uk", "Elvis", "Middleton" },
                    { 73, "jimi.hendrix@bbc.co.uk", "Jimi", "Hendrix" },
                    { 74, "mick.jagger@gov.us", "Mick", "Jagger" },
                    { 75, "donald.obama@gov.us", "Donald", "Obama" },
                    { 76, "jimi.middleton@bbc.co.uk", "Jimi", "Middleton" },
                    { 77, "barack.windsor@theworld.ca", "Barack", "Windsor" },
                    { 78, "charles.obama@gov.us", "Charles", "Obama" },
                    { 79, "audrey.hendrix@nasa.org.us", "Audrey", "Hendrix" },
                    { 80, "jimi.windsor@gov.gr", "Jimi", "Windsor" },
                    { 81, "elvis.hendrix@bbc.co.uk", "Elvis", "Hendrix" },
                    { 82, "charles.windsor@gov.nl", "Charles", "Windsor" },
                    { 83, "mick.hendrix@gov.gr", "Mick", "Hendrix" },
                    { 84, "oprah.winfrey@gov.nl", "Oprah", "Winfrey" },
                    { 85, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 86, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 87, "jimi.hendrix@tesla.com", "Jimi", "Hendrix" },
                    { 88, "donald.winslet@gov.gr", "Donald", "Winslet" },
                    { 89, "donald.trump@bbc.co.uk", "Donald", "Trump" },
                    { 90, "jimi.hendrix@bbc.co.uk", "Jimi", "Hendrix" },
                    { 91, "oprah.trump@theworld.ca", "Oprah", "Trump" },
                    { 92, "elvis.presley@gov.gr", "Elvis", "Presley" },
                    { 93, "barack.middleton@nasa.org.us", "Barack", "Middleton" },
                    { 94, "charles.winfrey@google.com", "Charles", "Winfrey" },
                    { 95, "audrey.obama@something.com", "Audrey", "Obama" },
                    { 96, "mick.jagger@gov.gr", "Mick", "Jagger" },
                    { 97, "kate.jagger@google.com", "Kate", "Jagger" },
                    { 98, "kate.middleton@gov.gr", "Kate", "Middleton" },
                    { 99, "kate.obama@gov.ru", "Kate", "Obama" },
                    { 100, "elvis.hepburn@gov.us", "Elvis", "Hepburn" },
                    { 101, "donald.windsor@something.com", "Donald", "Windsor" },
                    { 102, "oprah.hepburn@gov.us", "Oprah", "Hepburn" },
                    { 103, "charles.presley@something.com", "Charles", "Presley" },
                    { 104, "barack.middleton@gov.gr", "Barack", "Middleton" },
                    { 105, "elvis.winfrey@bbc.co.uk", "Elvis", "Winfrey" },
                    { 106, "kate.winfrey@tesla.com", "Kate", "Winfrey" },
                    { 107, "mick.hendrix@gov.ru", "Mick", "Hendrix" },
                    { 108, "kate.jagger@something.com", "Kate", "Jagger" },
                    { 109, "mick.trump@bbc.co.uk", "Mick", "Trump" },
                    { 110, "kate.jagger@gov.gr", "Kate", "Jagger" },
                    { 111, "kate.hendrix@bbc.co.uk", "Kate", "Hendrix" },
                    { 112, "kate.middleton@gov.nl", "Kate", "Middleton" },
                    { 113, "jimi.winfrey@something.com", "Jimi", "Winfrey" },
                    { 114, "charles.presley@gov.ru", "Charles", "Presley" },
                    { 115, "mick.middleton@gov.nl", "Mick", "Middleton" },
                    { 116, "oprah.jagger@tesla.com", "Oprah", "Jagger" },
                    { 117, "kate.winslet@gov.nl", "Kate", "Winslet" },
                    { 118, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 119, "audrey.hendrix@tesla.com", "Audrey", "Hendrix" },
                    { 120, "kate.obama@gov.gr", "Kate", "Obama" },
                    { 121, "jimi.winfrey@theworld.ca", "Jimi", "Winfrey" },
                    { 122, "charles.winfrey@bbc.co.uk", "Charles", "Winfrey" },
                    { 123, "donald.middleton@google.com", "Donald", "Middleton" },
                    { 124, "elvis.winslet@tesla.com", "Elvis", "Winslet" },
                    { 125, "jimi.obama@something.com", "Jimi", "Obama" },
                    { 126, "charles.jagger@gov.gr", "Charles", "Jagger" },
                    { 127, "oprah.obama@theworld.ca", "Oprah", "Obama" },
                    { 128, "oprah.hendrix@bbc.co.uk", "Oprah", "Hendrix" },
                    { 129, "donald.hendrix@theworld.ca", "Donald", "Hendrix" },
                    { 130, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 131, "jimi.trump@bbc.co.uk", "Jimi", "Trump" },
                    { 132, "barack.winfrey@bbc.co.uk", "Barack", "Winfrey" },
                    { 133, "kate.presley@gov.ru", "Kate", "Presley" },
                    { 134, "kate.presley@tesla.com", "Kate", "Presley" },
                    { 135, "barack.middleton@google.com", "Barack", "Middleton" },
                    { 136, "jimi.windsor@something.com", "Jimi", "Windsor" },
                    { 137, "kate.trump@bbc.co.uk", "Kate", "Trump" },
                    { 138, "kate.windsor@gov.ru", "Kate", "Windsor" },
                    { 139, "kate.presley@gov.us", "Kate", "Presley" },
                    { 140, "charles.jagger@gov.nl", "Charles", "Jagger" },
                    { 141, "jimi.winfrey@google.com", "Jimi", "Winfrey" },
                    { 142, "oprah.winslet@google.com", "Oprah", "Winslet" },
                    { 143, "kate.hendrix@gov.gr", "Kate", "Hendrix" },
                    { 144, "audrey.windsor@gov.gr", "Audrey", "Windsor" },
                    { 145, "mick.hepburn@tesla.com", "Mick", "Hepburn" },
                    { 146, "kate.trump@nasa.org.us", "Kate", "Trump" },
                    { 147, "mick.presley@tesla.com", "Mick", "Presley" },
                    { 148, "charles.windsor@gov.gr", "Charles", "Windsor" },
                    { 149, "oprah.hepburn@something.com", "Oprah", "Hepburn" },
                    { 150, "mick.obama@gov.ru", "Mick", "Obama" },
                    { 151, "charles.winfrey@something.com", "Charles", "Winfrey" },
                    { 152, "kate.winfrey@gov.nl", "Kate", "Winfrey" },
                    { 153, "barack.jagger@something.com", "Barack", "Jagger" },
                    { 154, "kate.hepburn@tesla.com", "Kate", "Hepburn" },
                    { 155, "elvis.hendrix@something.com", "Elvis", "Hendrix" },
                    { 156, "barack.winfrey@gov.nl", "Barack", "Winfrey" },
                    { 157, "elvis.winslet@theworld.ca", "Elvis", "Winslet" },
                    { 158, "donald.obama@gov.us", "Donald", "Obama" },
                    { 159, "elvis.winfrey@something.com", "Elvis", "Winfrey" },
                    { 160, "audrey.hendrix@theworld.ca", "Audrey", "Hendrix" },
                    { 161, "elvis.windsor@google.com", "Elvis", "Windsor" },
                    { 162, "elvis.winfrey@tesla.com", "Elvis", "Winfrey" },
                    { 163, "barack.hepburn@gov.nl", "Barack", "Hepburn" },
                    { 164, "donald.winfrey@gov.us", "Donald", "Winfrey" },
                    { 165, "mick.trump@google.com", "Mick", "Trump" },
                    { 166, "jimi.winslet@gov.nl", "Jimi", "Winslet" },
                    { 167, "jimi.middleton@something.com", "Jimi", "Middleton" },
                    { 168, "oprah.hepburn@google.com", "Oprah", "Hepburn" },
                    { 169, "audrey.trump@bbc.co.uk", "Audrey", "Trump" },
                    { 170, "oprah.trump@nasa.org.us", "Oprah", "Trump" },
                    { 171, "mick.hepburn@something.com", "Mick", "Hepburn" },
                    { 172, "kate.obama@nasa.org.us", "Kate", "Obama" },
                    { 173, "audrey.winfrey@bbc.co.uk", "Audrey", "Winfrey" },
                    { 174, "jimi.hepburn@something.com", "Jimi", "Hepburn" },
                    { 175, "kate.trump@theworld.ca", "Kate", "Trump" },
                    { 176, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 177, "barack.hendrix@gov.us", "Barack", "Hendrix" },
                    { 178, "donald.winslet@gov.us", "Donald", "Winslet" },
                    { 179, "donald.obama@something.com", "Donald", "Obama" },
                    { 180, "elvis.hepburn@gov.ru", "Elvis", "Hepburn" },
                    { 181, "jimi.hendrix@google.com", "Jimi", "Hendrix" },
                    { 182, "donald.middleton@gov.gr", "Donald", "Middleton" },
                    { 183, "donald.hepburn@something.com", "Donald", "Hepburn" },
                    { 184, "barack.winfrey@gov.us", "Barack", "Winfrey" },
                    { 185, "donald.presley@something.com", "Donald", "Presley" },
                    { 186, "kate.presley@gov.gr", "Kate", "Presley" },
                    { 187, "oprah.obama@theworld.ca", "Oprah", "Obama" },
                    { 188, "elvis.hendrix@theworld.ca", "Elvis", "Hendrix" },
                    { 189, "donald.winslet@nasa.org.us", "Donald", "Winslet" },
                    { 190, "donald.windsor@nasa.org.us", "Donald", "Windsor" },
                    { 191, "barack.presley@gov.nl", "Barack", "Presley" },
                    { 192, "audrey.hepburn@bbc.co.uk", "Audrey", "Hepburn" },
                    { 193, "barack.middleton@gov.ru", "Barack", "Middleton" },
                    { 194, "kate.windsor@gov.us", "Kate", "Windsor" },
                    { 195, "jimi.obama@nasa.org.us", "Jimi", "Obama" },
                    { 196, "oprah.hepburn@theworld.ca", "Oprah", "Hepburn" },
                    { 197, "oprah.presley@tesla.com", "Oprah", "Presley" },
                    { 198, "oprah.jagger@bbc.co.uk", "Oprah", "Jagger" },
                    { 199, "barack.hepburn@google.com", "Barack", "Hepburn" },
                    { 200, "elvis.obama@tesla.com", "Elvis", "Obama" },
                    { 201, "charles.hendrix@tesla.com", "Charles", "Hendrix" },
                    { 202, "donald.middleton@gov.ru", "Donald", "Middleton" },
                    { 203, "audrey.trump@gov.nl", "Audrey", "Trump" },
                    { 204, "donald.hepburn@google.com", "Donald", "Hepburn" },
                    { 205, "jimi.trump@gov.us", "Jimi", "Trump" },
                    { 206, "mick.obama@gov.nl", "Mick", "Obama" },
                    { 207, "donald.hepburn@nasa.org.us", "Donald", "Hepburn" },
                    { 208, "donald.middleton@tesla.com", "Donald", "Middleton" },
                    { 209, "kate.jagger@tesla.com", "Kate", "Jagger" },
                    { 210, "audrey.hendrix@gov.ru", "Audrey", "Hendrix" },
                    { 211, "kate.hendrix@nasa.org.us", "Kate", "Hendrix" },
                    { 212, "charles.obama@something.com", "Charles", "Obama" },
                    { 213, "mick.jagger@google.com", "Mick", "Jagger" },
                    { 214, "audrey.middleton@gov.us", "Audrey", "Middleton" },
                    { 215, "donald.trump@nasa.org.us", "Donald", "Trump" },
                    { 216, "charles.hepburn@theworld.ca", "Charles", "Hepburn" },
                    { 217, "mick.winslet@google.com", "Mick", "Winslet" },
                    { 218, "jimi.presley@gov.ru", "Jimi", "Presley" },
                    { 219, "charles.jagger@google.com", "Charles", "Jagger" },
                    { 220, "audrey.winfrey@nasa.org.us", "Audrey", "Winfrey" },
                    { 221, "elvis.windsor@gov.nl", "Elvis", "Windsor" },
                    { 222, "kate.winfrey@tesla.com", "Kate", "Winfrey" },
                    { 223, "mick.winslet@gov.us", "Mick", "Winslet" },
                    { 224, "jimi.winfrey@gov.ru", "Jimi", "Winfrey" },
                    { 225, "donald.presley@tesla.com", "Donald", "Presley" },
                    { 226, "jimi.obama@google.com", "Jimi", "Obama" },
                    { 227, "kate.middleton@bbc.co.uk", "Kate", "Middleton" },
                    { 228, "barack.winslet@nasa.org.us", "Barack", "Winslet" },
                    { 229, "mick.hendrix@nasa.org.us", "Mick", "Hendrix" },
                    { 230, "elvis.winfrey@theworld.ca", "Elvis", "Winfrey" },
                    { 231, "elvis.presley@theworld.ca", "Elvis", "Presley" },
                    { 232, "donald.obama@gov.gr", "Donald", "Obama" },
                    { 233, "jimi.middleton@google.com", "Jimi", "Middleton" },
                    { 234, "jimi.jagger@tesla.com", "Jimi", "Jagger" },
                    { 235, "elvis.jagger@theworld.ca", "Elvis", "Jagger" },
                    { 236, "oprah.obama@gov.nl", "Oprah", "Obama" },
                    { 237, "audrey.jagger@gov.nl", "Audrey", "Jagger" },
                    { 238, "mick.windsor@nasa.org.us", "Mick", "Windsor" },
                    { 239, "oprah.hendrix@gov.nl", "Oprah", "Hendrix" },
                    { 240, "kate.obama@google.com", "Kate", "Obama" },
                    { 241, "jimi.presley@nasa.org.us", "Jimi", "Presley" },
                    { 242, "kate.obama@google.com", "Kate", "Obama" },
                    { 243, "mick.winfrey@theworld.ca", "Mick", "Winfrey" },
                    { 244, "elvis.trump@theworld.ca", "Elvis", "Trump" },
                    { 245, "kate.hendrix@something.com", "Kate", "Hendrix" },
                    { 246, "jimi.winfrey@google.com", "Jimi", "Winfrey" },
                    { 247, "mick.middleton@something.com", "Mick", "Middleton" },
                    { 248, "elvis.obama@gov.nl", "Elvis", "Obama" },
                    { 249, "barack.jagger@something.com", "Barack", "Jagger" }
                });

            migrationBuilder.InsertData(
                table: "books",
                columns: new[] { "id", "AuthorId", "title" },
                values: new object[,]
                {
                    { 1, 67, "A bunch of Large Flowers" },
                    { 2, 146, "An army of Rose Smelling Leopards" },
                    { 3, 54, "The Large Leopards" },
                    { 4, 174, "An army of Transparent Houses" },
                    { 5, 16, "A herd of Rose Smelling Houses" },
                    { 6, 64, "A bunch of Large Planets" },
                    { 7, 222, "Two Purple Houses" },
                    { 8, 113, "A bunch of Microscopic Leopards" },
                    { 9, 193, "The Orange Houses" },
                    { 10, 87, "Several Orange Buildings" },
                    { 11, 229, "A bunch of Purple Flowers" },
                    { 12, 188, "An army of Green Buildings" },
                    { 13, 25, "Several Bitter Houses" },
                    { 14, 184, "Fifteen Microscopic Leopards" },
                    { 15, 92, "A bunch of Bitter Leopards" },
                    { 16, 83, "Fifteen Microscopic Buildings" },
                    { 17, 127, "The Large Cars" },
                    { 18, 133, "The Orange Leopards" },
                    { 19, 227, "Fifteen Purple Cars" },
                    { 20, 97, "An army of Microscopic Buildings" },
                    { 21, 39, "Fifteen Bitter Flowers" },
                    { 22, 100, "Fifteen Transparent Cars" },
                    { 23, 2, "A herd of Orange Leopards" },
                    { 24, 134, "A bunch of Large Houses" },
                    { 25, 196, "Several Transparent Buildings" },
                    { 26, 79, "The Orange Cars" },
                    { 27, 234, "The Orange Buildings" },
                    { 28, 238, "Fifteen Large Houses" },
                    { 29, 6, "Fifteen Bitter Flowers" },
                    { 30, 140, "Several Green Houses" },
                    { 31, 20, "A bunch of Microscopic Leopards" },
                    { 32, 95, "Several Transparent Planets" },
                    { 33, 126, "Several Orange Houses" },
                    { 34, 37, "The Rose Smelling Planets" },
                    { 35, 248, "A bunch of Bitter Flowers" },
                    { 36, 73, "An army of Large Buildings" },
                    { 37, 21, "A herd of Green Buildings" },
                    { 38, 226, "A bunch of Large Houses" },
                    { 39, 2, "Several Purple Leopards" },
                    { 40, 23, "Fifteen Orange Houses" },
                    { 41, 5, "Two Transparent Houses" },
                    { 42, 163, "Several Rose Smelling Leopards" },
                    { 43, 138, "An army of Bitter Planets" },
                    { 44, 182, "The Green Buildings" },
                    { 45, 236, "Two Bitter Planets" },
                    { 46, 173, "An army of Rose Smelling Houses" },
                    { 47, 139, "A bunch of Green Leopards" },
                    { 48, 118, "The Large Leopards" },
                    { 49, 224, "A herd of Purple Cars" },
                    { 50, 47, "A herd of Orange Buildings" },
                    { 51, 27, "Several Orange Planets" },
                    { 52, 146, "A bunch of Microscopic Houses" },
                    { 53, 5, "Two Green Planets" },
                    { 54, 18, "A herd of Microscopic Flowers" },
                    { 55, 25, "Two Microscopic Planets" },
                    { 56, 1, "The Purple Planets" },
                    { 57, 166, "Fifteen Rose Smelling Flowers" },
                    { 58, 153, "A bunch of Green Leopards" },
                    { 59, 130, "Fifteen Orange Houses" },
                    { 60, 133, "A herd of Bitter Buildings" },
                    { 61, 176, "An army of Large Buildings" },
                    { 62, 237, "Several Purple Houses" },
                    { 63, 66, "Several Orange Buildings" },
                    { 64, 123, "The Purple Planets" },
                    { 65, 68, "A herd of Green Buildings" },
                    { 66, 245, "An army of Orange Houses" },
                    { 67, 12, "Fifteen Transparent Flowers" },
                    { 68, 198, "Two Transparent Flowers" },
                    { 69, 20, "A herd of Green Flowers" },
                    { 70, 190, "A bunch of Transparent Flowers" },
                    { 71, 172, "Two Rose Smelling Leopards" },
                    { 72, 242, "A bunch of Bitter Flowers" },
                    { 73, 183, "A herd of Purple Houses" },
                    { 74, 118, "Two Orange Cars" },
                    { 75, 247, "Fifteen Microscopic Buildings" },
                    { 76, 219, "Two Transparent Leopards" },
                    { 77, 172, "Several Orange Houses" },
                    { 78, 195, "A herd of Large Flowers" },
                    { 79, 18, "Several Rose Smelling Buildings" },
                    { 80, 108, "A bunch of Purple Houses" },
                    { 81, 209, "Two Large Houses" },
                    { 82, 94, "Two Bitter Flowers" },
                    { 83, 127, "Two Orange Cars" },
                    { 84, 91, "Two Microscopic Flowers" },
                    { 85, 196, "The Microscopic Planets" },
                    { 86, 91, "A bunch of Large Buildings" },
                    { 87, 72, "A herd of Orange Flowers" },
                    { 88, 125, "Fifteen Green Houses" },
                    { 89, 204, "The Large Buildings" },
                    { 90, 180, "A bunch of Rose Smelling Leopards" },
                    { 91, 152, "A herd of Orange Cars" },
                    { 92, 240, "A bunch of Purple Cars" },
                    { 93, 240, "An army of Large Flowers" },
                    { 94, 180, "Fifteen Transparent Buildings" },
                    { 95, 233, "Two Bitter Houses" },
                    { 96, 53, "Fifteen Purple Houses" },
                    { 97, 48, "Several Purple Cars" },
                    { 98, 144, "The Transparent Cars" },
                    { 99, 117, "An army of Transparent Cars" },
                    { 100, 214, "A herd of Microscopic Buildings" },
                    { 101, 9, "An army of Transparent Buildings" },
                    { 102, 28, "A herd of Purple Leopards" },
                    { 103, 166, "A bunch of Orange Planets" },
                    { 104, 184, "Fifteen Large Leopards" },
                    { 105, 199, "The Purple Houses" },
                    { 106, 106, "An army of Green Flowers" },
                    { 107, 122, "Several Purple Flowers" },
                    { 108, 56, "A herd of Microscopic Cars" },
                    { 109, 150, "Two Orange Buildings" },
                    { 110, 223, "An army of Large Planets" },
                    { 111, 103, "Fifteen Microscopic Flowers" },
                    { 112, 176, "The Orange Buildings" },
                    { 113, 246, "Several Orange Leopards" },
                    { 114, 101, "The Large Planets" },
                    { 115, 38, "Two Purple Cars" },
                    { 116, 69, "An army of Microscopic Planets" },
                    { 117, 182, "An army of Bitter Buildings" },
                    { 118, 107, "A bunch of Purple Buildings" },
                    { 119, 184, "Fifteen Orange Flowers" },
                    { 120, 9, "The Purple Flowers" },
                    { 121, 72, "Several Purple Houses" },
                    { 122, 130, "An army of Rose Smelling Houses" },
                    { 123, 234, "The Transparent Cars" },
                    { 124, 80, "A herd of Orange Leopards" },
                    { 125, 209, "A herd of Purple Leopards" },
                    { 126, 74, "The Bitter Flowers" },
                    { 127, 36, "A herd of Rose Smelling Buildings" },
                    { 128, 18, "Several Microscopic Buildings" },
                    { 129, 161, "A herd of Transparent Planets" },
                    { 130, 32, "Fifteen Transparent Houses" },
                    { 131, 151, "A bunch of Large Buildings" },
                    { 132, 52, "A herd of Green Leopards" },
                    { 133, 52, "An army of Purple Cars" },
                    { 134, 37, "A herd of Green Houses" },
                    { 135, 106, "Fifteen Transparent Cars" },
                    { 136, 25, "A herd of Orange Cars" },
                    { 137, 208, "A herd of Transparent Buildings" },
                    { 138, 126, "An army of Transparent Buildings" },
                    { 139, 207, "The Large Cars" },
                    { 140, 106, "Two Transparent Houses" },
                    { 141, 73, "An army of Rose Smelling Planets" },
                    { 142, 129, "A bunch of Bitter Cars" },
                    { 143, 240, "Several Microscopic Leopards" },
                    { 144, 174, "A bunch of Rose Smelling Flowers" },
                    { 145, 89, "Several Orange Flowers" },
                    { 146, 219, "Two Microscopic Flowers" },
                    { 147, 103, "Several Rose Smelling Flowers" },
                    { 148, 155, "A bunch of Microscopic Buildings" },
                    { 149, 58, "A herd of Transparent Buildings" },
                    { 150, 151, "Two Green Planets" },
                    { 151, 243, "A herd of Rose Smelling Leopards" },
                    { 152, 209, "A herd of Green Houses" },
                    { 153, 92, "A herd of Purple Planets" },
                    { 154, 58, "The Purple Cars" },
                    { 155, 30, "Two Large Planets" },
                    { 156, 45, "A bunch of Microscopic Cars" },
                    { 157, 146, "A bunch of Green Buildings" },
                    { 158, 58, "Fifteen Bitter Houses" },
                    { 159, 246, "Two Green Flowers" },
                    { 160, 12, "Several Rose Smelling Buildings" },
                    { 161, 10, "Two Orange Planets" },
                    { 162, 93, "An army of Large Leopards" },
                    { 163, 18, "A herd of Transparent Planets" },
                    { 164, 71, "A herd of Orange Cars" },
                    { 165, 41, "Several Microscopic Planets" },
                    { 166, 7, "A herd of Large Planets" },
                    { 167, 18, "An army of Transparent Flowers" },
                    { 168, 128, "Fifteen Purple Buildings" },
                    { 169, 132, "Several Transparent Houses" },
                    { 170, 227, "Fifteen Purple Cars" },
                    { 171, 235, "Fifteen Green Flowers" },
                    { 172, 84, "The Orange Flowers" },
                    { 173, 65, "A herd of Purple Planets" },
                    { 174, 11, "A herd of Rose Smelling Cars" },
                    { 175, 198, "An army of Rose Smelling Planets" },
                    { 176, 44, "A herd of Rose Smelling Flowers" },
                    { 177, 96, "Two Green Cars" },
                    { 178, 228, "Fifteen Orange Buildings" },
                    { 179, 58, "Fifteen Rose Smelling Buildings" },
                    { 180, 170, "The Large Cars" },
                    { 181, 194, "An army of Orange Flowers" },
                    { 182, 242, "Two Orange Planets" },
                    { 183, 70, "A bunch of Purple Cars" },
                    { 184, 205, "Fifteen Rose Smelling Buildings" },
                    { 185, 249, "The Purple Buildings" },
                    { 186, 178, "An army of Microscopic Houses" },
                    { 187, 242, "Fifteen Purple Houses" },
                    { 188, 193, "Several Orange Flowers" },
                    { 189, 244, "Several Transparent Houses" },
                    { 190, 182, "A herd of Purple Flowers" },
                    { 191, 162, "A bunch of Green Houses" },
                    { 192, 118, "The Rose Smelling Houses" },
                    { 193, 230, "A bunch of Rose Smelling Buildings" },
                    { 194, 77, "A bunch of Purple Cars" },
                    { 195, 101, "The Microscopic Leopards" },
                    { 196, 61, "An army of Orange Leopards" },
                    { 197, 89, "Two Purple Flowers" },
                    { 198, 110, "A herd of Bitter Houses" },
                    { 199, 128, "Several Orange Planets" },
                    { 200, 88, "Two Transparent Flowers" },
                    { 201, 76, "A bunch of Orange Planets" },
                    { 202, 78, "Several Orange Planets" },
                    { 203, 199, "An army of Large Buildings" },
                    { 204, 161, "Two Purple Houses" },
                    { 205, 216, "The Green Cars" },
                    { 206, 88, "An army of Green Flowers" },
                    { 207, 75, "The Green Planets" },
                    { 208, 46, "An army of Rose Smelling Planets" },
                    { 209, 124, "The Purple Buildings" },
                    { 210, 30, "A bunch of Bitter Planets" },
                    { 211, 146, "An army of Rose Smelling Flowers" },
                    { 212, 94, "A herd of Microscopic Planets" },
                    { 213, 58, "The Purple Buildings" },
                    { 214, 145, "A bunch of Microscopic Leopards" },
                    { 215, 194, "The Microscopic Houses" },
                    { 216, 82, "Several Purple Houses" },
                    { 217, 24, "Two Transparent Cars" },
                    { 218, 187, "Several Bitter Leopards" },
                    { 219, 42, "Several Bitter Houses" },
                    { 220, 68, "A bunch of Large Flowers" },
                    { 221, 216, "An army of Large Flowers" },
                    { 222, 2, "Several Purple Cars" },
                    { 223, 169, "Two Bitter Planets" },
                    { 224, 204, "A herd of Transparent Leopards" },
                    { 225, 189, "A herd of Rose Smelling Houses" },
                    { 226, 100, "Fifteen Large Leopards" },
                    { 227, 167, "Fifteen Orange Houses" },
                    { 228, 174, "A herd of Large Buildings" },
                    { 229, 112, "Several Purple Cars" },
                    { 230, 10, "Several Microscopic Buildings" },
                    { 231, 223, "Two Rose Smelling Cars" },
                    { 232, 200, "The Green Leopards" },
                    { 233, 181, "The Rose Smelling Buildings" },
                    { 234, 43, "Several Transparent Cars" },
                    { 235, 16, "An army of Rose Smelling Cars" },
                    { 236, 6, "Two Microscopic Planets" },
                    { 237, 65, "Fifteen Rose Smelling Planets" },
                    { 238, 245, "Several Green Buildings" },
                    { 239, 244, "An army of Microscopic Cars" },
                    { 240, 102, "A herd of Large Houses" },
                    { 241, 112, "Several Bitter Houses" },
                    { 242, 69, "An army of Large Houses" },
                    { 243, 24, "The Transparent Buildings" },
                    { 244, 241, "An army of Orange Flowers" },
                    { 245, 69, "An army of Green Leopards" },
                    { 246, 209, "Several Large Flowers" },
                    { 247, 27, "A herd of Microscopic Cars" },
                    { 248, 170, "An army of Purple Houses" },
                    { 249, 206, "Fifteen Large Leopards" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_books_AuthorId",
                table: "books",
                column: "AuthorId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "books");

            migrationBuilder.DropTable(
                name: "authors");
        }
    }
}
