// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.webapi.Data;

#nullable disable

namespace exercise.webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.webapi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mick.winslet@gov.nl",
                            FirstName = "Mick",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 2,
                            Email = "audrey.jagger@nasa.org.us",
                            FirstName = "Audrey",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charles.middleton@gov.ru",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 4,
                            Email = "jimi.trump@gov.us",
                            FirstName = "Jimi",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 5,
                            Email = "kate.winfrey@something.com",
                            FirstName = "Kate",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 6,
                            Email = "jimi.winslet@gov.ru",
                            FirstName = "Jimi",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mick.obama@bbc.co.uk",
                            FirstName = "Mick",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 8,
                            Email = "oprah.presley@nasa.org.us",
                            FirstName = "Oprah",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 9,
                            Email = "kate.hepburn@something.com",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 10,
                            Email = "charles.trump@theworld.ca",
                            FirstName = "Charles",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 11,
                            Email = "barack.trump@gov.ru",
                            FirstName = "Barack",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 12,
                            Email = "charles.winfrey@google.com",
                            FirstName = "Charles",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 13,
                            Email = "elvis.winslet@gov.nl",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 14,
                            Email = "charles.hendrix@gov.ru",
                            FirstName = "Charles",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 15,
                            Email = "charles.jagger@google.com",
                            FirstName = "Charles",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 16,
                            Email = "oprah.middleton@something.com",
                            FirstName = "Oprah",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 17,
                            Email = "charles.presley@gov.gr",
                            FirstName = "Charles",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 18,
                            Email = "kate.trump@something.com",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 19,
                            Email = "barack.hendrix@gov.nl",
                            FirstName = "Barack",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 20,
                            Email = "kate.windsor@gov.ru",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 21,
                            Email = "jimi.hepburn@gov.gr",
                            FirstName = "Jimi",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 22,
                            Email = "charles.obama@bbc.co.uk",
                            FirstName = "Charles",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 23,
                            Email = "mick.winfrey@nasa.org.us",
                            FirstName = "Mick",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 24,
                            Email = "barack.jagger@gov.us",
                            FirstName = "Barack",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 25,
                            Email = "elvis.jagger@bbc.co.uk",
                            FirstName = "Elvis",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 26,
                            Email = "kate.trump@gov.ru",
                            FirstName = "Kate",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 27,
                            Email = "audrey.winslet@gov.ru",
                            FirstName = "Audrey",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 28,
                            Email = "kate.winslet@google.com",
                            FirstName = "Kate",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 29,
                            Email = "donald.presley@gov.ru",
                            FirstName = "Donald",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 30,
                            Email = "jimi.hendrix@gov.gr",
                            FirstName = "Jimi",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 31,
                            Email = "mick.windsor@tesla.com",
                            FirstName = "Mick",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 32,
                            Email = "donald.hepburn@gov.nl",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 33,
                            Email = "jimi.obama@gov.ru",
                            FirstName = "Jimi",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 34,
                            Email = "mick.trump@gov.ru",
                            FirstName = "Mick",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 35,
                            Email = "mick.windsor@tesla.com",
                            FirstName = "Mick",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 36,
                            Email = "mick.hepburn@gov.us",
                            FirstName = "Mick",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 37,
                            Email = "kate.hendrix@gov.gr",
                            FirstName = "Kate",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 38,
                            Email = "kate.jagger@gov.nl",
                            FirstName = "Kate",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 39,
                            Email = "donald.windsor@gov.gr",
                            FirstName = "Donald",
                            LastName = "Windsor"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 6,
                            Title = "A herd of Purple Leopards"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 38,
                            Title = "A bunch of Rose Smelling Cars"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 15,
                            Title = "The Orange Leopards"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 21,
                            Title = "Two Rose Smelling Buildings"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 20,
                            Title = "A herd of Purple Cars"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 22,
                            Title = "A herd of Bitter Buildings"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 14,
                            Title = "Two Microscopic Cars"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 31,
                            Title = "Two Bitter Buildings"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 34,
                            Title = "An army of Large Cars"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 20,
                            Title = "Several Rose Smelling Planets"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 8,
                            Title = "Two Large Buildings"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 38,
                            Title = "An army of Bitter Buildings"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 31,
                            Title = "Several Large Flowers"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 10,
                            Title = "Two Large Buildings"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 32,
                            Title = "A herd of Large Buildings"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 14,
                            Title = "Several Large Planets"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 16,
                            Title = "Several Rose Smelling Planets"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 10,
                            Title = "Two Green Leopards"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 16,
                            Title = "Several Large Leopards"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            Title = "A bunch of Green Houses"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 33,
                            Title = "Fifteen Green Houses"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 9,
                            Title = "A bunch of Orange Flowers"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 16,
                            Title = "Several Bitter Planets"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 12,
                            Title = "Two Large Houses"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 17,
                            Title = "The Microscopic Cars"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 15,
                            Title = "A bunch of Orange Planets"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 2,
                            Title = "A bunch of Rose Smelling Planets"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 20,
                            Title = "A herd of Green Leopards"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 16,
                            Title = "Two Rose Smelling Cars"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 23,
                            Title = "Several Green Cars"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 19,
                            Title = "A bunch of Orange Cars"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 13,
                            Title = "Fifteen Microscopic Leopards"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 24,
                            Title = "Fifteen Green Cars"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 18,
                            Title = "A bunch of Bitter Planets"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 1,
                            Title = "An army of Microscopic Houses"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 10,
                            Title = "A herd of Green Houses"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 31,
                            Title = "A bunch of Green Houses"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 34,
                            Title = "Fifteen Orange Cars"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 16,
                            Title = "The Purple Buildings"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Book", b =>
                {
                    b.HasOne("exercise.webapi.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("exercise.webapi.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
