// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.webapi.Data;

#nullable disable

namespace exercise.webapi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.webapi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "oprah.winslet@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 2,
                            Email = "kate.obama@google.com",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 3,
                            Email = "kate.middleton@gov.gr",
                            FirstName = "Kate",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 4,
                            Email = "charles.trump@tesla.com",
                            FirstName = "Charles",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 5,
                            Email = "audrey.winslet@bbc.co.uk",
                            FirstName = "Audrey",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 6,
                            Email = "donald.hepburn@something.com",
                            FirstName = "Donald",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 7,
                            Email = "elvis.hepburn@gov.nl",
                            FirstName = "Elvis",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 8,
                            Email = "oprah.winslet@gov.ru",
                            FirstName = "Oprah",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 9,
                            Email = "kate.hepburn@something.com",
                            FirstName = "Kate",
                            LastName = "Hepburn"
                        },
                        new
                        {
                            Id = 10,
                            Email = "barack.winfrey@gov.ru",
                            FirstName = "Barack",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 11,
                            Email = "mick.middleton@something.com",
                            FirstName = "Mick",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 12,
                            Email = "elvis.presley@gov.us",
                            FirstName = "Elvis",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 13,
                            Email = "charles.winslet@gov.us",
                            FirstName = "Charles",
                            LastName = "Winslet"
                        },
                        new
                        {
                            Id = 14,
                            Email = "barack.presley@google.com",
                            FirstName = "Barack",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 15,
                            Email = "jimi.winfrey@google.com",
                            FirstName = "Jimi",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 16,
                            Email = "kate.obama@gov.ru",
                            FirstName = "Kate",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 17,
                            Email = "kate.winfrey@gov.nl",
                            FirstName = "Kate",
                            LastName = "Winfrey"
                        },
                        new
                        {
                            Id = 18,
                            Email = "barack.windsor@gov.nl",
                            FirstName = "Barack",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 19,
                            Email = "oprah.trump@gov.us",
                            FirstName = "Oprah",
                            LastName = "Trump"
                        },
                        new
                        {
                            Id = 20,
                            Email = "audrey.middleton@theworld.ca",
                            FirstName = "Audrey",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 21,
                            Email = "jimi.windsor@nasa.org.us",
                            FirstName = "Jimi",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 22,
                            Email = "kate.windsor@google.com",
                            FirstName = "Kate",
                            LastName = "Windsor"
                        },
                        new
                        {
                            Id = 23,
                            Email = "elvis.obama@gov.gr",
                            FirstName = "Elvis",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 24,
                            Email = "mick.obama@gov.us",
                            FirstName = "Mick",
                            LastName = "Obama"
                        },
                        new
                        {
                            Id = 25,
                            Email = "charles.middleton@bbc.co.uk",
                            FirstName = "Charles",
                            LastName = "Middleton"
                        },
                        new
                        {
                            Id = 26,
                            Email = "elvis.hendrix@gov.ru",
                            FirstName = "Elvis",
                            LastName = "Hendrix"
                        },
                        new
                        {
                            Id = 27,
                            Email = "elvis.jagger@gov.gr",
                            FirstName = "Elvis",
                            LastName = "Jagger"
                        },
                        new
                        {
                            Id = 28,
                            Email = "mick.presley@google.com",
                            FirstName = "Mick",
                            LastName = "Presley"
                        },
                        new
                        {
                            Id = 29,
                            Email = "elvis.winslet@gov.nl",
                            FirstName = "Elvis",
                            LastName = "Winslet"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 24,
                            PublisherId = 6,
                            Title = "Two Rose Smelling Buildings"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 5,
                            PublisherId = 13,
                            Title = "Fifteen Large Planets"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 7,
                            PublisherId = 12,
                            Title = "Several Large Buildings"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 7,
                            PublisherId = 1,
                            Title = "A bunch of Orange Flowers"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 25,
                            PublisherId = 13,
                            Title = "A herd of Bitter Flowers"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 8,
                            PublisherId = 12,
                            Title = "Two Orange Planets"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 18,
                            PublisherId = 6,
                            Title = "The Purple Cars"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 13,
                            PublisherId = 3,
                            Title = "A herd of Microscopic Houses"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 21,
                            PublisherId = 4,
                            Title = "Fifteen Purple Planets"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 28,
                            PublisherId = 13,
                            Title = "An army of Transparent Flowers"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 13,
                            PublisherId = 8,
                            Title = "Fifteen Transparent Houses"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 22,
                            PublisherId = 1,
                            Title = "Fifteen Rose Smelling Houses"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 5,
                            PublisherId = 8,
                            Title = "A bunch of Large Houses"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 18,
                            PublisherId = 14,
                            Title = "Several Microscopic Cars"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 8,
                            PublisherId = 5,
                            Title = "A herd of Microscopic Buildings"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 17,
                            PublisherId = 12,
                            Title = "Several Purple Cars"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 16,
                            PublisherId = 4,
                            Title = "Two Green Houses"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 13,
                            PublisherId = 12,
                            Title = "The Purple Houses"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 3,
                            PublisherId = 8,
                            Title = "A herd of Bitter Cars"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 19,
                            PublisherId = 5,
                            Title = "A bunch of Orange Cars"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 16,
                            PublisherId = 9,
                            Title = "A herd of Rose Smelling Cars"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 29,
                            PublisherId = 3,
                            Title = "A herd of Bitter Planets"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 28,
                            PublisherId = 8,
                            Title = "Several Transparent Planets"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 18,
                            PublisherId = 14,
                            Title = "An army of Rose Smelling Buildings"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 4,
                            PublisherId = 3,
                            Title = "Two Large Flowers"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 22,
                            PublisherId = 3,
                            Title = "A herd of Rose Smelling Flowers"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 16,
                            PublisherId = 14,
                            Title = "Two Purple Leopards"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 15,
                            PublisherId = 2,
                            Title = "A herd of Orange Houses"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 3,
                            PublisherId = 11,
                            Title = "Several Large Houses"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pegalon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gyldenme"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Flamber"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pegage"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kagsus"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pegadal"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Flamme"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cappehoug"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Gyldenlon"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Flamlen"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kagme"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Oktodal"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Oktoge"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cappege"
                        });
                });

            modelBuilder.Entity("exercise.webapi.Models.Book", b =>
                {
                    b.HasOne("exercise.webapi.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exercise.webapi.Models.Publisher", "Publisher")
                        .WithMany("Published")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("exercise.webapi.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("exercise.webapi.Models.Publisher", b =>
                {
                    b.Navigation("Published");
                });
#pragma warning restore 612, 618
        }
    }
}
